### ISSUE TITLE
Allow the configuration of Vaadin home directory in vaadin-maven-plugin

### ISSUE THREAD

**Issue by tarekoraby** [vaadin/flow#10005]
Currently, `vaadin-maven-plugin` only looks for the `proKey` under the user's home directory. However, in some environments, the user's home directory might be corrupt or inaccessible for one reason or another. For such cases, it would be useful if there is a way to pass the Vaadin home directory to the plugin.

**Comment by pgerhard** [comment]
Since I recently had issues with this, and reach out to Tarek via Expert Chat I'll elaborate a bit further.

Currently the Vaadin Maven Plugin assumes that the user home is synonymous with the Vaadin Home directory. Especially in situations a shared build agent is used, such as when running builds on Jenkins slaves, this is arbitrary and causes issues. In my case ```System.getProperty("user.home")```, the underlying method call when resolving the user home directory, returned the path, but it had appended a '?' to it. Our home variable on the slave is set correctly, so we are assuming that this is caused by some weird interaction caused by the interaction between the different container orchestrating our build process running on Kubernetes cluster.

Furthermore, the evaluation of the user home path is done eagerly, even if the there is valid node installation and the proKey has been configured via a command line argument.

I propose the following changes
1. Allow the configuration of the vaadin home directory via a property in the maven plugin, analogous to how the npm folder is configurable. However it should be optional, so by default blank, in order to preserve the existing behaviour and not break builds. If the property is blank, fallback to the current mechanism
2. Only evaluate this property if
    * The Vaadin ProKey is not set
    * The alternative NPM dir needs to be used since no system wide node installation could be found

If there is interest in making this change, but there is a lack of time available to implement it, i'd be happy to give it a go. Providing that it will be included in the Vaadin 14 LTS releases, since this is what we are currently using for production.

**Comment by pleku** [comment]
Just to be clear - the vaadin-maven-plugin (which is disguised in the /flow repository with the name flow-maven-plugin) does not check the `proKey` itself, but during the build it triggers `node` execution that later on triggers the license checking. The license-checker itself is in https://github.com/vaadin/license-checker and I will transfer this issue there.

If needed, some configuration can be added to the maven plugin, but it is not the only way to build Vaadin projects so it should be done so that it is possible to do it via Gradle too.

**Comment by pgerhard** [comment]
Hi @pleku,

Thanks for the further clarification and information. To your points

* Regarding the license checking. If this is done after the fact then it makes even less sense in my eyes that the vaadin-maven-plugin forces the creation of the ```.vaadin``` directory. Since, in a scenario where node is available and the proKey is passed via the cmd, it is not required. 
* Good point regarding gradle, I would have forgotten about this since I personally only use Maven
* I don't think that this topic is directly related to the license checker. The license checker should not be affected by this change, unless it requires the ```.vaadin``` directory to be present in the user home, in which case I would suggest making it more flexible and change it so that it only requires the ```.vaadin``` directory when the proKey is not passed in via other means. I'd also ensure that the configure vaadin home directory is passed along to it.

**Comment by pleku** [comment]
One clarifying question - is there Multiplatform Runtime or TestBench being used as part of the build ?

**Comment by pgerhard** [comment]
No, this was happening with a project that I had directly downloaded from start.vaadin.com

**Comment by pleku** [comment]
> However the internal project in which this issue first appeared uses neither testbench nor MPR

Ok. The build time license check is only happening for TB at the moment, so, like you tried to point out, this issue is just about configuring the home folder for the Maven plugin (and to gradle plugin at the same time). There is a PR currently open trying to contribute moving the plugin code to another artifact so that it could be more shared between different plugins. I think adding the configuration for the home folder could be considered after that.

**Comment by matthew-sprague** [comment]
Is there a workaround for this issue? I have been attempting several hacks to get past this:

16:26:47 Caused by: java.lang.IllegalStateException: The user directory '/var/appl/jenkins/workspace/buildbranch-FWKU4RJUBIU562RMZGX2I26P7II45HXYRS7QLPWSVJCUD5WZMD4Q/?' doesn't exist
16:26:47 	at com.vaadin.flow.server.frontend.FrontendUtils.getVaadinHomeDirectory(FrontendUtils.java:918)
16:26:47 	at com.vaadin.gradle.VaadinUtilsKt$createFrontendTools$1.get(VaadinUtils.kt:152)
16:26:47 	at com.vaadin.gradle.VaadinUtilsKt$createFrontendTools$1.get(VaadinUtils.kt)
16:26:47 	at com.vaadin.flow.server.frontend.FrontendTools.getExecutable(FrontendTools.java:506)
16:26:47 	at com.vaadin.flow.server.frontend.FrontendTools.getNodeExecutable(FrontendTools.java:228)
16:26:47 	at com.vaadin.flow.server.frontend.FrontendTools.validateNodeAndNpmVersion(FrontendTools.java:312)
16:26:47 	at com.vaadin.gradle.VaadinPrepareFrontendTask.vaadinPrepareFrontend(VaadinPrepareFrontendTask.kt:77)

**Comment by tarekoraby** [comment]
A workaround (earlier reported by @pgerhard) is to pass in `-Duser.home=${env.WORKSPACE}` via the Maven command line

**Comment by pleku** [comment]
Just dropping a note from internal discussion referring to https://github.com/vaadin/flow/blob/790122df06e186e7ce2aa5a682dacd2ec2d0cdff/flow-server/src/main/java/com/vaadin/flow/server/frontend/FrontendTools.java#L503 in code
>OK, I think I recall something about that now.
Originally : global node had preference over anything else.
And the code in its state was written for that case.
Then at some point someone decided to use node installed in the home dir over anything else.
The code has been changed according to that but the design has not been changed.
The problem with vaadin home dir now : the dir is created indeed every time because only supplier is used to get the home dir and this supplier always creates a dir being called.
So the current impl design doesn't work anymore with current needs.
alternativeDirGetter
was alternative : the last fallback to search and install node if it doesn't exist.
Now it's not alternative . It's primary .
And the logic should search first in the home dir location, then globally and then install node in the home dir if it's not found in the end.
Everything has dramatically changed and the logic should be rewritten significantly.
