### ISSUE TITLE
V20 alpha 3: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getName()" because "schema" is null

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10256]
### Description of the bug / feature

A project with an endpoint like this does not compile
```
@Endpoint
@AnonymousAllowed
public class MyEnd {

    public void hello(FakePageable p) {

    }
}
```

The source of FakePageable is here https://github.com/Artur-/test-schema/blob/master/src/main/java/com/example/application/FakePageable.java along with the whole test project

### Minimal reproducible example
1. git clone https://github.com/Artur-/test-schema.git
2. mvn

### Expected behavior
Project starts, as it does with V20 alpha 2

### Actual behavior
```
Caused by: java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getName()" because "schema" is null
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.collectUsedTypesFromSchema(OpenApiObjectGenerator.java:487)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.collectUsedTypesFromSchema(OpenApiObjectGenerator.java:503)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.lambda$collectUsedTypesFromSchema$21(OpenApiObjectGenerator.java:517)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.collectUsedTypesFromSchema(OpenApiObjectGenerator.java:516)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.generatedRelatedSchemas(OpenApiObjectGenerator.java:758)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.parseNonEndpointClassAsSchema(OpenApiObjectGenerator.java:452)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.createSchemasFromQualifiedNameAndType(OpenApiObjectGenerator.java:476)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.init(OpenApiObjectGenerator.java:228)
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.generateOpenApi(OpenApiObjectGenerator.java:181)
	at com.vaadin.flow.server.connect.generator.OpenApiSpecGenerator.generateOpenApiSpec(OpenApiSpecGenerator.java:80)
	at com.vaadin.flow.server.connect.generator.OpenApiSpecGenerator.generateOpenApiSpec(OpenApiSpecGenerator.java:112)
	at com.vaadin.flow.server.frontend.fusion.TaskGenerateOpenApiImpl.execute(TaskGenerateOpenApiImpl.java:64)
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:698)
	at com.vaadin.flow.server.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:487)
	at com.vaadin.flow.server.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

### Versions:
    - Vaadin / Flow version: 20 alpha 3

**Comment by Artur-** [comment]
Simplified test
```java
@Endpoint
@AnonymousAllowed
public class MyEnd {

    public void hello(FakeSort p) {

    }
}

```

```java
public class FakeSort extends org.springframework.data.domain.Sort {

    public FakeSort() {
        super(new ArrayList<>());
    }

}
```

**Comment by Artur-** [comment]
Ok, this is the problem. It is a regression from #9709 
```
@Endpoint
@AnonymousAllowed
public class MyEnd {

    public void hello(MyBean p) {

    }
}

public class MyBean implements Iterable<String> {
