### ISSUE TITLE
ThemeLiveReloadIT::webpackLiveReload_newCssCreatedAndDeleted_stylesUpdatedOnFly is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10283]
`ThemeLiveReloadIT::webpackLiveReload_newCssCreatedAndDeleted_stylesUpdatedOnFly`  is flaky at least in `2.6` branch:

https://teamcity.vaadin.com/viewLog.html?buildId=73693&buildTypeId=Flow_FlowTests

```
Caused by: java.lang.AssertionError: Values should be different. Actual: rgba(255, 0, 0, 1)
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failEquals(Assert.java:187)
	at org.junit.Assert.assertNotEquals(Assert.java:163)
	at org.junit.Assert.assertNotEquals(Assert.java:177)
	at com.vaadin.flow.uitest.ui.ThemeLiveReloadIT.webpackLiveReload_newCssCreatedAndDeleted_stylesUpdatedOnFly(ThemeLiveReloadIT.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
```

See the error screenshot if the build link is not available anymore.

![webpackLiveReload_newCssCreatedAndDeleted_stylesUpdatedOnFly ANY_Chrome_ (com vaadin flow uitest ui ThemeLiveReloadIT)](https://user-images.githubusercontent.com/11425472/111132030-ee4d7700-8589-11eb-851b-e6bf8d3d1b51.png)

**Comment by mshabarov** [comment]
Doesn't exist anymore.
