### ISSUE TITLE
ComplexDialogShortcutIT.dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_] is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10284]
`ComplexDialogShortcutIT::dialogWithShortcutListenOnAndPreserveOnRefresh_refreshWhenDialogOpened_shortcutScopingWorks` is flaky in all branches.

It at least failed in the `6.0` SNAPSHOT and `2.6`  SNAPSHOT:

https://bender.vaadin.com/viewLog.html?buildId=218806&tab=buildResultsDiv&buildTypeId=Flow_Flow60_Flow60Snapshot
https://bender.vaadin.com/viewLog.html?buildId=218817&tab=buildResultsDiv&buildTypeId=Flow_Flow26_Snapshot

Here is an error snapshot if it's not available by the link in the builds
![dialogWithShortcutListenOnAndPreserveOnRefresh_refreshWhenDialogOpened_shortcutScopingWorks ANY_Chrome_ (com vaadin flow uitest ui ComplexDialogShortcutIT)](https://user-images.githubusercontent.com/11425472/111132588-98c59a00-858a-11eb-8862-16b02f81d6ee.png)

**Comment by denis-anisimov** [comment]
I've disabled the test since it fails too many builds: it's not possible to get latest SNAPSHOTS for many versions because of it.

**Comment by pleku** [comment]
The wrong test was mentioned to be flaky, it is not the preserve-on-refresh test.

**Comment by denis-anisimov** [comment]
Both of them are flaky.
Sometimes fails one sometimes both fail.

**Comment by mshabarov** [comment]
Two more failures occur recently:

https://bender.vaadin.com/viewLog.html?buildId=221347&buildTypeId=Flow_Flow60_Flow60Snapshot

![image](https://user-images.githubusercontent.com/61410877/112874828-1087de80-90cc-11eb-9858-1c5b3a7257f0.png)

```
java.lang.RuntimeException: dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.DialogShortcutIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: No element with tag <div> found with the attributes [id='CONTENT1'] using index 0
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-63', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.16.0-7-amd64', java.version: '1.8.0_201'
Driver info: driver.version: unknown
	at com.vaadin.testbench.ElementQuery.get(ElementQuery.java:321)
	at com.vaadin.testbench.ElementQuery.first(ElementQuery.java:245)
	at com.vaadin.testbench.ElementQuery.id(ElementQuery.java:154)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.getDialogInput(DialogShortcutIT.java:217)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted(DialogShortcutIT.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
------- Stderr: -------
Mar 29, 2021 1:25:56 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 29, 2021 1:25:59 PM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/bd8be42f93e09a33/flow-tests/test-root-context/error-screenshots/dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.DialogShortcutIT).png
Mar 29, 2021 1:26:01 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 29, 2021 1:26:03 PM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/bd8be42f93e09a33/flow-tests/test-root-context/error-screenshots/dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.DialogShortcutIT).png
```

**Comment by mshabarov** [comment]
https://bender.vaadin.com/viewLog.html?buildId=220934&buildTypeId=Flow_Flow60_Flow60Snapshot

```
java.lang.RuntimeException: dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: overlay1 (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:223)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:247)
	at com.vaadin.flow.testutil.TestBenchHelpers.waitForElementPresent(TestBenchHelpers.java:136)
	at com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT.waitForTransport(ComplexDialogShortcutIT.java:41)
	at com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT.openNewDialog(ComplexDialogShortcutIT.java:36)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted(DialogShortcutIT.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#overlay1"}
  (Session info: headless chrome=89.0.4389.82)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-226.eu-west-1.compute.internal', ip: '172.16.1.226', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.154-128.181.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 89.0.4389.82, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /tmp/.com.google.Chrome.j0KaL8}, goog:chromeOptions: {debuggerAddress: localhost:39843}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 9770570a68fdd01ff6993afe618...}
Session ID: 9770570a68fdd01ff6993afe618a78bd
*** Element info: {Using=id, value=overlay1}
	at sun.reflect.GeneratedConstructorAccessor31.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at com.vaadin.testbench.TestBenchDriverProxy.findElement(TestBenchDriverProxy.java:54)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst97d_0._d6findElement(TestBenchDriverProxy_$$_jvst97d_0.java)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.testbench.DriverInvocationHandler.invoke(DriverInvocationHandler.java:51)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst97d_0.findElement(TestBenchDriverProxy_$$_jvst97d_0.java)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:182)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:179)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	... 32 more
------- Stderr: -------
Mar 25, 2021 10:55:15 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 25, 2021 10:55:18 PM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/bd8be42f93e09a33/flow-tests/test-root-context/error-screenshots/dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT).png
Mar 25, 2021 10:55:22 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 25, 2021 10:55:34 PM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/bd8be42f93e09a33/flow-tests/test-root-context/error-screenshots/dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT).png
```

**Comment by pleku** [comment]
I cannot find the screenshot for the second failure, but the first one shows that it is continuing test execution while it is still waiting for the server roundtrip to finish (loading indicator visible) and in the screenshot the element it is failing for is present in the UI.

I'll do some tests locally and maybe push some changes based on those.

**Comment by mshabarov** [comment]
```
java.lang.RuntimeException: dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: overlay1 (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:223)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:247)
	at com.vaadin.flow.testutil.TestBenchHelpers.waitForElementPresent(TestBenchHelpers.java:136)
	at com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT.waitForTransport(ComplexDialogShortcutIT.java:41)
	at com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT.openNewDialog(ComplexDialogShortcutIT.java:36)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted(DialogShortcutIT.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#overlay1"}
  (Session info: headless chrome=89.0.4389.82)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-158', ip: '172.16.1.158', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.0-0.bpo.6-amd64', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 89.0.4389.82, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /tmp/.com.google.Chrome.LucDr9}, goog:chromeOptions: {debuggerAddress: localhost:37225}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 2fdca8e9eb02a252790b2f8623f...}
Session ID: 2fdca8e9eb02a252790b2f8623f3bfd2
*** Element info: {Using=id, value=overlay1}
	at sun.reflect.GeneratedConstructorAccessor35.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at com.vaadin.testbench.TestBenchDriverProxy.findElement(TestBenchDriverProxy.java:54)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst3bf_0._d6findElement(TestBenchDriverProxy_$$_jvst3bf_0.java)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.testbench.DriverInvocationHandler.invoke(DriverInvocationHandler.java:51)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst3bf_0.findElement(TestBenchDriverProxy_$$_jvst3bf_0.java)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:182)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:179)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	... 32 more
------- Stderr: -------
Apr 01, 2021 6:39:18 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Apr 01, 2021 6:39:21 AM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-root-context/error-screenshots/dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT).png
Apr 01, 2021 6:39:22 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Apr 01, 2021 6:39:34 AM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/a69251da2b2bb9e9/flow-tests/test-root-context/error-screenshots/dialogOpenedWithListenOnShortcut_sameShortcutListeningOnUi_focusDecidesWhichIsExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT).png
```

https://teamcity.vaadin.com/viewLog.html?buildId=74998&buildTypeId=Flow_FlowTests

![image](https://user-images.githubusercontent.com/61410877/113287523-617b1b00-92f6-11eb-932b-bf59e79008e6.png)

**Comment by pleku** [comment]
@mshabarov I don't think we need more than 3 issues for the same tests, they are ignored now anyway https://github.com/vaadin/flow/pull/10541

**Comment by mshabarov** [comment]
@pleku some branches have them enabled still.

**Comment by pleku** [comment]
@mshabarov but there have been no failures in 2.5 + 2.6 for over 10 days.

**Comment by mshabarov** [comment]
@pleku my bad, the reason of my worry was that some PR branch was based on old commit, even **before** this test has been disabled => PR validation fails. I've updated merged last commits to PR branch and that's it.
