### ISSUE TITLE
DialogShortcutIT::dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10302]
`DialogShortcutIT::dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted` failed in `2.6`:

https://bender.vaadin.com/viewLog.html?buildId=219206&tab=buildResultsDiv&buildTypeId=Flow_Flow26_Snapshot

Screenshot if link doesn't work:

![dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted ANY_Chrome_ (com vaadin flow uitest ui DialogShortcutIT)](https://user-images.githubusercontent.com/11425472/111423248-0c89b300-8701-11eb-8cb2-1c4b0c9011af.png)

**Comment by pleku** [comment]
It seems quite random that which test fails from `ComplexShortcutIT` or `DialogShortcutIT` so it might be just sense to merge this to https://github.com/vaadin/flow/issues/10284. I'm working on refactoring both tickets anyway.

**Comment by mshabarov** [comment]
One more failure spotted in Flow 6.0 snapshot validation:

https://bender.vaadin.com/viewLog.html?buildId=221404&buildTypeId=Flow_Flow60_Flow60Snapshot

![image](https://user-images.githubusercontent.com/61410877/112873290-1b417400-90ca-11eb-8691-244df1b79703.png)


```
java.lang.RuntimeException: dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for presence of element located by: By.id: overlay1 (tried for 10 second(s) with 500 milliseconds interval)
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:223)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:247)
	at com.vaadin.flow.testutil.TestBenchHelpers.waitForElementPresent(TestBenchHelpers.java:136)
	at com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT.waitForTransport(ComplexDialogShortcutIT.java:41)
	at com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT.openNewDialog(ComplexDialogShortcutIT.java:36)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted(DialogShortcutIT.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"css selector","selector":"#overlay1"}
  (Session info: headless chrome=89.0.4389.82)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-153.eu-west-1.compute.internal', ip: '172.16.1.153', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.146-119.123.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 89.0.4389.82, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /tmp/.com.google.Chrome.chNuXS}, goog:chromeOptions: {debuggerAddress: localhost:35959}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: f77c7084c8679c392ff8fa41183...}
Session ID: f77c7084c8679c392ff8fa41183d76a6
*** Element info: {Using=id, value=overlay1}
	at sun.reflect.GeneratedConstructorAccessor36.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:372)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at com.vaadin.testbench.TestBenchDriverProxy.findElement(TestBenchDriverProxy.java:54)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst2c_0._d6findElement(TestBenchDriverProxy_$$_jvst2c_0.java)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.testbench.DriverInvocationHandler.invoke(DriverInvocationHandler.java:51)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvst2c_0.findElement(TestBenchDriverProxy_$$_jvst2c_0.java)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:182)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:179)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
	... 32 more
------- Stderr: -------
Mar 29, 2021 4:42:51 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 29, 2021 4:42:54 PM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/bd8be42f93e09a33/flow-tests/test-root-context/error-screenshots/dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT).png
Mar 29, 2021 4:42:54 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 29, 2021 4:43:06 PM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: /opt/agent/work/bd8be42f93e09a33/flow-tests/test-root-context/error-screenshots/dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.ComplexDialogShortcutIT).png
```
