### ISSUE TITLE
flow-plugin-base needs to transitively depend on fusion-endpoint

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#10312]
When building a WAR project with the experimental Vaadin 20 Gradle plugin, the Gradle plugin needs to pull in `com.vaadin:fusion-endpoint:7.0.0.alpha1` along with `com.vaadin:flow-plugin-base:7.0.0.alpha1`, otherwise the build fails with the following exception:

```
 Caused by: java.lang.IllegalStateException: Could not find service class
 	at com.vaadin.flow.utils.LookupImpl.lookupAll(LookupImpl.java:65)
 	at com.vaadin.flow.utils.LookupImpl.lookup(LookupImpl.java:46)
 	at com.vaadin.flow.di.Lookup$2.lookup(Lookup.java:188)
 	at com.vaadin.flow.server.frontend.NodeTasks.addConnectServicesTasks(NodeTasks.java:665)
 	at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:591)
 	at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:51)
 	at com.vaadin.flow.server.frontend.NodeTasks$Builder.build(NodeTasks.java:197)
 	at com.vaadin.flow.plugin.base.BuildFrontendUtil.runNodeUpdater(BuildFrontendUtil.java:279)
 	at com.vaadin.gradle.VaadinBuildFrontendTask.vaadinBuildFrontend(VaadinBuildFrontendTask.kt:70)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:48)
 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:41)
 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:704)
 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:671)
 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:117)
 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:301)
 	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:293)
 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:175)
 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
 	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:106)
 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:85)
 	... 35 more
 Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.server.frontend.fusion.EndpointGeneratorTaskFactoryImpl
 	at com.vaadin.flow.utils.LookupImpl.lookupAll(LookupImpl.java:60)
 	... 60 more
```

**Comment by denis-anisimov** [comment]
The artifacts which are needed in runtime may not depend on fusion because fusion is not OSGi compatible.
The plugin should depend instead on fusion in the same way as it's done for maven plugin.

**Comment by mvysny** [comment]
@denis-anisimov In such case it would make sense for `flow-plugin-base` to depend on `fusion-endpoint`, in order for `flow-plugin-base` to provide everything that the plugin will need.

**Comment by denis-anisimov** [comment]
That can be done, indeed.
