### ISSUE TITLE
@Id mapping regression in 14.5

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#10367]
### Description of the bug / feature
Certain ids which are special in some sense work fine with `@Id` mapping in 14.4 but fails in 14.5

```html
<vaadin-grid id="grid"></vaadin-grid>
```

```java
@Id
private  Grid grid;
```

This works in 14.4 for a `PolymerTemplate` but is broken in 14.5:

Probably will be fixed by backporting https://github.com/vaadin/flow/pull/8483 and https://github.com/vaadin/flow/pull/10111

### Minimal reproducible example
```
vaadin init hello-145 --preset all-lts
```

Change the `id` for the text field from `name` to `grid` in `HelloworldviewjavahtmlView.java` and `helloworldviewjavahtml-view.js`

### Expected behavior
All ids should work with `@Id`

### Actual behavior
```
java.lang.IllegalStateException: The element with the tag name 'vaadin-text-field' and id 'grid' was not found in the parent with id='6'
	at com.vaadin.flow.server.communication.rpc.AttachTemplateChildRpcHandler.handleNode(AttachTemplateChildRpcHandler.java:82) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:410) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:391) ~[flow-server-2.5.0.jar:2.5.0]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:391) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:318) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1547) ~[flow-server-2.5.0.jar:2.5.0]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) ~[flow-server-2.5.0.jar:2.5.0]
```

### Versions:
    - Vaadin / Flow version: 14.5

**Comment by pelkeo** [comment]
Just a quick hint for people struggling with the HTML templates: This error can also appear when placing the custom element tag outside the template tag. The error message is actually appropriate for that case.
