### ISSUE TITLE
WebComponentIT.downloadLinkHasCorrectBaseURL is flaky

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#10364]
https://bender.vaadin.com/viewLog.html?buildId=220268&buildTypeId=Flow_Flow25_Nightly_ValidationWithWindows

**Comment by mshabarov** [comment]
```
java.lang.RuntimeException: downloadLinkHasCorrectBaseURL[ANY_Chrome_](com.vaadin.flow.webcomponent.WebComponentIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: No element with tag <a> found with the attributes [id='link'] using index 0
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '8A2A47E8BF40', ip: '172.22.248.86', os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_252'
Driver info: driver.version: unknown
	at com.vaadin.testbench.ElementQuery.get(ElementQuery.java:303)
	at com.vaadin.testbench.ElementQuery.first(ElementQuery.java:243)
	at com.vaadin.testbench.ElementQuery.id(ElementQuery.java:152)
	at com.vaadin.flow.webcomponent.WebComponentIT.downloadLinkHasCorrectBaseURL(WebComponentIT.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
------- Stderr: -------
Starting ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}) on port 24784
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Mar 23, 2021 1:08:08 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 23, 2021 1:08:10 AM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: C:\BuildAgent\work\1911471312825fc3\flow-tests\test-embedding\test-embedding-generic\error-screenshots\downloadLinkHasCorrectBaseURL[ANY_Chrome_](com.vaadin.flow.webcomponent.WebComponentIT).png
Starting ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}) on port 52436
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Mar 23, 2021 1:08:11 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Mar 23, 2021 1:08:14 AM com.vaadin.testbench.ScreenshotOnFailureRule failed
INFO: Error screenshot written to: C:\BuildAgent\work\1911471312825fc3\flow-tests\test-embedding\test-embedding-generic\error-screenshots\downloadLinkHasCorrectBaseURL[ANY_Chrome_](com.vaadin.flow.webcomponent.WebComponentIT).png
```
