### ISSUE TITLE
Flow 6.0 and 7.0 validation has been failing with Windows

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#10378]
Flow 6.0 and 7.0 validation has been failing with Windows since 13.03.2021:
https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow70_Nightly_ValidateFlowMasterWithWindows
https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow60_Nightly_ValidateFlow60withWindows

The build is interrupted while running `flow-client` validation.
Apparently related to Chrome Driver / Chrome browser or to other environment issue, because the logs say about problems with creating sessions:

```
[00:42:03]	[Step 1/1] Ready
[00:42:03]	[Step 1/1] Tunnel started
[00:43:05]	[Step 1/1] BUG: suiteEnd was received for invalid session 
[00:43:05]	[Step 1/1] (ãƒŽà² ç›Šà² )ãƒŽå½¡â”»â”�â”»
[00:43:05]	[Step 1/1] UnknownError: [POST http://localhost:4444/wd/hub/session / {"desiredCapabilities":{"name":"intern","idle-timeout":60,"browserName":"chrome","chromeOptions":{"args":["headless","disable-gpu","window-size=1024x768"]},"browser":"chrome"}}] unknown error: unable to discover open pages
[00:43:05]	[Step 1/1] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[00:43:05]	[Step 1/1] System info: host: '8A2A47E8BF40', ip: '172.22.248.86', os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_252'
[00:43:05]	[Step 1/1] Driver info: driver.version: unknown
[00:43:05]	[Step 1/1] remote stacktrace: Backtrace:
[00:43:05]	[Step 1/1] 	Ordinal0 [0x0090E7D3+124883]
[00:43:05]	[Step 1/1] 	Ordinal0 [0x0090E7B1+124849]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B58688+193832]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B73944+305124]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B7021B+291003]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B6E0AC+282444]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B94A90+440624]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B947FC+439964]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B9154B+426987]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B74FFD+310941]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B75D8E+314414]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00B75D19+314297]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00C331EC+1089676]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00C317C9+1082985]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00C313A3+1081923]
[00:43:05]	[Step 1/1] 	GetHandleVerifier [0x00D2D9FD+2115741]
[00:43:05]	[Step 1/1] 	Ordinal0 [0x00A5B82E+1488942]
[00:43:05]	[Step 1/1] 	Ordinal0 [0x009F5A7D+1071741]
[00:43:05]	[Step 1/1] 	Ordinal0 [0x009F559B+1070491]
[00:43:05]	[Step 1/1] 	Ordinal0 [0x009F54B1+1070257]
[00:43:05]	[Step 1/1] 	Ordinal0 [0x00A2FF53+1310547]
[00:43:05]	[Step 1/1] 	BaseThreadInitThunk [0x72F10419+25]
[00:43:05]	[Step 1/1] 	RtlGetAppContainerNamedObjectPath [0x77E466DD+237]
[00:43:05]	[Step 1/1] 	RtlGetAppContainerNamedObjectPath [0x77E466AD+189]
[00:43:05]	[Step 1/1] 
[00:43:05]	[Step 1/1]   at Server.post @ node_modules\src\Server.ts:401:16
[00:43:05]	[Step 1/1]   at Server.createSession @ node_modules\src\Server.ts:446:16
[00:43:05]	[Step 1/1]   at Suite.before @ src\lib\executors\Node.ts:491:15
[00:43:05]	[Step 1/1]   @ src\lib\Suite.ts:435:54
[00:43:05]	[Step 1/1]   at new e @ node_modules\@theintern\common\index.js:16:5068
[00:43:05]	[Step 1/1]   at runLifecycleMethod @ src\lib\Suite.ts:400:13
[00:43:05]	[Step 1/1]   at before @ src\lib\Suite.ts:503:13
[00:43:05]	[Step 1/1]   at Suite.run @ src\lib\Suite.ts:522:10
[00:43:05]	[Step 1/1]   @ src\lib\executors\Node.ts:976:27
[00:43:05]	[Step 1/1]   at FunctionQueue.next @ src\lib\executors\Node.ts:1104:19
[00:43:05]	[Step 1/1] 
[00:43:05]	[Step 1/1] TOTAL: tested 0 platforms, 0 passed, 0 failed; fatal error occurred
[00:43:06]	[Step 1/1] Stopping
[00:43:06]	[Step 1/1] Stopped
[00:43:06]	[Step 1/1] [ERROR] Command execution failed.
```

The full log can be discovered here:
https://bender.vaadin.com/viewLog.html?buildId=220245&buildTypeId=Flow_Flow70_Nightly_ValidateFlowMasterWithWindows&tab=buildLog

But from the other side, Flow `2.5` and `2.6` don't have this issue, so maybe related to code changes in `flow-client`.

**Comment by mshabarov** [comment]
This issue has been fixed by simple Windows agent restart.
```
[16:25:54]	[Step 2/2] Listening on localhost:9000 (ws 9001)
[16:25:56]	[Step 2/2] Tunnel download: 100.000%
[16:25:56]	[Step 2/2] Tunnel download: 100.000%
[16:25:56]	[Step 2/2] Ready
[16:25:56]	[Step 2/2] Tunnel started
[16:25:58]	[Step 2/2] 
[16:25:58]	[Step 2/2] â€£ Created remote session chrome on windows (8645415a14aa9c22f21f4f5d6c87c9e0)
[16:26:00]	[Step 2/2] âœ“ chrome on windows - Authentication - login - should return an error on invalid credentials (0.007s)
[16:26:00]	[Step 2/2] âœ“ chrome on windows - Authentication - login - should return a CSRF token on valid credentials (0.003s)
[16:26:00]	[Step 2/2] âœ“ chrome on windows - Authentication - login - should return an error on other unexpected responses (0.002s)
[16:26:00]	[Step 2/2] âœ“ chrome on windows - Authentication - logout - should set the csrf token on logout (0.002s)
```

**Comment by mshabarov** [comment]
Reoccured again after one successful build in Flow 7: https://bender.vaadin.com/viewLog.html?buildId=220884&buildTypeId=Flow_Flow70_Nightly_ValidateFlowMasterWithWindows

Seems that Flow 6, 7 run breaks the Win agent environment.

**Comment by mshabarov** [comment]
Cleanup of `.m2/repository` and `C:\BuildAgent\work` dirs content doesn't help.
Next step - downgrade chrome from last stable 89 to previous 88 and check (90 is in beta still).

**Comment by haijian-vaadin** [comment]
Could run the build manually with a branch to debug from which point the build started failing.

**Comment by mshabarov** [comment]
Both Flow 6.0 and 7.0 are not suffering from this issue anymore. The issue has gone suddenly without any meaningful reason. Since March 31, the builds has been passing flow-client validation.

**Comment by haijian-vaadin** [comment]
hmm, I see the Flow 6.0 nightly Windows build is still mostly red? https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow60_Nightly_ValidateFlow60withWindows

**Comment by mshabarov** [comment]
It fails indeed, but of another reasons than `flow-client` create session failure.
For those tests are currently failing, I propose to create a separate issues and disable them temporary in the windows build configuration (build steps section)
