### ISSUE TITLE
2.5: DialogShortcutIT is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10590]
SNAPSHOT sometimes fails with :
```
twoDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.DialogShortcutIT)  Time elapsed: 17.919 s  <<< ERROR!
[08:23:14] :	 [Step 4/6] java.lang.RuntimeException: twoDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted[ANY_Chrome_](com.vaadin.flow.uitest.ui.DialogShortcutIT): run failed 2 times
[08:23:14]W:		 [com.vaadin:flow-test-root-context-npm] Apr 08, 2021 5:23:11 AM org.openqa.selenium.remote.ProtocolHandshake createSession
[08:23:14]W:		 [com.vaadin:flow-test-root-context-npm] INFO: Detected dialect: W3C
[08:23:14] :	 [Step 4/6] 	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
[08:23:14] :	 [Step 4/6] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[08:23:14] :	 [Step 4/6] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[08:23:14] :	 [Step 4/6] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[08:23:14] :	 [Step 4/6] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[08:23:14] :	 [Step 4/6] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[08:23:14] :	 [Step 4/6] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[08:23:14] :	 [Step 4/6] 	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
[08:23:14] :	 [Step 4/6] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[08:23:14] :	 [Step 4/6] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[08:23:14] :	 [Step 4/6] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[08:23:14] :	 [Step 4/6] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[08:23:14] :	 [Step 4/6] 	at java.lang.Thread.run(Thread.java:748)
[08:23:14] :	 [Step 4/6] Caused by: org.junit.ComparisonFailure: Invalid latest event with 0::DIALOG1 expected:<[1-DIALOG1]> but was:<[0-DIALOG0]>
[08:23:14] :	 [Step 4/6] 	at org.junit.Assert.assertEquals(Assert.java:117)
[08:23:14] :	 [Step 4/6] 	at com.vaadin.flow.uitest.ui.DialogShortcutIT.validateShortcutEvent(DialogShortcutIT.java:205)
[08:23:14] :	 [Step 4/6] 	at com.vaadin.flow.uitest.ui.DialogShortcutIT.validateLatestDialogShortcut(DialogShortcutIT.java:192)
[08:23:14] :	 [Step 4/6] 	at com.vaadin.flow.uitest.ui.DialogShortcutIT.twoDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted(DialogShortcutIT.java:119)
```
![twoDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted ANY_Chrome_ (com vaadin flow uitest ui DialogShortcutIT)](https://user-images.githubusercontent.com/11425472/113986371-dc43b900-9855-11eb-9aa0-db28f2998271.png)

https://bender.vaadin.com/viewLog.html?buildId=222958&buildTypeId=Flow_Flow25_Flow25Snapshot&tab=buildResultsDiv

**Comment by MarcinVaadin** [comment]
Fixed on Flow 2.7
