### ISSUE TITLE
[Vaadin 19 + Node 14.x]: Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-checkbox" has already been used with this registry

### ISSUE THREAD

**Issue by darmro** [vaadin/flow#10612]
### Description of the bug / feature
Our Vaadin 19 app is a **war** project (deployed on production as war package on Tomcat).
When my app is build (in debug mode or production mode- doesn't matter) with node 14.x and deployed as war bundle in Tomcat, then the app is started without any errors, but when I'm trying to open some view in the browser, I can only see a vaadin loading indicator, and errors in chrome dev tool:

```
vaadin-bundle-0bf592acec7f269819d3.cache.js:152 
Path '/web/' is not properly resolved due to an error. Resolution had failed on route: '(.*)'   

vaadin-2-3ac7a1a1fa2d3f691a65.cache.js:3697 
Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-checkbox" has already been used with this registry
    at Object.<anonymous> (http://localhost:8080/web/VAADIN/build/vaadin-2-3ac7a1a1fa2d3f691a65.cache.js:3697:2521)
    at i (http://localhost:8080/web/VAADIN/build/vaadin-bundle-0bf592acec7f269819d3.cache.js:1:361)
    at Object.<anonymous> (http://localhost:8080/web/VAADIN/build/vaadin-2-3ac7a1a1fa2d3f691a65.cache.js:1362:6582)
    at i (http://localhost:8080/web/VAADIN/build/vaadin-bundle-0bf592acec7f269819d3.cache.js:1:361)
    at Object.<anonymous> (http://localhost:8080/web/VAADIN/build/vaadin-2-3ac7a1a1fa2d3f691a65.cache.js:2619:5671)
    at i (http://localhost:8080/web/VAADIN/build/vaadin-bundle-0bf592acec7f269819d3.cache.js:1:361)
    at Object.<anonymous> (http://localhost:8080/web/VAADIN/build/vaadin-2-3ac7a1a1fa2d3f691a65.cache.js:1262:4048)
    at i (http://localhost:8080/web/VAADIN/build/vaadin-bundle-0bf592acec7f269819d3.cache.js:1:361)
    at Module.207 (http://localhost:8080/web/VAADIN/build/vaadin-4-db08d435aed8f5d90fec.cache.js:2880:19832)
    at i (http://localhost:8080/web/VAADIN/build/vaadin-bundle-0bf592acec7f269819d3.cache.js:1:361)
```

I also tried with cleaning my project folder (removing node_modules, target folders and all *.js files), I left only src, frontend folders and pom file.  And build the project from the beginnig (in debug mode and production mode). It didn't help.

**When I do the same but with old node 12.16 everything is ok!  Why is that?** 
If node 14 is not supported, why vaadin is installing this version in .vaadin folder when there's no node on the machine?

I have to returned to node 12.16 to get my application working on production.

### Versions:
    - Vaadin / Flow version: 19.0.3
    - Java version: 1.8
    - OS version: win10
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Tomcat9

**Comment by knoobie** [comment]
There should be a fixed version in the next week or so.. in the meantime you can check this issue about the cause and possible workaround (disabling pnpm) 

https://github.com/vaadin/flow/issues/10571

**Comment by darmro** [comment]
Thanks @knoobie for info. You mean fix will be in next Vaadin 19 version?

**Comment by knoobie** [comment]
@darmro Yes, the next 19.0.x should contain the fix as well. If it's urgent you can downgrade to the previous 19.0.x or define explicitly in your pom that you want flow-* 6.0.5.
