### ISSUE TITLE
2.5: ComplexDialogShortcutIT.twoDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10614]
```
Caused by: org.junit.ComparisonFailure: Invalid latest event with 0::DIALOG0 expected:<[0-DIALOG]0> but was:<[Opened dialog DC0-EC]0>
[01:45:47] :	 [Step 4/6] 	at org.junit.Assert.assertEquals(Assert.java:117)
[01:45:47] :	 [Step 4/6] 	at com.vaadin.flow.uitest.ui.DialogShortcutIT.validateShortcutEvent(DialogShortcutIT.java:205)
[01:45:47] :	 [Step 4/6] 	at com.vaadin.flow.uitest.ui.DialogShortcutIT.validateLatestDialogShortcut(DialogShortcutIT.java:192)
[01:45:47] :	 [Step 4/6] 	at com.vaadin.flow.uitest.ui.DialogShortcutIT.twoDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted(DialogShortcutIT.java:116)

```

![twoDialogsOpenedWithSameShortcutKeyOnListenOn_dialogWithFocusExecuted ANY_Chrome_ (com vaadin flow uitest ui ComplexDialogShortcutIT)](https://user-images.githubusercontent.com/11425472/114347095-21752d00-9b6d-11eb-9840-3f0b60de2e05.png)

https://bender.vaadin.com/viewLog.html?buildId=223637&buildTypeId=Flow_Flow25_Flow25Snapshot&tab=buildResultsDiv

**Comment by MarcinVaadin** [comment]
Cherry picked on Flow 2.7 (https://github.com/vaadin/flow/pull/12830)
