### ISSUE TITLE
2.5: ComplexDialogShortcutIT.dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10616]
```
Caused by: org.junit.ComparisonFailure: Invalid latest event with 0::UI-ID expected:<[3-UI-ID]> but was:<[1-ui-button]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.validateShortcutEvent(DialogShortcutIT.java:205)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.validateLatestShortcutEvent(DialogShortcutIT.java:198)
	at com.vaadin.flow.uitest.ui.DialogShortcutIT.dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted(DialogShortcutIT.java:70)
```
![dialogOpenedWithShortcutNoListenOn_sameShortcutListeningOnUi_bothExecuted ANY_Chrome_ (com vaadin flow uitest ui ComplexDialogShortcutIT)](https://user-images.githubusercontent.com/11425472/114361288-a3218680-9b7e-11eb-9eee-1ba8cfe93beb.png)

https://bender.vaadin.com/viewLog.html?buildId=223677&buildTypeId=Flow_Flow25_Flow25Snapshot&tab=buildResultsDiv

**Comment by MarcinVaadin** [comment]
Cherry picked on Flow 2.7 (https://github.com/vaadin/flow/pull/12830)
