### ISSUE TITLE
[fusion] Tests in flow-tests/test-ccdm-flow-navigation are flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#10615]
It seems the whole module `flow-tests/test-ccdm-flow-navigation/` is flaky.
The tests there may fail at any point during PR validation or in the SNAPSHOT.
Here they are failing during nightly validation :
https://bender.vaadin.com/viewLog.html?buildId=223627&buildTypeId=Flow_Flow70_Nightly_FlowJava11Nightly&tab=buildLog

```
Errors: 
[01:01:41]W:	 [Step 3/3] [ERROR]   ConnectionIndicatorIT.offline_goingOnline_customisedMessageShown[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ConnectionIndicatorIT.offline_serverConnectionAttempted_customisedMessageShown[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ConnectionIndicatorIT.offline_serverConnectionAttempted_javaCustomisedMessagesShown[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ConnectionIndicatorIT.online_goingOffline_customisedMessageShown[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineDeepPath_reload_viewReloaded_baseUrlRewritten[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineNonRoot_reload_viewReloaded[ANY_Chrome_] » Runtime offl...
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineRoot_reload_viewReloaded[ANY_Chrome_] » Runtime offline...
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineServerView_navigateToServerView_offlineStubShown[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineServerView_navigateToTsView_navigationSuccessful[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineStub_backOnline_stubRemoved_serverViewShown[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineTsView_navigateToOtherTsView_navigationSuccessful[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offlineTsView_navigateToServerView_offlineStubShown[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.offline_cachedResourceRequest_resourceLoaded[ANY_Chrome_] » Runtime
[01:01:41]W:	 [Step 3/3] [ERROR]   ServiceWorkerIT.onlineRoot_serviceWorkerInstalled_serviceWorkerActive[ANY_Chrome_] » Runtime

```

Here is one of the stacktrace:
```
 [offlineRoot_reload_viewReloaded[ANY_Chrome_]] java.lang.RuntimeException: offlineRoot_reload_viewReloaded[ANY_Chrome_](com.vaadin.flow.navigate.ServiceWorkerIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:78)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.openqa.selenium.ScriptTimeoutException: script timeout
  (Session info: chrome=89.0.4389.82)
  (Driver info: chromedriver=89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}),platform=Linux 4.14.225-121.362.amzn1.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-184.eu-west-1.compute.internal', ip: '172.16.1.184', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.123-111.109.amzn2.x86_64', java.version: '11.0.4'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /tmp/.com.google.Chrome.nVzu0k}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:46763}, handlesAlerts: true, hasTouchScreen: true, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: true, nativeEvents: true, networkConnectionEnabled: true, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 89.0.4389.82, webStorageEnabled: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: b48577c01c2ba9c46641b26881c...}
Session ID: b48577c01c2ba9c46641b26881cd2f1f
	at jdk.internal.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.executeAsyncScript(RemoteWebDriver.java:506)
	at com.vaadin.testbench.TestBenchDriverProxy.executeAsyncScript(TestBenchDriverProxy.java:195)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvstc8f_0._d3executeAsyncScript(TestBenchDriverProxy_$$_jvstc8f_0.java)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.testbench.DriverInvocationHandler.invoke(DriverInvocationHandler.java:48)
	at com.vaadin.testbench.TestBenchDriverProxy_$$_jvstc8f_0.executeAsyncScript(TestBenchDriverProxy_$$_jvstc8f_0.java)
	at com.vaadin.flow.testutil.ChromeDeviceTest.waitForServiceWorkerReady(ChromeDeviceTest.java:174)
	at com.vaadin.flow.navigate.ServiceWorkerIT.offlineRoot_reload_viewReloaded(ServiceWorkerIT.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:490)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:464)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:68)
```

**Comment by joheriks** [comment]
Took a two-pronged stab at this:
1. This and other test modules are sensitive to depletion of `inotify` handles on Linux, causing them to fail. SD has increased `fs.inotify.max_user_watches` from 8192 to 65536.
2. PR #10661 fixes a unit test race condition leading to `webpack-dev-server` instances not being properly killed. This should fix the `inotify` handle resource leak.
