### ISSUE TITLE
Webpack exited prematurely if 'styles.css' is absent in custom theme folder

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#10621]
### Description of the bug / feature
Vaadin application fails to start with the exception shown below, if `styles.css` stylesheet file is absent in `frontend/themes/my-theme` folder.
This file is supposed to be auto-generated by Vaadin application, if absent. 
Works perfectly with V19+ (latest versions are 19.0.3 and 20.0.0.alpha6 at the moment of this issue was created).

Exception:
```java
2021-04-12 14:00:41.213 ERROR 14119 --- [nio-8080-exec-4] c.v.flow.server.DefaultErrorHandler      : 

java.lang.IllegalStateException: Webpack exited prematurely
        at com.vaadin.flow.server.DevModeHandler.doStartWebpack(DevModeHandler.java:665) ~[flow-server-2.6.0.beta1.jar:2.6.0.beta1]
        at com.vaadin.flow.server.DevModeHandler.doStartDevModeServer(DevModeHandler.java:591) ~[flow-server-2.6.0.beta1.jar:2.6.0.beta1]
        at com.vaadin.flow.server.DevModeHandler.runOnFutureComplete(DevModeHandler.java:538) ~[flow-server-2.6.0.beta1.jar:2.6.0.beta1]
        at com.vaadin.flow.server.DevModeHandler.lambda$new$0(DevModeHandler.java:148) ~[flow-server-2.6.0.beta1.jar:2.6.0.beta1]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774) ~[na:1.8.0_242]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750) ~[na:1.8.0_242]
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457) ~[na:1.8.0_242]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_242]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_242]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_242]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_242]
```
### Minimal reproducible example
1. Go to start.vaadin.com and choose `Vaadin 14.6 (pre)` option.
2. Download the project and add `frontend/themes/myapp` folder and `@Theme(themeFolder = "myapp")` annotation to `MainView` class.
3. Start the app and notice no `styles.css` has been created and exception thrown.
4. Stop the app, create `styles.css` manually under `frontend/themes/myapp` and start the app again.
5. Check that app starts and behaves fine.
### Expected behavior
`frontend/themes/myapp/styles.css` is being created automatically, no exception.
### Actual behavior
Exception thrown.
### Versions:
    - Vaadin / Flow version: V14.6.0.alpha2, Flow 2.6.0.beta1
    - Java version: 8
    - OS version: Mac OS
    - Browser version (if applicable): Chrome 89
    - Application Server (if applicable): spring-boot
    - IDE (if applicable): IntelliJ IDEA 2020.3

**Comment by mshabarov** [comment]
Marked it as a `Major`, because there is an evident workaround with adding this file manually.

**Comment by caalador** [comment]
Seems that webpack is running in production mode for some reason.
```
2021-04-15 09:52:33.163 ERROR 6776 --- [onPool-worker-9] dev-webpack                              : Failed webpack:
Webpack build failed with errors:
Error: styles.css file is missing and is needed for 'myTheme' in folder 'D:\Bugs\my-app\frontend\themes\myTheme'
    at generateThemeFile (D:\Bugs\my-app\node_modules\@vaadin\application-theme-plugin\theme-generator.js:81:13)
    at handleThemes (D:\Bugs\my-app\node_modules\@vaadin\application-theme-plugin\theme-handle.js:122:23)
    at findThemeFolderAndHandleTheme (D:\Bugs\my-app\node_modules\@vaadin\application-theme-plugin\theme-handle.js:64:23)
```

**Comment by mshabarov** [comment]
`devMode` option is missing in the `themeOptions` in `webpack.generated.js`.
It is present in Flow 6.0+:

```javascript
const themeOptions = {
  devMode: devMode,
....
```

Thus, it decides that it is a production mode, because `!devMode` is true
