### ISSUE TITLE
Graceful failure suggested when using untyped List in Endpoint bean

### ISSUE THREAD

**Issue by markhm** [vaadin/flow#10624]
### Description of the bug / feature
When an Endpoint uses a bean that contains a List that is not typed, Fusion does not start and fails with a scary, non-informative error. 

### Minimal reproducible example
We came across this by accident when defining the following bean: 
```
      public class PageResult {

          public List content;
          public int totalPages;
          public long totalElements;
          public int number;
          public int size;
          public int numberOfElements;          
      }
```
Note that the List is not typed. 

### Expected behavior
Failing is acceptable / understood, but it would be good if this could be done in an informative way. 

### Actual behavior
The error was the same as described in [this issue](https://github.com/vaadin/flow/issues/10256). 
```
java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.Schema.getName()" because "schema" is null
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.collectUsedTypesFromSchema(OpenApiObjectGenerator.java:501) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.collectUsedTypesFromSchema(OpenApiObjectGenerator.java:517) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.lambda$collectUsedTypesFromSchema$21(OpenApiObjectGenerator.java:531) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.collectUsedTypesFromSchema(OpenApiObjectGenerator.java:530) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.generatedRelatedSchemas(OpenApiObjectGenerator.java:774) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.parseNonEndpointClassAsSchema(OpenApiObjectGenerator.java:466) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.createSchemasFromQualifiedNameAndType(OpenApiObjectGenerator.java:490) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.init(OpenApiObjectGenerator.java:229) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiObjectGenerator.generateOpenApi(OpenApiObjectGenerator.java:181) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiSpecGenerator.generateOpenApiSpec(OpenApiSpecGenerator.java:80) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.connect.generator.OpenApiSpecGenerator.generateOpenApiSpec(OpenApiSpecGenerator.java:112) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.frontend.fusion.TaskGenerateOpenApiImpl.execute(TaskGenerateOpenApiImpl.java:65) ~[fusion-endpoint-7.0.0.alpha5.jar:na]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:739) ~[flow-server-7.0.0.alpha5.jar:7.0.0.alpha5]
	at com.vaadin.flow.server.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:492) ~[flow-server-7.0.0.alpha5.jar:7.0.0.alpha5]
	at com.vaadin.flow.server.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:380) ~[flow-server-7.0.0.alpha5.jar:7.0.0.alpha5]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```  
### Versions:
This issue was confirmed in `19.0.3`, `19.0.4` and `20.0.0alpha7`.

**Comment by Artur-** [comment]
List and List<Object> should probably be treated equally. Maybe with an additional warning as you should avoid using untyped lists
