### ISSUE TITLE
migration tool: java.lang.StringIndexOutOfBoundsException: String index out of range: 23

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#10896]
Running migration tool built from sources from flow 2.6 branch, I'm getting
```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 23
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.vaadin.flow.migration.CopyMigratedResourcesStep$CopyMigratedFiles.rewriteImport(CopyMigratedResourcesStep.java:116)
	at com.vaadin.flow.migration.CopyMigratedResourcesStep$CopyMigratedFiles.handle(CopyMigratedResourcesStep.java:79)
	at com.vaadin.flow.migration.AbstractCopyResourcesStep$CopyFileVisitor.visitFile(AbstractCopyResourcesStep.java:88)
	at com.vaadin.flow.migration.AbstractCopyResourcesStep$CopyFileVisitor.visitFile(AbstractCopyResourcesStep.java:68)
```

Indeed, the `CopyMigratedResourcesStep:116` reads
```
            char quote = importLine.charAt(line.length() - 2);
```
while it should read
```
            char quote = importLine.charAt(importLine.length() - 2);
```

**Comment by denis-anisimov** [comment]
You are right, thanks.
