### ISSUE TITLE
NPE in QueryParameters.parseQueryString if location contains colon

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#11019]
Steps to reproduce:
1. Generate project with Flow views using SVC
2. Start project
3. Navigate to `http://localhost:8080/a:`
4. Observe NPE in server logs:

```java
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "query" is null
	at com.vaadin.flow.router.QueryParameters.parseQueryString(QueryParameters.java:119) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.router.QueryParameters.fromString(QueryParameters.java:114) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.router.Location.parseParams(Location.java:247) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.router.Location.<init>(Location.java:60) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler$JavaScriptBootstrapContext.initRoute(JavaScriptBootstrapHandler.java:90) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.server.BootstrapHandler$BootstrapContext.<init>(BootstrapHandler.java:224) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler$JavaScriptBootstrapContext.<init>(JavaScriptBootstrapHandler.java:83) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler.createBootstrapContext(JavaScriptBootstrapHandler.java:160) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1309) ~[flow-server-7.0.0.beta3.jar:7.0.0.beta3]
```

**Comment by miguelatvaadin** [comment]
Hi @fluorumlabs ,

I have repeated your steps but I was not able to see the NPE in the server logs. 

It's truth that I got a weird white page when I asked for any route finished with `:`, but it also happens with V19 (not with V14).

Could you please provide more details so it can be reproduced?

**Comment by fluorumlabs** [comment]
I'm testing against hybrid fusion/flow app using Vaadin 20.0.0.beta1. I have some memories that starting with 20, the handling of initial navigation has changed, and the location is always passed via `location` query parameter in the `?v-r=init` request

**Comment by miguelatvaadin** [comment]
Ok. Thanks a lot for the comment, @fluorumlabs .

I will check again. As soon as I can reproduce the NPE I will label it, so it can be addressed

**Comment by miguelatvaadin** [comment]
I'm sorry but I'm not able to see the NPE. I have tried with 20.0.0.beta1, with an hybrid fusion/flow app, trying several urls ending with `:` and I have never seen the NPE. 

To finish sooner, is there any way you could share the project? Thanks

**Comment by fluorumlabs** [comment]
It seems that just comma is not enough, but that URL seems to be the one you're looking for: `http://localhost:8080/xxx:xxx/xxx?xxx`

**Comment by miguelatvaadin** [comment]
Yes. That made the difference. Thanks, @fluorumlabs
