### ISSUE TITLE
InvalidPathException: Illegal char @polymer

### ISSUE THREAD

**Issue by lsiem** [vaadin/flow#11110]
### Description of the bug / feature

When I try to launch my Spring app on Windows, I get the following error message:
```
java.nio.file.InvalidPathException: Illegal char <
> at index 43: @polymer/polymer/lib/elements/custom-style'

const $_documentContainer = document.createElement('template'
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:230) ~[na:na]
	at java.base/java.nio.file.Path.resolve(Path.java:515) ~[na:na]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.resolve(AbstractUpdateImports.java:579) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.visitImportsRecursively(AbstractUpdateImports.java:516) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.handleImports(AbstractUpdateImports.java:553) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.visitImportsRecursively(AbstractUpdateImports.java:537) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.handleImports(AbstractUpdateImports.java:553) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getUniqueEs6ImportPaths(AbstractUpdateImports.java:349) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getModuleLines(AbstractUpdateImports.java:385) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.collectModules(AbstractUpdateImports.java:298) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:107) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:389) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:512) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:325) ~[flow-server-2.4.4.jar:2.4.4]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:369) ~[vaadin-spring-12.3.2.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4714) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5177) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:434) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) ~[tomcat-embed-core-9.0.41.jar:9.0.41]
...

```
This seems to be a Windows specific error, as this problem does not occur under Linux.

### Minimal reproducible example

I have not yet managed to reproduce the error.

### Expected behavior

The Spring app should run normally with embedded Tomcat.

### Actual behavior

I get the above exception.

### Versions:
    - Vaadin / Flow version: 14.3.7
    - Java version: 16
    - OS version: Windows 10 Home 20H2
    - Browser version (if applicable):
    - Application Server (if applicable): Embedded Tomcat 9
    - IDE (if applicable): Intellij IDEA Ultimate 2021.1.1

**Comment by pleku** [comment]
Hello. First can you update your Vaadin version to 14.6.1 since 14.3 has not been supported for quite some time. For the 14 long term support release, only the latest minor release is supported as each new minor release is backwards compatible.

So @lsiem please test with a newer version to see if the issue reproduces.

**Comment by lsiem** [comment]
Thanks for the reply and the reminder to update Vaadin. Unfortunately, the problem still occurs with version 14.6.1.

**Comment by pleku** [comment]
@lsiem ok that is unfortunate, but without the steps to reproduce the issue, like the template that triggers the error, we cannot do anything about this.

Also I'm wondering why you reported that the issue was in Vaadin 14.3.7 and then the stack trace points to `flow-server` version 2.4.4. Maybe there is something completely broken in your project configuration and the used version is not right. With a Maven project, you can use `mvn dependency:tree` to actually see what versions are actually in use.

**Comment by denis-anisimov** [comment]
Sorry, but until you can provide the code that reproduces the issue, there is nothing that we can do. Until that we consider this an issue specific to your application. Please reopen the issue if you discover a root cause not dependent on your application and can provide the code to reproduce the issue.
