### ISSUE TITLE
Flow Npm 7 Nightly build fails

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#11148]
### Description of the bug / feature
Flow Npm 7 Nightly build has been failing since https://github.com/vaadin/flow/pull/11027 was applied:

https://bender.vaadin.com/viewLog.html?buildId=234665&buildTypeId=Flow_Flow80_Nightly_FlowNpm7Nightly

```
TaskRunNpmInstallTest.runNpmInstall_dirContainsOnlyFlowNpmPackage_npmInstallIsExecuted
TaskRunNpmInstallTest.runNpmInstall_emptyDir_npmInstallIsExecuted
TaskRunNpmInstallTest.runNpmInstall_matchingHashButEmptyModules_npmInstallIsExecuted
TaskRunNpmInstallTest.runNpmInstall_modified_npmInstallIsExecuted
TaskRunNpmInstallTest.runNpmInstall_nodeModulesContainsStaging_npmInstallIsExecuted
TaskRunNpmInstallTest.runNpmInstall_nonEmptyDirNoHashMatch_npmInstallIsExecuted
TaskRunNpmInstallTest.runNpmInstall_nonEmptyDirNoLocalHash_npmInstallIsExecuted
TaskRunNpmInstallTest.runNpmInstall_toolIsChanged_nodeModulesIsRemoved
TaskRunNpmInstallTest.runNpmInstall_toolIsNotChanged_nodeModulesIsNotRemoved
```

```
[Step 6/7] [ERROR] runNpmInstall_toolIsChanged_nodeModulesIsRemoved(com.vaadin.flow.server.frontend.TaskRunNpmInstallTest)  Time elapsed: 0.674 s  <<< ERROR!
[01:40:27]	[Step 6/7] com.vaadin.flow.server.ExecutionFailedException: Npm install has exited with non zero status. Some dependencies are not installed. Check npm command output
[01:40:27]	[Step 6/7] 	at com.vaadin.flow.server.frontend.TaskRunNpmInstall.runNpmInstall(TaskRunNpmInstall.java:434)
[01:40:27]	[Step 6/7] 	at com.vaadin.flow.server.frontend.TaskRunNpmInstall.execute(TaskRunNpmInstall.java:124)
[01:40:27]	[Step 6/7] 	at com.vaadin.flow.server.frontend.TaskRunNpmInstallTest.runNpmInstall_toolIsChanged_nodeModulesIsRemoved(TaskRunNpmInstallTest.java:134)
[01:40:27]	[Step 6/7] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:40:27]	[Step 6/7] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:40:27]	[Step 6/7] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:40:27]	[Step 6/7] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[01:40:27]	[Step 6/7] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
[01:40:27]	[Step 6/7] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
[01:40:27]	[Step 6/7] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
[01:40:27]	[Step 6/7] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
[01:40:27]	[Step 6/7] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[01:40:27]	[Step 6/7] 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
[01:40:27]	[Step 6/7] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[01:40:27]	[Step 6/7] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
[01:40:27]	[Step 6/7] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
[01:40:27]	[Step 6/7] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
[01:40:27]	[Step 6/7] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[01:40:27]	[Step 6/7] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

### Versions:
    - Vaadin / Flow version: Flow 7.0-SNAPSHOT and 8.0-SNAPSHOT
    - Npm version: 7

**Comment by pleku** [comment]
The build is not needed anymore, NOOP.
