### ISSUE TITLE
ParentTemplateIT tests fail with 12.4 Spring in BowerMode

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#11154]
### Description of the bug / feature

The following tests have been failing randomly in the Flow 2.6/2.7 Spring in BowerMode Validation probably because of this fix https://github.com/vaadin/flow/commit/e4cf42f11ce79a309025611295ffafac252ed247  (but it should be investigated):

1. ParentTemplateIT::injectedComponentIsSpringManaged
https://bender.vaadin.com/viewLog.html?buildId=234886&buildTypeId=Flow_Flow27_AddOns_FlowSpring124BowerMode
```
java.lang.RuntimeException: injectedComponentIsSpringManaged[ANY_Chrome_](com.vaadin.flow.spring.test.ParentTemplateIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.vaadin.flow.testutil.TestBenchHelpers$$Lambda$417/214371754@4b2ff1da (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-184.eu-west-1.compute.internal', ip: '172.16.1.184', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.123-111.109.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: com.vaadin.testbench.TestBenchDriverProxy_$$_jvst421_0
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.85, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.SEXwH4}, goog:chromeOptions: {debuggerAddress: localhost:41223}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 52805a0a61f72c87c6185f11edc...}
Session ID: 52805a0a61f72c87c6185f11edcb3422
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:223)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:247)
	at com.vaadin.flow.testutil.TestBenchHelpers.getShadowRoot(TestBenchHelpers.java:417)
	at com.vaadin.flow.testutil.TestBenchHelpers.getInShadowRoot(TestBenchHelpers.java:212)
	at com.vaadin.flow.spring.test.ParentTemplateIT.injectedComponentIsSpringManaged(ParentTemplateIT.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
------- Stderr: -------
Jun 03, 2021 11:35:29 PM com.vaadin.testbench.parallel.SauceLabsIntegration setDesiredCapabilities
WARNING: Null or empty sauce.options given. Ignoring.
Jun 03, 2021 11:35:29 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Jun 03, 2021 11:35:40 PM com.vaadin.testbench.parallel.SauceLabsIntegration setDesiredCapabilities
WARNING: Null or empty sauce.options given. Ignoring.
Jun 03, 2021 11:35:40 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

![image](https://user-images.githubusercontent.com/61410877/120752964-2920d480-c513-11eb-9b45-5d38782ec973.png)

2. ParentTemplateIT::customElementIsRegistered

https://bender.vaadin.com/viewLog.html?buildId=234225&buildTypeId=Flow_Flow27_AddOns_FlowSpring124BowerMode

```
java.lang.RuntimeException: customElementIsRegistered[ANY_Chrome_](com.vaadin.flow.spring.test.ParentTemplateIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for com.vaadin.flow.testutil.TestBenchHelpers$$Lambda$419/1414002819@7e5f9c41 (tried for 10 second(s) with 500 milliseconds interval)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-59.eu-west-1.compute.internal', ip: '172.16.1.59', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.123-111.109.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: com.vaadin.testbench.TestBenchDriverProxy_$$_jvst226_0
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 90.0.4430.85, chrome: {chromedriverVersion: 90.0.4430.24 (4c6d850f087da..., userDataDir: /tmp/.com.google.Chrome.oa6GmZ}, goog:chromeOptions: {debuggerAddress: localhost:46613}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true, webdriver.remote.sessionid: 3e7a58ce889809f783d9f9b1027...}
Session ID: 3e7a58ce889809f783d9f9b10276f9d8
	at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:223)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:247)
	at com.vaadin.flow.testutil.TestBenchHelpers.getShadowRoot(TestBenchHelpers.java:417)
	at com.vaadin.flow.testutil.TestBenchHelpers.getInShadowRoot(TestBenchHelpers.java:212)
	at com.vaadin.flow.spring.test.ParentTemplateIT.customElementIsRegistered(ParentTemplateIT.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
------- Stderr: -------
Jun 01, 2021 9:11:59 AM com.vaadin.testbench.parallel.SauceLabsIntegration setDesiredCapabilities
WARNING: Null or empty sauce.options given. Ignoring.
Jun 01, 2021 9:11:59 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Jun 01, 2021 9:12:10 AM com.vaadin.testbench.parallel.SauceLabsIntegration setDesiredCapabilities
WARNING: Null or empty sauce.options given. Ignoring.
Jun 01, 2021 9:12:10 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

![image](https://user-images.githubusercontent.com/61410877/120753304-a3515900-c513-11eb-81fe-970df9fbe58e.png)

3. TemplatePushIT::callFunctionPushed

https://bender.vaadin.com/viewLog.html?buildId=234484&buildTypeId=Flow_Flow27_AddOns_FlowSpring124BowerMode

```
java.lang.RuntimeException: callFunctionPushed[ANY_Chrome_](com.vaadin.flow.spring.test.TemplatePushIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.openqa.selenium.NoSuchElementException: No element with tag  found with the attributes [id='callFunctionTest'] using index 0
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-16-1-226.eu-west-1.compute.internal', ip: '172.16.1.226', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.154-128.181.amzn2.x86_64', java.version: '1.8.0_201'
Driver info: driver.version: unknown
	at com.vaadin.testbench.ElementQuery.get(ElementQuery.java:303)
	at com.vaadin.testbench.ElementQuery.first(ElementQuery.java:243)
	at com.vaadin.testbench.ElementQuery.id(ElementQuery.java:152)
	at com.vaadin.flow.spring.test.TemplatePushIT.callFunctionPushed(TemplatePushIT.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:494)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:468)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:59)
	... 12 more
------- Stderr: -------
Jun 02, 2021 5:49:34 AM com.vaadin.testbench.parallel.SauceLabsIntegration setDesiredCapabilities
WARNING: Null or empty sauce.options given. Ignoring.
Jun 02, 2021 5:49:34 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Jun 02, 2021 5:49:35 AM com.vaadin.testbench.parallel.SauceLabsIntegration setDesiredCapabilities
WARNING: Null or empty sauce.options given. Ignoring.
Jun 02, 2021 5:49:36 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
```

![image](https://user-images.githubusercontent.com/61410877/120753575-09d67700-c514-11eb-9675-a8b172b492e4.png)

**Comment by mshabarov** [comment]
The issue has suddenly gone for both Flow 2.6 and 2.7. Under monitoring for a while.

**Comment by mshabarov** [comment]
Not reproduced anymore.
