### ISSUE TITLE
Flow client module fails to build due to ESLint error

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#11176]
### Description of the bug / feature

Flow 6, 7, 8 SNAPSHOT validation builds fail on the `flow-client` module build phase with the following error:
```
[00:28:51]W:		 [com.vaadin:flow-client] 
[00:28:51]W:		 [com.vaadin:flow-client] Oops! Something went wrong! :(
[00:28:51]W:		 [com.vaadin:flow-client] 
[00:28:51]W:		 [com.vaadin:flow-client] ESLint: 7.21.0
[00:28:51]W:		 [com.vaadin:flow-client] 
[00:28:51]W:		 [com.vaadin:flow-client] /opt/agent/work/9d85dfe0e8dcfc54/flow-client/node_modules/eslint-plugin-lit/lib/rules/attribute-value-entities.js:48
[00:28:51]W:		 [com.vaadin:flow-client]                                 if (!loc || !rawValue?.value) {
[00:28:51]W:		 [com.vaadin:flow-client]                                                       ^
[00:28:51]W:		 [com.vaadin:flow-client] 
[00:28:51]W:		 [com.vaadin:flow-client] SyntaxError: Unexpected token '.'
[00:28:51]W:		 [com.vaadin:flow-client]     at new Script (vm.js:88:7)
[00:28:51]W:		 [com.vaadin:flow-client]     at NativeCompileCache._moduleCompile (/opt/agent/work/9d85dfe0e8dcfc54/flow-client/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
[00:28:51]W:		 [com.vaadin:flow-client]     at Module._compile (/opt/agent/work/9d85dfe0e8dcfc54/flow-client/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
[00:28:51]W:		 [com.vaadin:flow-client]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[00:28:51]W:		 [com.vaadin:flow-client]     at Module.load (internal/modules/cjs/loader.js:863:32)
[00:28:51]W:		 [com.vaadin:flow-client]     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[00:28:51]W:		 [com.vaadin:flow-client]     at Module.require (internal/modules/cjs/loader.js:887:19)
[00:28:51]W:		 [com.vaadin:flow-client]     at require (/opt/agent/work/9d85dfe0e8dcfc54/flow-client/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
[00:28:51]W:		 [com.vaadin:flow-client]     at /opt/agent/work/9d85dfe0e8dcfc54/flow-client/node_modules/requireindex/index.js:52:28
[00:28:51]W:		 [com.vaadin:flow-client]     at Array.forEach (<anonymous>)
[00:28:51]W:		 [com.vaadin:flow-client] npm ERR! code ELIFECYCLE
[00:28:51]W:		 [com.vaadin:flow-client] npm ERR! errno 2
[00:28:51]W:		 [com.vaadin:flow-client] npm ERR! @vaadin/flow-deps@0.0.1 lint: `eslint "src/main/frontend"`
[00:28:51]W:		 [com.vaadin:flow-client] npm ERR! Exit status 2
[00:28:51]W:		 [com.vaadin:flow-client] npm ERR! 
[00:28:51]W:		 [com.vaadin:flow-client] npm ERR! Failed at the @vaadin/flow-deps@0.0.1 lint script.
[00:28:51]W:		 [com.vaadin:flow-client] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[00:28:52]W:		 [com.vaadin:flow-client] 
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! A complete log of this run can be found in:
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR!     /root/.npm/_logs/2021-06-07T21_28_51_996Z-debug.log
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! code ELIFECYCLE
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! errno 2
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! @vaadin/flow-deps@0.0.1 compile: `npm run build && npm run lint`
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! Exit status 2
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! 
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! Failed at the @vaadin/flow-deps@0.0.1 compile script.
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[00:28:52]W:		 [com.vaadin:flow-client] 
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR! A complete log of this run can be found in:
[00:28:52]W:		 [com.vaadin:flow-client] npm ERR!     /root/.npm/_logs/2021-06-07T21_28_52_035Z-debug.log
```

**Comment by Haprog** [comment]
I can't reproduce this locally. `eslint-plugin-lit` 1.5.0 changed few lint rules which introduces couple of lint errors that break the build atm. but I don't get this syntax error.

**Comment by mshabarov** [comment]
I was able to reproduce it after removing `node-modules` and `package-lock.json`

**Comment by Haprog** [comment]
In `flow-client` dir after `rm -rf node_modules package-lock.json && mvn install`
I only get:
```
✖ 114 problems (4 errors, 110 warnings)
  4 errors and 20 warnings potentially fixable with the `--fix` option.

[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```
I do not get the `SyntaxError: Unexpected token '.'`.

**Comment by mshabarov** [comment]
@Haprog Could you please try `mvn clean install -DskipTests -Pvalidation,gen-dev-deps`. I'm not sure %100, but the profile perhaps matters here.

**Comment by Haprog** [comment]
@mshabarov I tried that and still I get only the "4 errors and 20 warnings" and no syntax error.
