### ISSUE TITLE
Exception when starting new Vaadin 21 alpha 3 projects

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11173]
### Description of the bug / feature
```
2021-06-07 16:10:32.540  INFO 76294 --- [  restartedMain] com.example.application.Application      : Started Application in 4.541 seconds (JVM running for 4.988)
Exception in thread "restartedMain" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.NoClassDefFoundError: com/vaadin/flow/server/DevModeHandler
	at org.vaadin.artur.helpers.LaunchUtil.isProductionMode(LaunchUtil.java:21)
	at org.vaadin.artur.helpers.LaunchUtil.launchBrowserInDevelopmentMode(LaunchUtil.java:68)
	at com.vaadin.starterwizard.StarterWizardApplication.main(StarterWizardApplication.java:17)
	... 5 more
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.server.DevModeHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 8 more
```

### Minimal reproducible example
```
vaadin init  --pre v21
cd v21
mvn
```

### Expected behavior
Application starts without errors

### Actual behavior
An exception is printed but the app still works

### Versions:
    - Vaadin / Flow version: 21 alpha 3
    - Java version: 16
    - OS version: macOs Big Sur

**Comment by fluorumlabs** [comment]
https://github.com/Artur-/a-vaadin-helper/blob/master/src/main/java/org/vaadin/artur/helpers/LaunchUtil.java#L9 ?

In V21 `DevModeHandler` is moved to `com.vaadin.flow.internal` package

**Comment by pleku** [comment]
Yes it seems like an add-on incompatibility. While it seems quite unlikely that many add-ons depend on this, the change was not marked as breaking one even if it should have (cc: @haijian-vaadin @joheriks ).  I changed the release notes to highlight the breaking change.

**Comment by haijian-vaadin** [comment]
Oh, yes, should've marked that as a breaking change. Meanwhile, I made a related ticket to the addon https://github.com/Artur-/a-vaadin-helper/issues/8, it could be useful if we want to exclude the `vaadin-dev-server` from the production mode.
