### ISSUE TITLE
Flow startup errors -- better startup error handling with informative messages (Part 2)

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow#11219]
12:17:51.898 INFO [paxweb-extender-1-thread-3] found TLD bundle://e1bcaccd-4778-445a-9a3d-3a0cb173cc9c_108.0:1/META-INF/x.tld
12:17:51.907 INFO [paxweb-extender-1-thread-3] Initializing AtmosphereFramework
12:17:51.910 INFO [paxweb-extender-1-thread-3] No Spring WebApplicationInitializer types detected on classpath
12:17:51.915 ERROR [paxweb-extender-1-thread-3] Error deploying web application
java.lang.NullPointerException: null
	at com.vaadin.flow.server.startup.ApplicationConfiguration.lambda$get$0(ApplicationConfiguration.java:52) ~[?:?]
	at com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:73) ~[?:?]
	at com.vaadin.flow.server.startup.ApplicationConfiguration.get(ApplicationConfiguration.java:49) ~[?:?]
	at com.vaadin.flow.server.DeploymentConfigurationFactory.createPropertyDeploymentConfiguration(DeploymentConfigurationFactory.java:82) ~[?:?]
	at com.vaadin.flow.server.startup.ServletDeployer$StubServletConfig.createDeploymentConfiguration(ServletDeployer.java:186) ~[?:?]
	at com.vaadin.flow.server.startup.ServletDeployer.lambda$getServletConfigurations$0(ServletDeployer.java:293) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_291]
	at com.vaadin.flow.server.startup.ServletDeployer.getServletConfigurations(ServletDeployer.java:292) ~[?:?]
	at com.vaadin.flow.server.startup.ServletDeployer.contextInitialized(ServletDeployer.java:210) ~[?:?]
	at com.vaadin.flow.server.startup.ServletContextListeners.contextInitialized(ServletContextListeners.java:44) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext$3.call(HttpServiceContext.java:339) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext$3.call(HttpServiceContext.java:335) ~[?:?]
	at org.ops4j.pax.swissbox.core.ContextClassLoaderUtils.doWithClassLoader(ContextClassLoaderUtils.java:60) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.callContextInitialized(HttpServiceContext.java:334) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:997) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:746) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.startContext(HttpServiceContext.java:392) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:911) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doStart(HttpServiceContext.java:268) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[?:?]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerImpl$1.start(JettyServerImpl.java:327) ~[?:?]
	at org.ops4j.pax.web.service.internal.HttpServiceStarted.end(HttpServiceStarted.java:1264) ~[?:?]
	at org.ops4j.pax.web.service.internal.HttpServiceProxy.end(HttpServiceProxy.java:456) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.RegisterWebAppVisitorWC.end(RegisterWebAppVisitorWC.java:405) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.model.WebApp.accept(WebApp.java:658) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.register(WebAppPublisher.java:228) ~[?:?]
	at org.ops4j.pax.web.extender.war.internal.WebAppPublisher$WebAppDependencyListener.addingService(WebAppPublisher.java:173) ~[?:?]

There is some analysis here at https://github.com/vaadin/flow/issues/11178 but I would like to see some more sensible error message at application startup however.

Vaadin 20.0.1

**Comment by enver-haase** [comment]
Could you please amend the error report in #11240 to hint people that the broken project set-up may mean "webapp/WEB-INF/web.xml" could have "metadata-complete="true" set (which disables scanning) or there may be an empty or incomplete "<absolute-ordering>" in that file or that there might be a Tomcat specific "webapp/META-INF/context.xml" with a <JarScanner> tag to disable scanning?

**Comment by pleku** [comment]
>Could you please amend the error report in #11240 to hint people that the broken project set-up may mean "webapp/WEB-INF/web.xml" could have metadata-complete="true" set (which disables scanning) or there may be an empty or incomplete <absolute-ordering> in that file or that there might be a Tomcat specific "webapp/META-INF/context.xml" with a <JarScanner> tag to disable scanning?

To be honest, where does the list have to end ? I think the error message should say what could be wrong in the project when there is only one, maybe two, alternatives. Otherwise I think it should be in some troubleshoot doc that is referred to from the error message.

**Comment by pleku** [comment]
@enver-haase please open a new issue and we'll figure out if we add it to the error or to docs.

I still consider this to be fixed.
