### ISSUE TITLE
Unable to read webpack stats file. 

### ISSUE THREAD

**Issue by corbettcode** [vaadin/flow#11258]
### Description of the bug / feature
Switch from 14.5.5 to 14.6.3 and now getting the following error:
com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.

Any ideas on what should be done to fix this?
### Versions:
    - Vaadin / Flow version:
    - Java version: 11
    - OS version: Pop Os 20.10
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Tomcat
    - IDE (if applicable): Intellij 2021.1.2

**Comment by caalador** [comment]
For webpack has probably failed with an exception and should be printed out somewhere.
If no webpack exception can be found there is the possibility to try running in the project folder `node node_modules/webpack/bin/webpack.js` and see if that passes the build.

With this information the only idea would be to remove the `node_modules` folder and try again.

**Comment by corbettcode** [comment]
Tried version 14.6.4 and still getting the same error:
2021-06-23 07:30:43.623 ERROR 10170 --- [0.1-8080-exec-7] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/development] threw exception [com.vaadin.flow.server.ServiceException: com.vaadin.flow.server.BootstrapException: Unable to read webpack stats file.] with root cause

java.net.ConnectException: Connection refused (Connection refused)

**Comment by corbettcode** [comment]
We have tried removing the node_modules folder with the same results

**Comment by corbettcode** [comment]
Output from running 'node node_modules/webpack/bin/webpack.js':

/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error: Cannot find module '@vaadin/stats-plugin'
Require stack:
- /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/webpack.generated.js
- /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/webpack.config.js
- /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/utils/convert-argv.js
- /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/cli.js
- /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/webpack.generated.js:14:21)
    at Module._compile (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/webpack.config.js:6:22)
    at Module._compile (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/yargs/yargs.js:567:18)
    at /home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/webpack.generated.js',
    '/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/webpack.config.js',
    '/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/utils/convert-argv.js',
    '/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack-cli/bin/cli.js',
    '/home/paulcorbett/corbettcode/clients/MedWorxs/onerev14/JavaModules/onerev-application/node_modules/webpack/bin/webpack.js'
  ]
}

**Comment by knoobie** [comment]
Looks like you have the wrong version of flow somewhere in your classpath. Your stacktrace mentioned "flow-server-2.5.4.jar:2.5.4" - this is the version distributed within Vaadin 14.5.x. in Vaadin 14.6.x you should get flow-server-2.6.x

Wild guess: you have different versions specified for your vaadin dependency and vaadin-maven-plugin. Probably the later, has the wrong version. 

Using the same version on both sides should do the trick.

**Comment by estronque** [comment]
I got the same error: "Unable to read webpack stats file" because I used an old node version download with maven plugin com.github.eirslett. I removed com.github.eirslett plugin and node was download by vaadin pluging and now works. 

https://vaadin.com/docs/v14/guide/install/frontend

**Comment by corbettcode** [comment]
Okay, this is weird: Rebuilt for 14.6.4, looked at external libraries which showed version 2.5.4. Closed intellij and reopened, version is now 2.6.4 and the application is running. Not sure how it is working but we are all celebrating! Thanks to everyone!

**Comment by caalador** [comment]
The exception `Error: Cannot find module '@vaadin/stats-plugin'` that you got for webpack with node points to the missing plugin that would not be installed with a version before Flow 2.6 as the feature was first introduced in Vaadin 14.6
The main problem here was that the webpack.generated.js was updated to the 2.6 version, but during execution the new tasks for copying plugins didn't run due to Idea starting with Flow 2.5 on the class path

**Comment by caalador** [comment]
I'm closing the issue as resolved as there isn't much we can do to the IDE using the wrong version on the classpath.

**Comment by pleku** [comment]
> I'm closing the issue as resolved as there isn't much we can do to the IDE using the wrong version on the classpath.

One thing we could do @caalador is an enhancement which checks the used flow version versus the maven/gradle plugin (+maybe dev-server?) version and then fail with a clear error. Not sure if we have an issue open for that already.
