### ISSUE TITLE
Relative path cannot start with /

### ISSUE THREAD

**Issue by penninghlhd** [vaadin/flow#11302]
**Describe the bug**
Since Vaadin Flow 14.6.1/2 the following warning is filling up our logs and eventually causing out-of-memory. It seems to be caused by a brute force attack targeting WordPress related files.

**To Reproduce**
Unknown

**Expected behavior**
Ideally Vaadin platform would detect brute-force attacks like this automatically and block it. If not, then please change the exception handling for incorrect relative paths such that it is not reported as a warning.

**Screenshots**
[qtp601893033-137] WARN com.vaadin.flow.router.Router - Exception when parsing location path /wp-includes/wlwmanifest.xml
java.lang.IllegalArgumentException: Relative path cannot start with /
	at com.vaadin.flow.router.Location.verifyRelativePath(Location.java:313)
	at com.vaadin.flow.router.Location.parsePath(Location.java:275)
	at com.vaadin.flow.router.Location.<init>(Location.java:74)
	at com.vaadin.flow.router.Router.getLocationForRequest(Router.java:115)
	at com.vaadin.flow.router.Router.resolveNavigationTarget(Router.java:153)
	at com.vaadin.flow.server.BootstrapUtils.resolvePageConfigurationHolder(BootstrapUtils.java:456)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapContext.<init>(BootstrapHandler.java:208)
	at com.vaadin.flow.server.BootstrapHandler.createBootstrapContext(BootstrapHandler.java:1580)
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1530)
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:474)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1570)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:590)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by denis-anisimov** [comment]
I don't see this as a bug.
This is rather an enhancement: it doesn't break anything.
Logger can be configured so that it ignores unwanted messages.

The log message about wrong location path can be useful for someone else: if it's not an intentional attack then it makes sense to see for the developer than something wrong has happened.

On the other hand if it's an intentional illegal URL request then it's worth to ignore such messages.
But again: this is a feature/enhancement request, not a bug.

I can suggest two ways here to solve this :
- to be able to simplify filtering the log messages we can introduce a specific `Marker` for such location parsing exceptions. The it's up to developer to use slf4j implementations and configure them to filter messages based on markers
- use `ErrorHandler` and introduce a dedicated `Exception` to distinguish event handling for these cases

the first approach is based on the already existing slf4j mechanisms and API but filtering is not a part of slf4j and it means that the solution will depend on chosen logger impl for slf4j.

The second approach will be Vaadin specific and doesn't rely on any logger impl. The developer will have to define its own `ErrorHandler` to be able to handle such errors differently.

Another approach : combine both cases . Use `ErrorHandler`  for this case and make an impl which uses markers.
I would go with the last one. 
And anyway: I'm going to keep the log level as is. So the default behavior won't be changed anyhow.
To be able to avoid undesired messages you should change the `DefaultErrorHandler` behavior via providing your own impl of `ErrorHandler`.

**Comment by knoobie** [comment]
@denis-anisimov I'm wondering about the javadoc of `Location` in this case, as it says `A possible "/" prefix of the location is ignored and a <code>null</code> location is interpreted as <code>""</code>` (on master). 

Could be the bug about, that this "behaviour" wasn't backported to 2.6/2.7?

**Comment by denis-anisimov** [comment]
I doubt.
I don't know the exact reasons for allowing `/` in the `Location` path but this is something for the `master` only :https://github.com/vaadin/flow/pull/10570

There are no reasons to have leading slash in any other branch for Location since it's removed by Router from the pathInfo before Location is created .

Anyway it doesn't fix anything since it's still possible to use as many leading slashes as you want and then it's still be invalid path in the `Location. and the exception will be thrown.

**Comment by pleku** [comment]
I've been looking at #9443 and it is relevant to this in the sense that if the `Location` cannot be created, then we should not return a 404 but 400 and thus not even create an UI for this case. I'm not sure if we need a dedicated error that is proposed in #11367 but lets see. Maybe it would be useful for customizing the default behavior that will change based on #9443. For logging, maybe the solution could be to just report the 400 as an one-liner message with WARNING level instead of the full stack trace.

**Comment by denis-anisimov** [comment]
Generic notions:
- we are tool lazy but in fact every time when we do a validation a dedicated exception has to be used instead a generic one. We are using only two exceptions everywhere: ISE and IAE. This is a  bad style.
- If we use logger then it should not be _our_ decision how to log the exception: the decision should be made via logger customization. Logging one-liner message with WARNING level is invalid approach: information is lost when it's written. It's developer decision how it want to see the log messages. Using a dedicated exceptions allows to use filters and output customizations for logger.

**Comment by pleku** [comment]
> Logging one-liner message with WARNING level is invalid approach: information is lost when it's written. It's developer's decision how he wants to see the log messages. Using a dedicated exceptions allows to use filters and output customizations for logger

I don't see how the stack trace helps or what information it gives to any developer when the reason is simply "Received request with malformed characters for route path <path>, returning 400". But yeah it is not even clear if that message is interesting, and they should be able to filter those messages if they don't care.
