### ISSUE TITLE
JsModules from addons are not loaded when running the Application class for Spring Boot

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#11325]
Based on new comments from #7752 from @stefanuebe:
"
This issue seems to still exists somehow, we have that now in a V20 project. I'll try to create a sample project with the reproducable issue.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sample.app.SampleCardView': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [sample.app.SampleCardView]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'content-card' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1316) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.8.jar:5.3.8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:314) ~[spring-beans-5.3.8.jar:5.3.8]
	at com.vaadin.flow.spring.SpringInstantiator.getOrCreate(SpringInstantiator.java:117) ~[vaadin-spring-17.0.1.jar:na]
	at com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:193) ~[flow-server-7.0.2.jar:7.0.2]
```

Reproduced with
1) clone https://github.com/vaadin/skeleton-starter-flow-spring (v20 branch is default)
2) add for instance
```
<dependency>
    <groupId>com.github.appreciated</groupId>
    <artifactId>card</artifactId>
    <version>2.0.0</version>
</dependency>
```
4) then clean install and run as a Spring Boot Java App.
"

**Comment by caalador** [comment]
This is the same problem as for #11220 

Webpack generates the name as `../target/flow-frontend/com/github/appreciated/card/content-card.js` and in the BundleParser we search for the fileName as is and with some changes if the module name contains either `node_modules/@vaadin/flow-frontend/` or `target/flow-frontend/` but due to the fix for supporting gradle builds with `build` instead of `target` the getFlowResourcesFolder (which basically returns `target/flow-frontend`) returns for windows `target\flow-frontend` as we use Paths.get to build the actual folder path. So in this instance we can't find the template because we don't remove the `./` in the beginning as the module name doesn't contain `target\flow-frontend` as it contains `target/flow-frontend`

This doesn't fail in the test as there we give the paths as written using mockito.
