### ISSUE TITLE
Do not log the full stack trace when the connection to webpack dev server is broken

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11390]
### Description of the bug / feature
If you make some change in the project that causes webpack to totally fail, e.g. remove an npm dependency used in the theme you see:

In the server log:
```
ℹ ｢wdm｣: Compiling...
/.../target/plugins/application-theme-plugin/theme-copy.js:133
    throw Error("Missing npm modules '" + missingModules.join("', '")
    ^
Error: Missing npm modules '...' for assets marked in 'theme.json'.
Install package(s) by adding a @NpmPackage annotation or install it using 'npm/pnpm i'
    at copyStaticAssets (/.../target/plugins/application-theme-plugin/theme-copy.js:133:11)
    at handleThemes (/.../target/plugins/application-theme-plugin/theme-handle.js:151:5)
    at findThemeFolderAndHandleTheme (/.../target/plugins/application-theme-plugin/theme-handle.js:95:23)
    at processThemeResources (/.../target/plugins/application-theme-plugin/theme-handle.js:68:5)
    at ThemeLiveReloadPlugin.processThemeResourcesCallback (/.../webpack.generated.js:201:51)
    at /.../target/plugins/theme-live-reload-plugin/theme-live-reload-plugin.js:98:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/.../node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:50:1)
    at Watching._go (/.../node_modules/webpack/lib/Watching.js:41:32)
    at Watching._invalidate (/.../node_modules/webpack/lib/Watching.js:169:9)
    at /.../node_modules/webpack/lib/Watching.js:138:11
2021-07-08 09:25:33.336 ERROR 30110 --- [nio-8080-exec-5] c.v.flow.server.DefaultErrorHandler      : 
```

Then it is followed by 
```
2021-07-08 09:25:33.336 ERROR 30110 --- [nio-8080-exec-5] c.v.flow.server.DefaultErrorHandler      : 

java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:669) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:645) ~[na:na]
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:497) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:600) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351) ~[na:na]
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:372) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1299) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1232) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1120) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1051) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1653) ~[na:na]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577) ~[na:na]
        at com.vaadin.flow.server.frontend.FrontendUtils.getFileFromWebpack(FrontendUtils.java:701) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.server.frontend.FrontendUtils.getFileContent(FrontendUtils.java:528) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.server.frontend.FrontendUtils.getIndexHtmlContent(FrontendUtils.java:515) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getIndexHtmlDocument(IndexHtmlRequestHandler.java:280) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.synchronizedHandleRequest(IndexHtmlRequestHandler.java:86) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1535) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:302) ~[flow-server-8.0.0.alpha10.jar:8.0.0.alpha10]
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109) ~[vaadin-spring-18.0.0.alpha4.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:457) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:645) ~[javax.servlet-api-4.0.1.jar:4.0.1]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.5.jar:5.3.5]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.5.jar:5.3.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.5.jar:5.3.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.5.jar:5.3.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.5.jar:5.3.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.44.jar:9.0.44]
        at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
```

Each time you reload the browser to see if it was a temporary problem, the above exception is logged 6 times more.

Logging this message gives no information and only makes it harder to see the cause of the problem.

### Minimal reproducible example
```
npx @vaadin/cli init hello
cd hello
```
Add `,"assets": {"fake": {"foo":"bar" }}` to frontend/themes/hello/theme.json
```
mvn
```

### Expected behavior
The exception is shown in the browser but not at all in the server logs

### Actual behavior
6 exceptions in the server log on each refresh

### Versions:
    - Vaadin / Flow version: 14.6.5

**Comment by denis-anisimov** [comment]
This is not a bug: it works as designed.
The exception is something which prevents application being normally functioning.
So it may not be silently ignored.

The exception is not something special with a specific handling: it's just caught inside `VaadinService` in the same way as any other exception and it goes through `ErrorHandler`.
It's up to you to change the default implementation of `ErrorHandler` and do what you want.

Logging can't be done in this way as well: it's incorrect to decide what information should be logged.
The decision should be made by the developer via Logger configuration.

For someone the stacktrace doesn't say anything , for others it's important information. That's why logger should log the exception and then it's up to logger configuration to filter out messages.

This issue may be considered as an enhancement. But the description needs improvement and proper design should be suggested.
At the moment with the current design it says that: don't log _ANY_ exception which breaks the application : this exception is just a generic `IOException` which is caught by the `VaadinService` via `ErrorHandler`.

If you consider some specific use case separately then it should be described in details: what exceptions should be logged and how. 
- Is the exception inside `FrontendUtils.getFileFromWebpack` the only which should be handled in a specific way?
- Is _any_ exception  inside `FrontendUtils.getFileFromWebpack` should be handled in a specific way or just only specific exceptions?

Without the proper clarification this has no chance to be fixed.

**Comment by Artur-** [comment]
`DefaultErrorHandler` would probably be the place to change this so the defaults are good. Right now the defaults are spammy.

I don't know where the exceptions originate but all exceptions that mean "Can't serve this dev mode request because I can't reach the webpack dev server" feel unnecessary to log to the server log. It is enough that they go to the browser, where you can see them.

**Comment by Artur-** [comment]
This works much better in v23 where the actual cause is logged instead of ´java.net.ConnectException: Connection refused
`. It is still logged many times though
