### ISSUE TITLE
Flow 8.0 snapshot sometimes is failing because of startup time test

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#11449]
There are several random failure recently in Flow 8.0/9.0 SNAPSHOT validation.

https://bender.vaadin.com/viewLog.html?buildId=244065&buildTypeId=Flow_Flow80_Flow80Snapshot
https://bender.vaadin.com/viewLog.html?buildId=244024&buildTypeId=Flow_Flow90_Flow90Snapshot

```
java.lang.RuntimeException: devModeInitializerToWebpackUpIsBelowThreshold[ANY_Chrome_](com.vaadin.flow.testnpmonlyfeatures.performanceregression.StartupPerformanceIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:78)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: startup time expected <= 12000 but was 60942
```

Looks like a test issue since the time increase is too high.

**Comment by caalador** [comment]
Closing as Flow 8.0/9.0 are not maintained.
