### ISSUE TITLE
Flow 2.6/2.7  Windows validation fails with because of DependencyTreeCacheTest::parallelParsing_potentialSpeedup

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#11485]
```
java.lang.AssertionError: Did not observe both slowdown and speedup. Max duration: 223, min duration: 80
com.vaadin.flow.component.internal.DependencyTreeCacheTest.parallelParsing_potentialSpeedup(DependencyTreeCacheTest.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by denis-anisimov** [comment]
Happens in every branch : 2.6, 2.7, 7.0, ...
