### ISSUE TITLE
Webpack exited prematurely

### ISSUE THREAD

**Issue by colinduplantis** [vaadin/flow#11536]
### Description of the bug / feature

Vaadin 20 app does not start. Tried Vaadin Dance (https://mvysny.github.io/Vaadin-troubleshooting). Problem occurs on multiple machines.

### Minimal reproducible example
Download sample app from https://vaadin.com/start. Choose Vaadin 20 and simply download the app first thing - all defaults.
Run app:
$ mvn
### Expected behavior
Should serve basic webpage at localhost:8080
### Actual behavior
```
------------------ Starting Frontend compilation. ------------------
2021-08-06 09:11:10.202  INFO 743747 --- [onPool-worker-1] com.vaadin.flow.server.DevModeHandler    : Running webpack to compile frontend resources. This may take a moment, please stand by...
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/tmp/x/my-app/node_modules/.pnpm/workbox-webpack-plugin@6.1.0_webpack@4.46.0/node_modules/workbox-webpack-plugin/build/generate-sw.js:20:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2021-08-06 09:11:12.637 ERROR 743747 --- [nio-8080-exec-7] c.v.flow.server.DefaultErrorHandler      : 

java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.flow.server.DevModeHandler.doStartWebpack(DevModeHandler.java:732) ~[flow-server-7.0.5.jar:7.0.5]
	at com.vaadin.flow.server.DevModeHandler.doStartDevModeServer(DevModeHandler.java:658) ~[flow-server-7.0.5.jar:7.0.5]
	at com.vaadin.flow.server.DevModeHandler.runOnFutureComplete(DevModeHandler.java:555) ~[flow-server-7.0.5.jar:7.0.5]
	at com.vaadin.flow.server.DevModeHandler.lambda$new$0(DevModeHandler.java:165) ~[flow-server-7.0.5.jar:7.0.5]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[na:1.8.0_221]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[na:1.8.0_221]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443) ~[na:1.8.0_221]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_221]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_221]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_221]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_221]

```

### Versions:
    - Vaadin / Flow version: 20
    - Java version: 1.8
    - OS version: Ubuntu 20.04.2
    - Browser version (if applicable): Chrome Version 92.0.4515.107 (Official Build) (64-bit) (also Firefox)
    - Application Server (if applicable): n/a
    - IDE (if applicable): n/a

**Comment by knoobie** [comment]
See https://github.com/vaadin/flow/issues/11524 for more information.

**Comment by kolle1986** [comment]
This still happens in 21.0.0.beta1

**Comment by denis-anisimov** [comment]
yes it happens because `21.0.0.beta1` is based on  Flow `8.0.0.beta1` which had been released 8 days ago before fix has been provided : https://github.com/vaadin/flow/releases/tag/8.0.0.beta1.
And there is no yet a new `8.x` Flow release.
