### ISSUE TITLE
NPE after live reload

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#11569]
In Vaadin 21.0.0.beta1, a session that was [deserializedAsEmpty](https://github.com/vaadin/flow/blob/8.0/flow-server/src/main/java/com/vaadin/flow/server/VaadinService.java#L2175-L2183) (#11304) will be unbound. The `lock` however is transient, leading to the following NPE:
```
java.lang.NullPointerException: null
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:720) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:221) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1831) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.session.StandardSession.removeAttribute(StandardSession.java:1317) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.session.StandardSession.removeAttribute(StandardSession.java:1289) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.session.StandardSessionFacade.removeAttribute(StandardSessionFacade.java:153) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at com.vaadin.flow.server.WrappedHttpSession.removeAttribute(WrappedHttpSession.java:126) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
	at com.vaadin.flow.server.VaadinService.readFromHttpSession(VaadinService.java:2169) ~[flow-server-8.0.0.beta1.jar:8.0.0.beta1]
```

Because of #11416
https://github.com/vaadin/flow/blob/32d648beb96fddb2cb811d45f655037b0cfec603/flow-server/src/main/java/com/vaadin/flow/server/VaadinSession.java#L220-L222

**Comment by denis-anisimov** [comment]
I don't understand how this may happen.
The NPE happens in `VaadinSession::unlock` where the lock instance is used to call `unlock`.
If the `lock` instance is null there then it should have been `null` already before this call.
There are a number of places where `lock` instance is used before this call : `VaadinSession:lock` calls `lock` method on the instance, also `VaadinSession::unlock` calling several method on `lock` instance and neither of them throws NPE.

So if `lock` had not been set then NPE should have happened earlier.

So `The lock however is transient`  doesn't work as an argument with this stacktrace for me even though I also don't understand how an empty session could have been locked at all.

So I need the exact steps to reproduce which are mandatory for every ticket.

**Comment by Artur-** [comment]
I see this on almost every server restart of the Start project

**Comment by denis-anisimov** [comment]
Alright..........
My bad.
The `lock` method is called inside `try` though usually it's outside of `try` block.
Then already `lock` throws and code goes inside `finally` block.
And then `checkHasLock` doesn't throw anything since it uses assertions instead of throwing in this specific case.
And then the last `finally` throws NPE.

**Comment by denis-anisimov** [comment]
@Artur- , if you remember this comment from the review: 
https://github.com/vaadin/flow/pull/11304/files#r657904349

This is exactly what happens.
