### ISSUE TITLE
Calling setEnabled(true) on anchor causing an IllegalArgumentException

### ISSUE THREAD

**Issue by karstenlehmann** [vaadin/flow#11571]
### Description of the bug / feature
Calling setEnabled(true) on an anchor without a href set causing an IllegalArgumentException

### Minimal reproducible example
```
Anchor anc = new Anchor();
anc.setEnabled(true);
<VertircalLayout>.add(anc);
```

### Expected behavior
Anchor component enabled without any exception

### Actual behavior
```
java.lang.IllegalArgumentException: Cannot set href to null
at com.vaadin.flow.component.PropertyDescriptors$PropertyDescriptorImpl.set(PropertyDescriptors.java:67)
at com.vaadin.flow.component.PropertyDescriptor.set(PropertyDescriptor.java:53)
at com.vaadin.flow.component.Component.set(Component.java:481)
at com.vaadin.flow.component.html.Anchor.setHref(Anchor.java:119)
at com.vaadin.flow.component.html.Anchor.restoreHref(Anchor.java:210)
```

### Versions:
    - Vaadin / Flow version: 20.0.6
    - Java version: 11
    - OS version: Windows

**Comment by denis-anisimov** [comment]
The fix for disabled `Anchor` is removed overall. So this is not an issue anymore.
