### ISSUE TITLE
NullPointerException in StateNode when setting locale and using UI.getCurrent() inside localeChange callback.

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/flow#11599]
### Description of the bug / feature
NullPointerException when changing locale
### Minimal reproducible example

Sometimes when changing the locale when Push is enabled, Vaadin throws a NullPointerException. It's difficult to reproduce.

### Expected behavior
No Exception should be thrown
### Actual behavior
A NullPointer Exception is thrown because in StateNode::dumpBeforeClientResponseEntries() there is a check missing for `entries == null`

![image](https://user-images.githubusercontent.com/2902403/129920187-86a21320-4fee-46d4-a007-f9a8543cfc38.png)

```
java.lang.RuntimeException: Push failed
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:200) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:175) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.component.UI.push(UI.java:686) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:708) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1474) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1549) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109) ~[vaadin-spring-17.0.2.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.45.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.6.jar:5.3.6]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.6.jar:5.3.6]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.45.jar:9.0.45]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-
	...
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.ArrayList.isEmpty()" because "entries" is null
	at com.vaadin.flow.internal.StateNode.dumpBeforeClientResponseEntries(StateNode.java:1026) ~[flow-server-7.0.6.jar:7.0.6]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.vaadin.flow.internal.StateTree.flushCallbacks(StateTree.java:407) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:384) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:391) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:174) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:212) ~[flow-server-7.0.6.jar:7.0.6]
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:196) ~[flow-server-7.0.6.jar:7.0.6]
	... 46 common frames omitted
```
### Versions:
    - Vaadin / Flow version: 20.0.6
    - Java version: 15
    - OS version: Windows 11
    - Browser version (if applicable): All
    - Application Server (if applicable): Tomcat/Spring
    - IDE (if applicable): IntelliJ

**Comment by Legioth** [comment]
This is typically the symptom of doing changes without properly locking the session. How is that locale change applied?

Vaadin will apply some additional checks for potentially missing the lock if the JVM is run with assertions enabled (`-ea` when running from the command line). Could you try running your application with that setting to potentially get some additional information?

**Comment by mrgreywater** [comment]
Adding the -ea parameter doesn't seem to trigger any assertion.

I get the following message as well (but only after this exception is thrown a few times):
2021-08-18 17:19:53.872  WARN 2928 --- [io-8080-exec-10] c.v.f.server.communication.PushHandler   : Error while unlocking session

Here is how the locale is changed: https://github.com/KasparScherrer/language-select/blob/master/src/main/java/ch/carnet/kasparscherrer/LanguageSelect.java#L68

**Comment by Legioth** [comment]
Thanks for the additional details.

There doesn't seem to be any direct indication of missing session locking in this case since the locale change is triggered from the value change listener of a Vaadin component. There could in theory be some hidden causes e.g. if some attached component does something unconventional in their `localeChange` method, but that's also quite unlikely if it doesn't trigger any extra assertion with `-ea`.

That leaves the possibility that there's something broken with the state management related to `StateNode::beforeClientResponseEntries`. There is an implicit assumption that any node that is added to `StateTree::pendingExecutionNodes` does also have a non-null `beforeClientResponseEntries` field but there might be some special case when this assumption doesn't hold true. There might be something related to components being attached or detached under unsuitable circumstances or something related to the way `VaadinSession::setLocale` affects all UIs in the session at the same time and `@Push` is causing changes for all of them to be written out immediately.

**Comment by mrgreywater** [comment]
I don't know this internal code at all, but I find it curious that both the function `StateNode::hasBeforeClientResponseEntries` above and the function below `StateNode::addBeforeClientResponseEntry` seem to expect that `beforeClientResponseEntries` can be null.

**Comment by mshabarov** [comment]
Can't say whether the workaround for this even exists, before making a minimal reproduce example.
I'll try to reproduce it.
Assuming that this issue comes randomly and it needs a Push to be set up, I think this is not probably about simply adding a `null` check into `dumpBeforeClientResponseEntries()`.

**Comment by mshabarov** [comment]
I couldn't reproduce this exception.
Here are the steps I used:
1. Example project based on Vaadin 20.0.7 with LanguageSelect component and Push:
[my-app-set-locale.zip](https://github.com/vaadin/flow/files/7048076/my-app-set-locale.zip)
2. Run `mvn`
3. Open `localhost:8080` in many tabs in two different browsers (chrome and safari in my case).
4. Refresh the pages and select the language randomly on tabs, many times.

**Comment by mrgreywater** [comment]
I can't reproduce it with your test project either, but in my original project I can. I'll try to figure out out what's missing to reproduce the issue (could be the I18NProvider, a side effect of running multiple SpringApplets, or side effect of something inside the localeChange callbacks).
