### ISSUE TITLE
Exception on every startup with Flow 8 rc 1

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#11620]
I see this on every startup of the Start project using 21.0.0.rc1

```
Mon Aug 23 14:55:05 EEST 2021
There was an unexpected error (type=Internal Server Error, status=500).
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinService.runPendingAccessTasks(com.vaadin.flow.server.VaadinSession)" because the return value of "com.vaadin.flow.server.VaadinSession.getService()" is null
com.vaadin.flow.server.ServiceException: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinService.runPendingAccessTasks(com.vaadin.flow.server.VaadinSession)" because the return value of "com.vaadin.flow.server.VaadinSession.getService()" is null
	at com.vaadin.flow.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1594)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1557)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:302)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:457)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
```

**Comment by Artur-** [comment]
To reproduce:
```
vaadin init hello
cd hello
mvn
# Wait for app to start, then ctrl-c
mvn
```

There seems to be two cases that can happen:

Case 1.
When pressing ctl-c, the following is logged
```
WARN 87674 --- [ionShutdownHook] com.vaadin.flow.server.VaadinSession     : A VaadinSession instance not associated to any service is getting unbound. Session destroy events will not be fired and UIs in the session will not get detached. This might happen if a session is deserialized but never used before it expires.
```
This seems to lead to the following logging on the next startup
```
2021-08-23 15:21:47.630 ERROR 87903 --- [  restartedMain] o.a.catalina.session.StandardManager     : Exception loading sessions from persistent storage

java.io.EOFException: null
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readBoolean(ObjectInputStream.java:3319) ~[na:na]
	at java.base/java.io.ObjectInputStream.readBoolean(ObjectInputStream.java:1047) ~[na:na]
	at com.vaadin.flow.server.VaadinSession.readObject(VaadinSession.java:1048) ~[flow-server-8.0.0.rc1.jar:8.0.0.rc1]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1224) ~[na:na]
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2378) ~[na:na]
```


Case 2.
Nothing is logged when pressing ctrl-c and the message in the issue is shown in the browser and logged as the first message (instead of the message about waiting for webpack to start)
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinService.runPendingAccessTasks(com.vaadin.flow.server.VaadinSession)" because the return value of "com.vaadin.flow.server.VaadinSession.getService()" is null
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:703)
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:221)
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1860)
	at org.apache.catalina.session.StandardSession.removeAttribute(StandardSession.java:1337)
	at org.apache.catalina.session.StandardSession.removeAttribute(StandardSession.java:1308)
	at org.apache.catalina.session.StandardSessionFacade.removeAttribute(StandardSessionFacade.java:153)
	at com.vaadin.flow.server.WrappedHttpSession.removeAttribute(WrappedHttpSession.java:126)
	at com.vaadin.flow.server.VaadinService.readFromHttpSession(VaadinService.java:2179)
	at com.vaadin.flow.server.VaadinService.loadSession(VaadinService.java:2153)
	at com.vaadin.flow.server.VaadinService.getExistingSession(VaadinService.java:1007)
	at com.vaadin.flow.server.VaadinService.doFindOrCreateVaadinSession(VaadinService.java:857)
	at com.vaadin.flow.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:832)
	at com.vaadin.flow.server.VaadinService.findVaadinSession(VaadinService.java:691)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1539)
```

**Comment by mshabarov** [comment]
This issue has been placed in P1 - good to fix it before the final release of flow 8.
