### ISSUE TITLE
BinderConverterValidatorTest.convertInvalidDataToField is flaky

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#11925]
BinderConverterValidatorTest.convertInvalidDataToField fails in flow PR validations sometimes.

<img width="1377" alt="Screenshot 2021-09-24 at 9 58 24" src="https://user-images.githubusercontent.com/61410877/134631811-02938d1f-5edd-403b-b325-b78bc76fb018.png">

https://teamcity.vaadin.com/viewLog.html?buildId=90832&buildTypeId=Flow_FlowTests

```
java.lang.Exception: Unexpected exception, expected<java.lang.IllegalArgumentException> but was<java.lang.NullPointerException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:30)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.data.binder.DefaultBindingExceptionHandler.handleException(DefaultBindingExceptionHandler.java:66)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1538)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.initFieldValue(Binder.java:1343)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.access$200(Binder.java:1176)
	at com.vaadin.flow.data.binder.Binder.lambda$readBean$2(Binder.java:2115)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.data.binder.Binder.readBean(Binder.java:2107)
	at com.vaadin.flow.data.binder.BinderConverterValidatorTest.convertInvalidDataToField(BinderConverterValidatorTest.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
```

**Comment by denis-anisimov** [comment]
This is called apparently by the latest changes in the Binder (exception handling) and the fact that some test doesn't clean up `UI` instance in the end of the execution,

I've fixed it ( I believe ) in one of my PRs.
It's too tricky  to find the test which is guilty in this behavior but at least `UI` can be cleaned up in the `BinderConverterValidatorTest` in `@Before`.
