### ISSUE TITLE
NullPointerException during WrappedSession.removeAttribute(String)

### ISSUE THREAD

**Issue by TobseF** [vaadin/flow#12088]
### Describe the bug

I noticed a `NullPointerException` during a `handleRequest` beause 
> _`Cannot invoke "com.vaadin.flow.server.WrappedSession.removeAttribute(String)" because "httpSession" is null`_

Because the stacktrace is triggered by a request and not during page load or a special site interaction, it's hard to reproduce it. Anyway the question is, if this `removeAttribute(String)` function shouldn't be null-safe. Or maybe one step further, the `WrappedSession` should not be created, with a nulled Session. The exception happens in Vaadin internals, so it's not clear if I should try to catch this Exception or if this is a framework bug.

The setup uses the [MPR](https://vaadin.com/multiplatform-runtime), but the stracktrace seems to bee independent from the MPR stuff.

Maybe the bug is a also related to: https://github.com/vaadin/multiplatform-runtime/issues/95

### ⚡ Stacktrace
``` java
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.WrappedSession.removeAttribute(String)" because "httpSession" is null
caused by: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.WrappedSession.removeAttribute(String)" because "httpSession" is null
at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62)
at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2056)
at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:699)
at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1498)
at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1573)
at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:252)
at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:111)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
```

### System Info

Project with MPR
vaadin-14.version: `14.7.1`
vaadin-8.version: `8.14.1`
vaadin.flow.plugin.version: `2.7.2`

**Comment by ZheSun88** [comment]
@TobseF Thanks for the ticket.. i move it to flow repo for further investigation.
