### ISSUE TITLE
NullPointerException in VaadinService.requestEnd because the return value of "VaadinRequest.getAttribute(s)" is null

### ISSUE THREAD

**Issue by TobseF** [vaadin/flow#12099]
I noticed a `NullPointerException` during a `VaadinService.requestEnd`: 
``` java
Cannot invoke "java.lang.Long.longValue()" because 
   the return value of "com.vaadin.flow.server.VaadinRequest.getAttribute(String)" is null
```

The stacktrace is triggered by a request:
> `c.v.f.server.communication.PushHandler   : Error while ending request [] `

Because the stracktrace only contains framework classes, it seems to be a framework bug.

The setup uses the [MPR](https://vaadin.com/multiplatform-runtime), but the stracktrace seems to be independent from the MPR stuff.

### ⚡ Stacktrace
``` java
java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "com.vaadin.flow.server.VaadinRequest.getAttribute(String)" is null
	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1494)
	at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:257)
	at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:522)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224)
	at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264)
	at org.eclipse.jetty.websocket.jsr356.endpoints.JsrEndpointEventDriver.onConnect(JsrEndpointEventDriver.java:144)
	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.openSession(AbstractEventDriver.java:216)
	at org.eclipse.jetty.websocket.jsr356.endpoints.AbstractJsrEventDriver.openSession(AbstractJsrEventDriver.java:103)
	at org.eclipse.jetty.websocket.common.WebSocketSession.open(WebSocketSession.java:488)
	at org.eclipse.jetty.websocket.common.WebSocketSession.onOpened(WebSocketSession.java:454)
	at org.eclipse.jetty.io.AbstractConnection.onOpened(AbstractConnection.java:213)
	at org.eclipse.jetty.io.AbstractConnection.onOpen(AbstractConnection.java:205)
	at org.eclipse.jetty.io.AbstractEndPoint.upgrade(AbstractEndPoint.java:442)
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:388)
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:734)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:363)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

### ℹ System Info

vaadin-14.version: `14.7.2`
vaadin-8.version: `8.14.1`
mpr-core: `2.2.5`
vaadin.flow.plugin.version: `2.7.2`

**Comment by caalador** [comment]
The base issue is that `requestStart` was not called successfully for a websocket push request.

This probably has something to do with MPR as there we basically have 2 push, but we route everything through flow push as looking at the code it should always do `requestEnd` for push if websocket and the same variable is used to run `requestStart` so it shouldn't get a null attribute there.
