### ISSUE TITLE
NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinSession.getErrorHandler()" logged when session is closed

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#12100]
### Description of the bug / feature
If your session times out, you may get the following exception:
```
com.vaadin.flow.component.UI             : Cannot invoke "com.vaadin.flow.server.VaadinSession.getErrorHandler()" because the return value of "com.vaadin.flow.component.UI.getSession()" is null

java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinSession.getErrorHandler()" because the return value of "com.vaadin.flow.component.UI.getSession()" is null
	at com.vaadin.flow.component.UI$2.handleError(UI.java:531) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.FutureAccess.handleError(FutureAccess.java:76) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2045) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:709) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2005) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1972) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1012) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinService.fireSessionDestroy(VaadinService.java:632) ~[flow-server-8.0.2.jar:8.0.2]
	at com.vaadin.flow.server.VaadinSession.valueUnbound(VaadinSession.java:204) ~[flow-server-8.0.2.jar:8.0.2]
	at org.apache.catalina.session.StandardSession.removeAttributeInternal(StandardSession.java:1860) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:861) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:660) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:608) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:591) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5622) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1365) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1347) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.52.jar:9.0.52]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

This is due to `getSession()` returning `null`. 
### Minimal reproducible example
(fresh project from start.vaadin.com)
[status-dashboard.zip](https://github.com/vaadin/flow/files/7380170/status-dashboard.zip)
### Expected behavior
Log should not show a NullPointerException but either nothing or a sensible message stating that the session has expired or somethingsimilar. 
### Actual behavior
NPE is shown in the log.
### Versions:
    - Vaadin / Flow version: Vaadin 21.0.2
    - Java version: 17
    - OS version: Windows 10
    - Browser version (if applicable): n/a
    - Application Server (if applicable): Spring Boot embedded Tomcat
    - IDE (if applicable): n/a

**Comment by miguelatvaadin** [comment]
Hi Olli,

definitely I'm not able to reproduce it. I have left the application running for more than 1 hour to let the session end several times and I have never experienced the issue you describe.

Surely one collegue will contact you during next days, in order to dig deeper into this.

Thanks!

**Comment by OlliTietavainenVaadin** [comment]
Unfortunately, I've also had problems being able to reproduce the issue. It's weird because when I _was_ able to reproduce the issue, it was consistent (even if slow to appear) - and when I was running the application in Debug, I was able to add the breakpoint and see the issue occur live.

**Comment by Artur-** [comment]
Saw this today in an start.vaadin.com "all" project using 14.7.8, running with command line Maven. Potentially related to using a collaboration engine view in the session

**Comment by Artur-** [comment]
What happens in my case is:
1. The session times out
2. `fireSessionDestroy` is called and this uses `session.access`
3. `session.access` first clears the access queue by running whatever is pending
4.  There is a pending `com.vaadin.collaborationengine.ComponentConnectionContext$$Lambda$1108.0x00000008011b9a28` command in the access queue 
5. `UI.access` throws `UIDetachedException` when running the command
6. The exception is passed to the command itself if it is of type `ErrorHandlingCommand` but in this case `UI.access` has wrapped the command into an `ErrorHandlingCommand` and handles the exception in `UI.access` as https://github.com/vaadin/flow/blob/42d71bed3c08a01f62ac9361c6cdbe9d21cec610/flow-server/src/main/java/com/vaadin/flow/component/UI.java#L531-L532

It seems that the problem is that the wrapping in UI.access assumes that the UI is always attached when an error occurs. That is not true.
