### ISSUE TITLE
[Vite] Handle removal of custom theme files

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#12154]
After #12113 adding theme files updates the custom theme, but removing a file will result in 
```
[hmr] Failed to reload /themes/myapp/components/vaadin-text-field.css. This could be due to syntax errors or importing non-existent modules. (see errors above)
```

Initial insight would be that the plugin is executed too early and the file seems to be removed after rebuild as in the logs can be seen:
```
Going through directory vitejs\frontend\themes\myapp\components
Trace: files in directory [ 'vaadin-text-field.css' ]
```

**Comment by mcollovati** [comment]
Other issues with theme live reload and Vite.
Perhaps we should add some guard as in `ThemeLiveReloadPlugin` used for webpack

```
[vite] page reload themes/app-theme/components/vaadin-text-field.css
[vite] page reload generated/theme-app-theme.generated.js
[vite] page reload generated/theme-parent-theme.generated.js
[vite] page reload generated/theme-app-theme.generated.js
[vite] page reload themes/app-theme/components/vaadin-text-field.css
Failed to resolve import "./theme-app-theme.generated.js" from "frontend/generated/theme.js". Does the file exist?
[vite] Internal server error: Failed to resolve import "./theme-app-theme.generated.js" from "frontend/generated/theme.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/marco/projects/vaadin/flow/flow_develop/flow-tests/test-application-theme/test-theme-component-live-reload/frontend/generated/theme.js
  1  |  import {applyTheme as _applyTheme} from './theme-app-theme.generated.js';
     |                                           ^
  2  |  export const applyTheme = _applyTheme;
  3  |
      at formatError (/home/marco/projects/vaadin/flow/flow_develop/flow-tests/test-application-theme/test-theme-component-live-reload/node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39055:46)
      at TransformContext.error (/home/marco/projects/vaadin/flow/flow_develop/flow-tests/test-application-theme/test-theme-component-live-reload/node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39051:19)
      at normalizeUrl (/home/marco/projects/vaadin/flow/flow_develop/flow-tests/test-application-theme/test-theme-component-live-reload/node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58329:26)
      at async TransformContext.transform (/home/marco/projects/vaadin/flow/flow_develop/flow-tests/test-application-theme/test-theme-component-live-reload/node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:58478:57)
      at async Object.transform (/home/marco/projects/vaadin/flow/flow_develop/flow-tests/test-application-theme/test-theme-component-live-reload/node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39292:30)
      at async doTransform (/home/marco/projects/vaadin/flow/flow_develop/flow-tests/test-application-theme/test-theme-component-live-reload/node_modules/.pnpm/vite@2.9.13/node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:50012:29)
```

**Comment by mcollovati** [comment]
Can be easily replicated running `ComponentThemeLiveReloadIT` (`flow-tests/test-application-theme/test-theme-component-live-reload/`) with Vite enabled.
To be noted that for Webpack, `watchOption.aggregateTimeout=5` has been added to `webpack.config.js` to make the test more reliable

**Comment by mcollovati** [comment]
It seems like the culprit for this issue is that Vite `handleHotUpdate` hook is invoked only for file changes, not for creation nor deletion
