### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry

### ISSUE THREAD

**Issue by allenvpn312** [vaadin/flow#12638]
### Description of the bug

After upgrading to Spring Boot version 2.6.2 and Vaadin flow 14.8.0, I am unable to launch the app due to the following errors:
`Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry
    at eval (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/elements/dom-module.js:168:16)
    at Module.../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/elements/dom-module.js (http://localhost:8080/VAADIN/build/vaadin-bundle-e03170e883ed0c89ced3.cache.js:915:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-e03170e883ed0c89ced3.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/utils/style-gather.js:10:81)
    at Module.../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/utils/style-gather.js (http://localhost:8080/VAADIN/build/vaadin-bundle-e03170e883ed0c89ced3.cache.js:1287:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-e03170e883ed0c89ced3.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/element-mixin.js:8:80)
    at Module.../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/mixins/element-mixin.js (http://localhost:8080/VAADIN/build/vaadin-bundle-e03170e883ed0c89ced3.cache.js:1023:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-e03170e883ed0c89ced3.cache.js:64:30)
    at eval (webpack-internal:///../node_modules/.pnpm/@polymer/polymer@3.2.0/node_modules/@polymer/polymer/lib/legacy/legacy-element-mixin.js:4:82)`

Ran npx find-duplicate-dependencies and got this:

`This package has the following duplicate dependencies:
@polymer/polymer :
[
  {
    name: '@polymer/polymer',
    version: '3.2.0',
    from: undefined,
    path: 'no-name/@lrnwebcomponents/pdf-browser-viewer/@polymer/paper-card/@polymer/iron-image'
  },
  {
    name: '@polymer/polymer',
    version: undefined,
    from: undefined,
    path: 'no-name/@lrnwebcomponents/pdf-browser-viewer'
  }
]

svg.select.js :
[
  {
    name: 'svg.select.js',
    version: undefined,
    from: undefined,
    path: 'no-name/apexcharts/svg.resize.js'
  },
  {
    name: 'svg.select.js',
    version: '3.0.1',
    from: undefined,
    path: 'no-name/apexcharts'
  }
]

Please run "npm dedupe" to see if that could be fixed. If not, manually resolve version conflicts`

I am at a lost how to resolve this issue.  Please advise.

Thank you

### Expected behavior

Expecting Spring boot 2.6.2 and Vaadin flow 14.8.0 upgrade not to break app.

### Minimal reproducible example

Update pom

Spring Boot to version 2.6.2
Vaadin to version 14.8.0

### Versions

- Vaadin / Flow version: 14.8
- Java version: 11
- OS version: Windows 10
- Browser version (if applicable): Chrome
- Application Server (if applicable): Tomcat 9
- IDE (if applicable): Eclipse 2020-12

**Comment by allenvpn312** [comment]
Found out the issue was the pdf-browser add-on by Alejandro Duarte.  I removed the add-on and it works correctly now.
