### ISSUE TITLE
Node 17 built with openssl < 3 does not work with Vaadin 21.0.8+

### ISSUE THREAD

**Issue by craigotis** [vaadin/flow#12649]
### Description of the bug

I downloaded a starter Flow 22 project from https://start.vaadin.com/app/, but a clean project fails on `./mvnw` with:

```
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Dec 29 07:27:00 EST 2021
There was an unexpected error (type=Internal Server Error, status=500).
java.lang.IllegalStateException: Webpack exited prematurely
com.vaadin.flow.server.ServiceException: java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.flow.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1616)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1579)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:109)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:353)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevModeServer(AbstractDevServerRunner.java:220)
	at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:172)
	at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

There's no further/more detailed stack trace that I can find.

### Expected behavior

The application should start.

### Minimal reproducible example

1. Visit https://start.vaadin.com/app/
2. Under Settings, change Vaadin version to 22
3. Download project
4. Start with `./mvnw`
5. Browser launches with stacktrace

### Versions

- Vaadin / Flow version: 22.0.2
- Java version: 11
- OS version: macOS 12.1

**Comment by Artur-** [comment]
Do you have Node 17 installed?

**Comment by craigotis** [comment]
@Artur- Yep, seems that way:
```
➜  my-project git:(main) ✗ node -v
v17.3.0
```

**Comment by craigotis** [comment]
Reverting to Node 16 seems to have resolved the issue, I found these seemingly-related tickets suggesting it's an issue between Webpack and Node 17:

https://github.com/microsoft/vscode/issues/136599

https://github.com/webpack/webpack/issues/14532

**Comment by Nyamkhuub** [comment]
@craigotis did you solve this issue? 
I have a same issue with you. I tried to downgrade my node version to 16. 13.1 (LTS). But it's still doesn't work... :( sad ...
Do you have any solution?

**Comment by Nyamkhuub** [comment]
@Artur- any idea?

**Comment by Artur-** [comment]
How can this be reproduced? If I take a Vaadin 22 project from start.vaadin.com and run it with Node 17.3.0, it works fine

**Comment by Nyamkhuub** [comment]
@Artur-  First, sorry about that. And I fixed that issue by changing my node version to 17.3.0. This issue was node version related problem. this has to be closed ...

**Comment by oflege** [comment]
To reproduce:
`git clone https://github.com/vaadin/base-starter-spring-gradle`
`cd base-starter-spring-gradle`
`LOGGING_LEVEL_COM_VAADIN_BASE=TRACE ./gradlew bootRun`

Log ends with

```
------------------ Starting Frontend compilation. ------------------
2022-01-04 08:36:21.886 DEBUG 68414 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  :
/usr/local/bin/node \
    ./node_modules/webpack-dev-server/bin/webpack-dev-server.js \
    --config \
    ./webpack.config.js --port 56574 \
    --watch-options-stdin --devtool=eval-source-map \
    --mode=development

2022-01-04 08:36:21.937  INFO 68414 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : Running Webpack to compile frontend resources. This may take a moment, please stand by...
2022-01-04 08:36:21.952  INFO 68414 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : /usr/local/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

and the webpack server will not be running. 
`--openssl-legacy-provider` is no longer supported in node 17.3.0, so
`com.vaadin.base.devserver.WebpackHandler#updateServerStartupEnvironment` is wrong with
`/usr/local/bin/node --version` = v17.3.0

**Comment by vt512** [comment]
By the way:
It works until Vaadin 21.0.7. Starting from 21.0.8 it fails.

**Comment by Artur-** [comment]
>git clone https://github.com/vaadin/base-starter-spring-gradle
cd base-starter-spring-gradle
LOGGING_LEVEL_COM_VAADIN_BASE=TRACE ./gradlew bootRun

Running this with Node 17.3.0 on a mac results in
```
------------------ Starting Frontend compilation. ------------------
2022-01-04 09:55:24.767 DEBUG 13193 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : 
/Users/artur/.nvm/versions/node/v17.3.0/bin/node \ 
    ./node_modules/webpack-dev-server/bin/webpack-dev-server.js \ 
    --config \ 
    ./webpack.config.js --port 62919 \ 
    --watch-options-stdin --devtool=eval-source-map \ 
    --mode=development 

2022-01-04 09:55:24.794  INFO 13193 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : Running Webpack to compile frontend resources. This may take a moment, please stand by...
2022-01-04 09:55:26.034  INFO 13193 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Project is running at:
2022-01-04 09:55:26.036  INFO 13193 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [webpack-dev-server] Loopback: http://localhost:62919/
```

**Comment by vt512** [comment]
Artur, this is my output with Vaadin 21.0.7:

```----------------- Frontend compiled successfully. -----------------

2022-01-04 09:21:30.972  INFO 24334 --- [onPool-worker-3] c.v.base.devserver.DevModeHandlerImpl    : Started webpack-dev-server. Time: 9416ms
No issues found.
ℹ ｢wdm｣: Compiling...
ℹ ｢wdm｣: wait until bundle finished: /manifest.json
<i> [FlowIdPlugin] Serving the 'stats.json' file dynamically.
⚠ ｢wdm｣: Hash: ef95f837acbe95c5ebc0
Version: webpack 4.46.0
Time: 333ms
Built at: 04.01.2022 09:21:30
        Asset       Size  Chunks             Chunk Names
   index.html  685 bytes          [emitted]  
manifest.json  662 bytes          [emitted]  
        sw.js    744 KiB          [emitted]  
 + 6 hidden assets
Entrypoint bundle = VAADIN/build/vaadin-bundle-8049068bd0ee2c21005a.cache.js
Entrypoint devmodeGizmo = VAADIN/build/vaadin-devmodeGizmo-b6677ccbb1d5947d3c41.cache.js
[./generated/theme-testac.generated.js] 4.69 KiB {bundle} [built]
    + 644 hidden modules

LOG from InjectManifest
<i> The service worker at sw.js will precache
<i>         7 URLs, totaling 19.5 MB.

WARNING in InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.
Child HtmlWebpackCompiler:
     1 asset
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
       1 module
Child InjectManifest:
     1 asset
    Entrypoint InjectManifest = sw.js
       94 modules
ℹ ｢wdm｣: Compiled with warnings.

----------------- Frontend compiled successfully. -----------------

No issues found.
```


And with Vaadin 21.0.8 the output ends with the node error message:

```
2022-01-04 09:23:30.189  INFO 24620 --- [onPool-worker-3] c.v.base.devserver.DevModeHandlerImpl    : Starting webpack-dev-server

------------------ Starting Frontend compilation. ------------------
2022-01-04 09:23:30.652  INFO 24620 --- [onPool-worker-3] c.v.base.devserver.DevModeHandlerImpl    : Running webpack to compile frontend resources. This may take a moment, please stand by...
/usr/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by vt512** [comment]
My environment for my last comment:

- Project from start.vaadin.com (Vaadin Version changed in pom.xml)
- Linux
- Node 17.3.0
- AdoptOpenJDK 11.0.11

**Comment by Artur-** [comment]
Does `/usr/bin/node --version` really say 17.3.0 or could there be multiple node versions?

**Comment by vt512** [comment]
/usr/bin/node --version
v17.3.0

**Comment by Artur-** [comment]
Not sure what is going on then
```
/usr/bin/node --help
```
should list 
```
--openssl-legacy-provider  enable OpenSSL 3.0 legacy provider
```
/usr/bin/node   -p 'crypto.createHash("md4")'
```
should fail with "Error: error:0308010C:digital envelope routines::unsupported"

and
```
node --openssl-legacy-provider  -p 'crypto.createHash("md4")'
```
should work and output 
```
Hash { 
...
```
and the same for
```
NODE_OPTIONS=--openssl-legacy-provider node -p 'crypto.createHash("md4")'
```

**Comment by vt512** [comment]
```
> /usr/bin/node --help | fgrep ssl
  --openssl-config=...        load OpenSSL configuration from the
  --use-openssl-ca            use OpenSSL's default CA store

> /usr/bin/node -p 'crypto.createHash("md4")'
Hash {
  _options: undefined,
  [Symbol(kHandle)]: Hash {},
  [Symbol(kState)]: { [Symbol(kFinalized)]: false }
}

> /usr/bin/node --openssl-legacy-provider -p 'crypto.createHash("md4")'
/usr/bin/node: bad option: --openssl-legacy-provider

> NODE_OPTIONS=--openssl-legacy-provider /usr/bin/node -p 'crypto.createHash("md4")'
/usr/bin/node: --openssl-legacy-provider is not allowed in NODE_OPTIONS
```

**Comment by Artur-** [comment]
We might need a fix similar to https://github.com/cloudflare/wrangler/commit/38e32d1c2859e7339c625b1d69610f29e1ddf596 then if it is possible that Node 17 is built with an older openssl

**Comment by oflege** [comment]
that seems to be it, node built w/ openssl@1.1 (default for `brew install node`) does not work on my mac, after switching to nvm v17.3.0 the sample project works

**Comment by Artur-** [comment]
I think we should actually skip the version detection completely and instead check using
```
/usr/bin/node -p 'crypto.createHash("md4")'
```

If that works, then webpack should work. If it fails, then you need the legacy option
