### ISSUE TITLE
Vaadin 23.0.0.alpha2 uses nodejs v17.3.0 by default which fails to build the production artifact

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#12732]
### Description of the bug

Vaadin 23.0.0.alpha2 uses nodejs v17.3.0 by default which seems to fail to build the production artifact. I'm building my Gradle-based app on Heroku and this is the output:

```
       * What went wrong:

       Execution failed for task ':vaadinBuildFrontend'.

       > Webpack process exited with non-zero exit code.

         Stderr: 'Error: error:0308010C:digital envelope routines::unsupported

             at new Hash (node:internal/crypto/hash:67:19)

             at Object.createHash (node:crypto:130:10)

             at module.exports (/tmp/build_79b192e9/node_modules/webpack/lib/util/createHash.js:135:53)

             at NormalModule._initBuildHash (/tmp/build_79b192e9/node_modules/webpack/lib/NormalModule.js:417:16)

             at handleParseError (/tmp/build_79b192e9/node_modules/webpack/lib/NormalModule.js:471:10)

             at /tmp/build_79b192e9/node_modules/webpack/lib/NormalModule.js:503:5

             at /tmp/build_79b192e9/node_modules/webpack/lib/NormalModule.js:358:12

             at /tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:373:3

             at iterateNormalLoaders (/tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:214:10)

             at iterateNormalLoaders (/tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:221:10)

             at /tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:236:3

             at runSyncOrAsync (/tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:130:11)

             at iterateNormalLoaders (/tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:232:2)

             at Array.<anonymous> (/tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:205:4)

             at Storage.finished (/tmp/build_79b192e9/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)

             at /tmp/build_79b192e9/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9

         /tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:106

         			throw new Error("callback(): The callback was already called.");

         			      ^

         

         Error: callback(): The callback was already called.

             at context.callback (/tmp/build_79b192e9/node_modules/loader-runner/lib/LoaderRunner.js:106:10)

             at Object.ESBuildLoader (/tmp/build_79b192e9/node_modules/esbuild-loader/dist/loader.js:62:9)

             at processTicksAndRejections (node:internal/process/task_queues:96:5)

         

         Node.js v17.3.0

         node:internal/process/promises:246

                   triggerUncaughtException(err, true /* fromPromise */);

                   ^

         

         RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 409.

             at /tmp/build_79b192e9/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47

             at processTicksAndRejections (node:internal/process/task_queues:82:21) {

           code: undefined,

           signal: undefined

         }

         

         Node.js v17.3.0

         '
```

Indeed, when running gradle with `--info`, Vaadin Gradle plugin confirms it's using nodejs 17.3.0:

```
       Running the vaadinBuildFrontend task with effective configuration VaadinFlowPluginExtension(productionMode=true, webpackOutputDirectory=/tmp/build_54de079d/build/resources/main/META-INF/VAADIN/webapp, npmFolder=/tmp/build_54de079d, generatedFolder=/tmp/build_54de079d/build/frontend, frontendDirectory=/tmp/build_54de079d/frontend, generateBundle=true, runNpmInstall=true, generateEmbeddableWebComponents=true, frontendResourcesDirectory=/tmp/build_54de079d/src/main/resources/META-INF/resources/frontend, optimizeBundle=true, pnpmEnable=false, useGlobalPnpm=false, requireHomeNodeExec=false, useDeprecatedV14Bootstrapping=false, eagerServerLoad=false, applicationProperties=/tmp/build_54de079d/src/main/resources/application.properties, openApiJsonFile=/tmp/build_54de079d/build/generated-resources/openapi.json, javaSourceFolder=/tmp/build_54de079d/src/main/java, javaResourceFolder=/tmp/build_54de079d/src/main/resources, generatedTsFolder=/tmp/build_54de079d/frontend/generated, nodeVersion=v17.3.0, nodeDownloadRoot=https://nodejs.org/dist/, nodeAutoUpdate=falseresourceOutputDirectory=/tmp/build_54de079d/build/vaadin-generatedpostinstallPackages=[])
       
       
```

Downgrading node.js version to v16.13.2 fixes the issue:

```
vaadin {
    nodeVersion = "v16.13.2"
}
```

### Expected behavior

The production build should succeed on nodejs 17

### Minimal reproducible example

1. Install nodejs 17
2. rm -rf ~/.vaadin
3. git-clone https://github.com/mvysny/karibu10-helloworld-application
4. git checkout 98edb385146a619f5fd68ba25b84f5514469ae6c
5. ./gradlew -Pvaadin.productionMode

### Versions

- Vaadin / Flow version: 23.0.0.alpha2, Flow 10.0.0.alpha3
- Java version: 11
- OS version: Ubuntu 21.10 x86-64

**Comment by mvysny** [comment]
Fixed by https://github.com/vaadin/flow/pull/12726
