### ISSUE TITLE
PiT v23: Upgrading from v22, unable to delete file in node_module

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#12810]
### Description of the bug

When bumping from v22 to v23 (alpha3) flow is unable to remove certain files under node_modules folder, and fronted compilation fails

### Expected behavior

No errors should be shown and compilation succeeded 

### Minimal reproducible example

```
git clone https://github.com/vaadin/base-starter-flow-osgi.git 
cd base-starter-flow-osgi/
git checkout v22 
mvn clean install
mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=23.0.0.alpha3
mvn clean install
```

Note that it also happens when migrating other projects, I found the same problem in:
- Karaf example: https://github.com/vaadin/vaadin-flow-karaf-example (master to v23)
- Start LTS app with all views: https://start.vaadin.com/app?preset=all-lts (v24 to v23)

### workaround

Either:
- Use pnpm in v23
- Remove manually `node_modules`

### Versions

- Vaadin / Flow version: v23.0.0.alpha3
- Java version: 11
- OS version: mac and linux

**Comment by manolo** [comment]
Reopening because it is still an issue in `alpha4`

You can reproduce following these steps

```
# Download the project
curl "https://start.vaadin.com/dl?preset=all-lts&projectName=all-lts" -o all-lts.zip

# Uncompress
unzip all-lts
cd all-lts
# Run dev-mode and check that app works
mvn

# Add vaadin-prereleases repository to pom.xml
<repository><id>vaadin</id><url>https://maven.vaadin.com/vaadin-prereleases/</url></repository>
<pluginRepository><id>vaadin</id><url>https://maven.vaadin.com/vaadin-prereleases/</url></pluginRepository>

# Bump version to V23 alpha4
mvn versions:set-property -Dproperty=vaadin.version -DnewVersion=23.0.0.alpha4

# Adapt API from v14 to v23 

## Remove Annotations (PWA, Theme, Push) from src/main/java/com/example/application/views/MainLayout.java
## Add the following code to src/main/java/com/example/application/Application.java
import com.vaadin.flow.component.page.AppShellConfigurator;
import com.vaadin.flow.component.page.Push;
import com.vaadin.flow.router.PageTitle;
import com.vaadin.flow.server.PWA;
import com.vaadin.flow.theme.Theme;
@Push @Theme(value = "pit-all-lts") @PageTitle("Main")
@PWA(name = "pit-all-lts", shortName = "pit-all-lts")
public class Application extends SpringBootServletInitializer implements AppShellConfigurator {

# Run dev-mode
mvn
```
It fails with the exception
```
java.io.IOException: Unable to delete directory /private/tmp/kk/all-lts/node_modules.
	at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1127) ~[commons-io-2.7.jar:2.7]
	at com.vaadin.flow.server.frontend.TaskUpdatePackages.removeDir(TaskUpdatePackages.java:467) ~[flow-server-10.0.0.alpha5.jar:10.0.0.alpha5]
	at com.vaadin.flow.server.frontend.TaskUpdatePackages.cleanUp(TaskUpdatePackages.java:449) ~[flow-server-10.0.0.alpha5.jar:10.0.0.alpha5]
	at com.vaadin.flow.server.frontend.TaskUpdatePackages.updatePackageJsonDependencies(TaskUpdatePackages.java:281) ~[flow-server-10.0.0.alpha5.jar:10.0.0.alpha5]
	at com.vaadin.flow.server.frontend.TaskUpdatePackages.execute(TaskUpdatePackages.java:103) ~[flow-server-10.0.0.alpha5.jar:10.0.0.alpha5]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:941) ~[flow-server-10.0.0.alpha5.jar:10.0.0.alpha5]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:414) ~[vaadin-dev-server-10.0.0.alpha5.jar:na]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:343) ~[vaadin-dev-server-10.0.0.alpha5.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```
