### ISSUE TITLE
custom frontend folder does not work

### ISSUE THREAD

**Issue by haijian-vaadin** [vaadin/flow#12880]
### Description of the bug

As a developer, I want to use a different frontend folder instead of the default one under the project's root, for example, `src/main/frontend` to be aligned with a Maven project. 

I tried with the configuration for the maven plugin in the `pom.xml` file
```
<configuration>
    <frontendDirectory>src/main/frontend</frontendDirectory>
</configuration>
```

But still most of the code is generated under the default frontend directory, including the theme generation, so that I got the error in the console
```
com.vaadin.flow.server.ExecutionFailedException: Discovered @Theme annotation with theme name 'custom-frontend', but could not find the theme directory in the project or available as a jar dependency. Check if you forgot to create the folder under '/Users/haijian/Downloads/custom-frontend/src/main/frontend/themes' or have mistyped the theme or folder name for 'custom-frontend'.
        at com.vaadin.flow.server.frontend.TaskUpdateThemeImport.verifyThemeDirectoryExistence(TaskUpdateThemeImport.java:120) ~[flow-server-10.0.0.alpha4.jar:10.0.0.alpha4]
        at com.vaadin.flow.server.frontend.TaskUpdateThemeImport.execute(TaskUpdateThemeImport.java:79) ~[flow-server-10.0.0.alpha4.jar:10.0.0.alpha4]
        at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:937) ~[flow-server-10.0.0.alpha4.jar:10.0.0.alpha4]
        at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:414) ~[vaadin-dev-server-10.0.0.alpha4.jar:na]
        at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:343) ~[vaadin-dev-server-10.0.0.alpha4.jar:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
```

### Expected behavior

After configuration with 
```
<configuration>
    <frontendDirectory>src/main/frontend</frontendDirectory>
</configuration>
```
or some other ways of defining a custom folder, Vaadin will generate the code to that folder and Application runs normally.

### Minimal reproducible example

[Uploading custom-frontend.zip…]()

### Versions

- Vaadin / Flow version: 23.0.0.alpha3
- Java version: 16.0.1, vendor: Amazon.com Inc.
- OS version: Mac Os

**Comment by mstahv** [comment]
Upvote!

In addition to just moving the frontend directory, I'd like to move also the front-end build files. Both having the directory and build files are quite badly against Maven conventions. If we could move those away from the top level directory, it would give much cleaner image for evaluators and users, who get confused about those files (many have chosen Vaadin not to fiddle with JS  and/or JS build). 

https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by mstahv** [comment]
See also: https://github.com/vaadin/flow/issues/6629
