### ISSUE TITLE
NPE in JavaScriptBootstrapUI.serverConnected when Dialog is opened during initial request

### ISSUE THREAD

**Issue by xdenser** [vaadin/flow#13269]
### Description of the bug

Part of stack trace
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.dom.Element.executeJs(String, java.io.Serializable[])" because the return value of "com.vaadin.flow.component.internal.JavaScriptBootstrapUI._jr$ig$wrapperElement(Object)" is null
at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.serverConnected(JavaScriptBootstrapUI.java:262)
at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.cancelClient(JavaScriptBootstrapUI.java:258)
at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.connectClient(JavaScriptBootstrapUI.java:125)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:222)
```

from code of methods in stacktrace I see that JavaScriptBootstrapUI.wrapperElement maybe null - this leads to NPE.
The message is a bit cryptic - probably dues to this new feature of JDK17 with NPE reporting.

I have workarround for this problem - I postpone dialog creation - this way it works w/o NPE. 

### Expected behavior

No error

### Minimal reproducible example

I will try to create minimal example to reproduce, this requires some time.
But In short application tries to open Dialog during initialization of UI.

### Versions

- Vaadin / Flow version: 23.0.1
- Java version:  J17
- OS version: Windows 10

**Comment by mshabarov** [comment]
This ticket is being closed. @xdenser please provide a reproducible example and reopen this ticket or create a new one.
