### ISSUE TITLE
java.lang.ClassCastException: Cannot cast com.vaadin.flow.di.LookupInitializer$LookupImpl to com.vaadin.flow.di.Lookup

### ISSUE THREAD

**Issue by rahuldjha** [vaadin/flow#13313]
### Description of the bug

I have migrated one of the projects from vaadin8 compatibility mode to vaadin flow 14.6.7. Now when I am trying to deploy the same, it is throwing some runtime exception at the time of deployment. Please find the stack trace below.

```
[2022-03-17 21:41:38,558] [ ] [ERROR] [ServerService Thread Pool -- 259] [org.jboss.msc.service.fail] [] [] [] [] MSC000001: Failed to start service jboss.deployment.subunit."appV14.ear"."appV14.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.subunit."appV14.ear"."appV14.war".undertow-deployment: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast com.vaadin.flow.di.LookupInitializer$LookupImpl to com.vaadin.flow.di.Lookup
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
    at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    at java.base/java.lang.Thread.run(Thread.java:834)
    at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast com.vaadin.flow.di.LookupInitializer$LookupImpl to com.vaadin.flow.di.Lookup
    at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:254)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
    ... 8 more
Caused by: java.lang.ClassCastException: Cannot cast com.vaadin.flow.di.LookupInitializer$LookupImpl to com.vaadin.flow.di.Lookup
    at java.base/java.lang.Class.cast(Class.java:3605)
    at deployment.appV14.ear//com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:76)
    at deployment.appV14.ear//com.vaadin.flow.server.VaadinContext.getAttribute(VaadinContext.java:58)
    at deployment.appV14.ear//com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:112)
    at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:204)
    at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
    at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
    at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at org.wildfly.extension.undertow@7.3.0.GA-redhat-00004//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
    at io.undertow.servlet@2.0.28.SP1-redhat-00001//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
    ... 10 more
```

### Expected behavior

The application should deploy smoothly.

### Minimal reproducible example

Migrate project from vaadin8 compatibility mode to vaadinflow 14.6.7. Deploy the same with jboss-eap-7.3 container.

### Versions

- Vaadin / Flow version: 14.6.7
- Java version: openjdk 11.0.8
- OS version: Windows 11 Pro 21H2 22000.588
- Browser version (if applicable): Google Chrome 99.0.4844.74
- Application Server (if applicable): jboss-eap-7.3
- IDE (if applicable): IntelliJ IDEA 2021.2.3 (Community Edition)

**Comment by Artur-** [comment]
This sounds like having duplicate versions of something on the classpath or a problem with the ear.

Without a reproducible example it is only guesses though

**Comment by rahuldjha** [comment]
Yes it was related to duplicate versions on the classpath.
