### ISSUE TITLE
Vaadin won't serve Page after updating to version 23.0.1

### ISSUE THREAD

**Issue by ImOlli** [vaadin/flow#13327]
### Description of the bug

When i try to start my application with vaadin 23.0.1 the page keeps with and in the javascript console is following error:

`Path '/login' is not properly resolved due to an error. Resolution had failed on route: '(.*)'`
```
Uncaught (in promise) TypeError: Object(...) is not a function
    at Object.<anonymous> (vaadin-1-2d47a2eca51b15f6a172.cache.js:241:40)
    at r (vaadin-bundle-4c267cba64641769406f.cache.js:1:361)
    at Object.<anonymous> (vaadin-1-2d47a2eca51b15f6a172.cache.js:2260:579)
    at r (vaadin-bundle-4c267cba64641769406f.cache.js:1:361)
    at Object.<anonymous> (vaadin-1-2d47a2eca51b15f6a172.cache.js:2492:17878)
    at r (vaadin-bundle-4c267cba64641769406f.cache.js:1:361)
    at Module.243 (vaadin-3-5c73bdb11b264af68475.cache.js:1:5543)
    at r (vaadin-bundle-4c267cba64641769406f.cache.js:1:361)
    at async Object.flowInit (vaadin-bundle-4c267cba64641769406f.cache.js:64:33235)
    at async Object.action (vaadin-bundle-4c267cba64641769406f.cache.js:64:31744)
```

### Expected behavior

Vaadin should start normaly and show my requested page

### Minimal reproducible example

Running maven clean install and then starting a application on vaadin 23.0.1

### Versions

- Vaadin / Flow version: 23.0.1
- Java version: 11.0.2
- OS version: Windows 10 64 Bit
- Application Server (if applicable): Spring Boot 2.6.1 with Spring 5.3.13
- IDE (if applicable): Intellij Idea Ultimate 2021.3.3

**Comment by caalador** [comment]
Hi.

I couldn't replicate the issue with a project.
You could try running `mvn vaadin:clean-frontend clean install` as it sounds like some js is wrong.

If that doesn't work could you give a sample application so that we can look into what goes wrong.

Also what node and npm versions are you using.

**Comment by ImOlli** [comment]
I figured out that an old depdency is causing the problem. Thank you anyways

**Comment by a-schild** [comment]
@ImOlli Hello, do you know which dependency did cause it?
I also see this warning, together with the following error then:
`Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry`
