### ISSUE TITLE
upgrade to v 23: provide either id or themeFor for @CssImport of resource ./org/vaadin/firitin/padding-fix-for-dialog.css 

### ISSUE THREAD

**Issue by bsutton** [vaadin/flow#13407]
I've just upgraded to vaadin 23 and I'm now seeing the following error:

```java

java.lang.IllegalStateException: provide either id or themeFor for @CssImport of resource ./org/vaadin/firitin/padding-fix-for-dialog.css, not both
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.addCssLines(AbstractUpdateImports.java:495) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.getCssLines(AbstractUpdateImports.java:230) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:120) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:391) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:941) ~[flow-server-23.0.3.jar:23.0.3]
	at com.vaadin.base.devserver.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:414) ~[vaadin-dev-server-23.0.3.jar:?]
	at com.vaadin.base.devserver.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:343) ~[vaadin-dev-server-23.0.3.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
```

This seems to be a vaadin package so I'm a little surprised that it is failing.

**Comment by mstahv** [comment]
This is a nasty breaking change that is supposed to make using Css imports easier 😬

If this is the only error, your fix is simple though. The resources seems to be coming from an add-on, so updating that to the latest version should do it. For this add-on (that I'm maintaining) also the group and artifact id has chaged as I moved the publishing to happen via Maven central. So replace flow-viritin dependency in your pom.xml with these new coordinates:

        <dependency>
            <groupId>in.virit</groupId>
            <artifactId>viritin</artifactId>
            <version>1.3.0</version>
            <type>jar</type>
        </dependency>

**Comment by bsutton** [comment]
Yes and thanks for the help and will close out.
