### ISSUE TITLE
Pnpm tests in FrontendToolsTest fail in CI

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#13560]
### Description of the bug

Flow test FrontendToolsTest::getSuitablePnpm_tooOldGlobalVersionInstalled_throws and other pnpm related tests fail in CI:

```
java.lang.AssertionError: expected java.lang.IllegalStateException to be thrown, but nothing was thrown
	at org.junit.Assert.assertThrows(Assert.java:1028)
	at org.junit.Assert.assertThrows(Assert.java:981)
	at com.vaadin.flow.server.frontend.FrontendToolsTest.getSuitablePnpm_tooOldGlobalVersionInstalled_throws(FrontendToolsTest.java:678)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

Bender agents have the following configuration in  `/root/.npmrc`:
`prefix = "/root/.npm-v8.6.0-global"`
This makes some pnpm related tests fail on Flow, because the test installs and uninstalls pnpm in that directory, that is not on PATH, so when FrontendToolsLocator searches for pnpm it either does not find it or it finds an unexpected version.

### Expected behavior

FrontendToolTest should pass

### Minimal reproducible example

https://bender.vaadin.com/viewLog.html?buildId=301442&buildTypeId=Flow_Flow231_Flow231Snapshot

### Versions

- Vaadin / Flow version: 23.0, 23.1
- Java version: 11

**Comment by mcollovati** [comment]
Checking if PATH can be updated on the agents instead of changing configuration for all jobs.
At the moment only for `Flow 23.1 Snapshot` has been modified, introducing the **env.PATH** parameter with value `/root/.npm-v8.6.0-global/bin:%env.PATH%`

**Comment by ZheSun88** [comment]
by the way, the build which has modified has been renamed to `Flow 23.2 SNAPSHOT` https://bender.vaadin.com/admin/editBuildParams.html?id=buildType:Flow_Flow232_Flow232SnapshotMaster

**Comment by mcollovati** [comment]
It turned out that the `prefix` in `.npmrc` was set by a job.
The job has been modify to remove `prefix` when it completes, even if the build fails.
Affected agents are going to be fixed soon.

**Comment by mcollovati** [comment]
Nightly builds are green and seems to be stable now
