### ISSUE TITLE
WebpackHandlerTest::should_CaptureWebpackOutput_When_Failed if flaky

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#13755]
### Description of the bug

This test is often failing in V23 snapshot validation with:

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to install Node
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:870)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalStateException: Failed to install Node
	at com.vaadin.flow.server.frontend.FrontendTools.installNode(FrontendTools.java:699)
	at com.vaadin.flow.server.frontend.FrontendTools.getNodeExecutable(FrontendTools.java:461)
	at com.vaadin.flow.server.frontend.FrontendTools.getNodeBinary(FrontendTools.java:1149)
	at com.vaadin.flow.server.frontend.FrontendTools.getNodeVersionAndExecutable(FrontendTools.java:669)
	at com.vaadin.flow.server.frontend.FrontendTools.validateNodeAndNpmVersion(FrontendTools.java:628)
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevServer(AbstractDevServerRunner.java:352)
	at com.vaadin.base.devserver.AbstractDevServerRunner.doStartDevModeServer(AbstractDevServerRunner.java:215)
	at com.vaadin.base.devserver.AbstractDevServerRunner.runOnFutureComplete(AbstractDevServerRunner.java:171)
	at com.vaadin.base.devserver.AbstractDevServerRunner.lambda$new$0(AbstractDevServerRunner.java:162)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	... 7 more
Caused by: com.vaadin.flow.server.frontend.installer.InstallationException: Could not install Node
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.installNode(NodeInstaller.java:270)
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.install(NodeInstaller.java:215)
	at com.vaadin.flow.server.frontend.FrontendTools.installNode(FrontendTools.java:697)
	... 16 more
Caused by: java.io.FileNotFoundException: Could not find the downloaded Node.js binary in /tmp/test-folder10854470797731189984/.vaadin/node/tmp/node-v16.15.0-linux-x64/bin/node
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.installNodeUnix(NodeInstaller.java:285)
	at com.vaadin.flow.server.frontend.installer.NodeInstaller.installNode(NodeInstaller.java:267)
	... 18 more
------- Stderr: -------
[ForkJoinPool.commonPool-worker-7] INFO com.vaadin.base.devserver.AbstractDevServerRunner - Starting Webpack
[ForkJoinPool.commonPool-worker-7] INFO com.vaadin.flow.server.frontend.FrontendTools - Globally node version 14.19.0 is older than 16.14.0. Using node from /tmp/test-folder10854470797731189984/.vaadin.
[ForkJoinPool.commonPool-worker-7] INFO com.vaadin.flow.server.frontend.FrontendTools - Couldn't find node. Installing Node and npm to /tmp/test-folder10854470797731189984/.vaadin.
[ForkJoinPool.commonPool-worker-7] INFO NodeInstaller - Installing node version v16.15.0
[ForkJoinPool.commonPool-worker-7] INFO NodeInstaller - Downloading https://nodejs.org/dist/v16.15.0/node-v16.15.0-linux-x64.tar.gz to /tmp/test-folder10854470797731189984/.vaadin/node-v16.15.0-linux-x64.tar.gz
[ForkJoinPool.commonPool-worker-7] INFO ProxyConfig - No proxies configured
[ForkJoinPool.commonPool-worker-7] INFO FileDownloader - No proxy was configured, downloading directly
[ForkJoinPool.commonPool-worker-7] INFO NodeInstaller - Unpacking /tmp/test-folder10854470797731189984/.vaadin/node-v16.15.0-linux-x64.tar.gz into /tmp/test-folder10854470797731189984/.vaadin/node/tmp
[ForkJoinPool.commonPool-worker-3] INFO com.vaadin.flow.server.frontend.TaskCopyFrontendFiles - Copying frontend resources from jar files ...
[ForkJoinPool.commonPool-worker-3] INFO com.vaadin.flow.server.frontend.TaskCopyFrontendFiles - Visited 0 resources. Took 0 ms.
[ForkJoinPool.commonPool-worker-3] INFO com.vaadin.base.devserver.AbstractDevServerRunner - Starting Webpack
[ForkJoinPool.commonPool-worker-3] INFO com.vaadin.flow.server.frontend.FrontendTools - Globally node version 14.19.0 is older than 16.14.0. Using node from /tmp/test-folder10854470797731189984/.vaadin.
[ForkJoinPool.commonPool-worker-3] INFO com.vaadin.flow.server.frontend.FrontendTools - Couldn't find node. Installing Node and npm to /tmp/test-folder10854470797731189984/.vaadin.
[ForkJoinPool.commonPool-worker-3] INFO NodeInstaller - Installing node version v16.15.0
[ForkJoinPool.commonPool-worker-3] INFO NodeInstaller - Unpacking /tmp/test-folder10854470797731189984/.vaadin/node-v16.15.0-linux-x64.tar.gz into /tmp/test-folder10854470797731189984/.vaadin/node/tmp
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.TaskCopyFrontendFiles - Copying frontend resources from jar files ...
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.TaskCopyFrontendFiles - Visited 0 resources. Took 0 ms.
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.base.devserver.AbstractDevServerRunner - Starting Webpack
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.FrontendTools - Globally node version 14.19.0 is older than 16.14.0. Using node from /tmp/test-folder10854470797731189984/.vaadin.
[ForkJoinPool.commonPool-worker-5] INFO com.vaadin.flow.server.frontend.FrontendTools - Couldn't find node. Installing Node and npm to /tmp/test-folder10854470797731189984/.vaadin.
[ForkJoinPool.commonPool-worker-5] INFO NodeInstaller - Installing node version v16.15.0
[ForkJoinPool.commonPool-worker-5] INFO NodeInstaller - Unpacking /tmp/test-folder10854470797731189984/.vaadin/node-v16.15.0-linux-x64.tar.gz into /tmp/test-folder10854470797731189984/.vaadin/node/tmp
[ForkJoinPool.commonPool-worker-3] INFO NodeInstaller - Copying node binary from /tmp/test-folder10854470797731189984/.vaadin/node/tmp/node-v16.15.0-linux-x64/bin/node to /tmp/test-folder10854470797731189984/.vaadin/node/node
[ForkJoinPool.commonPool-worker-3] INFO NodeInstaller - Extracting npm
```

Might be an agents issue.
Build log file:

[Flow_23.0_Flow_23.0_Snapshot_243.log](https://github.com/vaadin/flow/files/8676984/Flow_23.0_Flow_23.0_Snapshot_243.log)
.

Failed build example
https://bender.vaadin.com/viewLog.html?buildId=307136&buildTypeId=Flow_Flow230_Flow230Snapshot

### Expected behavior

Test passes always.

### Minimal reproducible example

N/A

### Versions

- Vaadin / Flow version: V23.0+ snapshots

**Comment by mshabarov** [comment]
WebPack is not a primary build tool anymore.
