### ISSUE TITLE
NoMethodError in vaadinPrepareFrontend of gradle plugin

### ISSUE THREAD

**Issue by mr1chter** [vaadin/flow#13854]
### Description of the bug

After trying to integrate vaadin into an existing big multi-module gradle build, compilation failed in the vaadin gradle plugin:

gradle build, deploy, or vaadinPrepareFrontend on its own, does not matter which gradle command

```
> Task :deployments:server-war:vaadinPrepareFrontend FAILED

Execution failed for task ':deployments:server-war:vaadinPrepareFrontend'.
> org.reflections.util.ConfigurationBuilder.setInputsFilter(Ljava/util/function/Predicate;)Lorg/reflections/util/ConfigurationBuilder;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':deployments:server-war:vaadinPrepareFrontend'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NoSuchMethodError: org.reflections.util.ConfigurationBuilder.setInputsFilter(Ljava/util/function/Predicate;)Lorg/reflections/util/ConfigurationBuilder;
	at com.vaadin.flow.server.scanner.ReflectionsClassFinder.<init>(ReflectionsClassFinder.java:56)
	at com.vaadin.flow.plugin.base.BuildFrontendUtil.getClassFinder(BuildFrontendUtil.java:98)
	at com.vaadin.gradle.GradlePluginAdapter.getClassFinder(GradlePluginAdapter.kt:71)
	at com.vaadin.flow.plugin.base.BuildFrontendUtil.prepareFrontend(BuildFrontendUtil.java:145)
	at com.vaadin.gradle.VaadinPrepareFrontendTask.vaadinPrepareFrontend(VaadinPrepareFrontendTask.kt:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
[...]
```
I looked at the code in question and it does not look weird at all and the method does exist.

Caller:
https://github.com/vaadin/flow/blob/b5d31c9054d7a84ca2ade252f716f6364c0eec6a/flow-plugins/flow-plugin-base/src/main/java/com/vaadin/flow/server/scanner/ReflectionsClassFinder.java#L55-L57

Method at org.reflections v10.2:
https://github.com/ronmamo/reflections/blob/5ff7a1d366e8656dfa0f2f476991b558b037e919/src/main/java/org/reflections/util/ConfigurationBuilder.java#L182-L187

I have tried the following things: 
- downgrading until the specified method is no longer called (Vaadin Plugin v14.3.7): compiles, but has a "webpack exited prematurely" exception when deploying in Wildfly (I have not investigated this more)
- upgrading gradle: difficult in our case, but does not seem to help
- trying gradle 5.6.4 in the gradle starter template: works -> gradle does not seem to be the issue (?)

I can't expect you to solve this with the limited information available to you, but do you have any(!) idea what could cause this?
For us this is a blocker for trying out vaadin in our existing application, but I'm pretty sure that the issue is somewhere on our side and any idea would help.

### Expected behavior

Compilation should complete without issues

### Minimal reproducible example

Sadly, I have no such example, this is in a corporate project and the starter template does not show this behaviour. I can share how I tried to integrate the gradle template project (https://github.com/vaadin/base-starter-gradle) :

- add the plugin to the deployment module build.gradle, put the javascript frontend stuff (webpack config, packages.json, ts files, css, html, etcpp)
- add a new module to the project containing the java code and add vaadin to its dependencies in build.gradle

Admittedly, I also did not try to create an MRE because I did not have the time for it.

### Versions

- Vaadin / Flow version: 23.0.9
- Java version: 11.0.6
- OS version: Windows 10, current cygwin
- Browser version (if applicable): -
- Application Server (if applicable): Wildfly 15, but not really applicable here
- IDE (if applicable): Intellij
- Gradle: v5.6.4 (old I know)

```
$ gradle buildEnv
11:34:53: Executing task ' buildEnvironment'...

[...]
> Task :deployments:server-war:buildEnvironment

------------------------------------------------------------
Project :deployments:server-war - Example war application based on [project] modules
------------------------------------------------------------

classpath
\--- com.vaadin:com.vaadin.gradle.plugin:23.0.9
     \--- com.vaadin:vaadin-gradle-plugin:23.0.9
          +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31
          |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31
          |    |    +--- org.jetbrains:annotations:13.0
          |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31
          |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31
          |         \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31 (*)
          \--- com.vaadin:flow-plugin-base:23.0.7
               +--- com.vaadin:flow-server:23.0.7
               |    +--- com.vaadin:flow-push:23.0.7
               |    |    \--- com.vaadin.external.atmosphere:atmosphere-runtime:2.7.3.slf4jvaadin4
               |    |         \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.35
               |    +--- org.slf4j:slf4j-api:1.7.35
               |    +--- javax.annotation:javax.annotation-api:1.3.2
               |    +--- com.vaadin.external.gwt:gwt-elemental:2.8.2.vaadin2
               |    +--- commons-fileupload:commons-fileupload:1.4
               |    +--- commons-io:commons-io:2.11.0
               |    +--- com.fasterxml.jackson.core:jackson-core:2.13.2
               |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.2.2
               |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.2
               |    |    \--- com.fasterxml.jackson.core:jackson-core:2.13.2
               |    +--- org.jsoup:jsoup:1.14.3
               |    +--- com.helger:ph-css:6.5.0
               |    |    +--- com.helger.commons:ph-commons:10.1.6
               |    |    |    +--- com.google.code.findbugs:jsr305:3.0.2
               |    |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.35
               |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.35
               |    +--- net.bytebuddy:byte-buddy:1.12.7
               |    +--- com.vaadin.external:gentyref:1.2.0.vaadin1
               |    +--- org.apache.commons:commons-compress:1.21
               |    +--- org.apache.httpcomponents:httpclient:4.5.13
               |    |    +--- org.apache.httpcomponents:httpcore:4.4.13
               |    |    +--- commons-logging:commons-logging:1.2
               |    |    \--- commons-codec:commons-codec:1.11 -> 1.15
               |    \--- commons-codec:commons-codec:1.15
               +--- com.vaadin:fusion-endpoint:23.0.7
               |    +--- com.vaadin:flow-server:23.0.7 (*)
               |    +--- commons-io:commons-io:2.11.0
               |    +--- javax.validation:validation-api:2.0.1.Final
               |    +--- org.springframework.data:spring-data-commons:2.6.4
               |    |    +--- org.springframework:spring-core:5.3.19
               |    |    |    \--- org.springframework:spring-jcl:5.3.19
               |    |    +--- org.springframework:spring-beans:5.3.19
               |    |    |    \--- org.springframework:spring-core:5.3.19 (*)
               |    |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.35
               |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.2
               |    +--- com.fasterxml.jackson.core:jackson-core:2.13.2
               |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.2.2 (*)
               |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.2
               |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.13.2
               |    |    +--- com.fasterxml.jackson.core:jackson-core:2.13.2
               |    |    \--- com.fasterxml.jackson.core:jackson-databind:2.13.2 -> 2.13.2.2 (*)
               |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.2
               |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.13.2 -> 2.13.2.2 (*)
               |    |    +--- org.yaml:snakeyaml:1.30
               |    |    \--- com.fasterxml.jackson.core:jackson-core:2.13.2
               |    +--- org.slf4j:slf4j-ext:1.7.35
               |    |    \--- org.slf4j:slf4j-api:1.7.35
               |    +--- javax.annotation:javax.annotation-api:1.3.2
               |    +--- com.github.javaparser:javaparser-symbol-solver-core:3.24.2
               |    |    +--- com.github.javaparser:javaparser-core:3.24.2
               |    |    +--- org.javassist:javassist:3.28.0-GA
               |    |    \--- com.google.guava:guava:31.1-jre
               |    |         +--- com.google.guava:failureaccess:1.0.1
               |    |         +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
               |    |         +--- com.google.code.findbugs:jsr305:3.0.2
               |    |         +--- org.checkerframework:checker-qual:3.12.0
               |    |         +--- com.google.errorprone:error_prone_annotations:2.11.0
               |    |         \--- com.google.j2objc:j2objc-annotations:1.3
               |    +--- io.swagger.codegen.v3:swagger-codegen:3.0.20
               |    |    +--- io.swagger:swagger-parser:1.0.51
               |    |    |    +--- io.swagger:swagger-core:1.6.1
               |    |    |    |    +--- org.apache.commons:commons-lang3:3.2.1 -> 3.7
               |    |    |    |    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.35
               |    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.1 -> 2.13.2
               |    |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.10.1 -> 2.13.2.2 (*)
               |    |    |    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.10.1 -> 2.13.2 (*)
               |    |    |    |    +--- io.swagger:swagger-models:1.6.1
               |    |    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.1 -> 2.13.2
               |    |    |    |    |    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.35
               |    |    |    |    |    \--- io.swagger:swagger-annotations:1.6.1
               |    |    |    |    +--- com.google.guava:guava:27.0.1-android -> 31.1-jre (*)
               |    |    |    |    \--- javax.validation:validation-api:1.1.0.Final -> 2.0.1.Final
               |    |    |    +--- org.slf4j:slf4j-ext:1.7.28 -> 1.7.35 (*)
               |    |    |    +--- org.slf4j:slf4j-api:1.7.28 -> 1.7.35
               |    |    |    \--- commons-io:commons-io:2.4 -> 2.11.0
               |    |    +--- io.swagger.parser.v3:swagger-parser:2.0.20
               |    |    |    +--- io.swagger.parser.v3:swagger-parser-v2-converter:2.0.20
               |    |    |    |    +--- io.swagger:swagger-core:1.6.1 (*)
               |    |    |    |    +--- io.swagger:swagger-parser:1.0.51 (*)
               |    |    |    |    +--- io.swagger:swagger-compat-spec-parser:1.0.51
               |    |    |    |    |    +--- io.swagger:swagger-core:1.6.1 (*)
               |    |    |    |    |    +--- io.swagger:swagger-parser:1.0.51 (*)
               |    |    |    |    |    +--- com.github.java-json-tools:json-schema-validator:2.2.8
               |    |    |    |    |    |    +--- com.github.java-json-tools:json-schema-core:1.2.8
               |    |    |    |    |    |    |    +--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
               |    |    |    |    |    |    |    +--- org.mozilla:rhino:1.7R4
               |    |    |    |    |    |    |    +--- com.github.fge:jackson-coreutils:1.8
               |    |    |    |    |    |    |    |    +--- com.github.fge:msg-simple:1.1
               |    |    |    |    |    |    |    |    |    +--- com.github.fge:btf:1.2
               |    |    |    |    |    |    |    |    |    |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
               |    |    |    |    |    |    |    |    |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
               |    |    |    |    |    |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.2.3 -> 2.13.2.2 (*)
               |    |    |    |    |    |    |    |    +--- com.google.guava:guava:16.0.1 -> 31.1-jre (*)
               |    |    |    |    |    |    |    |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
               |    |    |    |    |    |    |    \--- com.github.fge:uri-template:0.9
               |    |    |    |    |    |    |         +--- com.github.fge:msg-simple:1.1 (*)
               |    |    |    |    |    |    |         +--- com.google.guava:guava:16.0.1 -> 31.1-jre (*)
               |    |    |    |    |    |    |         \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
               |    |    |    |    |    |    +--- joda-time:joda-time:2.9.7
               |    |    |    |    |    |    +--- com.googlecode.libphonenumber:libphonenumber:8.0.0
               |    |    |    |    |    |    +--- com.google.code.findbugs:jsr305:3.0.1 -> 3.0.2
               |    |    |    |    |    |    \--- net.sf.jopt-simple:jopt-simple:5.0.3
               |    |    |    |    |    +--- com.github.fge:json-patch:1.6
               |    |    |    |    |    |    +--- com.github.fge:jackson-coreutils:1.6 -> 1.8 (*)
               |    |    |    |    |    |    \--- com.google.code.findbugs:jsr305:2.0.1 -> 3.0.2
               |    |    |    |    |    \--- org.apache.httpcomponents:httpclient:4.5.2 -> 4.5.13 (*)
               |    |    |    |    +--- io.swagger.core.v3:swagger-models:2.1.2
               |    |    |    |    |    \--- com.fasterxml.jackson.core:jackson-annotations:2.10.1 -> 2.13.2
               |    |    |    |    +--- io.swagger.parser.v3:swagger-parser-core:2.0.20
               |    |    |    |    |    \--- io.swagger.core.v3:swagger-models:2.1.2 (*)
               |    |    |    |    \--- io.swagger.parser.v3:swagger-parser-v3:2.0.20
               |    |    |    |         +--- io.swagger.core.v3:swagger-models:2.1.2 (*)
               |    |    |    |         +--- io.swagger.core.v3:swagger-core:2.1.2
               |    |    |    |         |    +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.2
               |    |    |    |         |    |    \--- jakarta.activation:jakarta.activation-api:1.2.1
               |    |    |    |         |    +--- org.apache.commons:commons-lang3:3.7
               |    |    |    |         |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.35
               |    |    |    |         |    +--- com.fasterxml.jackson.core:jackson-annotations:2.10.1 -> 2.13.2
               |    |    |    |         |    +--- com.fasterxml.jackson.core:jackson-databind:2.10.1 -> 2.13.2.2 (*)
               |    |    |    |         |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.10.1 -> 2.13.2 (*)
               |    |    |    |         |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.10.1 -> 2.13.2 (*)
               |    |    |    |         |    +--- io.swagger.core.v3:swagger-annotations:2.1.2
               |    |    |    |         |    +--- io.swagger.core.v3:swagger-models:2.1.2 (*)
               |    |    |    |         |    \--- jakarta.validation:jakarta.validation-api:2.0.2
               |    |    |    |         +--- io.swagger.parser.v3:swagger-parser-core:2.0.20 (*)
               |    |    |    |         +--- commons-io:commons-io:2.6 -> 2.11.0
               |    |    |    |         +--- com.fasterxml.jackson.core:jackson-annotations:2.10.2 -> 2.13.2
               |    |    |    |         +--- com.fasterxml.jackson.core:jackson-databind:2.10.2 -> 2.13.2.2 (*)
               |    |    |    |         \--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.10.2 -> 2.13.2 (*)
               |    |    |    +--- io.swagger.parser.v3:swagger-parser-v3:2.0.20 (*)
               |    |    |    +--- org.slf4j:slf4j-ext:1.7.30 -> 1.7.35 (*)
               |    |    |    +--- org.slf4j:slf4j-api:1.7.30 -> 1.7.35
               |    |    |    \--- commons-io:commons-io:2.6 -> 2.11.0
               |    |    +--- io.swagger:swagger-codegen:2.4.14
               |    |    |    +--- io.swagger:swagger-parser:1.0.51 (*)
               |    |    |    +--- io.swagger:swagger-compat-spec-parser:1.0.51 (*)
               |    |    |    +--- io.swagger:swagger-core:1.6.1 (*)
               |    |    |    +--- com.samskivert:jmustache:1.12
               |    |    |    +--- commons-io:commons-io:2.4 -> 2.11.0
               |    |    |    +--- org.slf4j:slf4j-ext:1.7.12 -> 1.7.35 (*)
               |    |    |    +--- org.slf4j:slf4j-api:1.7.12 -> 1.7.35
               |    |    |    +--- org.apache.commons:commons-lang3:3.4 -> 3.7
               |    |    |    +--- commons-cli:commons-cli:1.2
               |    |    |    \--- com.atlassian.commonmark:commonmark:0.9.0
               |    |    +--- com.samskivert:jmustache:1.12
               |    |    +--- commons-io:commons-io:2.4 -> 2.11.0
               |    |    +--- org.slf4j:slf4j-ext:1.7.25 -> 1.7.35 (*)
               |    |    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.35
               |    |    +--- org.apache.commons:commons-lang3:3.4 -> 3.7
               |    |    +--- commons-cli:commons-cli:1.2
               |    |    +--- com.google.guava:guava:23.0 -> 31.1-jre (*)
               |    |    +--- com.github.jknack:handlebars:4.1.2
               |    |    |    \--- org.slf4j:slf4j-api:1.7.25 -> 1.7.35
               |    |    \--- com.atlassian.commonmark:commonmark:0.9.0
               |    \--- io.swagger.codegen.v3:swagger-codegen-generators:1.0.20
               |         +--- io.swagger.codegen.v3:swagger-codegen:3.0.20 (*)
               |         +--- commons-io:commons-io:2.4 -> 2.11.0
               |         +--- org.slf4j:slf4j-ext:1.7.12 -> 1.7.35 (*)
               |         +--- org.slf4j:slf4j-api:1.7.12 -> 1.7.35
               |         +--- org.apache.commons:commons-lang3:3.4 -> 3.7
               |         +--- commons-cli:commons-cli:1.2
               |         \--- com.atlassian.commonmark:commonmark:0.9.0
               +--- org.reflections:reflections:0.10.2
               |    +--- org.javassist:javassist:3.28.0-GA
               |    +--- com.google.code.findbugs:jsr305:3.0.2
               |    \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.35
               \--- org.zeroturnaround:zt-exec:1.12
                    \--- org.slf4j:slf4j-api:1.7.2 -> 1.7.35

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7s
1 actionable task: 1 executed
11:35:01: Task execution finished ' buildEnvironment'.

**Comment by mr1chter** [comment]
Of course, since I don't even know what causes this, I welcome also any way I can investigate this issue.

**Comment by mshabarov** [comment]
It might be that the version of `org.reflections` is overridden, so you have another transitive version at runtime which has no such a method. Check if your project's dependencies don't bring another version of `org.reflections`. Or maybe it's WildFly 15 who uses another version.

**Comment by mr1chter** [comment]
hmm. I thought that buildEnv is the conclusive command to find that out but there might be something I missed. I will check and get back here. Thank you!

**Comment by mr1chter** [comment]
Yeah, the buildEnv command was from the deployment module, not in the root project. In the root project, the version of org.reflections is overwritten to 0.9.12 (from another internal gradle module), which perfectly explains this behaviour. Fixing this is on my side so I'll close this ticket.

Thank you and sorry for the trouble. For anyone encountering this bug (even tough improbable), run `gradle buildEnvironment` in all relevant modules/projects and check all the org.reflections versions.
