### ISSUE TITLE
Vaadin 14.8.11 production build fails

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#13884]
### Description of the bug

The build of a simple application fails with the following exception

```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at CompressionPlugin.taskGenerator (C:\Projects\my-todo\node_modules\.pnpm\compression-webpack-plugin@4.0.1_webpack@4.42.0\node_modules\compression-webpack-plugin\dist\index.js:88:22)
    at taskGenerator.next (<anonymous>)
    at C:\Projects\my-todo\node_modules\.pnpm\compression-webpack-plugin@4.0.1_webpack@4.42.0\node_modules\compression-webpack-plugin\dist\index.js:216:49
    at CompressionPlugin.runTasks (C:\Projects\my-todo\node_modules\.pnpm\compression-webpack-plugin@4.0.1_webpack@4.42.0\node_modules\compression-webpack-plugin\dist\index.js:236:9)
    at C:\Projects\my-todo\node_modules\.pnpm\compression-webpack-plugin@4.0.1_webpack@4.42.0\node_modules\compression-webpack-plugin\dist\index.js:270:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:18:17)
    at AsyncSeriesHook.lazyCompileHook (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at Compiler.emitAssets (C:\Projects\my-todo\node_modules\.pnpm\webpack@4.42.0\node_modules\webpack\lib\Compiler.js:491:19)
    at onCompiled (C:\Projects\my-todo\node_modules\.pnpm\webpack@4.42.0\node_modules\webpack\lib\Compiler.js:278:9)
    at C:\Projects\my-todo\node_modules\.pnpm\webpack@4.42.0\node_modules\webpack\lib\Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Projects\my-todo\node_modules\.pnpm\webpack@4.42.0\node_modules\webpack\lib\Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Projects\my-todo\node_modules\.pnpm\webpack@4.42.0\node_modules\webpack\lib\Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Projects\my-todo\node_modules\.pnpm\webpack@4.42.0\node_modules\webpack\lib\Compilation.js:1414:32
    at eval (eval at create (C:\Projects\my-todo\node_modules\.pnpm\tapable@1.1.3\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:20:1)
    at C:\Projects\my-todo\node_modules\.pnpm\terser-webpack-plugin@1.4.5_webpack@4.42.0\node_modules\terser-webpack-plugin\dist\index.js:321:9
    at step (C:\Projects\my-todo\node_modules\.pnpm\terser-webpack-plugin@1.4.5_webpack@4.42.0\node_modules\terser-webpack-plugin\dist\TaskRunner.js:87:9)
    at done (C:\Projects\my-todo\node_modules\.pnpm\terser-webpack-plugin@1.4.5_webpack@4.42.0\node_modules\terser-webpack-plugin\dist\TaskRunner.js:98:30)
    at tryCatcher (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Projects\my-todo\node_modules\.pnpm\bluebird@3.7.2\node_modules\bluebird\js\release\promise.js:729:18)
```

### Expected behavior

Build should work

### Minimal reproducible example

Extract this application

mvn spring-boot:run -Pproduction

[vaadin14-test.zip](https://github.com/vaadin/flow/files/8812221/vaadin14-test.zip)

### Versions

- Vaadin / Flow version: 14.8.11
- Java version: Java 8
- OS version: Windows 11
- Node version: 16.14.0

**Comment by taefi** [comment]
@TatuLund Thanks for creating this issue. 
I tried the setup mentioned here on a Windows11 machine both with your attached project and also the [skeleton-starter-spring-flow-14](https://github.com/vaadin/skeleton-starter-flow-spring/archive/v14.zip) and it is working without a problem. I must admit that the `JsonEditor` you instantiated in the `MainView` had no `@TAG`, but after I added that, the blank page shows with no error. Obviously, I added other visible components to the page and it is working fine ;)

Is there any chance that some platform version change is done in the project and the application is started without clearing out the node_modules, etc. which is known as "the dance"? :)

**Comment by TatuLund** [comment]
> Is there any chance that some platform version change is done

No, it happened just suddenly. The build ran last week and this week it did not. And yes, I did frontend clean up and full clean several times. Now I wiped the entire workspace and re-imported the project. And now it works. Also the problem I was originally studying seems to be gone.
