### ISSUE TITLE
devserver crash when editing css with emacs

### ISSUE THREAD

**Issue by mijutu** [vaadin/flow#13885]
### Description of the bug

Emacs saves a file, devserver notices a temporary file and tries to load it. But then the file is already gone and devserver crashes. No further updates happen before restarting manually.
```
120225 [qtp1625913564-55] DEBUG com.my-themesoftware.rwd.servlets.ContentPreviewImageServlet  - sending fallback image: no previewimage in content 8
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - node:internal/fs/utils:344
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     throw err;
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     ^
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - 
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - Error: ENOENT: no such file or directory, stat '/home/me/my-project/frontend/themes/my-theme/components/.#vaadin-text-field.css'
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Object.statSync (node:fs:1538:3)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at /home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:75:12
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Array.forEach (<anonymous>)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at collectFolders (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:73:32)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at /home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:77:22
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Array.forEach (<anonymous>)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at collectFolders (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:73:32)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at copyThemeResources (/home/me/my-project/target/plugins/application-theme-plugin/theme-copy.js:39:22)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at handleThemes (/home/me/my-project/target/plugins/application-theme-plugin/theme-handle.js:169:5)
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at findThemeFolderAndHandleTheme (/home/me/my-project/target/plugins/application-theme-plugin/theme-handle.js:97:23) {
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   errno: -2,
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   syscall: 'stat',
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   code: 'ENOENT',
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   path: '/home/me/my-project/frontend/themes/my-theme/components/.#vaadin-text-field.css'
122799 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - }

```

### Expected behavior

theme-copy.js should ignore temporary files. Perhaps ignore all file names starting with a dot, or just file names starting with ".#"

### Minimal reproducible example

The problem does not occur every time a css file is saved in emacs. I'm currenctly using a computer with fast cpu, a lot of ram and the project is on a slow spinner drive. The problem occurs about every 5th time a file is saved. It is a plain java Vaadin 23 project.

### Versions

Vaadin
    23.0.10
Flow
    23.0.7
Java
    JetBrains s.r.o. 17
OS
    amd64 Linux 5.16.9

**Comment by mijutu** [comment]
Vaadin 23.3.5 and the problem has gone worse. Now I occasionally  get a
```
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - node:fs:1596
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   handleErrorFromBinding(ctx);
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   ^
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - Error: ENOENT: no such file or directory, stat '/home/me/my-project/g/frontend/themes/my-theme/.#my-css.css'
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Object.statSync (node:fs:1596:3)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at /home/me/my-project/g/vite.config.ts:60:16
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at Array.forEach (<anonymous>)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at collectFolders (/home/me/my-project/g/vite.config.ts:58:36)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at copyThemeResources (/home/me/my-project/g/vite.config.ts:40:26)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at handleThemes (/home/me/my-project/g/vite.config.ts:455:9)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at findThemeFolderAndHandleTheme (/home/me/my-project/g/vite.config.ts:414:27)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at processThemeResources2 (/home/me/my-project/g/vite.config.ts:401:9)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at FSWatcher.handleThemeFileCreateDelete (/home/me/my-project/g/vite.config.ts:969:57)
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -     at FSWatcher.emit (node:events:525:35) {
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   errno: -2,
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   syscall: 'stat',
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   code: 'ENOENT',
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -   path: '/home/me/my-project/g/frontend/themes/my-theme/.#my-css.css'
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - }
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  -
726720 [dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker  - Node.js v18.13.0
```

And after that I can't reload my vaadin app on browser because 
```
java.net.ConnectException: Yhteys torjuttu
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        ...
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at com.vaadin.base.devserver.AbstractDevServerRunner.serveDevModeRequest(AbstractDevServerRunner.java:728)
	at com.vaadin.flow.server.StaticFileServer.serveStaticResource(StaticFileServer.java:243)
	at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:401)
```

I also tried edit target/plugins/application-theme-plugin/theme-copy.js to catch the exception, but my changes get overwrited immediately.

**Comment by Artur-** [comment]
Sounds like a try-catch-ignore inside `collectFolders` would solve it

If you copy the `theme-copy.js` file into `src/main/resources/plugins/application-theme-plugin/theme-copy.js` then the project copy should be used and you can test if try-catch is enough

**Comment by mijutu** [comment]
Yes, try-catch helps. Thanks. 

Perhaps issue could be fixed by try-catching and ignoring ENOENTs and throwing the rest again.

**Comment by Artur-** [comment]
Sounds so, want to make a PR?

**Comment by mijutu** [comment]
> Sounds so, want to make a PR?

No, but did it anyway.
