### ISSUE TITLE
Deadlock after restart

### ISSUE THREAD

**Issue by gpsfl** [vaadin/flow#13962]
### Description of the bug

We have encountered a deadlock on our production multiple times. It doesn't always occur and we had a hard time reproducing it, but if it occurs then it's immediately after the startup. I have included a stacktrace of the two threads which cause the deadlock. Hopefully this is enough information to find the issue.

### Expected behavior

Do not deadlock

### Stacktrace

```"http-nio-8012-exec-29":
  waiting to lock monitor 0x0000ffff8548a9c0 (object 0x000000072f352960, a com.vaadin.flow.server.VaadinServletContext),
  which is held by "http-nio-8012-exec-66"
"http-nio-8012-exec-66":
  waiting to lock monitor 0x0000ffff8548c1c0 (object 0x000000072bf59270, a org.apache.catalina.core.ApplicationContextFacade),
  which is held by "http-nio-8012-exec-29"

http-nio-8012-exec-29":
	at com.vaadin.experimental.FeatureFlags.get(FeatureFlags.java:122)
	- waiting to lock <0x000000072f352960> (a com.vaadin.flow.server.VaadinServletContext)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getIndexHtmlDocument(IndexHtmlRequestHandler.java:319)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.access$100(IndexHtmlRequestHandler.java:68)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler$IndexHtmlHolder.<init>(IndexHtmlRequestHandler.java:364)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler$IndexHtmlHolder.<init>(IndexHtmlRequestHandler.java:359)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.lambda$getCachedIndexHtmlDocument$0(IndexHtmlRequestHandler.java:311)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler$$Lambda$1023/0x0000000800c0cc40.get(Unknown Source)
	at com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:73)
	- locked <0x000000072bf59270> (a org.apache.catalina.core.ApplicationContextFacade)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getCachedIndexHtmlDocument(IndexHtmlRequestHandler.java:310)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.synchronizedHandleRequest(IndexHtmlRequestHandler.java:108)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1567)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x000000072f35d0e0> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11-ea/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11-ea/ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(java.base@11.0.11-ea/Thread.java:829)
"http-nio-8012-exec-66":
	at com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:70)
	- waiting to lock <0x000000072bf59270> (a org.apache.catalina.core.ApplicationContextFacade)
	at com.vaadin.flow.server.VaadinContext.getAttribute(VaadinContext.java:58)
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.getInstance(ApplicationRouteRegistry.java:110)
	- locked <0x000000072f352960> (a com.vaadin.flow.server.VaadinServletContext)
	at com.vaadin.flow.server.VaadinServletService.getRouteRegistry(VaadinServletService.java:226)
	at com.vaadin.flow.server.SessionRouteRegistry.getParentRegistry(SessionRouteRegistry.java:254)
	at com.vaadin.flow.server.SessionRouteRegistry.getNavigationRouteTarget(SessionRouteRegistry.java:155)
	at com.vaadin.flow.router.internal.DefaultRouteResolver.resolve(DefaultRouteResolver.java:42)
	at com.vaadin.flow.router.Router.resolveNavigationTarget(Router.java:140)
	at com.vaadin.flow.server.BootstrapUtils.resolvePageConfigurationHolder(BootstrapUtils.java:311)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapContext.<init>(BootstrapHandler.java:238)
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler$JavaScriptBootstrapContext.<init>(JavaScriptBootstrapHandler.java:88)
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler.createBootstrapContext(JavaScriptBootstrapHandler.java:165)
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1390)
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler.createAndInitUI(JavaScriptBootstrapHandler.java:127)
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler.getInitialJson(JavaScriptBootstrapHandler.java:258)
	at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler.synchronizedHandleRequest(JavaScriptBootstrapHandler.java:191)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1567)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x000000072f373898> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.11-ea/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.11-ea/ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(java.base@11.0.11-ea/Thread.java:829)
```

### Versions

- Vaadin / Flow version: 22.0.6
- Java version: 11.0.11
- OS version: Amazon Linux 2
- Application Server (if applicable): Tomcat 9.0.45

**Comment by Artur-** [comment]
I think the problem is the following

The attribute related methods in `VaadinServletContext` synchronize on the servlet context.

The init methods in `ApplicationRouteRegistry`, `FeatureFlags` and more synchronize on the `VaadinContext` instance to avoid double initialization.

The mentioned init methods use the attribute methods from `VaadinServletContext` inside their synchronized block to store the initialized object as an attribute.

So far it works fine as locking always goes 
1. Lock `VaadinContext`
2. Lock `ServletContext`

In the `IndexHtmlRequestHandler.getCachedIndexHtmlDocument` case however, the `VaadinServletContext.getAttribute` variant with a default supplier is used. `VaadinServletContext.getAttribute` will then lock on `ServletContext` (without having locked the vaadin context) and when it detects that there is no attribute available, it will run the provider. The supplier in this case will end up in the `FeatureFlags` initialization block which tries to use the above pattern of locking `VaadinContext` and then `ServletContext`.

Now there is a problem because locking in the `getCachedIndexHtmlDocument` happened in the other order (`ServletContext` first and then `VaadinContext`) and there is a dead lock.

Assuming the above is correct, the deadlock would happen on startup when the first request for the index page happens at an unsuitable time.

**Comment by Artur-** [comment]
Potential solutions (I did not really think these through):
1. Lock on vaadin context in `getCachedIndexHtmlDocument` to avoid locking in another order. Seems quite fragile and there might be other similar cases here and there.
2. Use the same object for locking in all cases. Can't see why we really need to synchronize on different ones for these operations
