### ISSUE TITLE
PropertyDefinition.getType() silently converts primitive class to its boxed counterpart

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#13992]
### Description

I'd expect PropertyDefinition.getType() to return the actual type of the field (e.g. `int.class`) and not the boxed counterpart (`Integer.class`). Please either make getType() return the actual type, or document that it will return the class of the boxed counterpart (+provide a function named getActualType() that returns the original type, e.g. primitive int.class).

### Expected outcome

-

### Minimal reproducible example

-

### Steps to reproduce

-

### Environment

Vaadin version(s): 14.8.11
OS: Windows

**Comment by DiegoCardoso** [comment]
> Sorry, can we move this to vaadin/flow?

Done.

**Comment by Legioth** [comment]
The idea is that `getType()` gives the type that would be returned when the getter method is called using reflection, which is the wrapped type in case of primitives. At the very least, this could indeed be documented.

What use case do you have that would need to distinguish between primitives and wrappers?

**Comment by mvysny** [comment]
Thank you Leif. My use-case: calculating default values. The default value of `int.class` is 0 while of `Integer.class` is null. I was building a FilterBar showing closable filter "pills" for filter fields with different than the default value.

![Screenshot from 2022-06-22 13-56-51](https://user-images.githubusercontent.com/254091/175012770-78654239-b7eb-41cd-85b1-353454012d92.png)

In this example, the "Active Only" filter bean is primitive `boolean` with the default value of false; the FilterBar only displays the "Active Only" "pill" when it's different from the default value, which in this case is false. For booleans it probably doesn't make much sense (3-state vs 2-state is not a sound model :-D ) but it makes much more sense for, say, `int.class`.

Note the red cross button which resets the filter to the default value, which is `null` for Objects but a non-null value for primitives. I was using the PropertyDefinition API to figure out the default value and setting nulls via reflection, which gave me exceptions... hence the issue.

**Comment by archiecobbs** [comment]
I'm using Vaadin 23.2.10 and have discovered the hard way that you **can't** have `PropertyDefinition.getType()` return a primitive type, otherwise you'll get an exception like this:
```
com.vaadin.flow.data.binder.BindingException: An exception has been thrown inside binding logic for the field element [label='This config package is active']
        at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1570)
        at com.vaadin.flow.data.binder.Binder$BindingImpl.doConversion(Binder.java:1314)
        at com.vaadin.flow.data.binder.Binder$BindingImpl.doValidation(Binder.java:1334)
        at com.vaadin.flow.data.binder.Binder$BindingImpl.validate(Binder.java:1268)
        at com.vaadin.flow.data.binder.Binder.lambda$doWriteIfValid$3(Binder.java:2294)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.vaadin.flow.data.binder.Binder.doWriteIfValid(Binder.java:2295)
        at com.vaadin.flow.data.binder.Binder.writeBean(Binder.java:2197)
        ... [elided] ...
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: Cannot cast java.lang.Boolean to boolean
        at com.vaadin.flow.data.binder.Binder$BindingBuilderImpl.lambda$createConverter$e536042e$2(Binder.java:997)
        at com.vaadin.flow.data.binder.Result.of(Result.java:92)
        at com.vaadin.flow.data.converter.Converter.lambda$from$b652e465$1(Converter.java:104)
        at com.vaadin.flow.data.converter.Converter$1.convertToModel(Converter.java:130)
        at com.vaadin.flow.data.converter.Converter$2.lambda$convertToModel$6b579330$1(Converter.java:165)
        at com.vaadin.flow.data.binder.SimpleResult.flatMap(SimpleResult.java:65)
        at com.vaadin.flow.data.binder.ValidationResultWrap.flatMap(ValidationResultWrap.java:67)
        at com.vaadin.flow.data.converter.Converter$2.convertToModel(Converter.java:165)
        at com.vaadin.flow.data.converter.Converter$2.convertToModel(Converter.java:163)
        at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$doConversion$0(Binder.java:1316)
        at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1560)
        ... 60 more
Caused by: java.lang.ClassCastException: Cannot cast java.lang.Boolean to boolean
        at java.base/java.lang.Class.cast(Class.java:3946)
        at com.vaadin.flow.data.converter.Converter.lambda$from$957be2b0$1(Converter.java:104)
        at com.vaadin.flow.data.binder.Result.of(Result.java:90)
        ... 69 more
```

So I'd recommend either fixing that bug or updating the Javadoc for `PropertyDefinition.getType()` to specify that wrapper types should be returned in the case of primitive typed  properties.

**Comment by archiecobbs** [comment]
> So I'd recommend either fixing that bug or updating the Javadoc for `PropertyDefinition.getType()` to specify that wrapper types should be returned in the case of primitive typed properties.

Actually the best solution would be to make any code in Vaadin that uses `PropertyDefinition.getType() do the "wrapping" itself. This solution is safe, fixes all possible cases, and is backward compatible.

**Comment by archiecobbs** [comment]
> Actually the best solution would be to make any code in Vaadin that uses `PropertyDefinition.getType()` do the "wrapping" itself. 

Here's such a patch:
```diff
diff --git a/flow-data/src/main/java/com/vaadin/flow/data/binder/AbstractBeanPropertyDefinition.java b/flow-data/src/main/java/com/vaadin/flow/data/binder/AbstractBeanPropertyDefinition.java
index 0e183c770d..69177fcc2d 100644
--- a/flow-data/src/main/java/com/vaadin/flow/data/binder/AbstractBeanPropertyDefinition.java
+++ b/flow-data/src/main/java/com/vaadin/flow/data/binder/AbstractBeanPropertyDefinition.java
@@ -68,8 +68,7 @@ public abstract class AbstractBeanPropertyDefinition<T, V>
     @SuppressWarnings("unchecked")
     @Override
     public Class<V> getType() {
-        return (Class<V>) ReflectTools
-                .convertPrimitiveType(descriptor.getPropertyType());
+        return (Class<V>)descriptor.getPropertyType();
     }
 
     @Override
diff --git a/flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java b/flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
index f100135c1a..1460fda9de 100644
--- a/flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
+++ b/flow-data/src/main/java/com/vaadin/flow/data/binder/BeanPropertySet.java
@@ -34,6 +34,7 @@ import java.util.stream.Stream;
 
 import com.vaadin.flow.function.ValueProvider;
 import com.vaadin.flow.internal.BeanUtil;
+import com.vaadin.flow.internal.ReflectTools;
 
 /**
  * A {@link PropertySet} that uses reflection to find bean properties.
@@ -116,11 +117,12 @@ public class BeanPropertySet<T> implements PropertySet<T> {
         }
 
         @Override
+        @SuppressWarnings("unchecked")
         public ValueProvider<T, V> getGetter() {
             return bean -> {
                 Method readMethod = getDescriptor().getReadMethod();
                 Object value = invokeWrapExceptions(readMethod, bean);
-                return getType().cast(value);
+                return (V)ReflectTools.convertPrimitiveType(getType()).cast(value);
             };
         }
 
@@ -195,12 +197,13 @@ public class BeanPropertySet<T> implements PropertySet<T> {
         }
 
         @Override
+        @SuppressWarnings("unchecked")
         public ValueProvider<T, V> getGetter() {
             return bean -> {
                 Method readMethod = getDescriptor().getReadMethod();
                 Object value = invokeWrapExceptions(readMethod,
                         parent.getGetter().apply(bean));
-                return getType().cast(value);
+                return (V)ReflectTools.convertPrimitiveType(getType()).cast(value);
             };
         }
 
diff --git a/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java b/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
index 04a80b2add..fa53ba15b1 100644
--- a/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
+++ b/flow-data/src/main/java/com/vaadin/flow/data/binder/Binder.java
@@ -992,7 +992,7 @@ public class Binder<BEAN> implements Serializable {
 
         @SuppressWarnings("unchecked")
         private Converter<TARGET, Object> createConverter(Class<?> getterType) {
-            return Converter.from(getterType::cast,
+            return Converter.from(ReflectTools.convertPrimitiveType(getterType)::cast,
                     propertyValue -> (TARGET) propertyValue, exception -> {
                         throw new RuntimeException(exception);
                     });
```
