### ISSUE TITLE
Apexcharts does not work in production mode with Vite

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#14039]
### Description of the bug
Apexcharts addon from the directory + Vite + Vaadin 23.1.1 works fine in development mode but in production mode you get a JS error

### Minimal reproducible example
```
git clone https://github.com/Artur-/test-apexcharts
cd test-apexcharts
mvn -Pproduction
```

### Expected behavior
A charts should be shown when opening http://localhost:8080

### Actual behavior
```
Uncaught ReferenceError: require is not defined
    at ApexChartsWrapper.ready (generated-flow-imports.cd02bd77.js:2229:622)
    at E.ready (FlowClient.fb0b2676.js:3:77461)
    at ApexChartsWrapper._enableProperties (generated-flow-imports.cd02bd77.js:196:2486)
    at ApexChartsWrapper.connectedCallback (generated-flow-imports.cd02bd77.js:238:1559)
    at ApexChartsWrapper.connectedCallback (generated-flow-imports.cd02bd77.js:248:4997)
    at C1 (FlowClient.fb0b2676.js:3:12787)
    at CE (FlowClient.fb0b2676.js:3:45064)
```

### Versions:
    - Vaadin / Flow version: 23.1.1

**Comment by Artur-** [comment]
This works with Vite 3 beta 0, possibly resolved by https://github.com/vitejs/vite/pull/8459

**Comment by Artur-** [comment]
The cause is probably the dynamic require in https://github.com/appreciated/apexcharts-flow/blob/master/src/main/resources/META-INF/resources/frontend/com/github/appreciated/apexcharts/apexcharts-wrapper.js#L97

**Comment by Artur-** [comment]
A PR for Apexcharts to make this work also with Vite 2: https://github.com/appreciated/apexcharts-flow/pull/134

**Comment by Artur-** [comment]
Closing this as there is nothing that can be fixed in Flow. Either the Apexcharts PR should be applied or this will work once Flow upgrades to Vite 3 (which currently has some other issues)
