### ISSUE TITLE
Please add null check for ComponentEventBus.ListenerWrapper.listener

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#14150]
### Description of the bug

It's possible to add a null listener which will cause Vaadin to fail much later on, with a more cryptic error message:
```
java.lang.NullPointerException: null
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206) ~[flow-server-23.1.1.jar:23.1.1]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:448) ~[flow-server-23.1.1.jar:23.1.1]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:265) ~[flow-server-23.1.1.jar:23.1.1]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-23.1.1.jar:23.1.1]
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447) ~[flow-server-23.1.1.jar:23.1.1]
```

### Expected behavior

Adding a null listener should fail with a clear error message eagerly. That can be achieved with checking that ListenerWrapper.listener is not null in ListenerWrapper's constructor.

Eager null check is in line with the "fail eagerly" principle.

On top of that:
1. ListenerWrapper.listener should be final
2. ComponentEventBus.component should be final
3. ComponentEventBus.component should be null-checked in ComponentEventBus's constructor

### Minimal reproducible example

```java
public class MainView extends VerticalLayout {

    public MainView() {

        Button button = new Button("Say hello");
        button.addClickListener(null);
        add(button);
    }
}
```
Click the "Say hello" button - a NPE is thrown. The exception should have been thrown much earlier, during the `button.addClickListener(null);` call.

### Versions

- Vaadin / Flow version: 14.8.13
- Java version: 11

**Comment by web-padawan** [comment]
Similar issue for passing `null` to a value change listener: https://github.com/vaadin/flow-components/issues/3437

**Comment by web-padawan** [comment]
Another similar issue reported also for `IntegerField`: https://github.com/vaadin/flow-components/issues/3453
