### ISSUE TITLE
Dependency incompatibility when using Element.getOuterHTML

### ISSUE THREAD

**Issue by mrgreywater** [vaadin/flow#14180]
### Description

When using placeholder items in VirtualList (and having a dependency to io.github.bonigarcia.webdrivermanager:4.4.0), the following exception is thrown:

```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.isBlock()" because the return value of "org.jsoup.nodes.Element.parent()" is null
	at org.jsoup.nodes.Element.isInlineable(Element.java:1619) ~[jsoup-1.13.1.jar:na]
	at org.jsoup.nodes.Element.outerHtmlHead(Element.java:1479) ~[jsoup-1.13.1.jar:na]
	at org.jsoup.nodes.Node$OuterHtmlVisitor.head(Node.java:740) ~[jsoup-1.13.1.jar:na]
	at org.jsoup.select.NodeTraversor.traverse(NodeTraversor.java:25) ~[jsoup-1.13.1.jar:na]
	at org.jsoup.nodes.Node.outerHtml(Node.java:606) ~[jsoup-1.13.1.jar:na]
	at org.jsoup.nodes.Node.outerHtml(Node.java:601) ~[jsoup-1.13.1.jar:na]
	at com.vaadin.flow.dom.Element.getOuterHTML(Element.java:1293) ~[flow-server-23.1.3.jar:23.1.3]
	at com.vaadin.flow.component.virtuallist.VirtualList.updateTemplateInnerHtml(VirtualList.java:325) ~[vaadin-virtual-list-flow-23.1.3.jar:na]
	at com.vaadin.flow.component.virtuallist.VirtualList.lambda$registerTemplateUpdate$f7fe4649$1(VirtualList.java:295) ~[vaadin-virtual-list-flow-23.1.3.jar:na]
	at com.vaadin.flow.component.virtuallist.VirtualList.lambda$runBeforeClientResponse$34f88668$1(VirtualList.java:302) ~[vaadin-virtual-list-flow-23.1.3.jar:na]
	...
```

The dependency (and version) was in my pom because it was in a starter project of a previous version of vaadin. This incompatibility was difficult to find, as there is no good indication what's actually causing the problem.

### Expected outcome

VirtualList is shown with placeholder items.

### Minimal reproducible example

[my-todo.zip](https://github.com/vaadin/flow-components/files/9111202/my-todo.zip)

### Steps to reproduce

Run the repro example and notice the Nullpointer Exception

### Environment

Vaadin version(s): 23.1.3
OS: Windows 11

**Comment by mcollovati** [comment]
Checking at the project it seems like that the `webdrivermanager` is not used at all and can be removed.
Otherwise it should be upgraded. Latest starter preset has version 5.1.1

**Comment by caalador** [comment]
Closing issue as there is nothing specific we can do as the jsoup transitive dependency in webdrivermanager is found for a shorter path than the flow-server dependency.
```
\- io.github.bonigarcia:webdrivermanager:jar:4.4.0:test
   \- org.jsoup:jsoup:jar:1.13.1:compile
```
vs
```
+- com.vaadin:vaadin:jar:23.1.1:compile
 |  +- com.vaadin:vaadin-core:jar:23.1.1:compile
 |  |  +- com.vaadin:flow-server:jar:23.1.1:compile
 |  |  |  +- org.jsoup:jsoup:jar:1.14.3:compile
```

This works exactly as defined in [Maven dependency doc](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) even though the webdrivermanager is in the test scope.

**Comment by mrgreywater** [comment]
Well, one could add a dependency version check, similarly to how the version of node and npm is checked.
But probably the likelyhood of this issue occuring for someone else is low and if it happens hopefully he will find this issue report...

**Comment by caalador** [comment]
As I can't find any documentation mentioning the 4.x version I would expect that not many encounter this.
Also the exception is quite specific so this issue is the only match if you search with the null pointer exception.
