### ISSUE TITLE
Flow-Client 9.0 is not compatible with Node 18

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#14554]
### Description of the bug

when building flow project on branch `9.0`, the build fail on `flow-client` module with error:
```
[INFO] --- exec-maven-plugin:3.0.0:exec (run-tests) @ flow-client ---

> @vaadin/flow-deps@0.0.1 test
> npm run build && npm run webpack && intern


> @vaadin/flow-deps@0.0.1 build
> npm run client && tsc


> @vaadin/flow-deps@0.0.1 client
> node scripts/client.js

> @vaadin/flow-deps@0.0.1 webpack
> webpack --config=webpack.tests.config.js

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\WorkFolder\flow\flow-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\WorkFolder\flow\flow-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\WorkFolder\flow\flow-client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\WorkFolder\flow\flow-client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\WorkFolder\flow\flow-client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\WorkFolder\flow\flow-client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\WorkFolder\flow\flow-client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\WorkFolder\flow\flow-client\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.9.0
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)

```

### Expected behavior

project builds successfully 

### Minimal reproducible example

- node -v (should be Node 18)
- clone flow project 
- git checkout 9.0
- mvn install 
  - or just build `flow-client` module with the same command, if you have other flow 9.0-SNAPSHOT artifacts 

### Versions

- Vaadin / Flow version: Vaadin 22, flow 9.0
- Node 18.9.0/node 18.7.0 on TeamCity

**Comment by ZheSun88** [comment]
the same workaround mentioned [here](https://github.com/webpack/webpack/issues/14532) still works

for example the following steps works:
- cd flow-client
- export NODE_OPTIONS=--openssl-legacy-provider
- mvn install

**Comment by mshabarov** [comment]
Fixed by https://github.com/vaadin/flow/pull/14601
