### ISSUE TITLE
Can't move a node from one state tree to another when using @PreserveOnRefresh

### ISSUE THREAD

**Issue by mlopezFC** [vaadin/flow#14609]
### Description of the bug

A Vaadin 23.1.6 (the same issue was still appearing after upgrading to 23.2.1) application that works fine, starts to throw the following exception when adding @PreserveOnRefresh on the Layout that is used by the views when the views are reloaded (F5).

```
java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree
at com.vaadin.flow.internal.StateNode.doSetTree(StateNode.java:738) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.internal.StateNode.lambda$setTree$3(StateNode.java:379) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.internal.StateNode.visitNodeTree(StateNode.java:687) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.internal.StateNode.setTree(StateNode.java:379) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:273) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:80) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:55) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.internal.nodefeature.ElementChildrenList.add(ElementChildrenList.java:44) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.insertChild(AbstractNodeStateProvider.java:104) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.dom.Node.insertChild(Node.java:295) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.dom.Node.appendChild(Node.java:141) ~[flow-server-23.1.6.jar:23.1.6]
at com.vaadin.flow.component.internal.JavaScriptBootstrapUI$JavaScriptUIInternalUpdater.updateRoot(JavaScriptBootstrapUI.java:422) 
```

Adding a breakpoint in line 739 of com.vaadin.flow.internal.StateNode (Vaadin 23.2.1) showed that isOwnerAttached=true and isNotReplaced=false. Inspecting the StateTree showed that the associated element was the <body/> tag.

### Expected behavior

The Views should preserve the state after adding @PreserveOnRefresh on the MainLayout used by the views

### Minimal reproducible example

I do not have a reproducible example for this

### Versions

- Vaadin version: 23.2.1

**Comment by mcollovati** [comment]
I cannot reproduce the issue in a plain java project.
I created two views with and a layout and added the `@PreserveOnRefresh` annotation on the layout.
Reloading the page works fine and state is preserved, I never get the reported error.

```java
@Route(value = "view1", layout = MainLayout.class)
public class MainView1 extends VerticalLayout {
    ...
}

@Route(value = "view2", layout = MainLayout.class)
public class MainView2 extends VerticalLayout {
    ....
}

@PreserveOnRefresh
public class MainLayout extends Div implements RouterLayout {
    ...
}
```
@mlopezFC could you provide an example project that presents the problem, or share the code of your views/layout?

**Comment by mlopezFC** [comment]
Hi Marco.
I found the problem and it was because another instance of a @ Route component was created somewhere else in the project. It would be nice to have more information when this kind of errors happen in a project because it's super hard to find what is causing this and the exception could provide a more meaningful message (like showing which is the associated component / tag and where Vaadin is trying to attach to)
Thanks for taking a look!
