### ISSUE TITLE
Page reload with `@PreserveOnRefresh` fails when a Notification is open

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#14670]
### Description of the bug

When reloading the browser page for a view with `@PreserveOnRefresh` and an open notification, an error occurs and the screen is blank.
Error on server console is `Trying to detach an element from parent that does not have it`

<details><summary>Stacktrace</summary>
<pre>
java.lang.IllegalArgumentException: Trying to detach an element from parent that does not have it.
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:125)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:377)
	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:515)
	at com.vaadin.flow.component.notification.Notification.removeAutoAdded(Notification.java:222)
	at com.vaadin.flow.component.notification.Notification.lambda$initBaseElementsAndListeners$9b1b5227$1(Notification.java:212)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:206)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:195)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:378)
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:401)
	at com.vaadin.flow.component.ComponentUtil.onComponentDetach(ComponentUtil.java:263)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.vaadin.flow.internal.nodefeature.ComponentMapping.onDetach(ComponentMapping.java:109)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at com.vaadin.flow.internal.StateNode.forEachFeature(StateNode.java:358)
	at com.vaadin.flow.internal.StateNode.fireDetachListeners(StateNode.java:856)
	at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:342)
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:281)
	at com.vaadin.flow.internal.nodefeature.NodeFeature.detatchPotentialChild(NodeFeature.java:97)
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.remove(StateNodeNodeList.java:67)
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.remove(ElementChildrenList.java:54)
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:128)
	at com.vaadin.flow.dom.Node.removeChild(Node.java:377)
	at com.vaadin.flow.dom.Element.removeFromTree(Element.java:530)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI$JavaScriptUIInternalUpdater.lambda$moveToNewUI$0(JavaScriptBootstrapUI.java:436)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI$JavaScriptUIInternalUpdater.moveToNewUI(JavaScriptBootstrapUI.java:435)
	at com.vaadin.flow.component.internal.UIInternals.moveElementsFrom(UIInternals.java:774)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getPreservedChain$5(AbstractNavigationStateRenderer.java:803)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getPreservedChain(AbstractNavigationStateRenderer.java:802)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:168)
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getPreservedChain$cdbeaece$1(AbstractNavigationStateRenderer.java:778)
	at com.vaadin.flow.component.page.Page.lambda$retrieveExtendedClientDetails$fc941a8c$1(Page.java:576)
	at com.vaadin.flow.component.internal.PendingJavaScriptInvocation.complete(PendingJavaScriptInvocation.java:96)
	at com.vaadin.flow.server.communication.UidlWriter.lambda$createReturnValueChannel$d9004ac5$1(UidlWriter.java:316)
	at com.vaadin.flow.internal.nodefeature.ReturnChannelMap.lambda$registerChannel$2a20409b$1(ReturnChannelMap.java:124)
	at com.vaadin.flow.internal.nodefeature.ReturnChannelMap$ChannelImpl.invoke(ReturnChannelMap.java:74)
	at com.vaadin.flow.server.communication.ReturnChannelHandler.handleNode(ReturnChannelHandler.java:78)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:75)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:438)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:419)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:419)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:320)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:115)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1564)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
</pre>
</details>

### Expected behavior

Page is shown after reload.
Perhaps notification should be still visible

### Minimal reproducible example

Create a view as following, navigate to it, press the button and once the notification is shown, reload the page (e.g. press F5)

```java
@Route(value = "testview")
@PreserveOnRefresh
public class TestView extends Div {

    public TestView() {
        add(new Button("Say hello", 
                e -> Notification.show("Hello world")));
    }
}
```

### Versions

- Vaadin / Flow version: 23.1.8, 23.2.2
- Java version: 11

**Comment by knoobie** [comment]
Sounds like the same as https://github.com/vaadin/flow-components/issues/3541

**Comment by mcollovati** [comment]
Seems so, will close this one.
Thank you very much for pointing out @knoobie
