### ISSUE TITLE
Error compiling frontend with Vite on Windows

### ISSUE THREAD

**Issue by sferrazjr** [vaadin/flow#14713]
### Description of the bug

I migrated from vaadin version 23.1.3 to 23.2.2 and tried to use Vite but I got an error while starting my app.
### Minimal reproducible example
1. I deleted the folders /node_modules and /frontend/generated and files /webpack* and /package* 
2. Changed the vaadin version on pom.xml
3. Ran mvn clean install
4. Started the app on IntelliJ and got the message before starting frontend compilation:
```
node:internal/errors:856
  const err = new Error(message);
              ^

Error: Command failed: C:\Users\myuser\.vaadin\node\node.exe C:\Users\myuser\mycompany\myproject\node_modules\esbuild\bin\esbuild --version
node:child_process:879
    throw err;
    ^
```
5. Then after compilation fails I get the message
```
java.lang.IllegalStateException: Startup of Vite failed. Output was:
failed to load config from C:\Users\myuser\development\repos\mycompany\myproject\vite.config.ts
error when starting dev server:
Error: spawn EPERM
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:713:9)
    at ensureServiceIsRunning (C:\Users\myuser\development\repos\mycompany\myproject\node_modules\esbuild\lib\main.js:2041:29)
    at build (C:\Users\myuser\development\repos\mycompany\myproject\node_modules\esbuild\lib\main.js:1931:26)
    at bundleConfigFile (file:///C:/Users/myuser/development/repos/mycompany/myproject/node_modules/vite/dist/node/chunks/dep-665b0112.js:63328:26)
    at loadConfigFromFile (file:///C:/Users/myuser/development/repos/mycompany/myproject/node_modules/vite/dist/node/chunks/dep-665b0112.js:63304:31)
    at resolveConfig (file:///C:/Users/myuser/development/repos/mycompany/myproject/node_modules/vite/dist/node/chunks/dep-665b0112.js:62904:34)
    at createServer (file:///C:/Users/myuser/development/repos/mycompany/myproject/node_modules/vite/dist/node/chunks/dep-665b0112.js:61978:26)
    at CAC.<anonymous> (file:///C:/Users/myuser/development/repos/mycompany/myproject/node_modules/vite/dist/node/cli.js:700:30)

```
7. from package.json -> "esbuild-loader": "2.19.0"
8. the same app runs without problems in Unix environment
9. running `C:\Users\myuser\.vaadin\node\node.exe C:\Users\myuser\mycompany\myproject\node_modules\esbuild\bin\esbuild --version` on command line return the same error
10. node version v16.17.0

### Expected behavior

App should start without error messages
### Actual behavior

App fails to start
### Versions:
    - Vaadin / Flow version: 23.2.2
    - Java version: Eclipse Temurin 17.0.3
    - OS version: Windows 11
    - Browser version (if applicable):
    - Application Server (if applicable):
    - IDE (if applicable):
    - Development or production mode: development
    - Project from start.vaadin.com or activated in application:

**Comment by caalador** [comment]
esbuild-loder is a webpack dependency and shouldn't be in the package.json at all.
For a clean project from start.vaadin.com I got `esbuild` version `0.15.10` through `vite@3.1.0`
Does the same issue appear with a starter from [start](https://start.vaadin.com)?

**Comment by sferrazjr** [comment]
Hi @caalador, thanks for your reply

I was cleaning the files manually instead of running `mvn clean vaadin:clean-frontend`, when I got package.json deleted too, then I could run my app without problems.

and now package.json doesn't have any reference to esbuild and vite is v3.1.0

Thanks
