### ISSUE TITLE
NoClassDefFound exception in Vaadin 24 Quarkus tests

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#14739]
### Description of the bug

V24 Quarkus IT tests fail with:

```
2022-09-09 09:36:54,617 ERROR [io.und.request] (executor-thread-0) UT005071: Undertow request failed HttpServerExchange{ GET /uievents delegate io.undertow.vertx.VertxHttpExchange@23eecb48}: java.lang.NoClassDefFoundError: jakarta/servlet/ServletConnection
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:132)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:120)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:417)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:560)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletConnection
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:114)
        at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:64)
        ... 14 more

```

### Expected behavior

Tests pass

### Minimal reproducible example

-

### Versions

-

**Comment by MarcinVaadin** [comment]
Unfortunately Quarkus looks like decided to skip Servlet 5 and go ahead towards Servlet 6 :-1: https://github.com/quarkusio/quarkus/commit/c1e080372a540ec4a24b56a262704c21cd52e735

**Comment by Artur-** [comment]
That shouldn't be an issue as servlet 6 is compatible with servlet 5, right?

**Comment by Artur-** [comment]
Yes but that is not a problem, right?

**Comment by Artur-** [comment]
Of course it means that Quarkus cannot work on a servlet 5 server but that is out of our control

**Comment by MarcinVaadin** [comment]
Yes, adding jakarta servlet 6 api dependency fixes the missing class issue but is it a proper approach to use it by default in vaadin-quarkus? Quarkus uses Undertow in some 5.0.0 (Jakarta 6) alpha version by default.

**Comment by MarcinVaadin** [comment]
After updating servlet-api to 6 PR is green https://github.com/vaadin/quarkus/pull/83
