### ISSUE TITLE
New Vaadin v23.2.3 starter don't work under tomcat

### ISSUE THREAD

**Issue by husein-musawa** [vaadin/flow#14779]
### Description of the bug

New Vaadin v23.2.3 starter don't work when running under Apache Tomcat (tested on version 9.0.48 & 9.0.68 & 10.0.20, JDK version 11.0.16).

Here's the Tomcat's deployment log:

```
10-Oct-2022 05:19:41.358 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
10-Oct-2022 05:19:41.375 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/todo] startup failed due to previous errors
10-Oct-2022 05:19:41.401 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches Failed to clear soft references from ObjectStreamClass$Caches for web application [todo]
	java.lang.ClassCastException: class java.io.ObjectStreamClass$Caches$1 cannot be cast to class java.util.Map (java.io.ObjectStreamClass$Caches$1 and java.util.Map are in module java.base of loader 'bootstrap')
		at org.apache.catalina.loader.WebappClassLoaderBase.clearCache(WebappClassLoaderBase.java:2325)
		at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesObjectStreamClassCaches(WebappClassLoaderBase.java:2300)
		at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1669)
		at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1597)
		at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:463)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5515)
		at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:257)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:187)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:728)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:696)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1024)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1911)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:825)
		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:475)
		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1618)
		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:319)
		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:948)
		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:835)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1388)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:921)
		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:263)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:437)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:934)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:476)
10-Oct-2022 05:19:41.413 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/home/husein/Apps/apache-tomcat-9.0.48/webapps/todo.war] has finished in [3,820] ms
```

### Expected behavior

The App should work under tomcat without any modification, as it's a common usage and working on previous versions. Last time I use Vaadin v23.0.10.

### Minimal reproducible example

* Download Vaadin 23.2.3 starter from the following url: https://vaadin.com/docs/latest/guide/quick-start
* Change the pom.xml's packaging into war: `<packaging>war</packaging>`
* Run mvn clean package -Pproduction
* Rename the resulted .war file inf target folder into a simpler one, eg. todo.war, then copy to webapps folder under tomcat installation
* Run the Tomcat server if it's not already running
* Check the log (mine is catalina.out on Tomcat 9.0.48)

### Versions

- Vaadin / Flow version: 23.2.3
- Java version: 11.0.16
- OS version: Fedora Desktop x86_64 Linux 5.19.8-200.fc36.x86_64
- Browser version (if applicable):
- Application Server (if applicable): Apache Tomcat 9.0.48, 9.0.68, 10.0.20
- IDE (if applicable):

**Comment by mstahv** [comment]
Changing the packaging to war is not enough with Spring Boot project. Did you follow some documentation that ought to be updated?

There is actually nothing Vaadin specific here and we should only refer to official Spring Boot docs: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.traditional-deployment

**Comment by husein-musawa** [comment]
You're right. It works now. I missed the ` extends SpringBootServletInitializer`. It's been a long time since I use a new starter. Thank you for your info. Sorry for the fuss.
