### ISSUE TITLE
VaadinMVCWebAppInitializer does not work in v23 with jetty

### ISSUE THREAD

**Issue by jsalts** [vaadin/flow#14964]
### Description of the bug

VaadinMVCWebAppInitializer does not properly call setAsyncSupported on all servlets it is configuring. The class generates two servlets, SpringServlet and a dispatcher servlet. setAsyncSupported() is only called on the former and not the latter. Jetty servlets. When running with v23 and jetty 9.4.49.v20220914 the application displays the following exception in console. Logging into the app works but the response time is sluggish.  This same setup with VaadinMVCWebAppInitializer and jetty worked fine in v14. 

```
Caused by: java.lang.IllegalStateException: !asyncSupported: NotAsync:org.springframework.web.servlet.DispatcherServlet@3968376c
	at org.eclipse.jetty.server.Request.startAsync(Request.java:2351) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at javax.servlet.ServletRequestWrapper.startAsync(ServletRequestWrapper.java:464) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.atmosphere.cpr.AtmosphereRequestImpl.startAsync(AtmosphereRequestImpl.java:635) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:?]
	at org.atmosphere.container.Servlet30CometSupport.suspend(Servlet30CometSupport.java:91) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:?]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:69) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:?]
	at org.atmosphere.container.AbstractJetty9AsyncSupportWithWebSocket.service(AbstractJetty9AsyncSupportWithWebSocket.java:161) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:?]
	at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:35) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:?]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2292) ~[atmosphere-runtime-2.7.3.slf4jvaadin4.jar:?]
	at com.vaadin.flow.server.communication.PushRequestHandler.handleRequest(PushRequestHandler.java:254) ~[flow-server-23.2.4.jar:23.2.4]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1564) ~[flow-server-23.2.4.jar:23.2.4]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369) ~[flow-server-23.2.4.jar:23.2.4]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-23.2.4.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:618) ~[jetty-security-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:167) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:81) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:964) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.23.jar:5.3.23]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1450) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505) ~[jetty-servlet-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.49.v20220914.jar:9.4.49.v20220914]
	... 18 more
```

The workaround is to extend VaadinMVCWebAppInitializer and add this code to onStartup(). 

```
Registration.Dynamic reg = (Registration.Dynamic) servletContext.getServletRegistration("dispatcher");
    reg.setAsyncSupported(true);
```

### Expected behavior

No exception present. 

### Minimal reproducible example

Haven't set one up yet. A basic jetty / spring / VaadinMVCWebAppInitializer setup should work. Start the application. In development mode the errors start when navigating to the app. In production mode the errors start immediately. 

### Versions

- Vaadin / Flow version: 23.2.4
- Java version: 17.0.4.1
- OS version: Mac OS 12.5.1
- Browser version (if applicable): Chrome 106.0.5249.119 
- IDE (if applicable): Intellij

**Comment by caalador** [comment]
As I do not have any SpringMVC + vaadin applications available I tested with the only one I had using vaadin `23.2.6` and jetty `9.4.49.v20220914` and it didn't have any problems.

If possible could you add a project here that replicates the issue.

**Comment by mcollovati** [comment]
I tried to reproduce with a spring bases project (not Spring Boot) and Vaadin 23.2.4 (using VaadinMVCWebAppInitializer) running on jetty 9.4.49.v20220914, but I never got the error reported in the issue.

@jsalts do you have some specific configuration, such as a custom Vaadin servlet? Would you be able to provide an example project to reproduce the issue?
Otherwise, there is not much what we can do with this.

**Comment by mshabarov** [comment]
@jsalts we close this issue because of no response within more than 2 weeks. Please let us know if you have the issue still on your side.
