### ISSUE TITLE
Importing styles from SCSS files in lit webcomponent fails with Vite

### ISSUE THREAD

**Issue by rna2i** [vaadin/flow#15058]
### Description of the bug

We are having issues with web components that import scss files. We get the same error as described in:
https://github.com/vaadin/flow/issues/14142
![Screenshot 2022-11-09 at 11 15 23](https://user-images.githubusercontent.com/66952933/200812091-0c0b9754-9373-49dd-ac5e-76fff780f7e0.png)

### Expected behavior

SCSS styles should import and work as expected.

### Minimal reproducible example

Example app: https://github.com/rna2i/hilla-vite-lit-scss-test

In the hello-world view, I am trying to import and use a test-component which uses SCSS, but we get an error in browser console and the test component is not shown.

css-tag.js:106 Uncaught TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet'.
    at adoptStyles (css-tag.js:106:1)
    at TestComponent.createRenderRoot (reactive-element.js:544:20)
    at TestComponent.createRenderRoot (lit-element.js:95:1)
    at TestComponent.connectedCallback (reactive-element.js:556:1)
    at TestComponent.connectedCallback (lit-element.js:144:1)
    at TestComponent.connectedCallback (mixin.ts:43:19)
    at TestComponent.connectedCallback (view.ts:68:11)
    at ChildPart._insert (lit-html.js:867:1)
    at ChildPart._commitNode (lit-html.js:906:1)
    at ChildPart._commitTemplateResult (lit-html.js:1008:1)

### Versions

- Vaadin / Flow version: Hilla 1.2.7
- Java version: 17
- OS version: Mac OS X 12.6
- Browser version (if applicable): Chrome 107.0.5304.87
- Application Server (if applicable):Spring Boot 2.7.5
- IDE (if applicable): IntelliJ

**Comment by Artur-** [comment]
```
import styles from './test-component.scss'
```

imports the css as a string and

```
    static get styles() {
        return [styles];
    }
```

in lit expects a `CSSResult` or `CSSStyleSheet`. It works if you do
```
    static get styles() {
        return [unsafeCSS(styles)];
    }
```

**Comment by rna2i** [comment]
Thank you - that helped :)
But I am a bit unsure if this is the "final" solution to use unsafeCss?

**Comment by mshabarov** [comment]
I've put a documentation label here to add this case and the recommendation into Vaadin docs.

**Comment by gethari** [comment]
@rna2i did you get solution to this issue ?

**Comment by rna2i** [comment]
> @rna2i did you get solution to this issue ?

The proposed solution from Arthur worked for us.
