### ISSUE TITLE
Closed UI with corrupted state tree cannot be removed

### ISSUE THREAD

**Issue by p-engl** [vaadin/flow#15100]
### Description of the bug

In our application we use @PreserveOnRefresh. In rare cases a state tree gets corrupted (this might happen in case that a component - which was added and removed before browser refresh - is readded to the new UI). This immediately leads to an exception which is fine in my opinion.
The problem however is that the VaadinSession of the UI cannot be cleaned up since the cleanup will always cause an exception. This leads to Exceptions every few seconds (it seems that a heartbeat request is resent every few seconds in this case).
This is the console output we receive (the first line is a custom log which will always we logged before the exception):

```
2022-11-11 09:56:16,236 INFO : Received heartbeat request for UI
Nov 11, 2022 9:56:16 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [my_servlet] in context with path [] threw exception
java.lang.IllegalStateException: Unregistered node was not found based on its id. The tree is most likely corrupted.
	at com.vaadin.flow.internal.StateTree.unregister(StateTree.java:243)
	at com.vaadin.flow.internal.StateNode.handleOnDetach(StateNode.java:778)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.internal.StateNode.onDetach(StateNode.java:338)
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:281)
	at com.vaadin.flow.internal.StateTree$RootNode.setParent(StateTree.java:65)
	at com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:410)
	at com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:623)
	at com.vaadin.flow.server.VaadinService.lambda$removeClosedUIs$20ed7015$1(VaadinService.java:1336)
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:447)
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:408)
	at com.vaadin.flow.server.VaadinService.removeClosedUIs(VaadinService.java:1334)
	at com.vaadin.flow.server.VaadinService.cleanupSession(VaadinService.java:1298)
	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1498)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:299)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:41002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
```

### Expected behavior

A corrupted state tree should not prevent the removal of closed UIs. 

### Minimal reproducible example

Create a corrupted state tree and wait until the UI closes.

### Versions

- Vaadin / Flow version: 23.1.11
- Java version: 17
- OS version: Windows 10

**Comment by mshabarov** [comment]
@p-engl thanks for reporting this issue!
> In rare cases a state tree gets corrupted (this might happen in case that a component - which was added and removed before browser refresh - is readded to the new UI)

What does it mean "gets corrupted"? From your observations, was it a missing element in the state tree, or?

**Comment by mcollovati** [comment]
Sorry, but until you can provide additional information or some code that reproduces the issue, there is nothing that we can do. Please reopen the issue if you can provide the code to reproduce the issue
