### ISSUE TITLE
Flow plugin doesn't say which .jar file is corrupted

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#15457]
### Description of the bug

See https://github.com/vaadin/flow/issues/15458 for more details. When `BuildFrontendUtil.runNodeUpdater()` fails with `ZipException`, it doesn't log the name of the offending file:

```
Caused by: com.vaadin.flow.server.ExecutionFailedException: Error occured during goal execution: Unable to compute frontend dependenciesPlease run Maven with the -e switch (or Gradle with the --stacktrace switch), to learn the full stack trace.
        at com.vaadin.flow.plugin.base.BuildFrontendUtil.runNodeUpdater(BuildFrontendUtil.java:358)
        at com.vaadin.gradle.VaadinBuildFrontendTask.vaadinBuildFrontend(VaadinBuildFrontendTask.kt:71)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        ... 112 more
Caused by: java.lang.IllegalStateException: Unable to compute frontend dependencies
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.<init>(FrontendDependencies.java:142)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependenciesScanner$FrontendDependenciesScannerFactory.createScanner(FrontendDependenciesScanner.java:130)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependenciesScanner$FrontendDependenciesScannerFactory.createScanner(FrontendDependenciesScanner.java:92)
        at com.vaadin.flow.server.frontend.NodeTasks.<init>(NodeTasks.java:733)
        at com.vaadin.flow.server.frontend.NodeTasks$Builder.build(NodeTasks.java:236)
        at com.vaadin.flow.plugin.base.BuildFrontendUtil.runNodeUpdater(BuildFrontendUtil.java:352)
        ... 117 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at net.bytebuddy.jar.asm.ClassReader.readStream(ClassReader.java:322)
        at net.bytebuddy.jar.asm.ClassReader.<init>(ClassReader.java:287)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:606)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:624)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:624)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:624)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.visitClass(FrontendDependencies.java:624)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.collectEndpoints(FrontendDependencies.java:303)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.computeEndpoints(FrontendDependencies.java:271)
        at com.vaadin.flow.server.frontend.scanner.FrontendDependencies.<init>(FrontendDependencies.java:130)
        ... 122 more
```

### Expected behavior

The exception should be wrapped and rethrown with a more detailed error message which contains the name of the offending file.

### Minimal reproducible example

Not reproducible easily. However, the solution is clear.

### Versions

- Vaadin / Flow version: both 14.x and 23.x

**Comment by Artur-** [comment]
Which was added in #12910

**Comment by Artur-** [comment]
Asssuming this is ok now

**Comment by skiedrowski** [comment]
Correct... we've found the class but still have no idea why it is viewed as being corrupted. And why it is resolved when die gradle daemon is restarted.
