### ISSUE TITLE
UIDetachedException thrown in race condition if HTTP session invalidated

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/flow#15490]
### Description of the bug

I have a Vaadin application with an admin console that allows you to kill other Vaadin sessions, resulting in a logout of that user.

The admin session does this to `targetSession` like this:
```java
targetSession.access(() -> Optional.of(targetSession)
                            .map(VaadinSession::getSession)
                            .map(WrappedSession::invalidate));
```

Note I'm closing the session this way per the documentation for `VaadinSession.close()`. Besides, I want all traces of the session gone from the server and that includes the servlet HTTP session.

However, this generates a `UIDetachedException` in the logs:
```
java.util.concurrent.ExecutionException: com.vaadin.flow.component.UIDetachedException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62)
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2062)
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:712)
	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1503)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.dellroad.stuff.servlet.ExceptionLoggingFilter.doFilterInternal(ExceptionLoggingFilter.java:36)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: com.vaadin.flow.component.UIDetachedException
	at com.vaadin.flow.component.UI.handleAccessDetach(UI.java:415)
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:432)
	at com.vaadin.flow.component.UI$2.execute(UI.java:522)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2059)
	... 31 more
```

### Expected behavior

There should be no uncaught exceptions.

### Minimal reproducible example

Create a target Vaadin session.

Then do this:

```java
targetSession.access(() -> Optional.of(targetSession)
                            .map(VaadinSession::getSession)
                            .map(WrappedSession::invalidate));
```

### Versions

- Vaadin / Flow version: 23.2.11
- Java version: 11
- OS version: MacOS

**Comment by tepi** [comment]
Unfortunately I'm unable to reproduce this issue using the snippet provided.

I added a button to a view, which then finds and invalidates all sessions except the current one. This seems to work fine, other sessions get expired and there are no exceptions.

Could there be something else affecting this @archiecobbs ?

**Comment by archiecobbs** [comment]
OK I think I see what's happening.

There are two tasks queued up for the session, one is a normal one via `UI.access()` and the other is the one to invalidate the session. The latter task happens first and then the former, which of course fails because the session is dead by that point.

This scenario leads to this bit of code in `UI.java` (~line 535):
```java
/*
 * The session has expired after `ui.access` was called.
 * It makes no sense to pollute the logs with a
 * UIDetachedException at this point.
 */
if (exception instanceof ExecutionException
        && ((ExecutionException) exception)
                .getCause() instanceof UIDetachedException) {
    getLogger().debug(exception.getMessage(),
            exception);
} else {
    getLogger().error(exception.getMessage(),
            exception);
}
```
and it fact looking back at the original error I see the error was in fact logged at level DEBUG not ERROR.

So an exception was logged, but it was logged at DEBUG instead of ERROR (which I didn't realize before) - which is entirely appropriate for this scenario.

So, not a bug - closing issue. Thanks & sorry for the confusion.
