### ISSUE TITLE
Quarkus vertx issues with Vite dev mode connection

### ISSUE THREAD

**Issue by MarcinVaadin** [vaadin/flow#15744]
### Description of the bug

Discovered during Quarkus update:
`2023-01-24 09:15:41,523 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 3895 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked`

Quarkus build works using `java.net.preferIPv4Stack=true`

On development mode connecting to dev server is not possible while using IPv6.

Related to https://github.com/vaadin/flow/pull/15689

### Expected behavior

Localhost IP should not be hardcoded?

### Minimal reproducible example
Build app in dev mode

### Versions

- Vaadin / Flow version: 24.0-SNAPSHOT
- OS version: Any with IPv6

**Comment by Artur-** [comment]
Is IPv4 not available? Vite is configured to bind to 127.0.0.1
```
    server: {
      host: '127.0.0.1',
```

but based on the logs it seems like it does not bind to that but to IPv6?

**Comment by Artur-** [comment]
It would probably be possible to parse the 
```
Local: http://host:port/VAADIN/
```
from the Vite output and always use the address from there, then it would work no matter how it is bound

**Comment by MarcinVaadin** [comment]
Broader stacktrace:
`2023-01-24 11:55:02,088 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 604084 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
  at java.base@17.0.2/jdk.internal.misc.Unsafe.park(Native Method)
  at java.base@17.0.2/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
  at java.base@17.0.2/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
  at java.base@17.0.2/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)
  at java.base@17.0.2/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)
  at java.base@17.0.2/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
  at java.base@17.0.2/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
  at com.vaadin.base.devserver.viteproxy.ViteWebsocketConnection.<init>(ViteWebsocketConnection.java:73) <---- HERE
  at com.vaadin.base.devserver.viteproxy.ViteWebsocketProxy.<init>(ViteWebsocketProxy.java:55)
  at com.vaadin.base.devserver.viteproxy.ViteWebsocketEndpoint.onOpen(ViteWebsocketEndpoint.java:95)
  at io.undertow.websockets.EndpointSessionHandler.connected(EndpointSessionHandler.java:119)`

**Comment by mcollovati** [comment]
It seems like a deadlock in the `onMessage` callback provided by `ViteWebsocketProxy` to `ViteWebsocketConnection` when there are many concurrent clients, such as in Quarkus tests

The following one blocks on `sendText`
```java
browserSession.getBasicRemote().sendText(msg);
getLogger().debug("Message sent to browser: " + msg);
```

Refactoring it with asynchronous call seems to work and Quarkus test pass
```java
browserSession.getAsyncRemote().sendText(msg, result -> {
    getLogger().debug("Message sent to browser: " + msg);
});
```

**Comment by Artur-** [comment]
If that helps, I see no reason why not to change it

**Comment by mcollovati** [comment]
The problem with IPv6 is probably because the development mode integration tests modules set `-Dvaadin.devmode.vite.options=--host`.
This configuration is not needed anymore, not that we proxy the Vite websocket
