### ISSUE TITLE
PiT 24.0: cannot run IT's with selenium 

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#15845]
### Description of the bug

When running TB ITs in a project using 24.0-SNAPSHOT it fails:

```
[ERROR] checkRowsCount[ANY_Chrome_](com.vaadin.starter.bakery.testbench.DashboardViewIT)  Time elapsed: 1.991 s  <<< ERROR!
java.lang.NoSuchMethodError: 'void com.sun.jna.Memory.close()'
	at oshi.util.Util.freeMemory(Util.java:83)
	at oshi.jna.ByRef$CloseableSizeTByReference.close(ByRef.java:110)
	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:61)
	at oshi.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:40)
	at oshi.hardware.platform.mac.MacCentralProcessor.initProcessorCounts(MacCentralProcessor.java:119)
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:65)
	at oshi.hardware.platform.mac.MacCentralProcessor.<init>(MacCentralProcessor.java:47)
	at oshi.hardware.platform.mac.MacHardwareAbstractionLayer.createProcessor(MacHardwareAbstractionLayer.java:42)
	at oshi.util.Memoizer$1.get(Memoizer.java:61)
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:48)
	at com.vaadin.pro.licensechecker.MachineId.getComputerId(MachineId.java:29)
	at com.vaadin.pro.licensechecker.MachineId.get(MachineId.java:16)
```

It only happens when using platform SNAPSHOT, but not alpha.
It does not happens in linux, but in mac and windows

### Expected behavior

I can run tests

### Minimal reproducible example

```
git clone https://github.com/vaadin/bakery-app-starter-flow-spring.git
cd bakery-app-starter-flow-spring
git checkout v24
mvn clean verify -Pproduction,it -Dcom.vaadin.testbench.Parameters.testsInParallel=1
```

### Versions

- Vaadin / Flow version: 24.0.0-SNAPSHOT
- Java version: 17
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
- OS version: mac and windows

**Comment by Artur-** [comment]
Sounds like TestBench, not Flow

**Comment by manolo** [comment]
So, finally it was a problem in license-checker, 1.11-SNAPSHOT was including upgrades to oshi-core and jna, which should only happen in 1.12-SNAPSHOT

bumping license-checker to 1.12 and re-deploying 1.11 to the correct hash it works now.
