### ISSUE TITLE
Some web components fail to bundle in production and express modes

### ISSUE THREAD

**Issue by MarcinVaadin** [vaadin/flow#15913]
### Description of the bug

After adding some external components, for example based on LitElement [Adobe Spectrum Tab Panel](https://opensource.adobe.com/spectrum-web-components/components/tabs/):
```
@Tag("sp-tab-panel")
@NpmPackage(value = "@spectrum-web-components/tabs", version = "0.10.7")
@JsModule("@spectrum-web-components/tabs/sp-tab-panel.js") {
```

I cannot build project due to:
```
[ForkJoinPool.commonPool-worker-1] INFO com.vaadin.flow.server.frontend.TaskRunDevBundleBuild - Creating a new express mode bundle. This can take a while but will only run when the project setup is changed, addons are added or frontend files are modified
[commonjs--resolver] Cannot read properties of undefined (reading 'replace')
file: /Users/vaadin/personal/vaadin-spectrum-web-components/node_modules/@spectrum-web-components/tabs/src/tab-panel.css.js
error during build:
TypeError: Cannot read properties of undefined (reading 'replace')
    at escape (/Users/vaadin/personal/vaadin-spectrum-web-components/vite.config.ts:600:27)
    at /Users/vaadin/personal/vaadin-spectrum-web-components/vite.config.ts:631:53
    at walk (/Users/vaadin/personal/vaadin-spectrum-web-components/node_modules/dash-ast/index.js:69:28)
    at walkArray (/Users/vaadin/personal/vaadin-spectrum-web-components/node_modules/dash-ast/index.js:74:27)
    at walk (/Users/vaadin/personal/vaadin-spectrum-web-components/node_modules/dash-ast/index.js:64:9)
    at dashAst (/Users/vaadin/personal/vaadin-spectrum-web-components/node_modules/dash-ast/index.js:17:5)
    at string.walk (/Users/vaadin/personal/vaadin-spectrum-web-components/node_modules/transform-ast/index.js:55:5)
    at Object.transform (/Users/vaadin/personal/vaadin-spectrum-web-components/vite.config.ts:627:19)
    at file:///Users/vaadin/personal/vaadin-spectrum-web-components/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:23899:40
```

In V24 with express mode enabled and in production mode, In V23 in production mode. Works in dev mode (and without express build).

### Expected behavior

Should work with all components in both dev and prod mode.

### Minimal reproducible example

Create class in starter-flow project with component:
```
@Tag("sp-tab-panel")
@NpmPackage(value = "@spectrum-web-components/tabs", version = "0.10.7")
@JsModule("@spectrum-web-components/tabs/sp-tab-panel.js")
public class SpTabPanel extends Component { }
```

### Versions

- Vaadin / Flow version: 24.0.0.beta1, 23.3.6
- Java version: 18
- npm 8.19.2
- node 18.12.1

**Comment by Artur-** [comment]
This is caused by passing `, "**/*.css?*"`as an include pattern to `postcssLit`
`node_modules/@spectrum-web-components/tabs/src/tab-panel.css.js` is not a CSS file
