### ISSUE TITLE
Service worker caches resources with the wrong name for the default bundle

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#16031]
### Description of the bug

When you start a new 24 beta4+ application with `@PWA` you get an error like
```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"http://localhost:8080/VAADIN/build/component-picker-b47c27aa.js","status":404}]
    at d._handleInstall (http://localhost:8080/sw.js:1:8531)
    at async d._handle (http://localhost:8080/sw.js:1:7942)
    at async d._getResponse (http://localhost:8080/sw.js:1:7010)
```

The service worker contains
```
{url:"VAADIN/build/component-picker-b47c27aa.js",revision:"9b2f5c65e10095ac1546b734c3af3f9a"}
```

but the application serves and uses `VAADIN/dev-bundle/VAADIN/build/component-picker-b47c27aa.js` with a `VAADIN/dev-bundle` prefix

### Expected behavior

Caching works

### Minimal reproducible example

The skeleton starter spring app

### Versions

- Vaadin / Flow version: 24 beta 4

**Comment by bsutton** [comment]
We are having a (possibly) related issue.

When we upgrade our vaadin 23.3 web app the name of the generated-flow-imports-fallback.8df3886e.js changes.
However the users browser caches sw.js which contains a refererence to the old fallback import causing the sw to attempt to import the old js file.

It would seem that we need a way to force the sw.js file to reload in the users browser after we do an upgrade.

Is there some way to give the sw.js a unique name e.g. sw.xxxxxx.js so it is forced to reload after each build/upgrade cycle of our website?

**Comment by tltv** [comment]
Reported error is not appearing anymore with 24.0.5. Skeleton starter spring app just logs `A development mode bundle build is not needed`. It was build before by default with this starter but not needed anymore. To test the original issue, force dev mode bundle build e.g. by adding any `@NpmPackage` to view class.

@bsutton Do you still get the same caching issue with 24.0.5 or newer? With 24.0.5 `sw.js` is cached with `Cache-Control: max-age=0` header which should ensure it being reloaded on each page load. Registering of the service worker is done in the end of the bootstrap page which should make sure that changed `sw.js` gets updated or registered for the first time.
