### ISSUE TITLE
Deadlock on logout with V14.9.6+ when using MPR+V7+V14.9 and Push

### ISSUE THREAD

**Issue by johannest** [vaadin/flow#16293]
### Description of the bug

When logging out and invalidating the session the deadlock appears. Example stack traces of dead locked threads (with obfuscated customer details). Leak suspect identified by both customers: https://github.com/vaadin/flow/pull/15767/commits/75bbb7fa60c384ab7d49c695e036e2dbeb7a8b03 

Customer 1 (Jetty)
```
Thread-2210 (I think this thread is created by V7 UI class line 472)

stackTrace:
java.lang.Thread.State: WAITING (parking)
at sun.misc.Unsafe.park(Native Method)
- parking to wait for <0x0000000766669eb8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
at org.eclipse.jetty.util.thread.Locker.lock(Locker.java:46)
at org.eclipse.jetty.server.session.Session.isValid(Session.java:438)
at org.eclipse.jetty.server.session.SessionHandler.isValid(SessionHandler.java:821)
at org.eclipse.jetty.server.Request.getSession(Request.java:1555)
at org.eclipse.jetty.server.session.SessionHandler$SessionAsyncListener.onComplete(SessionHandler.java:168)
at org.eclipse.jetty.server.HttpChannelState$4.run(HttpChannelState.java:908)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1418)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1135)
at org.eclipse.jetty.server.HttpChannelState.onComplete(HttpChannelState.java:924)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:519)
at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:311)
at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1436)
at org.eclipse.jetty.server.HttpChannelState.runInContext(HttpChannelState.java:1135)
at org.eclipse.jetty.server.HttpChannelState.complete(HttpChannelState.java:718)
at org.eclipse.jetty.server.AsyncContextState.complete(AsyncContextState.java:74)
at org.atmosphere.container.Servlet30CometSupport.endAsyncContext(Servlet30CometSupport.java:129)
at org.atmosphere.container.Servlet30CometSupport.complete(Servlet30CometSupport.java:115)
at org.atmosphere.container.Servlet30CometSupport.complete(Servlet30CometSupport.java:45)
at org.atmosphere.cpr.AtmosphereResourceImpl.cancel(AtmosphereResourceImpl.java:807)
at org.atmosphere.cpr.AtmosphereResourceImpl.close(AtmosphereResourceImpl.java:901)
at com.vaadin.flow.server.communication.AtmospherePushConnection.disconnect(AtmospherePushConnection.java:351)
- locked <0x000000076917dc50> (a java.lang.Object)
at com.vaadin.mpr.core.MprPushConnection$$Lambda$2699/1850491731.accept(Unknown Source)
at java.util.Optional.ifPresent(Optional.java:159)
at com.vaadin.mpr.core.MprPushConnection.disconnect(MprPushConnection.java:62)
at com.vaadin.ui.UI.setPushConnection(UI.java:1603)
at com.vaadin.mpr.core.AbstractMprUI.setPushConnection(AbstractMprUI.java:100)
at com.vaadin.ui.UI$3.run(UI.java:482)
at java.lang.Thread.run(Thread.java:750)
Locked ownable synchronizers:
- None


qtp573102881-77535 (Jetty thread)
java.lang.Thread.State: BLOCKED (on object monitor)
at com.vaadin.flow.server.communication.AtmospherePushConnection.disconnect(AtmospherePushConnection.java:317)
- waiting to lock <0x000000076917dc50> (a java.lang.Object)
at com.vaadin.flow.component.internal.UIInternals.setPushConnection(UIInternals.java:453)
at com.vaadin.flow.component.internal.UIInternals.setSession(UIInternals.java:405)
at com.vaadin.flow.server.VaadinSession.removeUI(VaadinSession.java:617)
at com.XXXX.client.flow.XXXXVaadinSession.removeUI(XXXXVaadinSession.java:129)
at com.vaadin.flow.server.VaadinService.lambda$null$65d65655$1(VaadinService.java:666)
at com.vaadin.flow.server.VaadinService$$Lambda$1839/642029137.execute(Unknown Source)
at com.vaadin.flow.component.UI.accessSynchronously(UI.java:435)
at com.vaadin.flow.component.UI.accessSynchronously(UI.java:396)
at com.vaadin.flow.server.VaadinService.lambda$fireSessionDestroy$9c853e43$1(VaadinService.java:656)
at com.vaadin.flow.server.VaadinService$$Lambda$1838/744346178.execute(Unknown Source)
at com.vaadin.flow.server.FutureAccess$$Lambda$1833/352432463.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2073)
at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:707)
at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2039)
at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2006)
at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1010)
at com.XXXXX.client.flow.XXXXVaadinSession.valueUnbound(XXXXVaadinSession.java:448)
at org.eclipse.jetty.server.session.Session.unbindValue(Session.java:379)
at org.eclipse.jetty.server.session.Session.callSessionAttributeListeners(Session.java:355)
at org.eclipse.jetty.server.session.Session.finishInvalidate(Session.java:1100)
at org.eclipse.jetty.server.session.Session.invalidate(Session.java:979)
at org.eclipse.jetty.server.session.SessionHandler.getSession(SessionHandler.java:1009)
at org.eclipse.jetty.server.session.SessionHandler.getHttpSession(SessionHandler.java:610)
at org.eclipse.jetty.server.session.SessionHandler.checkRequestedSessionId(SessionHandler.java:1748)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1650)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:502)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
at java.lang.Thread.run(Thread.java:750)
```

Customer 2 (WebSphere):
![image](https://user-images.githubusercontent.com/2297689/225837375-7d9d0de5-c637-4baf-847b-c93f583c01f4.png)
![image](https://user-images.githubusercontent.com/2297689/225837578-d843b6f1-b1c3-47c0-ad07-70d43a837271.png)

### Expected behavior

Logging out should succeed without deadlock appearing. 

### Minimal reproducible example

To be discussed..

### Versions

- Vaadin / Flow version: 14.9.6+
- Java version: Java8
- OS version: Windows 10+
- Application servers: IBM WebSphere traditional 9.0+ or Jetty

**Comment by mcollovati** [comment]
The deadlock may happen when an HTTP session is invalidated in a thread, causing `VaadinSession` and all Flow UIs to be closed and `AtmospherePushConnection`s to be disconnected, but a push disconnection is concurrently requested by another thread spawned by the Vaadin 8 UI when its session is nullified.
So, there are two concurrent calls to `AtmospherePushConnection.disconnect`; one of those acquires the `AtmospherePushConnection` lock and the other one waits for it to be released.
Unfortunately, it seems that HTTP session operations also are using locks.
In the above case, a lock is held by the thread that is performing session invalidation, but when `AtmospherePushConnection.disconnect` is invoked on the other thread, it calls `AtmosphereResource.close` that tries to access the HTTP session, but it gets stuck waiting for the HTTP session lock to be released.

Actually, we have a thread holding the `AtmosphereConnection` lock unable to release it because it cannot complete disconnection due to the HTTP session lock, that is, however, held by the other thread that is waiting for the `AtmosphereConnection` lock to be released.
