### ISSUE TITLE
"Reset cancel_stream_error" with Firefox and Jetty over HTTP/2

### ISSUE THREAD

**Issue by mperktold** [vaadin/flow#16311]
### Description of the bug

Our exception logs show several instances of the following stack trace:

```
2023-03-20 09:27:22.894 [qtp1072601481-140] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
org.eclipse.jetty.io.EofException: Reset cancel_stream_error
	at org.eclipse.jetty.http2.server.HTTP2ServerConnectionFactory$HTTPServerSessionListener.onReset(HTTP2ServerConnectionFactory.java:163)
	at org.eclipse.jetty.http2.HTTP2Stream.notifyReset(HTTP2Stream.java:853)
	at org.eclipse.jetty.http2.HTTP2Stream.onReset(HTTP2Stream.java:563)
	at org.eclipse.jetty.http2.HTTP2Stream.process(HTTP2Stream.java:392)
	at org.eclipse.jetty.http2.HTTP2Session.onReset(HTTP2Session.java:320)
	at org.eclipse.jetty.http2.parser.Parser$Listener$Wrapper.onReset(Parser.java:367)
	at org.eclipse.jetty.http2.parser.BodyParser.notifyReset(BodyParser.java:139)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.onReset(ResetBodyParser.java:92)
	at org.eclipse.jetty.http2.parser.ResetBodyParser.parse(ResetBodyParser.java:61)
	at org.eclipse.jetty.http2.parser.Parser.parseBody(Parser.java:193)
	at org.eclipse.jetty.http2.parser.Parser.parse(Parser.java:122)
	at org.eclipse.jetty.http2.parser.ServerParser.parse(ServerParser.java:110)
	at org.eclipse.jetty.http2.HTTP2Connection$HTTP2Producer.produce(HTTP2Connection.java:278)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produceTask(AdaptiveExecutionStrategy.java:450)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:243)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
	at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208)
	at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155)
	at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:378)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:936)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1080)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Apparently, this happens sometimes when refreshing the page in Firefox. It only happens when using HTTP/2, and only when WebSockets are enabled.

One reason we would like this to be fixed is because we are also seeing other exceptions, which could be caused by this one.

### Expected behavior

Refreshing the page should not produce exceptions.

### Minimal reproducible example

I created a reproducer in this repo: [mperktold/vaadin14-embedded-jetty](https://github.com/mperktold/vaadin14-embedded-jetty). Despite the name, I upgraded it to Vaadin 23.3.7 and a Jetty version. It also includes a self-signed certificate, which is needed for HTTP/2. You can also create your own if you prefer.

In order to reproduce:
1. Clone the reproducer.
2. Run `Main.java`.
3. Open Firefox and go to https://localhost:8443
4. Click around and refresh the page. You might need to try this a few times.

Afterwards, you should see the exception in the IDE's console.

### Versions

- Vaadin / Flow version: 23.3.7
- Java version: 17
- OS version: Windows 10
- Browser version: Firefox 111.0 (64-Bit)
- Application Server: Jetty 10.0.14

**Comment by mperktold** [comment]
Interesting, I didn't know about `QuietException`. Seems like this would indeed solve the issue, thanks!

**Comment by Artur-** [comment]
Should the default error handler ignore `QuietException`s ?

**Comment by Artur-** [comment]
Not if you do some reflection magic like trying to find a class named `QuiteException` in a super class name

**Comment by mcollovati** [comment]
Sure. It requires inspecting implemented interfaces for the exception hierarchy until `Expection` or `RuntimeException`.
I was just wondering if it is worth it to do in the framework, as it is so specific to the servlet container.
But probably it is
