### ISSUE TITLE
Vites throws warning if using importCss

### ISSUE THREAD

**Issue by knoobie** [vaadin/flow#16528]
### Description of the bug

Creating a theme based on e.g. FontAwesome and using it within the theme.json like so:

```json
{
  "importCss": ["@fortawesome/fontawesome-free/css/all.min.css"],
  "lumoImports": ["typography","color","spacing","badge","utility"]
}
```

Throws the following warning on start-up: 

```log

<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : [vite] warning: 
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : /Users/knoobie/projects/xxx/frontend/generated/theme-xxx.generated.js
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 79 |  import { badge } from '@vaadin/vaadin-lumo-styles/badge.js';
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 80 |  import { utility } from '@vaadin/vaadin-lumo-styles/utility.js';
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 81 |  import module0 from '@fortawesome/fontawesome-free/css/all.min.css';
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :    |                       ^
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 82 |  import vaadinAccordionHeadingCss from 'themes/xxx/components/vaadin-accordion-heading.css?inline';
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : 83 |  import vaadinAccordionCss from 'themes/xxx/components/vaadin-accordion.css?inline';
<6> 2023-04-04T13:49:38.465+02:00  INFO 61104 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Default and named imports from CSS files are deprecated. Use the ?inline query instead. For example: import module0 from '@fortawesome/fontawesome-free/css/all.min.css?inline'


```

Doing the recommended "Use the ?inine query instead" in the theme.json results in a total failure where the application doesn't start anymore:

```log
<6> 2023-04-04T13:52:14.095+02:00  INFO 61173 --- [onPool-worker-1] c.v.b.devserver.AbstractDevServerRunner  : Running Vite to compile frontend resources. This may take a moment, please stand by...
<6> 2023-04-04T13:52:15.768+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : error when starting dev server:
<6> 2023-04-04T13:52:15.768+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Error: Missing npm modules or files '@fortawesome/fontawesome-free/css/all.min.css?inline' for importCss marked in 'theme.json'.
<6> 2023-04-04T13:52:15.768+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Install or update package(s) by adding a @NpmPackage annotation or install it using 'npm/pnpm i'
<6> 2023-04-04T13:52:15.768+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at generateThemeFile (/Users/knoobie/projects/xxx/vite.config.ts:347:13)
<6> 2023-04-04T13:52:15.769+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at handleThemes (/Users/knoobie/projects/xxx/vite.config.ts:509:23)
<6> 2023-04-04T13:52:15.769+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at findThemeFolderAndHandleTheme (/Users/knoobie/projects/xxx/vite.config.ts:467:23)
<6> 2023-04-04T13:52:15.769+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at processThemeResources (/Users/knoobie/projects/xxx/vite.config.ts:454:5)
<6> 2023-04-04T13:52:15.769+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at config (/Users/knoobie/projects/xxx/vite.config.ts:1039:7)
<6> 2023-04-04T13:52:15.769+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at runConfigHook (file:///Users/knoobie/projects/xxx/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:62364:31)
<6> 2023-04-04T13:52:15.769+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
<6> 2023-04-04T13:52:15.769+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at async resolveConfig (file:///Users/knoobie/projects/xxx/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:61865:14)
<6> 2023-04-04T13:52:15.770+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at async createServer (file:///Users/knoobie/projects/xxx/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:61142:20)
<6> 2023-04-04T13:52:15.770+02:00  INFO 61173 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   :     at async CAC.<anonymous> (file:///Users/knoobie/projects/xxx/node_modules/vite/dist/node/cli.js:734:24)

------------------ Frontend compilation failed. ------------------
```

### Expected behavior

Build is successful without Warnings or Errors. 

### Minimal reproducible example

I would argue that it should be reproduceable with the current tests: https://github.com/vaadin/flow/blob/main/flow-tests/test-themes/frontend/themes/app-theme/theme.json

### Versions

- Vaadin / Flow version: 24.0.3 (and probably earlier; just migrated from V23)
- Java version: 17
- OS version: MacOS
- Browser version (if applicable): ---
- Application Server (if applicable): ---
- IDE (if applicable): IDEA

**Comment by Artur-** [comment]
Fixed in #16402
