### ISSUE TITLE
HTMLInputElement's do not function or render after switching views enough times. Uncaught RangeError: Maximum call stack size exceeded at HTMLInputElement.n  

### ISSUE THREAD

**Issue by mcclaicx** [vaadin/flow#16710]
### Description of the bug

After switching views a handful of times, all HTMLInputElement's either do not accept input or do not render
Error: 
Uncaught RangeError: Maximum call stack size exceeded
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38089)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
    at HTMLInputElement.n (vaadin-bundle-26483efc201ed93718f1.cache.js:11897:38099)
n

### Expected behavior

The HTMLInputElement's should render and function properly no matter how many times a user changes views

### Minimal reproducible example

Switch views until error occurs

### Versions

- Vaadin / Flow version: 14.9.6
- Java version: 11
- OS version: 22H2
- Browser version (if applicable): 112.0.5615.138 (Official Build) (64-bit)
- Application Server (if applicable): Tomcat
- IDE (if applicable): IntelliJ 2023

**Comment by mcollovati** [comment]
Hi, thanks for the issue, but with the provided information, I was unable to reproduce it.
Could you please share an example project based on https://github.com/vaadin/skeleton-starter-flow or https://github.com/vaadin/skeleton-starter-flow-spring that reproduces the issue?
Or at least a minimal code snippet that can be used to reproduce the problem

**Comment by mshabarov** [comment]
Closed because of no reply from author for more than 2 weeks.
