### ISSUE TITLE
The "this" variable is undefined in js script with hotdeploy enabled

### ISSUE THREAD

**Issue by finn0s** [vaadin/flow#16842]
### Description of the bug

I'm using the [ChartJs addon](https://vaadin.com/directory/component/chartjs-add-on-for-vaadin-14) in my vaadin 24 application.
When I start the application without hotdeploy enabled its works fine. But with hotdeploy i get this javascript error.
<pre>
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'moment')
    at Moment.js:10:19
    at Moment.js:11:2
</pre>

The ChartJs addon includes a js script with `@JsModule` Annotation.
This script uses the `this` keyword. If `hotdeploy` is enabled the `this` keyword is always `undefined`

I'm using hotdeploy as a workaround for another bug appeared during the migration from vaadin 23 to vaadin 24 described in #16679.
@Silicat-git said he fixed the problem with enabling hotdeploy: https://github.com/vaadin/flow/issues/16679#issuecomment-1522934112

### Expected behavior

I expect that the ChartJs addon works with vaadin 24 and hot deploy enabled.

### Minimal reproducible example

Example: [vaadin-hotdeploy.zip](https://github.com/vaadin/flow/files/11530800/vaadin-hotdeploy.zip)
To enable/disable hotdeploy, set the `vaadin.frontend.hotdeploy` to true or false in the `src/main/resources/application.properties` file

### Versions

- Vaadin / Flow version: 24.0.5
- Java version: 17
- OS version: Windows 10
- Browser version (if applicable): Chrome 113.0.5672.127
- IDE (if applicable): Intellij

**Comment by Artur-** [comment]
Seems like it ships with a quite old version of Momentjs. If you upgrade it to a newer one, it works without problems

**Comment by Artur-** [comment]
The addon also includes a `META-INF/VAADIN/config/flow-build-info.json` which can interfere with the project and should be removed
