### ISSUE TITLE
Vaadin 23.3.13 logging Broadcaster messages repeatedly

### ISSUE THREAD

**Issue by banatom73** [vaadin/flow#16968]
### Description of the bug

After upgrade from 23.3.12 to 23.3.13 application starts to log broadcaster messages repeatedly.
However, the application seems to work properly.
```
2023-06-06 16:31:55.648  WARN VV --- [sphere-Shared-0] org.atmosphere.cpr.DefaultBroadcaster    : This message Entry{message=com.vaadin.flow.server.communication.AtmospherePushConnection$PushMessage@65b85c8b, type=RESOURCE, future=org.atmosphere.cpr.BroadcasterFuture@135a2a27} will be lost
2023-06-06 16:31:55.649  WARN VV --- [sphere-Shared-0] org.atmosphere.cpr.DefaultBroadcaster    : Failed to submit broadcast handler runnable to for Broadcaster/*

java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at com.vaadin.flow.server.communication.LongPollingCacheFilter.filter(LongPollingCacheFilter.java:60)
	at org.atmosphere.cpr.BroadcasterConfig.filter(BroadcasterConfig.java:452)
	at org.atmosphere.cpr.DefaultBroadcaster.perRequestFilter(DefaultBroadcaster.java:822)
	at org.atmosphere.cpr.DefaultBroadcaster.deliverPush(DefaultBroadcaster.java:695)
	at org.atmosphere.cpr.DefaultBroadcaster.push(DefaultBroadcaster.java:572)
	at org.atmosphere.cpr.DefaultBroadcaster$1.run(DefaultBroadcaster.java:423)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Here is my entry point
```
@SpringBootApplication
@Theme(value = "itp")
@PWA(name = "ISO Test Plattform", shortName = "ITP", offlineResources = {})
@NpmPackage(value = "line-awesome", version = "1.3.0")
@NpmPackage(value = "@vaadin-component-factory/vcf-nav", version = "1.0.6")
@Push(transport = Transport.LONG_POLLING)
@PropertySource({
        "classpath:reports.properties",
        "classpath:javamoney.properties",
})
@EnableAsync(proxyTargetClass = true)
public class Application extends SpringBootServletInitializer implements AppShellConfigurator {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
```

### Expected behavior

This did not happen in V23.3.12 or earlier.

### Minimal reproducible example

It seems to start "spamming" after navigation to route with / within
```
@PageTitle("Bill")
@Route(value = BillPayerView.VIEW_NAME, layout = AppMainLayout.class)
@RolesAllowed({"ROLE_SIMULATION_SIMPLE", "ROLE_SIMULATION_ADVANCED"})
public class BillPayerView extends FlexLayout {

    public static final String VIEW_NAME = "Bill/PAYER";

```
### Versions

- Vaadin / Flow version: 23.3.13
- Java version: temurin-17.0.7
- OS version: Mac OS (ARM) 13.4 (22F66)
- Browser version : Chrome Version 114.0.5735.106 (Official Build) (arm64)
- IDE (if applicable): ntelliJ IDEA 2023.1.2 (Ultimate Edition)

**Comment by mcollovati** [comment]
@banatom73 thanks for the issue.
A couple of questions:
* is the application using the embedded tomcat provided by spring boot starter, or are you producing a WAR that is deployed on an external servlet container? If so, what type and version of servlet container are you using?
* Does your application manually trigger push (`UI.push()`)
* Do you have background threads that update the UI using the `UI.access()` feature?
* Does the error happen as a consequence of some specific action on the UI (e.g. pressing a button, etc.) or does it happen randomly or at fixed intervals?

Also, could you please set log level for `com.vaadin.flow.server.communication` category to DEBUG and share the full logs?

**Comment by banatom73** [comment]
- embedded tomcat provided by spring boot starter -> YES
- UI.push() -> NO
- UI.access() -> YES
- As I wrote above, it starts to log after navigate to route path with "/" i.E. bill/biller oder at using QueryParameters. Below "navigateTo" call
```
    private Registration onNavigateTo(AttachEvent attachEvent) {
        return ComponentUtil.addListener(attachEvent.getUI(), NavigateToEvent.class, event -> {
            if (event != null) {
                Tab menuItemTab = menuItems.get(event.getViewClass());
                if (menuItemTab != null) {
                    setSelectedTab(menuItemTab);
                    event.getSource().navigate(event.getViewClass());
                }
            }
        });
    }
```

**Comment by mcollovati** [comment]
Unfortunately, I cannot reproduce the issue with the above information.

Could you be able to share a working project that can be used to reproduce the problem?

**Comment by mcollovati** [comment]
@edler-san thank you for investigation. This should have been fixed in the commit you can see referenced in this ticket.
For Vaadin 23, the change has been released on 23.3.15

**Comment by mcollovati** [comment]
The weird thing about the issues is that a null check was performed a couple of lines before the `parseInt`

**Comment by banatom73** [comment]
With 23.3.15 is the issue fixed ->_**java.lang.NumberFormatException: Cannot parse null string.**_ But the application still runs in an endless loop, although no PUSH was requested in this case.

```
2023-06-27 14:28:35.570 DEBUG VV --- [nio-8082-exec-6] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.570 DEBUG VV --- [nio-8082-exec-6] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.570 DEBUG VV --- [nio-8082-exec-6] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.570 DEBUG VV --- [nio-8082-exec-6] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.577 DEBUG VV --- [nio-8082-exec-3] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.577 DEBUG VV --- [nio-8082-exec-3] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.577 DEBUG VV --- [nio-8082-exec-3] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.577 DEBUG VV --- [nio-8082-exec-3] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.582 DEBUG VV --- [io-8082-exec-10] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.582 DEBUG VV --- [io-8082-exec-10] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.582 DEBUG VV --- [io-8082-exec-10] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.582 DEBUG VV --- [io-8082-exec-10] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.587 DEBUG VV --- [nio-8082-exec-5] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.587 DEBUG VV --- [nio-8082-exec-5] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.587 DEBUG VV --- [nio-8082-exec-5] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.587 DEBUG VV --- [nio-8082-exec-5] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.595 DEBUG VV --- [nio-8082-exec-7] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.595 DEBUG VV --- [nio-8082-exec-7] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.595 DEBUG VV --- [nio-8082-exec-7] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.595 DEBUG VV --- [nio-8082-exec-7] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.600 DEBUG VV --- [nio-8082-exec-2] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.600 DEBUG VV --- [nio-8082-exec-2] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.600 DEBUG VV --- [nio-8082-exec-2] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.600 DEBUG VV --- [nio-8082-exec-2] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.605 DEBUG VV --- [nio-8082-exec-8] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.605 DEBUG VV --- [nio-8082-exec-8] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.605 DEBUG VV --- [nio-8082-exec-8] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.605 DEBUG VV --- [nio-8082-exec-8] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.610 DEBUG VV --- [nio-8082-exec-9] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.610 DEBUG VV --- [nio-8082-exec-9] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
2023-06-27 14:28:35.610 DEBUG VV --- [nio-8082-exec-9] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.610 DEBUG VV --- [nio-8082-exec-9] c.v.f.server.communication.UidlWriter    : * Creating response to client
2023-06-27 14:28:35.614 DEBUG VV --- [nio-8082-exec-1] c.v.f.server.communication.PushHandler   : New push connection for resource 8c07243f-7329-4acd-b9de-0fa6b34d509a with transport LONG_POLLING
2023-06-27 14:28:35.615 DEBUG VV --- [nio-8082-exec-1] c.v.f.s.c.AtmospherePushConnection       : Disconnection already in progress, ignoring request
```

**Comment by mcollovati** [comment]
Unfortunately, as said, I'm not able to reproduce the problem locally with the provided information.
It would be very helpful if you could create and share an example project that can be used to investigate the issue.
Otherwise, it will be very hard to find the cause of the issue

**Comment by mcollovati** [comment]
An example project would be the best thing, but I can understand it may not be so easy to create.
Let me check if we can arrange a debugging session

**Comment by mcollovati** [comment]
@banatom73 do you have invisible components on the views?

**Comment by banatom73** [comment]
Do you mean i.e. `headerLayout.setVisible(false)`? Yes

**Comment by mcollovati** [comment]
Thanks. 
This could possibly be a cause for the continuous reconnection if the invisible components are registering JS invocations.
A fix has already been merged, but not yet released.
I'll keep you posted

**Comment by mcollovati** [comment]
@banatom73 Flow 23.3.15 has been released with the JS invocation fix. There's not yet a new Vaadin Platform version, but you can try the fix by adding in your project the flow-bom right over the vaadin-bom

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>flow-bom</artifactId>
                <version>23.3.15</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by banatom73** [comment]
@mcollovati YESS. JS invocation fix solves the problem.

**Comment by mcollovati** [comment]
@banatom73 great to hear! Do you think we can close the issue now?

**Comment by banatom73** [comment]
With com.vaadin:flow-bom:23.3.15 works as expected. Issue can be closed.
