### ISSUE TITLE
New session created when http URL has more than one trailing slash

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#17018]
### Description of the bug

When opening a URL like `http://localhost:8080/foo/bar//` (more than one trailing slash) a new `VaadinSession` is always initiated (even with a normal refresh). After that, a blank page is presented to the user.

As a side effect, the list of Vaadin-provided static resources (file names) are returned by `BeforeEnterEvent::getRouteParameters`: `webcomponents-loader.js`, `client-XYZ.cache.js` etc.

From @mcollovati 's analysis:

The problem seems to be that `BootstrapHandler` computes a wrong relative `base` path, so the resources are not loaded from `/VAADIN/xxx` but from `/foo/VAADIN/xxx`, causing a new UI to be initialised.

However, in the Spring base project, the culprit seems to be the Spring `ForwardingRequestWrapper` that returns a wrong `pathInfo`. Basically, it tries to sanitise the path with the following method

```java
	/**
	 * Sanitize the given path. Uses the following rules:
	 * <ul>
	 * <li>replace all "//" by "/"</li>
	 * </ul>
	 */
	private static String getSanitizedPath(final String path) {
		int start = path.indexOf("//");
		if (start == -1) {
			return path;
		}
		char[] content = path.toCharArray();
		int slowIndex = start;
		for (int fastIndex = start + 1; fastIndex < content.length; fastIndex++) {
			if (content[fastIndex] != '/' || content[slowIndex] != '/') {
				content[++slowIndex] = content[fastIndex];
			}
		}
		return new String(content, 0, slowIndex + 1);
	}
```

And this results in the `pathInfo` having the last '/' char removed (`/foo/asd//` --> `/foo/asd/`). When the `BootstrapHandler` computes the base path, it then returns `./../..` instead of `./../../../`.

A couple of links related to the above Spring behavior, all quite old

https://github.com/spring-projects/spring-framework/issues/15845
https://github.com/spring-projects/spring-framework/issues/16979

This issue is valid only for Spring-based applications.

### Expected behavior

No new session is created for `//` if any already exists.
`getRouteParameters` shouldn't list the resource names.

### Minimal reproducible example

Use Vaadin Spring skeleton starter to reproduce the issue with session.

Add the following session listener:

```java
@Component 
public class MyRuntimeListener implements VaadinServiceInitListener {

   @Override public void serviceInit(ServiceInitEvent event) { 
      event.getSource().addSessionInitListener(initEvent -> { 
         LoggerFactory.getLogger(getClass()).info("A new Session has been initialized!"); 
      }); 
   } 
}
```

Add before enter observer to reproduce the issue with static resources:

```java
@Route("foo/:bar\*") 
public class FooView extends Div implements BeforeEnterObserver {

  @Override
   public void beforeEnter(BeforeEnterEvent event) {
       LoggerFactory.getLogger(getClass()).info("Before enter: " + event.getRouteParameters());
   }

}
```
and navigate to `http://localhost:8080/foo/bar//`.

### Versions

- Vaadin / Flow version: 14.10, 22.1, 23.3, 24.0, 24.1

**Comment by knoobie** [comment]
Note: Once Spring Security is on the classpath (at least for Spring Boot based Applications). The `StrictHttpFirewall` is in used, which rejects such attacks. 

If you enable logging `org.springframework.security.web.firewall: DEBUG` you can clearly see the rejection. 

```log

2023-06-14T16:33:02.160+02:00 DEBUG 63896 --- [nio-8080-exec-1] s.s.w.f.HttpStatusRequestRejectedHandler : Rejecting request due to: The request was rejected because the URL contained a potentially malicious String "//"

org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "//"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlocklistedUrls(StrictHttpFirewall.java:535)
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:505)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by enver-haase** [comment]
Still present in **Vaadin 25.2.x**, and worth adding what it looks like today — the wrong resource paths are no longer the visible part, the app simply hangs.

**1. The base href gains one `..` per empty path segment.** Plain `curl`, no browser needed:

| requested path  | emitted base href       |
|-----------------|-------------------------|
| `/`             | `<base href=".">`       |
| `//`            | `<base href="./..">`    |
| `///`           | `<base href="./../..">` |
| `/references`   | `<base href=".">`       |
| `//references`  | `<base href="./..">`    |
| `/references//` | `<base href="./../..">` |

**2. The client then derives a `location` with a leading slash, and the init request is rejected with 400.** Reduced to the init endpoint alone, the rule is just "any leading slash":

```
GET /?v-r=init&location=              -> 200  {"appConfig":{...}}
GET /?v-r=init&location=references    -> 200  {"appConfig":{...}}
GET /?v-r=init&location=%2F           -> 400  {"status":400,"error":"Bad Request","path":"/"}
GET /?v-r=init&location=%2F%2F        -> 400
GET /?v-r=init&location=%2Freferences -> 400
```

On `/` the browser sends `location=` (empty) and gets 200; on `//` it sends `location=%2F` and gets 400. **Nothing is written to the server log** — no WARN, no ERROR, no stack trace — and the 400 body is Spring Boot's default error JSON.

**3. The client does not check the init response before using it**, which is what turns this into a hang rather than an error:

```
TypeError: Cannot destructure property 'appId' of 't' as it is undefined.
    at Il.flowInit (indexhtml-<hash>.js)
    at async Object.action (indexhtml-<hash>.js)
```

The result is an empty `<div id="outlet">` with the loading indicator animating indefinitely. Nothing tells the user or the operator anything.

**Point 3 looks worth fixing on its own**, independently of how the base path and `location` are computed: a non-OK init response should surface as a visible error and a server-side log entry. That alone turns "the site is stuck and nobody knows why" into something diagnosable in a minute instead of an afternoon.

On the `StrictHttpFirewall` workaround mentioned above: it only helps the subset of users who have Spring Security on the classpath, and that is far from every Vaadin application — a plain Vaadin Spring Boot app has none, and then nothing stands between a stray `//` and this hang.

Reproduced in development mode on `localhost` **without** a reverse proxy, and in production behind nginx 1.24.0, on a plain Vaadin Spring Boot application (custom views and theme, no Spring Security).

Versions: `com.vaadin:vaadin-core:25.2.3`, `com.vaadin:flow-server:25.2.4`, Spring Boot 4.1.0, Java 25, macOS.
