### ISSUE TITLE
Websocket fails with Vaadin 24 and Jetty 12

### ISSUE THREAD

**Issue by oliveryasuna** [vaadin/flow#17244]
### Description of the bug

Atmosphere is not initialized properly. Not sure exactly the problem, but Expert Chat suggests I hand off the research to the Flow team.

On startup:

```
13:54:05.820 [main] WARN  o.a.cpr.DefaultAsyncSupportResolver - Failed to create AsyncSupport class: class org.atmosphere.container.JSR356AsyncSupport, error: {}
java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:126)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:197)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:183)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2078)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:908)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:832)
	at com.vaadin.flow.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:263)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.initAtmosphereForVaadinServlet(JSR356WebsocketInitializer.java:186)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.init(JSR356WebsocketInitializer.java:151)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.contextInitialized(JSR356WebsocketInitializer.java:120)
	at com.vaadin.flow.server.startup.ServletContextListeners.contextInitialized(ServletContextListeners.java:44)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:1568)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.contextInitialized(ServletContextHandler.java:490)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.initialize(ServletHandler.java:662)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.startContext(ServletContextHandler.java:1302)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1210)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1037)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1200)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1034)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:484)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:601)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.server.Server.doStart(Server.java:542)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at com.oliveryasuna.v24j24ws.App.main(App.java:21)
Caused by: java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:58)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:47)
	... 33 common frames omitted
13:54:05.821 [main] ERROR o.a.cpr.DefaultAsyncSupportResolver - Real error: Unable to configure jsr356 at that stage. ServerContainer is null
java.lang.IllegalStateException: Unable to configure jsr356 at that stage. ServerContainer is null
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:58)
	at org.atmosphere.container.JSR356AsyncSupport.<init>(JSR356AsyncSupport.java:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.newCometSupport(DefaultAsyncSupportResolver.java:126)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolveWebSocket(DefaultAsyncSupportResolver.java:197)
	at org.atmosphere.cpr.DefaultAsyncSupportResolver.resolve(DefaultAsyncSupportResolver.java:183)
	at org.atmosphere.cpr.AtmosphereFramework.autoDetectContainer(AtmosphereFramework.java:2078)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:908)
	at org.atmosphere.cpr.AtmosphereFramework.init(AtmosphereFramework.java:832)
	at com.vaadin.flow.server.communication.PushRequestHandler.initAtmosphere(PushRequestHandler.java:263)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.initAtmosphereForVaadinServlet(JSR356WebsocketInitializer.java:186)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.init(JSR356WebsocketInitializer.java:151)
	at com.vaadin.flow.server.communication.JSR356WebsocketInitializer.contextInitialized(JSR356WebsocketInitializer.java:120)
	at com.vaadin.flow.server.startup.ServletContextListeners.contextInitialized(ServletContextListeners.java:44)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:1568)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.contextInitialized(ServletContextHandler.java:490)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.initialize(ServletHandler.java:662)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.startContext(ServletContextHandler.java:1302)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.startContext(WebAppContext.java:1210)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.lambda$doStart$0(ServletContextHandler.java:1037)
	at org.eclipse.jetty.server.handler.ContextHandler$ScopedContext.call(ContextHandler.java:1200)
	at org.eclipse.jetty.ee10.servlet.ServletContextHandler.doStart(ServletContextHandler.java:1034)
	at org.eclipse.jetty.ee10.webapp.WebAppContext.doStart(WebAppContext.java:484)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171)
	at org.eclipse.jetty.server.Server.start(Server.java:601)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121)
	at org.eclipse.jetty.server.Handler$Abstract.doStart(Handler.java:395)
	at org.eclipse.jetty.server.Server.doStart(Server.java:542)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93)
	at com.oliveryasuna.v24j24ws.App.main(App.java:21)
```

Odd though, later I get `WARN  c.v.f.s.c.JSR356WebsocketInitializer - Atmosphere already initialized` and whenever a request I get `WARN  o.a.cpr.AsynchronousProcessor - Websocket protocol not supported`.

### Expected behavior

Atmosphere works as expected.

### Minimal reproducible example

https://github.com/oliveryasuna/vaadin24-jetty12-websocket-issue

Just run `main`.

### Versions

- Vaadin / Flow version: 24.1.3
- Java version: Coretto 17.0.7
- OS version: macOS 13.4
- Browser version (if applicable): Independent
- Application Server (if applicable): Jetty 12.0.0.beta3
- IDE (if applicable): Independent

**Comment by mcollovati** [comment]
Based on this [example](https://github.com/jetty-project/embedded-jetty-websocket-examples/blob/12.0.x/jakarta.websocket-example/src/main/java/org/eclipse/jetty/demo/EventServer.java#L49C2-L59) from jetty, it looks like that you need to set up the embedded jetty to configure the Jakarta Web socket support
In your project, adding `JakartaWebSocketConfiguration` to the context configurations solves the issue

```
    context.setConfigurations(new Configuration[] {
        ...
        new JakartaWebSocketConfiguration()
    });
```

**Comment by oliveryasuna** [comment]
@mcollovati That seems to fix it, thank you.
