### ISSUE TITLE
PiT 24.2: clear message when running app in production without 'build-frontend' goal

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#17438]
### Description of the bug

If I package a vaadin application without creating the frontend bundle, there are a set of errors that do not indicate how to fix, like:

```
java.lang.RuntimeException: Unable to initialize com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener
	at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:191) ~[vaadin-spring-24.1.5.jar!/:na]
	at com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener.lambda$contextInitialized$0(VaadinServletContextInitializer.java:213) ~[vaadin-spring-24.1.5.jar!/:na]
```
or

```
java.lang.IllegalStateException:

  Failed to find the following files:
      - ./generated/jar-resources/lit-renderer.ts
      - ./generated/jar-resources/dialogConnector.js
      - ./generated/jar-resources/gridConnector.js
```

### Expected behavior

When running in production:
- It should never try to install node, or install npm dependencies
- It should no try to compile frontend
- It should print out a meaningful message pointing to the documentation
```
****
This application artefact does not have a valid client bundle, probably you have not executed the goal to generate it.
Please add the `vaadin-maven-plugin` as it's indicated in the documentation
Or generate the application artifact for production by activating the appropriate profile
****
```

#### A project without the profile
```
git clone git@github.com:spring-guides/gs-crud-with-vaadin.git
cd gs-crud-with-vaadin/complete/
./mvnw package
java -jar target/*.jar
```
### A project with the profile but not activating it
1. download a maven project from https://start.spring.io/ (Select maven=
2.
```
./mvnw package
java -jar target/*.jar
```

### Versions

- Vaadin / Flow version: 24 and previous

**Comment by mstahv** [comment]
I guess technically it is not run in production mode in this case 🤷‍♂️, but the development mode fails to start correctly when run via jar file. If it is impossible to to fix it properly this kind of improved error message would be great 👍 I'd though add some text for development mode as well. Like:

```
****
Vaadin development mode failed to start properly. Try running the application directly from IDE or using Spring Boot Plugin (e.g. mvn spring-boot:run).

If you are intending to build a production ready deployment artifact, add the `vaadin-maven-plugin` as it's indicated in
the documentation https://vaadin.com/docs/latest/production/production-build,
or generate the package for production by activating the appropriate profile,
normally by adding `-Pproduction` parameter
****
```
