### ISSUE TITLE
Gradle plug-in doesn't work with JDK 20

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#17444]
### Description of the bug

Starting Vaadin 24 project with Gradle results in "Unsupported class file major version" exception when JDK 20 is used:
```
Caused by: java.lang.RuntimeException: Error scanning file .../base-starter-gradle/base-starter-gradle/build/classes/java/main/com/vaadin/starter/skeleton/GreetService.class
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:802)
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:730)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:170)
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:551)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 64
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:287)
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:896)
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:795)
        ... 6 common frames omitted
```

### Expected behavior

Application should compile and run with JDK 20

### Minimal reproducible example

1. Download github.com/vaadin/base-starter-gradle
2. Checkout v24 branch
3. Be sure you are using Java 20
4. Run `./gradlew clean appRun`

### Versions

- Vaadin / Flow version: 24.1.4
- Java version: 20
- OS version: Mac OS

**Comment by caalador** [comment]
@masc3d Any more information on the project setup, java and gradle version used?
Is your asm version  at least 9.4?
