### ISSUE TITLE
Potential deadlock with VaadinContext.getAttribute and FeateureFlags.get

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#17637]
### Description of the bug

A deadlock situation may happen when two requests concurrently try to access an attribute with `VaadinContext.getAttribute(Class<T>, Supplier<T>)`, and at least one of them is also invoking `FeatureFlags.get` in the provided supplier.

An example from `flow-tests/test-themes` Flow 23.3 test module (can be occasionally reproduced locally after, until #17636 is merged or reverting that change) :

* thread A invokes `IndexHtmlRequestHandler.getCachedIndexHtmlDocument()`, that locks the `ServletContext` through `VaadinContext.getAttribute(...)` providing a supplier that calls `FeatureFlags.get()`,
* thread B concurrently executes `IndexHtmlRequestHandler.getIndexHtmlDocument()` that also calls `FeatureFlags.get()` that locks on `FeaturFlags` class
* When B invokes `FeatureFlags.get() -> VaadinContext.getAttribute()` it has to wait because `ServletContext` is already locked A, but A is calling `FeatureFlags.get()` and it is waiting to lock on `FeatureFlags` class.

<details>
    <summary>Example JStack output</summary>

Found one Java-level deadlock:
=============================
"qtp854203033-62":
  waiting to lock monitor 0x00007ff7c4003130 (object 0x000000071a590f10, a org.eclipse.jetty.webapp.WebAppContext$Context),
  which is held by "qtp854203033-68"

"qtp854203033-68":
  waiting to lock monitor 0x00007ff894014a60 (object 0x0000000724856600, a java.lang.Class),
  which is held by "qtp854203033-133"

"qtp854203033-133":
  waiting to lock monitor 0x00007ff7c4003130 (object 0x000000071a590f10, a org.eclipse.jetty.webapp.WebAppContext$Context),
  which is held by "qtp854203033-68"

Java stack information for the threads listed above:
===================================================
"qtp854203033-62":
	at com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:70)
	- waiting to lock <0x000000071a590f10> (a org.eclipse.jetty.webapp.WebAppContext$Context)
	at com.vaadin.flow.server.webcomponent.WebComponentConfigurationRegistry.getInstance(WebComponentConfigurationRegistry.java:273)
	at com.vaadin.flow.server.communication.WebComponentBootstrapHandler.hasWebComponentConfigurations(WebComponentBootstrapHandler.java:497)
	at com.vaadin.flow.server.communication.WebComponentBootstrapHandler.canHandleRequest(WebComponentBootstrapHandler.java:186)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:34)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1560)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1383)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1305)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel$$Lambda$1182/0x000000080159b498.dispatch(Unknown Source)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy$$Lambda$1104/0x00000008015576b0.run(Unknown Source)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
	at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)

"qtp854203033-68":
	at com.vaadin.experimental.FeatureFlags.get(FeatureFlags.java:146)
	- waiting to lock <0x0000000724856600> (a java.lang.Class for com.vaadin.experimental.FeatureFlags)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getFeatureFlags(IndexHtmlRequestHandler.java:357)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getIndexHtmlDocument(IndexHtmlRequestHandler.java:333)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler$IndexHtmlHolder.<init>(IndexHtmlRequestHandler.java:381)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.lambda$getCachedIndexHtmlDocument$0(IndexHtmlRequestHandler.java:325)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler$$Lambda$1271/0x00000008015cb720.get(Unknown Source)
	at com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:73)
	- locked <0x000000071a590f10> (a org.eclipse.jetty.webapp.WebAppContext$Context)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getCachedIndexHtmlDocument(IndexHtmlRequestHandler.java:324)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.synchronizedHandleRequest(IndexHtmlRequestHandler.java:84)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1560)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1383)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1305)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel$$Lambda$1182/0x000000080159b498.dispatch(Unknown Source)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy$$Lambda$1104/0x00000008015576b0.run(Unknown Source)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
	at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)

"qtp854203033-133":
	at com.vaadin.flow.server.VaadinServletContext.getAttribute(VaadinServletContext.java:70)
	- waiting to lock <0x000000071a590f10> (a org.eclipse.jetty.webapp.WebAppContext$Context)
	at com.vaadin.flow.server.VaadinContext.getAttribute(VaadinContext.java:58)
	at com.vaadin.experimental.FeatureFlags.get(FeatureFlags.java:146)
	- locked <0x0000000724856600> (a java.lang.Class for com.vaadin.experimental.FeatureFlags)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getFeatureFlags(IndexHtmlRequestHandler.java:357)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.getIndexHtmlDocument(IndexHtmlRequestHandler.java:333)
	at com.vaadin.flow.server.communication.IndexHtmlRequestHandler.synchronizedHandleRequest(IndexHtmlRequestHandler.java:85)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1560)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:369)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1383)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1305)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel$$Lambda$1182/0x000000080159b498.dispatch(Unknown Source)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy$$Lambda$1104/0x00000008015576b0.run(Unknown Source)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:934)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1078)
	at java.lang.Thread.run(java.base@17.0.7/Thread.java:833)

Found 1 deadlock.

</details>

### Expected behavior

There should be no deadlock when `VaadinContex.getAttribute(Class<T>, Supplier<T>)` supplier calls `FeatureFlags,get()`

### Minimal reproducible example

Add and execute the following test in `VaadinServletContextTest` class (`flow-server` module`).
The assertion should fail.

```java
    @Test
    public void getAttribute_supplierAccessFeatureFlag_deadlock() throws Exception {
        CountDownLatch latch = new CountDownLatch(2);
        CompletableFuture.allOf(CompletableFuture.runAsync(() -> {
            context.getAttribute(FeatureFlags.class, () -> {
                FeatureFlags out = FeatureFlags.get(context);
                latch.countDown();
                return out;
            });
        }), CompletableFuture.runAsync(() -> {
            FeatureFlags.get(context);
            latch.countDown();
        }));
        Assert.assertTrue("Futures not completed, potential deadlock", latch.await(2, TimeUnit.SECONDS));
    }
```

With Intellij IDEA, to inspect what is happening, you can increase the `latch.await` timeout (e.g. 5 minutes), run the test in debug mode and then from the IDE menu launch `Run -> Debugging Actions -> Get Thread Dump`.
It will show details about the blocked threads.

![image](https://github.com/vaadin/flow/assets/4648894/3dcb83f6-0770-4a32-a446-fe6fffa2b946)
![image](https://github.com/vaadin/flow/assets/4648894/6734420f-8800-49d8-838e-fc493986c5f7)

### Versions

- Vaadin / Flow version: 23.3, but highly probable also 24
- Java version: 17
- OS version: Linux
- Browser version (if applicable):
- Application Server (if applicable):
- IDE (if applicable):

**Comment by mcollovati** [comment]
A better place for the test is `FeatureFlagsTest`

**Comment by mcollovati** [comment]
I wonder if instead of synchronizing on `FeatureFlags` class to avoid creating `FeatureFlagsWrapper` multiple times, we could just rely on the `VaadinContext.getAttribute(Class, Supplier)` feature.

The synchronization on `FeatureFlags` class was introduced In https://github.com/vaadin/flow/pull/14741, to avoid a similar deadlock, when the original code synchronized on `VaadinContext` instance.

On the other hand, removing synchronization on `FeatureFlags.get()` means we assume that `VaadinContext.getAttribute(Class, Supplier)` is thread safe, that makes sense, but should probably emphasized in the Javadocs.
