### ISSUE TITLE
ThemeEditorIT::testCheckbox is failing in Bender

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#17678]
### Description of the bug

ThemeEditorIT.testCheckbox[any_Chrome_]
--
```
java.lang.RuntimeException: testCheckbox[any_Chrome_](com.vaadin.flow.uitest.ui.ThemeEditorIT): run failed 2 times
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:96)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:345)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.AssertionError: expected:<CssRule[vaadin-checkbox.theme-editor-view-checkbox-1::part(checkbox){background-color:rgba(116,219,0,1);border-color:rgba(116,219,0,1);border-width:3px;border-style:solid;}]> but was:<CssRule[vaadin-checkbox.theme-editor-view-checkbox-1::part(checkbox){background-color:rgba(116,219,0,1);border-color:rgba(116,219,0,1);}]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.vaadin.flow.uitest.ui.ThemeEditorIT.checkCssSelectorProperties(ThemeEditorIT.java:195)
	at com.vaadin.flow.uitest.ui.ThemeEditorIT.performTagTest(ThemeEditorIT.java:182)
	at com.vaadin.flow.uitest.ui.ThemeEditorIT.testCheckbox(ThemeEditorIT.java:108)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:491)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:465)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:73)
	... 12 more
```

![image](https://github.com/vaadin/flow/assets/61410877/b3ad76ea-cc9c-4fd2-8a06-eb3c9292bb39)

### Expected behavior

-

### Minimal reproducible example

https://bender.vaadin.com/viewLog.html?buildId=444364&buildTypeId=Flow_Flow242_Flow242Snapshot

### Versions

- Vaadin / Flow version: 24.2-SNAPSHOT

**Comment by mshabarov** [comment]
Fixed.
