### ISSUE TITLE
FrontendLiveReloadIT is flaky

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#18053]
`FrontendLiveReloadIT` in test module `flow-tests/test-live-reload-multimodule/ui/` fails randomly
```
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 32.13 s <<< FAILURE! -- in com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT
Error:  com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile[any_Chrome_] -- Time elapsed: 31.88 s <<< FAILURE!
org.junit.ComparisonFailure: expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile(FrontendLiveReloadIT.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:491)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:465)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:345)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - 
[dev-server-output] INFO com.vaadin.base.devserver.DevServerOutputTracker - [TypeScript] Found 0 errors. Watching for file changes.
[INFO] Running com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT
[pool-3-thread-6] INFO com.vaadin.testbench.ScreenshotOnFailureRule - Error screenshot written to: /home/runner/work/flow/flow/flow-tests/test-live-reload-multimodule/ui/error-screenshots/modifyThemeFile[any_Chrome_](com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT).png
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.221 s <<< FAILURE! -- in com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT
Error:  com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile[any_Chrome_] -- Time elapsed: 1.221 s <<< FAILURE!
org.junit.ComparisonFailure: expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile(FrontendLiveReloadIT.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:491)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:465)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:345)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

[INFO] Running com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT
[pool-3-thread-8] INFO com.vaadin.testbench.ScreenshotOnFailureRule - Error screenshot written to: /home/runner/work/flow/flow/flow-tests/test-live-reload-multimodule/ui/error-screenshots/modifyThemeFile[any_Chrome_](com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT).png
Error:  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.908 s <<< FAILURE! -- in com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT
Error:  com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile[any_Chrome_] -- Time elapsed: 0.908 s <<< FAILURE!
org.junit.ComparisonFailure: expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile(FrontendLiveReloadIT.java:129)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:491)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:465)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:345)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:  com.vaadin.flow.uitest.multimodule.ui.FrontendLiveReloadIT.modifyThemeFile[any_Chrome_]
Error:    Run 1: FrontendLiveReloadIT.modifyThemeFile:129 expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
Error:    Run 2: FrontendLiveReloadIT.modifyThemeFile:129 expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
Error:    Run 3: FrontendLiveReloadIT.modifyThemeFile:129 expected:<rgba([173, 216, 230, 1])> but was:<rgba([0, 0, 0, 0])>
[INFO] 
[INFO] 
Error:  Tests run: 3, Failures: 1, Errors: 0, Skipped: 0

```

**Comment by mcollovati** [comment]
The test always fails locally if `com.vaadin.testbench.Parameters.maxAttempts` is set to 1.
The problem seems to be that a CSS in the watched theme folder is updated twice in a few milliseconds.
The first update is to ensure the file contains the expected initial CSS; the second one to effectively test the reload feature.
However, the first update is performed also if the file contents are the same.
When these two fast file updates happen, Vite triggers only one reload, so the browser page is not reloaded for the second change.

To fix the test, the first update should be done only if the content of the file is not the expected one.
In addition, if the CSS content is not the expected, the test will fail anyway.
