### ISSUE TITLE
RestartMonitorTest is flaky

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#18160]
RestartMonitorTest fails randomly on GitHub actions.
Works fine locally, but the issue could be related to timing expectation when using of common the common ForkJoin poll and parallel tests

```
2023-11-29T12:49:28.5881557Z [ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 3.208 s <<< FAILURE! -- in com.vaadin.base.devserver.RestartMonitorTest
2023-11-29T12:49:28.5884743Z [ERROR] com.vaadin.base.devserver.RestartMonitorTest.waitForServerReady_serverRestartFailure_executionBlockedAndResumed -- Time elapsed: 1.594 s <<< FAILURE!
2023-11-29T12:49:28.5887144Z java.lang.AssertionError: Restart completed, execution should have been completed
2023-11-29T12:49:28.5888368Z 	at org.junit.Assert.fail(Assert.java:89)
2023-11-29T12:49:28.5889266Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2023-11-29T12:49:28.5890652Z 	at com.vaadin.base.devserver.RestartMonitorTest.simulateServerRestart(RestartMonitorTest.java:71)
2023-11-29T12:49:28.5892937Z 	at com.vaadin.base.devserver.RestartMonitorTest.waitForServerReady_serverRestartFailure_executionBlockedAndResumed(RestartMonitorTest.java:55)
2023-11-29T12:49:28.5895060Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-11-29T12:49:28.5896849Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-11-29T12:49:28.5898897Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-11-29T12:49:28.5900583Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-11-29T12:49:28.5902019Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-11-29T12:49:28.5903724Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-11-29T12:49:28.5905424Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-11-29T12:49:28.5907130Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-11-29T12:49:28.5908620Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.5910129Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2023-11-29T12:49:28.5911649Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2023-11-29T12:49:28.5913458Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2023-11-29T12:49:28.5915139Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2023-11-29T12:49:28.5916608Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-11-29T12:49:28.5917889Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-11-29T12:49:28.5919208Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-11-29T12:49:28.5920573Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-11-29T12:49:28.5921868Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-11-29T12:49:28.5923202Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.5924466Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-11-29T12:49:28.5925562Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2023-11-29T12:49:28.5927255Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2023-11-29T12:49:28.5928392Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-11-29T12:49:28.5929647Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-11-29T12:49:28.5930998Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-11-29T12:49:28.5932349Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-11-29T12:49:28.5933637Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-11-29T12:49:28.5934963Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.5936227Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-11-29T12:49:28.5937551Z 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
2023-11-29T12:49:28.5939184Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
2023-11-29T12:49:28.5940991Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
2023-11-29T12:49:28.5943295Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
2023-11-29T12:49:28.5944844Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
2023-11-29T12:49:28.5946294Z 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
2023-11-29T12:49:28.5947747Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2023-11-29T12:49:28.5949104Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2023-11-29T12:49:28.5950387Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2023-11-29T12:49:28.5951640Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2023-11-29T12:49:28.5952386Z 
2023-11-29T12:49:28.5953628Z [ERROR] com.vaadin.base.devserver.RestartMonitorTest.waitForServerReady_serverReady_notBlocking -- Time elapsed: 0.014 s <<< FAILURE!
2023-11-29T12:49:28.5955196Z java.lang.AssertionError: Not restarting, execution should not have been blocked
2023-11-29T12:49:28.5956097Z 	at org.junit.Assert.fail(Assert.java:89)
2023-11-29T12:49:28.5956781Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2023-11-29T12:49:28.5958114Z 	at com.vaadin.base.devserver.RestartMonitorTest.waitForServerReady_serverReady_notBlocking(RestartMonitorTest.java:41)
2023-11-29T12:49:28.5959781Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-11-29T12:49:28.5961291Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-11-29T12:49:28.5963003Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-11-29T12:49:28.5964312Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-11-29T12:49:28.5965428Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-11-29T12:49:28.5967325Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-11-29T12:49:28.5968777Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-11-29T12:49:28.5970194Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-11-29T12:49:28.5971446Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.5972662Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2023-11-29T12:49:28.5973866Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2023-11-29T12:49:28.5975067Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2023-11-29T12:49:28.5976446Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2023-11-29T12:49:28.5977636Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-11-29T12:49:28.5978888Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-11-29T12:49:28.5979885Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-11-29T12:49:28.5980894Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-11-29T12:49:28.5981918Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-11-29T12:49:28.5982920Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.5983897Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-11-29T12:49:28.5985200Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2023-11-29T12:49:28.5986584Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2023-11-29T12:49:28.5987444Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-11-29T12:49:28.5988465Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-11-29T12:49:28.5989610Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-11-29T12:49:28.5990760Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-11-29T12:49:28.5991885Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-11-29T12:49:28.5992992Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.5994135Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-11-29T12:49:28.5995307Z 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
2023-11-29T12:49:28.5996854Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
2023-11-29T12:49:28.5998670Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
2023-11-29T12:49:28.6000298Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
2023-11-29T12:49:28.6001928Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
2023-11-29T12:49:28.6003508Z 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
2023-11-29T12:49:28.6005147Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2023-11-29T12:49:28.6006991Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2023-11-29T12:49:28.6008374Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2023-11-29T12:49:28.6009705Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2023-11-29T12:49:28.6010501Z 
2023-11-29T12:49:28.6011973Z [ERROR] com.vaadin.base.devserver.RestartMonitorTest.waitForServerReady_serverRestarting_executionBlockedAndResumed -- Time elapsed: 1.600 s <<< FAILURE!
2023-11-29T12:49:28.6013951Z java.lang.AssertionError: Restart completed, execution should have been completed
2023-11-29T12:49:28.6014909Z 	at org.junit.Assert.fail(Assert.java:89)
2023-11-29T12:49:28.6015627Z 	at org.junit.Assert.assertTrue(Assert.java:42)
2023-11-29T12:49:28.6017165Z 	at com.vaadin.base.devserver.RestartMonitorTest.simulateServerRestart(RestartMonitorTest.java:71)
2023-11-29T12:49:28.6019282Z 	at com.vaadin.base.devserver.RestartMonitorTest.waitForServerReady_serverRestarting_executionBlockedAndResumed(RestartMonitorTest.java:49)
2023-11-29T12:49:28.6021360Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-11-29T12:49:28.6022907Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-11-29T12:49:28.6024777Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-11-29T12:49:28.6026266Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-11-29T12:49:28.6027535Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-11-29T12:49:28.6029050Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-11-29T12:49:28.6031117Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-11-29T12:49:28.6032621Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2023-11-29T12:49:28.6033880Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.6035173Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2023-11-29T12:49:28.6036488Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2023-11-29T12:49:28.6037787Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2023-11-29T12:49:28.6039276Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2023-11-29T12:49:28.6040549Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-11-29T12:49:28.6041649Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-11-29T12:49:28.6042819Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-11-29T12:49:28.6043992Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-11-29T12:49:28.6045192Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-11-29T12:49:28.6046480Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.6047468Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-11-29T12:49:28.6048359Z 	at org.junit.runners.Suite.runChild(Suite.java:128)
2023-11-29T12:49:28.6049199Z 	at org.junit.runners.Suite.runChild(Suite.java:27)
2023-11-29T12:49:28.6050390Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2023-11-29T12:49:28.6051477Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2023-11-29T12:49:28.6052608Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2023-11-29T12:49:28.6053742Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2023-11-29T12:49:28.6054876Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2023-11-29T12:49:28.6055991Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-11-29T12:49:28.6057070Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-11-29T12:49:28.6058196Z 	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
2023-11-29T12:49:28.6059773Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
2023-11-29T12:49:28.6061587Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
2023-11-29T12:49:28.6063585Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
2023-11-29T12:49:28.6065112Z 	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
2023-11-29T12:49:28.6066745Z 	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
2023-11-29T12:49:28.6068351Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
2023-11-29T12:49:28.6070138Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2023-11-29T12:49:28.6071560Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
2023-11-29T12:49:28.6072870Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
2023-11-29T12:49:28.6073643Z 
```

**Comment by mcollovati** [comment]
Not reproducible locally. Also tested with several re-runs of GH validation, but the error never happened.
Let's keep the ticket open and monitor other PRs as well

**Comment by mcollovati** [comment]
Happened on this build https://github.com/vaadin/flow/actions/runs/7049349132/job/19187742873?pr=18172

**Comment by mcollovati** [comment]
Anther failure https://github.com/vaadin/flow/actions/runs/7057167723/job/19210405045?pr=18169#step:11:9542

It is worth noticing that `RestatMonitorTest` failures seem to always happen togheter with `AbstractDevServerRunnerTest.shouldPassEncodedUrlToDevServer` (#18159)

**Comment by mcollovati** [comment]
After merge of #18238, a PR failed with only `AbstractDevServerRunnerTest.shouldPassEncodedUrlToDevServer`.
Let's continue monitoring PRs for a while to verify if the issue is resolved

**Comment by mcollovati** [comment]
Closing, as it looks like the latest PRs are not affected by this failure anymore
