### ISSUE TITLE
Exception after logout and redirect: Cannot invoke "com.vaadin.flow.component.UI.getPage()" because the return value of "com.vaadin.flow.component.UI.getCurrent()" is null

### ISSUE THREAD

**Issue by isensee-bastian** [vaadin/flow#18284]
### Description of the bug

I followed the official [Vaadin documentation about plain Java authentication](https://vaadin.com/docs/latest/security/advanced-topics/securing-plain-java-app) to setup a simple demo project.

When I deploy the built application to a Tomcat instance with configured test realm users, login and logout work in general but pressing the logout button throws the exception shown below.

Overall, the issue looks very similiar to the closed issue #12807. However, this time it is easily reproducible with the linked example project below.

```
[http-nio-8080-exec-9] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.component.UI.getPage()" because the return value of "com.vaadin.flow.component.UI.getCurrent()" is null
        at com.github.isenseebastian.vaadinplainauthdemo.AuthUtils.logout(AuthUtils.java:39)
        at com.github.isenseebastian.vaadinplainauthdemo.MainLayout.lambda$new$c89cdfec$1(MainLayout.java:17)
        at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239)
        at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:488)
        at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:298)
        at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
        at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
        at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74)
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:459)
        at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$2(ServerRpcHandler.java:440)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:440)
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:323)
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114)
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1522)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Expected behavior

No exception should be thrown as the logout seems to work as expected. The session is invalidated and the user is redirected to the login page.

### Minimal reproducible example

* See my demo app repository [vaadin-plain-auth-demo](https://github.com/isensee-bastian/vaadin-plain-auth-demo).
* See the included [README.md](https://github.com/isensee-bastian/vaadin-plain-auth-demo/blob/master/README.md) file on how to run it.

### Versions

- Vaadin / Flow version: 24.2.5
- Java version: 17.0.8-tem
- OS version: Linux 6.5.0-10010-tuxedo (64-bit)
- Browser version (if applicable): Chrome 120.0.6099.71 (64-bit) and Firefox 120.0.1 (64-bit) 
- Application Server (if applicable): Apache Tomcat 10.1.17
- IDE (if applicable): IntelliJ IDEA Ultimate 2023.3

**Comment by mshabarov** [comment]
@isensee-bastian thanks for the issue! As a first step toward fixing this issue, could you please try reorder session invalidation and setting the location, like below:
```java
    public static void logout() {
        UI.getCurrent().getPage().setLocation(LOGOUT_SUCCESS_URL);
        VaadinSession.getCurrent().getSession().invalidate();
    }
```
?

There might be an issue that UI instance is being cleaned up after session invalidation, thus it throws NPE.

For Spring projects we have an example that sets the location first, see https://vaadin.com/docs/latest/security/enabling-security#log-out-capability.

**Comment by mshabarov** [comment]
For further investigation: we need to check if the `UI.getCurrent` is called from request-handling thread and not from custom thread, where the UI instance might not be available.

**Comment by isensee-bastian** [comment]
> @isensee-bastian thanks for the issue! As a first step toward fixing this issue, could you please try reorder session invalidation and setting the location, like below:
> 
> ```java
>     public static void logout() {
>         UI.getCurrent().getPage().setLocation(LOGOUT_SUCCESS_URL);
>         VaadinSession.getCurrent().getSession().invalidate();
>     }
> ```
> 
> ?
> 
> There might be an issue that UI instance is being cleaned up after session invalidation, thus it throws NPE.
> 
> For Spring projects we have an example that sets the location first, see https://vaadin.com/docs/latest/security/enabling-security#log-out-capability.

@mshabarov Thanks for your suggestion. Switching the order of both statements works fine without throwing an Exception. Maybe it is sufficient to update [the example code in Vaadins plain Java authentication tutorial](https://vaadin.com/docs/latest/security/advanced-topics/securing-plain-java-app#handling-user-log-in-out) (unless you see another problem here).

**Comment by mcollovati** [comment]
I can replicate the issue on Tomcat, but not on Jetty.
The problem is that when the HTTP session is invalidated, `AtmospherePushConnection` gets notified, and it sets the current UI instance thread local to null, thus the `getPage()` call fails.
I can also confirm that swapping the instructions seems the correct configuration; documentation needs to be updated.
