### ISSUE TITLE
Run Application in Docker with read-only filesystem

### ISSUE THREAD

**Issue by alexzelenuyk** [vaadin/flow#18364]
### Describe your motivation

My team developed an application with the jmix framework that uses internally Vaadin Flow UI. We run the application in the docker container. Unfortunetely, we stumbled upon a problem, that we can’t run applications in Docker in a read-only filesystem.

For example:
`docker run --read-only --rm -it -p 8080:8080 ... <ID>`

Results to: 

```

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-27T10:53:39.826Z ERROR 8 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:610) ~[spring-context-6.1.1.jar!/:6.1.1]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at com.example.application.Application.main(Application.java:20) ~[!/:1.0-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[app.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[app.jar:1.0-SNAPSHOT]
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[app.jar:1.0-SNAPSHOT]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to create tempDir. java.io.tmpdir is set to /tmp
        at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:241) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:202) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188) ~[spring-boot-3.2.0.jar!/:3.2.0]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-3.2.0.jar!/:3.2.0]
        ... 15 common frames omitted
Caused by: java.nio.file.FileSystemException: /tmp/tomcat.8080.17109295513146195170: Read-only file system
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[na:na]
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(Unknown Source) ~[na:na]
        at java.base/java.nio.file.Files.createDirectory(Unknown Source) ~[na:na]
        at java.base/java.nio.file.TempFileHelper.create(Unknown Source) ~[na:na]
        at java.base/java.nio.file.TempFileHelper.createTempDirectory(Unknown Source) ~[na:na]
        at java.base/java.nio.file.Files.createTempDirectory(Unknown Source) ~[na:na]
        at org.springframework.boot.web.server.AbstractConfigurableWebServerFactory.createTempDir(AbstractConfigurableWebServerFactory.java:235) ~[spring-boot-3.2.0.jar!/:3.2.0]
        ... 18 common frames omitted

Process completed with exit code 1

```

Running containers with read-only file systems is considered a good practice and a requirement in many companies.

### Describe the solution you'd like

I would like to be able to run Vaadin Flow UI application in the Docker in read-only filesystem

Thank you very much in advance for taking a look.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by mcollovati** [comment]
The reported issue is not directly related to Vaadin. The problem is with the embedded Tomcat configured by Spring Boot.

Here's are related issues on the Spring repository:

https://github.com/spring-projects/spring-boot/issues/8578
https://github.com/spring-projects/spring-boot/issues/21519

Anyway, there may be other components that require writing temporary files.

**Comment by mshabarov** [comment]
On our side we can review whether Vaadin itself can be used with read-only file systems and that Vaadin app, when deployed, doesn't touch the filesystem.
