### ISSUE TITLE
Dynamic file creation and subsequent download doesn't work on jetty 12

### ISSUE THREAD

**Issue by xottabi4** [vaadin/flow#18410]
### Description of the bug

Hi, recently updated my app to latest versions spring boot 3.2.1 + vaadin flow 24.3.2 + jetty 12.0.5 and functionality of dynamic file creation, for user to download, stopped to work.

If I switch app to tomcat, then everything works fine.

Using com.vaadin.flow.server.InputStreamFactory for file creation.

Seems problem is in method writeModificationTimestamp of class com.vaadin.flow.server.StaticFileServer

Below is full stacktrace:

```
2024-01-08 14:49:49,157 WARN  [com.vaadin.flow.server.StaticFileServer] Error closing URLConnection input stream
java.io.FileNotFoundException: JAR entry META-INF/resources/VAADIN/dynamic/resource/0/c6e3e1e7-4c9e-47d2-ad57-7e392cae56e8/118435686.zip not found in some-app-SNAPSHOT.jar!/BOOT-INF/lib/vaadin-menu-bar-flow-24.3.2.jar
        at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.lambda$notFoundConnection$1(JarUrlConnection.java:365)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.throwFileNotFound(JarUrlConnection.java:329)
        at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.getInputStream(JarUrlConnection.java:181)
        at com.vaadin.flow.server.StaticFileServer.writeModificationTimestamp(StaticFileServer.java:506)
        at com.vaadin.flow.server.StaticFileServer.serveStaticResource(StaticFileServer.java:341)
        at com.vaadin.flow.server.VaadinServlet.serveStaticOrWebJarRequest(VaadinServlet.java:430)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:385)
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
        at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)
        at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
        at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1586)
        at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:797)
        at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:428)
        at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
        at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:703)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:761)
        at org.eclipse.jetty.server.Server.handle(Server.java:179)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:594)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:424)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

### Expected behavior

Application should start with no warnings and file should be dynamically created and be downloadable by user, when using jetty as application server.

### Minimal reproducible example

https://github.com/xottabi4/vaadin-jetty-dynamic-file-creation-bug

* build jar using maven with enabled production profile
* run jar using `java - jar`
* open page in browser and you will see bunch of 
`c.vaadin.flow.server.StaticFileServer : Error closing URLConnection input stream`

if you will switch app from jetty to tomcat everything will work fine

### Versions

- Vaadin / Flow version: 24.3.2
- Java version: 17
- Application Server (if applicable): jetty 12.0.5

**Comment by mcollovati** [comment]
At a first quick analysis, it looks like the issue is caused by the changes in resource resolution in Jetty 12.
When Vaadin calls `getServlet().getServletContext().getResource(path)`, Jetty returns a not null URL pointing to a not existing resource (e.g. `jar:file:///some/path/vaadin-jetty-dynamic-file-creation-bug/target/spring-skeleton-1.0-SNAPSHOT.jar!/BOOT-INF/lib/vaadin-menu-bar-flow-24.3.2.jar!/META-INF/resources/index.html`).

For example, `WebAppContext.Context.getResource` in Jetty 11 filters out not existing resources

https://github.com/jetty/jetty.project/blob/581f9ae9f4a6506a281c4df31ad3d653aa6149aa/jetty-ee9/jetty-ee9-webapp/src/main/java/org/eclipse/jetty/ee9/webapp/WebAppContext.java#L1435-L1440


But the filter is not applied anymore in Jetty 12 (`WebAppContext.ServletApiContext.getResource`)

https://github.com/jetty/jetty.project/blob/581f9ae9f4a6506a281c4df31ad3d653aa6149aa/jetty-ee10/jetty-ee10-webapp/src/main/java/org/eclipse/jetty/ee10/webapp/WebAppContext.java#L1370-L1374
