### ISSUE TITLE
IntegerField: Clearing an integer field with a bound binder produces a NPE

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#18516]
### Description

When binding an out-of-the-box IntegerField to a Binder, clearing that field leads to a NullPointerException. 

```
com.vaadin.flow.data.binder.BindingException: An exception has been thrown inside binding logic for the field element [label='Numeric']
	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1597) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.writeFieldValue(Binder.java:1450) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Binder.lambda$doWriteIfValid$4(Binder.java:2367) ~[flow-data-24.3.2.jar:24.3.2]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
	at com.vaadin.flow.data.binder.Binder.doWriteIfValid(Binder.java:2366) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Binder.handleFieldValueChange(Binder.java:1838) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.handleFieldValueChange(Binder.java:1435) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$new$f9b94f89$1(Binder.java:1251) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.lambda$addValueChangeListener$828eca10$1(AbstractFieldSupport.java:98) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:228) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.Component.fireEvent(Component.java:411) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:416) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:209) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setModelValue(AbstractFieldSupport.java:169) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.AbstractField.setModelValue(AbstractField.java:225) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.textfield.AbstractNumberField.setModelValue(AbstractNumberField.java:209) ~[vaadin-text-field-flow-24.3.2.jar:na]
	at com.vaadin.flow.component.textfield.AbstractNumberField.setModelValue(AbstractNumberField.java:40) ~[vaadin-text-field-flow-24.3.2.jar:na]
	at com.vaadin.flow.component.AbstractSinglePropertyField.doSetModelValue(AbstractSinglePropertyField.java:360) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.AbstractSinglePropertyField.handlePropertyChange(AbstractSinglePropertyField.java:352) ~[flow-server-24.3.2.jar:24.3.2]
	at com.vaadin.flow.component.AbstractSinglePropertyField$1.propertyChange(AbstractSinglePropertyField.java:329) ~[flow-server-24.3.2.jar:24.3.2]
   ... (omitted)
Caused by: java.lang.NullPointerException: null
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$writeFieldValue$5169480d$1(Binder.java:1454) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.SimpleResult.handle(SimpleResult.java:77) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.ValidationResultWrap.handle(ValidationResultWrap.java:83) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Result.ifOk(Result.java:145) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$writeFieldValue$3(Binder.java:1453) ~[flow-data-24.3.2.jar:24.3.2]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.execute(Binder.java:1583) ~[flow-data-24.3.2.jar:24.3.2]
	... 86 common frames omitted
```

### Expected outcome

The binder or the integer field should be able to handle clearing the value (either by using the keyboard or the clear value button) without any additional redundant setup of a default value or similar.

### Minimal reproducible example

```java
public SampleView() {
    var intField = new IntegerField("Numeric");
    intField.setClearButtonVisible(true);

    var bean = new Data();
    var binder = new Binder<Data>();

    binder.bind(intField, Data::getNumeric, Data::setNumeric);

    binder.setBean(bean);

    add(intField)
}

private static class Data {
    private int numeric;

    public int getNumeric() {
        return numeric;
    }

    public void setNumeric(int numeric) {
        this.numeric = numeric;
    }
}
```

### Steps to reproduce

1. Add the given sample code to your view
2. The initial value of the intField will be "0". Remove that value using the clear button or your keyboard
3. Check your server logs for an exception.

### Environment

Vaadin version(s): 24.3.2

**Comment by mshabarov** [comment]
As a workaround a converter (or a custom setter) can be used to handle a null value, but this should be handled by Flow automatically, so bug.
