### ISSUE TITLE
Spring native application fails at startup when using default I18n provider

### ISSUE THREAD

**Issue by mcollovati** [vaadin/flow#18545]
### Description of the bug

A Vaadin Spring application using the Flow default i18n provider, compiled to native, produces errors when trying to access pages with the browser.

The error in the logs is the following

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.vaadin.flow.i18n.I18NProvider' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:343) ~[native:6.1.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:334) ~[native:6.1.2]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1250) ~[native:6.1.2]
	at com.vaadin.flow.spring.SpringInstantiator.getI18NProvider(SpringInstantiator.java:86) ~[na:na]
	at com.vaadin.flow.server.VaadinService.createAndRegisterSession(VaadinService.java:942) ~[native:24.3.3]
	at com.vaadin.flow.server.VaadinService.doFindOrCreateVaadinSession(VaadinService.java:901) ~[native:24.3.3]
	at com.vaadin.flow.server.VaadinService.findOrCreateVaadinSession(VaadinService.java:843) ~[native:24.3.3]
	at com.vaadin.flow.server.VaadinService.findVaadinSession(VaadinService.java:682) ~[native:24.3.3]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1567) ~[native:24.3.3]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[native:24.3.3]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[native:na]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[native:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[na:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
```

The problem seems to be that the translation files are not registered by `VaadinHintsRegistrar`

### Expected behavior

The application compiled to native should work with the default Flow I18n provider

### Minimal reproducible example

* Create a Vaadin application (e.g. `npx @vaadin/cli init native`)
* add translations files to `src/main/resource/vaadin-i18n` (e.g. `translations.properties` and `translations_it.properties`, see https://vaadin.com/docs/latest/advanced/i18n-localization)
* build the native executable (needs  graalvm, `mvn -Pnative -Pproduction native:compile`)
* run the native executable, open the browser and navigate to http//localhost:8080
* verify that the Flow view is not shown and an error is printed on the server logs

### Versions

- Vaadin / Flow version: 24.3.3
- Java version: 17 (graalvm for native compilation)
- OS version: Linux

**Comment by mcollovati** [comment]
The workaround is to add a hints registrar class to the application 

```java
package com.example.application;

import org.springframework.aot.hint.RuntimeHints;
import org.springframework.aot.hint.RuntimeHintsRegistrar;

public class Hints implements RuntimeHintsRegistrar {
    @Override
    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
        hints.resources().registerPattern("vaadin-i18n/*");
    }
}
```

To register the class, create the `src/main/resources/META-INF/spring/aot.factories` file with the following content

```
org.springframework.aot.hint.RuntimeHintsRegistrar=com.example.application.Hints
```
