### ISSUE TITLE
NPE in VaadinSession.getState during startup (when spring-security is involved)

### ISSUE THREAD

**Issue by jorgheymans** [vaadin/flow#18796]
### Description of the bug

Discord thread:
https://discord.com/channels/732335336448852018/1209838670203588638

Since we applied spring-security to our application, sometimes we're getting this in the startup logs of our application. Unsure if it's harmless or not, but the fact that it's happening seems to indicate somewhere a condition is being triggered that was not foreseen in the framework.

```
Caused by: com.vaadin.flow.server.ServiceException: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinSession.getState()" because the return value of "com.vaadin.flow.component.UI.getSession()" is null
    at com.vaadin.flow.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1635) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1586) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[flow-server-24.3.5.jar:24.3.5]
    ... 141 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinSession.getState()" because the return value of "com.vaadin.flow.component.UI.getSession()" is null
......
Caused by: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinSession.getState()" because the return value of "com.vaadin.flow.component.UI.getSession()" is null
    at com.vaadin.flow.server.communication.MetadataWriter.createMetadata(MetadataWriter.java:69) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:162) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:215) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.BootstrapHandler.getInitialUidl(BootstrapHandler.java:1503) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler.getInitialJson(JavaScriptBootstrapHandler.java:284) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.communication.JavaScriptBootstrapHandler.synchronizedHandleRequest(JavaScriptBootstrapHandler.java:205) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-24.3.5.jar:24.3.5]
    at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1574) ~[flow-server-24.3.5.jar:24.3.5]
    ... 142 common frames omitted
```

### Expected behavior

No stacktrace should be shown ?

### Minimal reproducible example

It's hard to reproduce as it only happens sometimes. It does not seem to impact the working of the application but then again we're not entirely sure. 

### Versions

- Vaadin / Flow version: 24.3.5
- Java version: 17
- OS version: ubuntu
- Browser version (if applicable): firefox, edge, chrome
- Application Server (if applicable): latest spring-boot 3.2.x 
- IDE (if applicable):

**Comment by jorgheymans** [comment]
This looks similar, and it happened after i modified a class and hotswapped it using HotswapAgent. Could it be that somehow the hotswapping mechanism somehow / sometimes invalidates the VaadinSession ? 

```
2024-08-02T10:10:44.471+02:00  WARN  330151 --- [dev_heymajo] [nio-8080-exec-3] o.a.websocket.DefaultWebSocketProcessor  : Failed invoking AtmosphereFramework.doCometSupport()

java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinSession.access(com.vaadin.flow.server.Command)" because the return value of "com.vaadin.flow.server.VaadinSession.getCurrent()" is null
	at com.vaadin.copilot.RouteHandler.handleMessage(RouteHandler.java:56)
	at com.vaadin.copilot.Copilot.handleMessage(Copilot.java:126)
	at com.vaadin.base.devserver.DebugWindowConnection.onMessage(DebugWindowConnection.java:321)
	at com.vaadin.flow.server.communication.PushHandler.handleDebugWindowMessage(PushHandler.java:650)
	at com.vaadin.flow.server.communication.PushHandler.callWithServiceAndSession(PushHandler.java:227)
	at com.vaadin.flow.server.communication.PushHandler.onMessage(PushHandler.java:626)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:90)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:79)
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:217)
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103)
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:574)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.lambda$dispatch$2(DefaultWebSocketProcessor.java:326)
	at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:323)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:428)
	at org.atmosphere.container.JSR356Endpoint.lambda$onOpen$2(JSR356Endpoint.java:261)
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:390)
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:130)
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:484)
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:284)
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130)
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:85)
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:184)
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:164)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:152)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:60)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:57)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:904)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:840)

2024-08-02T10:10:44.479+02:00  WARN  330151 --- [dev_heymajo] [nio-8080-exec-3] o.a.w.protocol.SimpleHttpProtocol        : java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinSession.access(com.vaadin.flow.server.Command)" because the return value of "com.vaadin.flow.server.VaadinSession.getCurrent()" is null. Unable to deliver the websocket messages to installed component. Status 500 Message Server Error
```

**Comment by mcollovati** [comment]
AFAIK, nothing on the Vaadin side should invalidate the session on hotswap. I wonder if it could be something related to the Spring hotswap plugin.
Is this a situation that can be easily reproduced, or does it happen randomly?

**Comment by jorgheymans** [comment]
>  Is this a situation that can be easily reproduced, or does it happen randomly?

Alas, same as with the other stacktrace, it appears when i don't want it to and does not appear when i'm trying to reproduce it :-( 

In CurrentInstance there's some debug logging about garbage collecing stale instances, i'll enable it maybe it gives us a clue.

**Comment by StefanPenndorf** [comment]
We're seeing this exception as well in production after a migration to Vaadin 23 using MPR. Didn't happen in tests. Has there been any progress/additional findings, @jorgheymans ?

**Comment by jorgheymans** [comment]
For reference, this was the original discord discussion now in Vaadin Forum: https://vaadin.com/forum/t/npe-in-vaadinsession-getstate-during-startup-when-spring-security-is-involved/165590/8

We have not seen this exception for a long time now. It was very likely some mechanism in spring-security that invalidated the session. I think we had either `setCheckForPrincipalChanges` or `setInvalidateSessionOnPrincipalChange` set to true in our filter extending `AbstractPreAuthenticatedProcessingFilter`. Hope this helps.

EDIT also remember now putting an HttpSessionListener in the app to help troubleshooting, YMMV
