### ISSUE TITLE
Upgrade non-Spring starters to Vaadin 24.4

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#18897]
### Describe your motivation

Upgrade and test how to exclude Hilla and Spring in the following non-Spring starters:

- [x] Flow plain servlet starter
- [x] Flow CDI starter
- [x] Flow Quarkus starter

Create a new branch for 24.4.

### Additional context

Vaadin 24.4

**Comment by manolo** [comment]
Pit script is creating branch v24.4 and the appropriate PR in each prerelease, PRs should not be merged until 24.4.0 final is released
This is the list of PRs for these projects:

https://github.com/vaadin/skeleton-starter-flow/pull/821
https://github.com/vaadin/base-starter-flow-quarkus/pull/138
https://github.com/vaadin/skeleton-starter-flow-cdi/pull/635

**Comment by mshabarov** [comment]
I got this exception when start the Quarkus starter:
```
2024-03-08 10:45:33,814 ERROR [io.qua.run.boo.StartupActionImpl] (Quarkus Main Thread) Error running Quarkus: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
        at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
        at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
        at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 3 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: com.vaadin.hilla.FeatureFlagCondition$1
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:516)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:466)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.UndertowBuildStep$build767851419.deploy(Unknown Source)
        ... 17 more

```

**Comment by mcollovati** [comment]
The exception is because even if Hilla artifacts are not on classpath, Hilla classes are listed in the Jandex index
https://github.com/vaadin/platform/pull/5145 should fix the error

**Comment by mshabarov** [comment]
All three starters are tested in dev and prod mode and have branches for 24.4 upgrade.

This [issue](https://github.com/vaadin/skeleton-starter-flow-cdi/issues/636) was observed for CDI starter, but can be handled separately.
