### ISSUE TITLE
PiT 24.4: Regression in alpha19 projects with client routes fail in windows

### ISSUE THREAD

**Issue by manolo** [vaadin/flow#19093]
### Description of the bug

```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/a/platform/platform/tmp/react-tutorial/src/main/frontend/generated/views.json
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:na]
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[na:na]
	at java.base/java.nio.file.Path.of(Path.java:147) ~[na:na]
	at java.base/java.nio.file.Paths.get(Paths.java:69) ~[na:na]
	at com.vaadin.hilla.route.ClientRouteRegistry.registerClientRoutes(ClientRouteRegistry.java:137) ~[hilla-endpoint-24.4.0.alpha18.jar:na]
```

### Expected behavior

no failures

### Minimal reproducible example

Run attached project in a Windows desktop

[react-tutorial.zip](https://github.com/vaadin/flow/files/14856326/react-tutorial.zip)

```
mvn install -Pproduction
java -jar -Dvaadin.productionMode target/*.jar
```

### Versions

- Vaadin / Flow version: 24.4.0.alpha19
- OS version: Windows

**Comment by caalador** [comment]
This seems to be from the hilla ClientRouteRegistry that doesn't handle some paths correctly: ` com.vaadin.hilla.route.ClientRouteRegistry.registerClientRoutes(ClientRouteRegistry.java:137)`

**Comment by tltv** [comment]
https://github.com/vaadin/hilla/pull/2271 has a fix for this issue.

**Comment by ZheSun88** [comment]
can be closed now, as it is fixed in alpha20
