### ISSUE TITLE
TreeData allows for cycles breaking the 'tree' invariant. See Video.

### ISSUE THREAD

**Issue by enver-haase** [vaadin/flow#19337]
### Description of the bug

https://github.com/vaadin/flow/assets/7870436/4a046c0d-4204-46e1-916e-c1e1d8096e2d

It is possible to corrupt a TreeData making it expose a cyclic (non-tree) structure.

### Expected behavior

I expect there to be an exception so that the data is not corrupted.

### Minimal reproducible example

```
package org.vaadin.example;

import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.grid.dnd.GridDropLocation;
import com.vaadin.flow.component.grid.dnd.GridDropMode;
import com.vaadin.flow.component.notification.Notification;
import com.vaadin.flow.component.treegrid.TreeGrid;

import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.data.provider.hierarchy.TreeData;
import com.vaadin.flow.router.Route;

import java.util.ArrayList;
import java.util.List;


@Route
public class MainView extends VerticalLayout {

    private static class DemoTreeData extends TreeData<String> {
        private DemoTreeData() {
            final String[] five = {"A", "B", "C", "D", "E"};

            addRootItems(five);

            for (String s : five) {
                List<String> children = new ArrayList<>();
                for (String ch : five) {
                    String child = s+ch;
                    children.add(child);
                }

                addItems(s, children);
            }
        }
    }
    public MainView() {

        TreeGrid<String> treeGrid = new TreeGrid<>();

        treeGrid.addHierarchyColumn(String::toString).setHeader("Name");

        treeGrid.setTreeData(new DemoTreeData());

        treeGrid.setDropMode(GridDropMode.ON_TOP_OR_BETWEEN);
        treeGrid.setSelectionMode(Grid.SelectionMode.SINGLE);
        treeGrid.setRowsDraggable(true);

        List<String> dragged = new ArrayList<>();
        treeGrid.addDragStartListener( evt -> {
            dragged.clear();
            dragged.addAll(evt.getDraggedItems());
        } );

        treeGrid.addDropListener( evt -> {
            try {
                if (GridDropLocation.ON_TOP == evt.getDropLocation()) {
                    evt.getDropTargetItem().ifPresent(s -> {
                        for (String drag : dragged) {
                            String oldParent = treeGrid.getTreeData().getParent(s);
                            treeGrid.getTreeData().setParent(drag, s);
                            if (oldParent != null) {
                                treeGrid.getDataProvider().refreshItem(oldParent, true);
                                treeGrid.getDataProvider().refreshItem(s, true);
                            }
                            else {
                                treeGrid.getDataProvider().refreshAll();
                            }
                        }
                    });
                }
            }
            catch (Exception e) {
                Notification.show("Exception: "+e);
            }
        } );

        treeGrid.setWidthFull();
        treeGrid.setHeight("800px");
        add(treeGrid);
    }

}

```

### Versions

- Vaadin / Flow version: 24.3.10
- Java version: n/a
- OS version: n/a
- Browser version (if applicable): n/a
- Application Server (if applicable): n/a
- IDE (if applicable): n/a

**Comment by mcollovati** [comment]
In Vaadin 25, TreeGrid works differently, and an exception is thrown but is caught by the VaadinSession error handler, most likely because the real issue happens on a different UIDL request.

```
2026-02-03T15:07:26.030+01:00 ERROR 526358 --- [nio-8080-exec-2] c.v.flow.server.DefaultErrorHandler      : Unexpected error: null

java.lang.StackOverflowError
	at java.base/java.util.HashMap.hash(HashMap.java:338) ~[na:na]
	at java.base/java.util.HashMap.getNode(HashMap.java:576) ~[na:na]
	at java.base/java.util.HashMap.containsKey(HashMap.java:602) ~[na:na]
	at com.vaadin.flow.data.provider.hierarchy.TreeData.contains(TreeData.java:472) ~[flow-data-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.data.provider.hierarchy.TreeData.getChildren(TreeData.java:348) ~[flow-data-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.data.provider.hierarchy.TreeDataProvider.flatten(TreeDataProvider.java:198) ~[flow-data-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.data.provider.hierarchy.TreeDataProvider.flatten(TreeDataProvider.java:208) ~[flow-data-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.data.provider.hierarchy.TreeDataProvider.flatten(TreeDataProvider.java:208) ~[flow-data-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.data.provider.hierarchy.TreeDataProvider.flatten(TreeDataProvider.java:208) ~[flow-data-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
	at com.vaadin.flow.data.provider.hierarchy.TreeDataProvider.flatten(TreeDataProvider.java:208) ~[flow-data-25.1-SNAPSHOT.jar:25.1-SNAPSHOT]
```


I guess the best option for both V24 and V25 should be to immediately throw an exception when manipulating the tree data.
