### ISSUE TITLE
Updating to Spring Boot 3.3.1 raises NPE in VaadinService

### ISSUE THREAD

**Issue by timomeinen** [vaadin/flow#19754]
### Description of the bug

After upgrading from Spring Boot 3.3.0 to 3.3.1 and upwards, I receive the following exception:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Aug 06 21:01:43 CEST 2024
There was an unexpected error (type=Internal Server Error, status=500).
java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.RequestHandler.handleRequest(com.vaadin.flow.server.VaadinSession, com.vaadin.flow.server.VaadinRequest, com.vaadin.flow.server.VaadinResponse)" because "handler" is null
com.vaadin.flow.server.ServiceException: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.RequestHandler.handleRequest(com.vaadin.flow.server.VaadinSession, com.vaadin.flow.server.VaadinRequest, com.vaadin.flow.server.VaadinResponse)" because "handler" is null
	at com.vaadin.flow.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1645)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1596)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658)
...
```

[stack.txt](https://github.com/user-attachments/files/16514673/stack.txt)

### Expected behavior

Should run like before

### Minimal reproducible example

Spring Boot 3.3.1
Vaadin 24.4.7

### Versions

- Vaadin / Flow version: 24.4.7
- Java version: 21.0.3
- OS version: macOS 14.5

**Comment by timomeinen** [comment]
Sorry, misconfiguration on my side.
