### ISSUE TITLE
Production build failing "no DevModeHandlerManager implementation found but but dev server enabled"

### ISSUE THREAD

**Issue by peeterburger** [vaadin/flow#19776]
### Description of the bug

When trying to deploy our application in production, it fails on startup, complaining that no implementation of the DevModeHandlerManager is present.

We are using a two-stage Dockerfile. The building stage uses maven to build the production .jar file. The runtime stage copies the .jar from the build stage and runs it in the JVM. Building the image using `docker build` finishes without any errors.

Once the image is built, we run it using the `docker run` command. On startup, the application fails due to "no DevModeHandlerManager implementation found but but dev server enabled". For the entire stacktrace, see below.

### Expected behavior

The application should start properly. No DevModeHandlerManager component should be required, since we built for production.

### Minimal reproducible example

I cannot publish the entire repository, since it is proprietary code. However, I will try to submit all of the build-related content:

pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.2</version>
		<relativePath />
	</parent>

       ...

	<properties>
		<java.version>22</java.version>
		<vaadin.version>24.4.8</vaadin.version>
	</properties>

       ...

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-bom</artifactId>
				<version>${vaadin.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
          ...
	</dependencies>

	<build>
		<defaultGoal>spring-boot:run</defaultGoal>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<jvmArguments>
						-Xdebug
						-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5633</jvmArguments>
					<wait>500</wait>
					<maxAttempts>240</maxAttempts>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.vaadin</groupId>
				<artifactId>vaadin-maven-plugin</artifactId>
				<version>${vaadin.version}</version>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>production</id>
			<dependencies>
				<dependency>
					<groupId>com.vaadin</groupId>
					<artifactId>vaadin-core</artifactId>
					<exclusions>
						<exclusion>
							<groupId>com.vaadin</groupId>
							<artifactId>vaadin-dev</artifactId>
						</exclusion>
					</exclusions>
				</dependency>
			</dependencies>
			<build>
				<plugins>
					<plugin>
						<groupId>com.vaadin</groupId>
						<artifactId>vaadin-maven-plugin</artifactId>
						<version>${vaadin.version}</version>
						<executions>
							<execution>
								<goals>
									<goal>build-frontend</goal>
								</goals>
								<phase>compile</phase>
							</execution>
						</executions>
						<configuration>
							<frontendHotdeploy>false</frontendHotdeploy>
							<forceProductionBuild>true</forceProductionBuild>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
```

Dockerfile:
```
FROM maven:3.9.8-eclipse-temurin-22 as build

WORKDIR /build

# Files that are not relevant are excluded by the .dockerignore file
COPY . .

RUN mvn dependency:go-offline

RUN mvn package -Pproduction -DskipTests -Dvaadin.offlineKey=...

FROM eclipse-temurin:22 as runtime

WORKDIR /app

COPY --from=build /build/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
```

.dockerignore:
```
# Ignore everything by default
*

# Allow the source code
!src/
!pom.xml

# Allow the Vaadin frontend
!frontend/
```

Building the image:
```
docker build -t application .
```

```
[+] Building 1155.4s (14/14) FINISHED                                                                                      docker:default
 => [internal] load build definition from Dockerfile                                                                                 0.1s
 => => transferring dockerfile: 2.60kB                                                                                               0.0s
 => [internal] load metadata for docker.io/library/eclipse-temurin:22                                                                0.7s
 => [internal] load metadata for docker.io/library/maven:3.9.8-eclipse-temurin-22                                                    0.8s
 => [internal] load .dockerignore                                                                                                    0.1s
 => => transferring context: 212B                                                                                                    0.0s
 => [build 1/5] FROM docker.io/library/maven:3.9.8-eclipse-temurin-22@sha256:9404325339d120296b53e7cb80bacc578d760bb94d42da16efd01e  0.0s
 => [runtime 1/3] FROM docker.io/library/eclipse-temurin:22@sha256:765569cd83ecc47b87cc1b5c4d986f367edac0fad2979bd9e2dde99c211d3727  0.0s
 => [internal] load build context                                                                                                    0.2s
 => => transferring context: 198.14kB                                                                                                0.1s
 => CACHED [build 2/5] WORKDIR /build                                                                                                0.0s
 => [build 3/5] COPY . .                                                                                                             0.9s
 => [build 4/5] RUN mvn dependency:go-offline                                                                                      657.3s
 => [build 5/5] RUN mvn package -Pproduction -DskipTests -Dvaadin.offlineKey=...  492.0s 
 => CACHED [runtime 2/3] WORKDIR /app                                                                                                0.0s 
 => [runtime 3/3] COPY --from=build /build/target/*.jar app.jar                                                                      0.2s 
 => exporting to image                                                                                                               0.8s 
 => => exporting layers                                                                                                              0.8s
 => => writing image sha256:48aa6d359e90f3695aae4c67602070468125fd589b5ccb3ab405bab056b34fd8                                         0.0s
 => => naming to docker.io/library/application                                                                                      0.0s
```
Running the container:
```
docker run application
```

```
2024-08-12T11:45:03.433Z  INFO 1 --- [           main] com.enevo.gridos.GridOSApplication       : Starting GridOSApplication v0.1.202408 using Java 22.0.2 with PID 1 (/app/app.jar started by root in /app)
2024-08-12T11:45:03.624Z  INFO 1 --- [           main] com.enevo.gridos.GridOSApplication       : No active profile set, falling back to 1 default profile: "default"
2024-08-12T11:45:07.885Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2024-08-12T11:45:07.893Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-08-12T11:45:08.433Z  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 506 ms. Found 10 JPA repository interfaces.
2024-08-12T11:45:10.577Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-08-12T11:45:10.635Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-08-12T11:45:10.637Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.26]
2024-08-12T11:45:10.753Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-08-12T11:45:10.754Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 6778 ms
2024-08-12T11:45:10.780Z  WARN 1 --- [           main] c.v.f.s.VaadinServletContextInitializer  : vaadin.whitelisted-packages is deprecated and may not be supported in the future. Use vaadin.allowed-packages instead.
2024-08-12T11:45:11.927Z ERROR 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener]

java.lang.RuntimeException: Unable to initialize com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener
        at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:201)
        at com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener.lambda$contextInitialized$0(VaadinServletContextInitializer.java:225)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
        at com.vaadin.flow.spring.VaadinServletContextInitializer$CompositeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:225)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3995)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4424)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:874)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
        at org.apache.catalina.startup.Tomcat.start(Tomcat.java:437)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:128)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:107)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:516)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:222)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
        at com.enevo.gridos.GridOSApplication.main(GridOSApplication.java:37)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: java.lang.RuntimeException: no DevModeHandlerManager implementation found but but dev server enabled. Either disable by setting vaadin.frontend.hotdeploy=false (and run the build-frontend maven goal) or include the vaadin-dev-server dependency
        at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.failFastContextInitialized(VaadinServletContextInitializer.java:492)
        at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:197)
        ... 46 common frames omitted

2024-08-12T11:45:11.935Z ERROR 1 --- [           main] o.apache.catalina.core.StandardContext   : One or more listeners failed to start. Full details will be found in the appropriate container log file
2024-08-12T11:45:11.936Z ERROR 1 --- [           main] o.apache.catalina.core.StandardContext   : Context [] startup failed due to previous errors
2024-08-12T11:45:12.214Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-08-12T11:45:12.235Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server
2024-08-12T11:45:12.267Z  INFO 1 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-08-12T11:45:12.383Z ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
        at com.enevo.gridos.GridOSApplication.main(GridOSApplication.java:37)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:147)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:107)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:516)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:222)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:188)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
        ... 13 common frames omitted
Caused by: java.lang.IllegalStateException: StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[] failed to start
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.rethrowDeferredStartupExceptions(TomcatWebServer.java:209)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:131)
        ... 18 common frames omitted
```

### Versions

- Vaadin / Flow version: 24.4.8
- Java version: 22
- OS version: Fedora 39 (KDE Plasma), Kernel 6.8.11-200.fc39.x86_64
- Browser version (if applicable): /
- Application Server (if applicable): /
- IDE (if applicable): /

**Comment by louis-santucci** [comment]
Hi there,

I have the same issue.

When I open my jar produced during my maven build, on META-INF/VAADIN/config/flow-build-info.json
I have the following:

{
  "productionMode": false,
  "eagerServerLoad": false,
  "npmFolder": "...",
  "node.version": "v20.18.0",
  "frontend.hotdeploy": true,
  "node.download.root": "https://nodejs.org/dist/",
  "frontendFolder": "...",
  "connect.javaSourceFolder": "...",
  "javaResourceFolder": "...",
  "connect.applicationProperties": "...",
  "connect.openApiFile": "...",
  "project.frontend.generated": "...",
  "pnpm.enable": false,
  "bun.enable": false,
  "require.home.node": false,
  "build.folder": "target",
  "react.enable": true
}

Did you find any way to fix this issue?

**Comment by mcollovati** [comment]
@louis-santucci Can you please post the logs of the maven build, especially the outputs of the execution of Vaadin prepare-frontend and build-frontend goals?

**Comment by mcollovati** [comment]
Closing since it was not possible to reproduce the issue and no additional information has been provided.
