### ISSUE TITLE
Hotswapper throws Null pointer exception on Login page 

### ISSUE THREAD

**Issue by abdullahtellioglu** [vaadin/flow#20244]
### Description of the bug

When I start the application and open the /login page which comes from vaadin security for the first time, the following exceptions are thrown:
![Screenshot 2024-10-14 at 15 42 07](https://github.com/user-attachments/assets/98d4aaf5-60db-4ae3-9c57-79af7707b3d3)

https://github.com/user-attachments/assets/28e27d56-b4bf-46fa-bbd5-ae5ce18d76c7

```java
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getInterfaces()" because "clazz" is null
	at com.vaadin.flow.internal.AnnotationReader.getAnnotationFor(AnnotationReader.java:150)
	at com.vaadin.flow.router.internal.RouteUtil.collectRouteParentLayouts(RouteUtil.java:248)
	at com.vaadin.flow.hotswap.Hotswapper.computeRefreshStrategy(Hotswapper.java:369)
	at com.vaadin.flow.hotswap.Hotswapper.lambda$computeRefreshStrategies$3(Hotswapper.java:302)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.vaadin.flow.hotswap.Hotswapper.forEachActiveUI(Hotswapper.java:315)
	at com.vaadin.flow.hotswap.Hotswapper.computeRefreshStrategies(Hotswapper.java:301)
	at com.vaadin.flow.hotswap.Hotswapper.onHotswapInternal(Hotswapper.java:262)
	at com.vaadin.flow.hotswap.Hotswapper.onHotswap(Hotswapper.java:145)
```

### Expected behavior

No exception should be thrown. 

### Minimal reproducible example

I think it happens with any example project where Vaadin security is enabled. Also, you can use internal 
https://github.com/vaadin/copilot-internal/tree/main/copilot-client-test-flow project. I use copilot plugin for IntelliJ and run the application via Debug with Hotswap Agent option 

### Versions

Hilla: 24.5.0.rc1
Flow: 24.5.0.rc1
Vaadin: 24.5.0.beta5
Copilot: 24.5-SNAPSHOT
Frontend Hotswap: Enabled, using Vite
OS: aarch64 Mac OS X 14.6.1
Java: JetBrains s.r.o. 17.0.10
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Java Hotswap: Java Hotswap is enabled
IDE Plugin: 1.3.3 IntelliJ

**Comment by mcollovati** [comment]
This should have been fixed by #20214 and released in Flow 24.5.0.rc2.
@abdullahtellioglu do you mind trying with that Flow version?
