### ISSUE TITLE
Hotswap does not work with Push enabled if a client-side view is present

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#20258]
### Description of the bug

In an application with `@Push` enabled and both Flow and Hilla views, hotswapping does not work and this exception is logged
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinRequest.getUserPrincipal()" because "vaadinRequest" is null
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[na:na]
        at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:62) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2158) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:755) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:2120) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:2087) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:1059) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.component.UI.access(UI.java:570) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.component.UI.access(UI.java:553) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.hotswap.Hotswapper.lambda$triggerClientUpdate$9(Hotswapper.java:451) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[na:na]
        at com.vaadin.flow.hotswap.Hotswapper.triggerClientUpdate(Hotswapper.java:451) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.hotswap.Hotswapper.onHotswapInternal(Hotswapper.java:266) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.hotswap.Hotswapper.onHotswap(Hotswapper.java:145) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
        at org.hotswap.agent.command.ReflectionCommand.doExecuteReflectionCommand(ReflectionCommand.java:207) ~[hotswap-agent.jar:2.0.1]
        at org.hotswap.agent.command.ReflectionCommand.executeCommand(ReflectionCommand.java:168) ~[hotswap-agent.jar:2.0.1]
        at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43) ~[hotswap-agent.jar:2.0.1]
Caused by: java.lang.NullPointerException: Cannot invoke "com.vaadin.flow.server.VaadinRequest.getUserPrincipal()" because "vaadinRequest" is null
        at com.vaadin.flow.internal.menu.MenuRegistry.filterClientViews(MenuRegistry.java:405) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.internal.menu.MenuRegistry.collectClientMenuItems(MenuRegistry.java:335) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.internal.menu.MenuRegistry.collectClientMenuItems(MenuRegistry.java:269) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.internal.menu.MenuRegistry.getClientRoutes(MenuRegistry.java:521) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.internal.menu.MenuRegistry.hasClientRoute(MenuRegistry.java:504) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:191) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:106) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:305) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.router.Router.navigate(Router.java:237) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.component.internal.UIInternals.refreshCurrentRoute(UIInternals.java:1107) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.component.UI.refreshCurrentRoute(UI.java:1259) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.hotswap.Hotswapper.lambda$triggerClientUpdate$295d7b78$1(Hotswapper.java:451) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.component.UI.accessSynchronously(UI.java:498) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at com.vaadin.flow.component.UI$2.execute(UI.java:573) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:2155) ~[flow-server-24.5.0.rc2.jar:24.5.0.rc2]
        ... 16 common frames omitted
```

### Expected behavior

Excepted that hotswapping works

### Minimal reproducible example

1. Add a Flow view and a Hilla view at start.vaadin.com
2. Download with `24.5 (pre)` selected
3. Add `@Push` to the `Application` class
4. Launch using Hotswap agent
5. Make a change to the Flow view

### Versions

- Vaadin / Flow version: 24.5.0.rc2

**Comment by mcollovati** [comment]
The issue seems to be in `MenuRegistry.collectClientMenuItems()` that assumes the `VaadinRequest` thread local is set.

**Comment by mshabarov** [comment]
Fixed in https://github.com/vaadin/flow/pull/20269.
