### ISSUE TITLE
Composite::initComponent() called before beforeEnter() method

### ISSUE THREAD

**Issue by engor** [vaadin/flow#20453]
### Description

I want to use parameter from `beforeEnter()` inside `initContent()` of my "composite" component, but I can't because `initContent()` called before `beforeEnter()`.

The reason is Vaadin uses `getElement().getContent()` under the hood and therefore it calls `initContent()`:
```
java.lang.RuntimeException: breakpoint
	at com.citysense.elk.module.address_phone_book.profile.content.TestView.initContent(TestView.java:18)
	at com.citysense.elk.module.address_phone_book.profile.content.TestView.initContent(TestView.java:11)
	at com.vaadin.flow.component.Composite.getContent(Composite.java:129)
	at com.vaadin.flow.component.Composite.getElement(Composite.java:173)
	at com.vaadin.flow.router.EventUtil.collectBeforeEnterObserversFromChainElement(EventUtil.java:154)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEventAndPopulateChain(AbstractNavigationStateRenderer.java:512)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:482)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:226)
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78)
	at com.vaadin.flow.component.UI.handleNavigation(UI.java:2005)
	at com.vaadin.flow.component.UI.renderViewForRoute(UI.java:1968)
	at com.vaadin.flow.component.UI.browserNavigate(UI.java:1833)
        .......
```

### Expected outcome

I would expect `beforeEnter()` is called before `initContent()`.

### Minimal reproducible example

Example "page":
```
@Route("test")
public class TestView extends Composite<Div> implements BeforeEnterObserver {
    private String param;

    @Override
    protected Div initContent() {
        System.out.println("init content, param: " + param);
        return new Div("test");
    }

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        System.out.println("before enter");
        param = "my-param";
    }

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        System.out.println("on attach");
    }
}
```

### Steps to reproduce

1. Add page listed above
2. Goto /test in browser
3. And you will see output:
  - init content, param: null
  - before enter
  - on attach

Expected output for me:
- before enter
- init content, param: my-param
- on attach

### Environment

Vaadin version(s): 24.4.8
OS: MacOS 15.1

**Comment by Legioth** [comment]
This is as designed. You should think of `initContent` as an extension of the component's constructor. The constructor is run before `beforeEnter` and the same also goes for `initContent`.

Furthermore, there are cases where `beforeEnter` will be run for an "old" component instance which means that `beforeEnter` should anyways be implemented in a way that works regardless of the component's lifecycle.
