### ISSUE TITLE
Production Build using Vaadin 24.5.6 starts in Development Mode when started from IDE

### ISSUE THREAD

**Issue by FelixLanghof** [vaadin/flow#20581]
### Description of the bug

When building a Vaadin application using the production profile and starting it from an IDE, it will start up in Development Mode.
Tested with Eclipse and IntelliJ.

### Expected behavior

The application starts in production mode. As is the case with Vaadin 24.4.18.

### Minimal reproducible example

- Download the Hello World Project from https://start.vaadin.com/app (Flow/Java/Maven/Spring Boot)
- (Check that Vaadin Version is 24.5.6)
- Run `mvn install -Pproduction` (in IDE or otherwise)
- Start application via IDE
  - In Eclipse using Spring Boot Dashboard or basic Java Application Run Configuration
  - In IntelliJ using basic Run Configuration 

Using Vaadin 24.4.18, when following the same steps, the application starts in Production Mode
Using plain `mvn install -Pproduction` and `java -jar` or `mvn spring-boot:run -Pproduction` works fine. 

### Versions

- Vaadin / Flow version: 24,5,6
- Java version: 17/21
- OS version: Win10
- IDE (if applicable): 
  - Eclipse 2024-09
  - IntelliJ 2024.3

**Comment by Artur-** [comment]
Any particular reason why you would expect it to start in production mode in your IDE because you made a build outside the IDE? 

The production artifact is the jar file in the `target` folder and that one runs in production mode. This was a bug that was fixed in #20294

**Comment by knoobie** [comment]
> It would however be nice to be able to start the application in production mode with all the same configurations as in development mode

You can do that by going to your target folder and execute java -jar "your arguments" app.jar

**Comment by mshabarov** [comment]
The real question seems to be "How I can run my Vaadin app in production with the IDE run configuration", so that you don't actually need the `mvn install -Pproduction` step to run.
IntelliJ IDEA provides an option to run the spring boot maven plugin with the IDEA run configuration where you can add your system properties.
Have you tried that? What prevents you to run this way?

**Comment by guygoldwasser** [comment]
> The real question seems to be "How I can run my Vaadin app in production with the IDE run configuration", so that you don't actually need the `mvn install -Pproduction` step to run. IntelliJ IDEA provides an option to run the spring boot maven plugin with the IDEA run configuration where you can add your system properties. Have you tried that? What prevents you to run this way?

this is exactly the problem. despite it build in production mode, it not run in production mode when run after build via IDE.
this is extremely important as some bugs happened only with production mode, and still developer need minimal way of local recreation via IDE.

**Comment by guygoldwasser** [comment]
my wired workarounds:
1. via console window.Vaadin.developmentMode=false (assuming server side will obay the production build that anyhow exclude dev featuers)
2. base on https://stackoverflow.com/questions/79009991/vaadin-24-4-production-mode-build-not-working-flow-build-info-json
i just added vaadin.productionMode=true  which in the dark as not exist at: https://vaadin.com/docs/latest/flow/configuration/properties

**Comment by MarioTrappein** [comment]
This issue even causes on our windows dev machines that the classpath parsing threw exceptions:
`Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 12: jar:file:/C:\Users\xyz\.m2\repository\com\vaadin\vaadin-ordered-layout-testbench\24.6.5\vaadin-ordered-layout-testbench-24.6.5.jar!/
`
which was initialized by the DevModeServletContextListener
`java.lang.RuntimeException: Unable to initialize com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener`

Adding `vaadin.productionMode=true `  restored the default behavior, but shouldn't be necessary in my opinion.

**Comment by kmartin88** [comment]
This also breaks running tests via the IDE. 

Using Vaadin 24.6.12 and starting a test in IntelliJ (click on the green arrow) the result is this:

```
Vaadin is running in DEVELOPMENT mode - do not use for production deployments.

java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because the return value of "com.vaadin.flow.function.DeploymentConfiguration.getProjectFolder()" is null

	at com.vaadin.hilla.startup.EndpointRegistryInitializer.getOpenApiAsResource(EndpointRegistryInitializer.java:41)
	at com.vaadin.hilla.startup.EndpointRegistryInitializer.serviceInit(EndpointRegistryInitializer.java:33)
	at com.vaadin.flow.server.VaadinService.lambda$init$0(VaadinService.java:271)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	...
```

So now we need to always run a test via maven to debug it which takes way more time and is more complicated than just clicking on the debug icon.

Is there any way to force it to run in production mode or at least to not break like it does in my stacktrace?

**Comment by jorgheymans** [comment]
Could be related to https://github.com/vaadin/flow/issues/21021 ? If the jvm that Intellij uses does not terminate, this token file never gets deleted and Vaadin assumes dev mode. In the past, i've prefixed my run configuration with a script that would go and search for this file and delete it.

**Comment by kmartin88** [comment]
Somewhat, yeah. The JVM in fact _does_ terminate, the token file gets deleted and thus there is no file to tell Vaadin to start in production mode.
With Vaadin 24.4.22, the file does not get deleted even if the JVM process terminates, so the token file stays and I can run tests with my IDE as  Vaadin is running in production mode. 

Any "fix" that deletes the file after running a build is, in my opinion, a bad idea. The argument from [here](https://github.com/vaadin/flow/pull/20346/#pullrequestreview-2398939300) that it isn't documented so it's no problem if you can't run it correctly via your IDE anymore is... well I don't agree. I expect to be able to run applications and tests with my IDE if I'm not doing something really unusual (which using Vaadin shouldn't be) and I guess I'm not the only developer with this expectation.
