### ISSUE TITLE
Navigating to URL with a percent (%) in a query parameter value fails

### ISSUE THREAD

**Issue by bwajtr** [vaadin/flow#20654]
### Description of the bug

I noticed a failure of my Vaadin webapp (Flow version) when navigating to the URL with a query parameter that contains percent, like: `http://localhost:8080/article/1038992?tag=10%`. Instead of some sensible result, I'm getting "Connection lost" message from Vaadin.

I managed to reproduce something similar with Vaadin Starter app with just the HelloWorld page (version 24.5.5), where navigating to `http://localhost:8080/?param=test%` results in errors in the javascript console, and no page is shown:

```
indexhtml-qb7H9qKD.js:71542 Uncaught (in promise) TypeError: Cannot destructure property 'appId' of 'appConfig' as it is undefined.
    at Flow.flowInit (indexhtml-qb7H9qKD.js:71542:15)
    at async Object.action (indexhtml-qb7H9qKD.js:71457:11)
```

<img width="1569" alt="image" src="https://github.com/user-attachments/assets/e2a856b6-f7c5-46be-a1b4-89be50b1e971">

### Expected behavior

I'd expect no errors as the percent sign should be properly escaped and it should be possible to query for values containing percentages (right?)

### Minimal reproducible example

1. Download Vaadin starter for 24.5+
2. Start it up
3. Navigate to `localhost:8080?param=test%`
4. See the Javascript console

### Versions

- Vaadin / Flow version: 24.5.5
- Java version: 21
- OS version: macOS 15.1.1
- Browser version (if applicable): Chrome
- Application Server (if applicable):
- IDE (if applicable): Intellij Idea

**Comment by caalador** [comment]
On the server I can see the exception:
```
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
        at java.base/java.net.URLDecoder.decode(URLDecoder.java:230) ~[na:na]
        at java.base/java.net.URLDecoder.decode(URLDecoder.java:147) ~[na:na]
        at com.vaadin.flow.router.QueryParameters.decode(QueryParameters.java:337) ~[flow-server-24.6-SNAPSHOT.jar:24.6-SNAPSHOT]
        at com.vaadin.flow.router.QueryParameters.makeQueryParamList(QueryParameters.java:158) ~[flow-server-24.6-SNAPSHOT.jar:24.6-SNAPSHOT]
```
Having it as encoded e.g. `%25` instead of `%` the request passes fine.

**Comment by bwajtr** [comment]
I'll only add that the initial request to the page does not fail. Only the subsequent request made by Vaadin fails - and it appears that the query string is properly escaped there... so from my point of view something goes sideways in Vaadin Flow server (the Request URL produced by Vaadin for that request is `
http://localhost:8080/?v-r=init&location=article%2F1038992&query=tag%3D10%25`):

<img width="1371" alt="image" src="https://github.com/user-attachments/assets/12f6be32-66dc-4da2-94b1-e2d1fe919efb">

**Comment by AndreasSamjeske** [comment]
Let's be clear: A URL having an "naked" % is an invalid URL.
So, the questions at hand are:
1. Why is the initial request successful?
2. Shall Vaadin do better or is "Connection lost" the desired behavior?

I won't get  into the discussion of the latter. But here is my take to point 1:
In the initial request, the browser does some magic. Having an % without trailing digits is an error, so the browser escapes the % as %25. Thus Vaadin gets a request with a valid URL and happily answers. After Vaadin is active in the browser, the subsequent request take a different route. Vaadin starts those and the escaping the browser did for the initial request won't take place.

Final note: Don't rely on those developer tools in the browser to much in these cases. They might show escaping that didn't happen and vice versa. Take a look at Servers access.log to see what is actually going on.
