### ISSUE TITLE
Flow Reload Time Test is broken

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#20739]
All flow reload tests are failing, see e.g. https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Flow247main_mainNightly_FlowReloadTimeTest

```
Caused by: org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.id: result (tried for 20 second(s) with 500 milliseconds interval)

at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:84)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:228)
	at com.vaadin.testbench.TestBenchTestCase.waitUntil(TestBenchTestCase.java:201)
	at org.vaadin.example.SpringDevToolsReloadViewIT.runTestReturnResult(SpringDevToolsReloadViewIT.java:50)
	at com.vaadin.flow.spring.test.SpringDevToolsReloadUtils.lambda$runAndCalculateAverageResult$0(SpringDevToolsReloadUtils.java:45)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:617)
	at com.vaadin.flow.spring.test.SpringDevToolsReloadUtils.runAndCalculateAverageResult(SpringDevToolsReloadUtils.java:44)
	at org.vaadin.example.SpringDevToolsReloadViewIT.testSpringBootReloadTime_withLargerApp(SpringDevToolsReloadViewIT.java:36)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.vaadin.testbench.parallel.ParallelRunner$TBMethod.invokeExplosively(ParallelRunner.java:491)
	at com.vaadin.testbench.parallel.ParallelRunner$1.evaluate(ParallelRunner.java:465)
	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:73)
```

Some observations:
1. The test is failing when it is waiting for the `result` span element that outputs the string with a reload time value. Failure screenshots sometimes show a loaded page without this element (but with a button), sometimes the blinking loading indicator, sometimes even the result span presented on the page.
2. I couldn't reproduce this timeout not by running this test from Flow root directory same as in CI, nor by starting the app and manually triggering the reload.
3. Browser console doesn't have anything suspicious after I've added `checkLogsForErrors();`.
4. Increasing the timeout from 20 sec to 40 sec doesn't help.
5. I noticed that the rate of failing tests because of the threshold overrun has increased significantly, so in average the reload time has been increased.

That could be an infra problem, i.e. agents performance degraded so that the reload and reuqest handling takes longer time, but I'm not 100% sure.

To check:
In some builds the failure has started after LC and Open upgrade:
```
chore: License Checker 1.13.2 (#20535) (#20538)

* chore: License Checker 1.13.2

* chore: upgrade open to 8.5.0.4
```

**Comment by mcollovati** [comment]
Here are the results of the investigation:

* Some steps in the CI job had the Testbench `maxAttempts=2` setting that was hiding the real cause of the failure. Now all steps have `com.vaadin.testbench.Parameters.maxAttempts=1`
* In one module, there are two test methods that trigger server reload. However, Testbench was running them in parallel, causing potentially wrong results. Now all steps have `com.vaadin.testbench.Parameters.testsInParallel=1` to run test methods sequentially.
* In the step that tests an application with hundreds of CSS or Javascript, after a couple of restarts, the page in the browser was blank only showing the loading indicator. This happened because Chrome was failing to load resources (ERR_INSUFFICIENT_RESOURCES error).


For the last problem, I was able to reproduce it locally, starting a `selenium/standalone-chrome docker` container and running the test against it. To make the test complete, I had to increase the `--shm-size` docker parameter from 2GB to 3GB. Since this worked, I updated the tests to start chrome with `--disable-dev-shm-usage` flag; with this configuration, the test also passed with 2GB shm.

Also, for the build step with 1000 routes, I had to raise the restart threshold to 3500 ms. I tried to run tests against older Flow version, and it looks like the culprit of the increased startup time is the Spring Boot upgrade to 3.4. After a couple of executions, the average startup time seems now 3.2 secs.

Related PR: #20761
