### ISSUE TITLE
The log shows several `java.net.SocketTimeoutException: Timeout on Read` messages  when running a Flow app in every 5 minutes

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/flow#2176]
I could reproduce the error this way: when you have an application with `@Push` enabled, and open initial page (creating a first session), in every 5 minutes you get this error in the log:

```
org.atmosphere.container.Jetty9WebSocketHandler onWebSocketError
SEVERE: {}
java.net.SocketTimeoutException: Timeout on Read
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onReadTimeout(AbstractWebSocketConnection.java:588)
	at org.eclipse.jetty.io.AbstractConnection.onFillInterestedFailed(AbstractConnection.java:168)
	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillInterestedFailed(AbstractWebSocketConnection.java:534)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.failed(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.onFail(FillInterest.java:125)
	at org.eclipse.jetty.io.AbstractEndPoint.onIdleExpired(AbstractEndPoint.java:167)
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:166)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The error doesn't look to create any issue in the application itself, but pollutes the log and can potentially hide some actual error after several hours of execution.

**Comment by pleku** [comment]
This has been fixed by using a newer version of Atmosphere framework (currently 2.4.30).
