### ISSUE TITLE
Flow fails to reconstruct Kotlin bean from Polymer template server-side

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#2736]
Just git clone https://github.com/mvysny/karibu-dsl, run the `example-v10` project and try to edit any Review. The server will report internal error.

The stacktrace:
```
20-Oct-2017 12:00:16.955 SEVERE [http-nio-8080-exec-2] com.vaadin.server.DefaultErrorHandler.error 
 java.lang.IllegalStateException: Invisible parameter type of kotlin.jvm.internal.DefaultConstructorMarker arg7 for public com.vaadin.starter.beveragebuddy.backend.Review$(java.lang.Long,int,java.lang.String,java.time.LocalDate,com.vaadin.starter.beveragebuddy.backend.Category,int,int,kotlin.jvm.internal.DefaultConstructorMarker)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:925)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:465)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:162)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:155)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:2639)
	at com.vaadin.flow.model.TemplateModelProxyHandler.createProxyConstructor(TemplateModelProxyHandler.java:246)
	at com.vaadin.flow.model.TemplateModelProxyHandler.createClassConstructor(TemplateModelProxyHandler.java:222)
	at com.vaadin.flow.model.TemplateModelProxyHandler.createProxyConstructor(TemplateModelProxyHandler.java:204)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.vaadin.flow.util.ReflectionCache.get(ReflectionCache.java:69)
	at com.vaadin.flow.model.TemplateModelProxyHandler.createModelProxy(TemplateModelProxyHandler.java:193)
	at com.vaadin.flow.model.BeanModelType.modelToApplication(BeanModelType.java:314)
	at com.vaadin.server.communication.rpc.PublishedServerEventHandlerRpcHandler.getTemplateItem(PublishedServerEventHandlerRpcHandler.java:257)
	at com.vaadin.server.communication.rpc.PublishedServerEventHandlerRpcHandler.decodeArg(PublishedServerEventHandlerRpcHandler.java:224)
	at com.vaadin.server.communication.rpc.PublishedServerEventHandlerRpcHandler.decodeArgs(PublishedServerEventHandlerRpcHandler.java:174)
	at com.vaadin.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:128)
	at com.vaadin.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:112)
	at com.vaadin.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:92)
	at com.vaadin.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:50)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:397)
	at com.vaadin.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:387)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:387)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:304)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:86)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1480)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:298)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

The bug is probably in the ByteBuddy library and has already been reported: https://github.com/raphw/byte-buddy/issues/350

**Comment by pleku** [comment]
Based on  raphw/byte-buddy#350 it is a Kotlin issue.
