### ISSUE TITLE
Vaadin 10 Failing

### ISSUE THREAD

**Issue by iardena** [vaadin/flow#2959]
Hi, I am trying to run Vaadin 10 Demo and it does not work.
Maybe you could help me. It is showing the following error in Intellij:

```
javax.servlet.ServletException: com.vaadin.server.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.denomatic.ui.BakeryApp': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.denomatic.ui.BakeryApp]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Can't find resource 'frontend://src/app/bakery-app.html' via the servlet context
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:300) ~[flow-server-1.0.0.alpha7.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:349) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:175) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.15.jar:8.5.15]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: com.vaadin.server.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.denomatic.ui.BakeryApp': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.denomatic.ui.BakeryApp]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Can't find resource 'frontend://src/app/bakery-app.html' via the servlet context
	at com.vaadin.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1528) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1491) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:298) ~[flow-server-1.0.0.alpha7.jar:na]
	... 23 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.denomatic.ui.BakeryApp': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.denomatic.ui.BakeryApp]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Can't find resource 'frontend://src/app/bakery-app.html' via the servlet context
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1155) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:292) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at com.vaadin.spring.SpringInstantiator.getObject(SpringInstantiator.java:77) ~[flow-spring-addon-1.0.0.alpha7.jar:na]
	at com.vaadin.spring.SpringInstantiator.createRouteTarget(SpringInstantiator.java:65) ~[flow-spring-addon-1.0.0.alpha7.jar:na]
	at com.vaadin.router.ErrorStateRenderer.lambda$getRouteTarget$1(ErrorStateRenderer.java:83) ~[flow-server-1.0.0.alpha7.jar:na]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_151]
	at com.vaadin.router.ErrorStateRenderer.getRouteTarget(ErrorStateRenderer.java:82) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.router.ErrorStateRenderer.handle(ErrorStateRenderer.java:107) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.router.Router.navigateToExceptionView(Router.java:160) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.router.Router.navigate(Router.java:140) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.router.Router.initializeUI(Router.java:90) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.ui.UI.doInit(UI.java:194) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:754) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:246) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1479) ~[flow-server-1.0.0.alpha7.jar:na]
	... 24 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.denomatic.ui.BakeryApp]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Can't find resource 'frontend://src/app/bakery-app.html' via the servlet context
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1147) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 42 common frames omitted
Caused by: java.lang.IllegalStateException: Can't find resource 'frontend://src/app/bakery-app.html' via the servlet context
	at com.vaadin.ui.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:105) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.ui.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:133) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.ui.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:57) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.vaadin.ui.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:70) ~[flow-server-1.0.0.alpha7.jar:na]
	at com.denomatic.ui.BakeryApp.<init>(BakeryApp.java:17) ~[classes/:na]
	at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_151]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_151]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 44 common frames omitted
```
I know it is related with the path, but I do not know where I have to change it. Thank you!

**Comment by gilberto-torrezan** [comment]
Hi @iardena, is this the basic Bakery app, or did you change something in the project?
Also, can you check which version of Vaadin 10 the project is using? It's located in your `pom.xml` file, at the `<vaadin.version>10.0.0-alphaX</vaadin.version>` tag. The latest version is `<vaadin.version>10.0.0-alpha6</vaadin.version>`.

**Comment by iardena** [comment]
Hi, @gilberto-torrezan! Thank you for answering. 
My version is: <vaadin.version>10.0.0-alpha5</vaadin.version>
I have upgrade it to 10.0.0-alpha6 version, as you said. But I go the same error and Maven doesn't foun some dpeendencies.
![image](https://user-images.githubusercontent.com/29092545/32936418-7ac04d3a-cb74-11e7-8883-4a9253bd823e.png)

Thank you!

**Comment by caalador** [comment]
How are you starting it?
Running it with `mvn spring-boot:run` from Idea works fine for me, but I cant event start the server using the built in Spring Boot application runner.

That exception is because it can not find the html template file. You could try with `mvn clean spring-boot:run`

**Comment by pleku** [comment]
Closing as no answer, please reopen if this valid after updating to a newer Platform version.

**Comment by echeypaz** [comment]
I have the same problem. Have @iardena resolved it?. But i get it when debug spring-boot profile is used.
Thnks.

**Comment by echeypaz** [comment]
Resolved it!!!. I has a Run/Debug configuration mistake:
I have set working directory to "Web" project.
![imagen](https://user-images.githubusercontent.com/1755257/42878528-54f1b0d2-8a85-11e8-8273-aae286552313.png)
