### ISSUE TITLE
Router.getUrl(Class, T) doesn't handle null parameters

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#3159]
For a navigation target with an `@OptionalParameter`, calling `getUrl(Target.class, null)` should give the same result as for `getUrl(Target.class)`. If the parameter isn't optional, then an `IllegalArgumentException` should be thrown.

**Comment by caalador** [comment]
How do you actually target `getUrl(Target.class, null)` as it becomes an ambiguous method call?
it matches `getUrl(Class, T)` and `getUrl(Class, List<T>)`

**Comment by Legioth** [comment]
The actual code is not written as `getUrl(Target.class, null)`, but rather as e.g. `getUrl(Target.class, potentiallyNullVariableWithTypeT)`. This in turn causes an NPE with this stacktrace:
```
Caused by: java.lang.NullPointerException: null
	at com.vaadin.flow.router.Router.getUrl(Router.java:337) ~[flow-server-1.0.0.alpha15.jar:na]
	at com.vaadin.flow.router.Router.getUrl(Router.java:307) ~[flow-server-1.0.0.alpha15.jar:na]
	at com.vaadin.flow.router.Router.getUrl(Router.java:288) ~[flow-server-1.0.0.alpha15.jar:na]
```
