### ISSUE TITLE
Unparseable URL parameters should not be logged as errors

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#3185]
If you have a view mapped to `/` and are using e.g. `HasUrlParameter<Long>` then when the browser tries to load any non-existing file, such as `/service-worker.js` (which happens all the time on localhost if you have ever installed a `service-worker.js` for any localhost app) you will get
```
2017-12-19 14:09:06.870 ERROR 39108 --- [nio-8080-exec-9] com.vaadin.router.InternalServerError    : There was an exception while trying to navigate to 'service-worker.js'

java.lang.NumberFormatException: For input string: "service-worker.js"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_112]
	at java.lang.Long.parseLong(Long.java:589) ~[na:1.8.0_112]
	at java.lang.Long.valueOf(Long.java:803) ~[na:1.8.0_112]
	at com.vaadin.router.ParameterDeserializer.deserializeParameter(ParameterDeserializer.java:56) ~[flow-server-1.0.0.alpha13.jar:na]
	at com.vaadin.router.HasUrlParameter.deserializeUrlParameters(HasUrlParameter.java:75) ~[flow-server-1.0.0.alpha13.jar:na]
	at com.vaadin.router.NavigationStateRenderer.lambda$handle$2(NavigationStateRenderer.java:143) ~[flow-server-1.0.0.alpha13.jar:na]
```
in the logs.

**Comment by alexberazouski** [comment]
Problem appears even if url parameter is marked as @OptionalParameter

**Comment by alexberazouski** [comment]
Any updates on this issue? It breaks a processing of NotFoundException in Bakery.
Since default root page implements HasUrlParameter<Long>, when I access the /non-existing-page, flow shows:
`There was an exception while trying to navigate to 'non-existing-page' with the exception message 'For input string: "non-existing-page"'`
instead of NotFoundError page.
