### ISSUE TITLE
When Flow is not able to resolve a resource, I want more descriptive exception message.

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/flow#3330]
When the user specifies incorrect template path, the application throws an exception when the corresponding page is open:

```
Caused by: java.lang.IllegalStateException: Can't find resource 'frontend://src/HelloWorld1.html' via the servlet context
	at com.vaadin.flow.component.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:106)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:122)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:62)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:72)
	at com.vaadin.flow.demo.helloworld.HelloWorldTemplate.<init>(HelloWorldTemplate.java:40)
	... 51 more
```

This exception makes it hard to understand which path was used for resource location.
This is especially bad when debugging the application in production mode, since it's very unclear from which paths the resources are used.

We need to 
* show the resolved path in the exceptio message
* display the path mappings for each protocol when the application starts (i.e. show frontend:// and context:// paths resolution)

Steps to reproduce:
* Have an app that has a template used, for instance https://github.com/vaadin/flow-demo/tree/master/demo-hello-worlds
* Spoil the template url in corresponding @HtmlImport in the class that extends `PolymerTemplate` (HelloWorldTemplate for demo-hello-worlds)
* launch the app and open the corresponding page (http://localhost:8080/template for demo-hello-worlds)

**Comment by Didi95** [comment]
+1 i am running in one of this issues and its hard for me to figure out what i've done wrong....
