### ISSUE TITLE
THe exception message is not informative: "For security reasons, the property must be defined as synchronized..."

### ISSUE THREAD

**Issue by vlukashov** [vaadin/flow#3470]
When getting a server-side error at run time the error message below is missing the information on the element causing the issue:

```
java.lang.IllegalArgumentException: Feature 'com.vaadin.flow.internal.nodefeature.ElementPropertyMap' doesn't allow the client to update 'size'. For security reasons, the property must be defined as synchronized through the Element's API.
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.deferredUpdateFromClient(ElementPropertyMap.java:96) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.communication.rpc.MapSyncRpcHandler.handleNode(MapSyncRpcHandler.java:68) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:60) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:338) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:288) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:88) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1516) ~[flow-server-1.0-SNAPSHOT.jar:na]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:342) [flow-server-1.0-SNAPSHOT.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
```

Please add more details into the error message to make it possible to identify the component causing the issue.

**Comment by Legioth** [comment]
We can traverse the StateNode tree upwards until we find an element and/or a component and include the tag name and/or component class name in the error message.

What we cannot easily do is to tell the full path (i.e. for sub properties) of the property inside that element/component since that information isn't directly available in any data structures right now.
