### ISSUE TITLE
IllegalArgumentException: No properties are defined for the model bean type 'java.lang.Long'

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#3549]
I have a bean which extends another bean and adds a property of type java.lang.Long. Vaadin 10.0.0.alpha18 doesn't seem to like that and fails with:

```
Caused by: java.lang.IllegalArgumentException: No properties are defined for the model bean type 'java.lang.Long'. Such bean is always represented by an empty object during server-client communication. It might be that you are trying to use some abstract super class which is not a bean instead of its direct bean subclass
	at com.vaadin.flow.templatemodel.BeanModelType.<init>(BeanModelType.java:107)
	at com.vaadin.flow.templatemodel.BeanModelType.<init>(BeanModelType.java:125)
	at com.vaadin.flow.templatemodel.BeanModelType.getModelType(BeanModelType.java:162)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.createModelType(PropertyMapBuilder.java:98)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.buildProperty(PropertyMapBuilder.java:84)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.access$200(PropertyMapBuilder.java:42)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder.lambda$new$2(PropertyMapBuilder.java:169)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder.<init>(PropertyMapBuilder.java:168)
	at com.vaadin.flow.templatemodel.BeanModelType.<init>(BeanModelType.java:125)
	at com.vaadin.flow.templatemodel.BeanModelType.getListModelType(BeanModelType.java:251)
	at com.vaadin.flow.templatemodel.BeanModelType.getModelType(BeanModelType.java:172)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.createModelType(PropertyMapBuilder.java:98)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.buildProperty(PropertyMapBuilder.java:84)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.access$200(PropertyMapBuilder.java:42)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder.lambda$new$2(PropertyMapBuilder.java:169)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder.<init>(PropertyMapBuilder.java:168)
	at com.vaadin.flow.templatemodel.BeanModelType.<init>(BeanModelType.java:150)
	at com.vaadin.flow.templatemodel.ModelDescriptor.<init>(ModelDescriptor.java:32)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:69)
	at com.vaadin.flow.templatemodel.ModelDescriptor.get(ModelDescriptor.java:50)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.createTemplateModelInstance(PolymerTemplate.java:165)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.getModel(PolymerTemplate.java:158)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.initModel(PolymerTemplate.java:189)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:75)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:83)
	at com.vaadin.starter.beveragebuddy.ui.ReviewsList.<init>(ReviewsList.kt:50)
```

**Comment by mvysny** [comment]
You can find the class in here: https://github.com/mvysny/vaadin-on-kotlin/blob/master/vok-example-flow-sql2o/src/main/kotlin/com/vaadin/starter/beveragebuddy/backend/Review.kt

To reproduce the issue, just change the `ReviewWithCategory.categoryId` field type to `Long?` and launch the `vok-example-flow-sql2o` app - the Reviews list will fail to load.

**Comment by denis-anisimov** [comment]
Just to clarify:
`Long`  is not supported by Flow.
Because it's not supported by the client side (JS).

So you have to exclude `Long` property via the `@Exclude` annotation on the bean or you model.
As a result we can't fix the original issue with `Long` : it still won't work.
But what we can do is:
- Don't consider `Long`  as a bean
- Throw exception which says that `Long` is not supported type.

This is what I'm going to do.
Please shout if you disagree.

**Comment by mvysny** [comment]
I'm sorry what? Are you suggesting that Flow supports primitive `long` but can't support `java.lang.Long`? `java.lang.Long` is widely used: for example every JPA entity has `java.lang.Long` as its ID.

This is not acceptable. Flow must accept `java.lang.Long` and must convert it into appropriate JS integer type and back.

**Comment by heruan** [comment]
Is this limited to `PolymerTemplate`, right? I'm using `java.lang.Long` without issues in components like `Grid`, etc.

**Comment by denis-anisimov** [comment]
>I'm sorry what? Are you suggesting that Flow supports properties of the primitive type long but can't support java.lang.Long

`long` is never support.

We may not support it.
As I said: JS doesn't support `long`.

So if you want support `long`  then please update the title of the ticket and clarify its description.
This ticket won't be fixed in the nearest future since we don't know how to fix it. May be there is already such ticket.

I'm going to fix an easy part: the appropriate exception message.

**Comment by denis-anisimov** [comment]
>Is this limited to PolymerTemplate, right? I'm using java.lang.Long without issues in components like Grid, etc.

It's about `TemplateModel` . Yes, it's only related to `PolymerTemplate`.
There  is no counterpart type for `long` on JS side.

**Comment by mvysny** [comment]
Yes, but there is no counterpart type for `int` on JS side as well since there's just `Number` type in JS, right?

`Number` covers both (unbounded) integers and floats. The direct counterpart of that is `BigDecimal` in Java, but it is handy to also support conversions to `byte`, `short`, `int`, `long`, `float`, `double` and their boxed counterparts.

So in this regard, why `java.lang.Integer` is supported, but `java.lang.Long` is not?

Please let me know whether I should modify the title of this bug, or create a new bug report.

**Comment by denis-anisimov** [comment]
>Please let me know whether I should modify the title of this bug, or create a new bug report.

Please modify this one.
I will create another ticket.
Also I will search for duplicate and may be close this one if it's about supporting `Long`.

Please, trust me : `long` is not supported by JS.
Any type that you may imagine in JS doesn't match directly to `long`.
You will loose some bits if the number is too big. Yes, we may convert `long` to `int` , `float`  , `double` but there may be loss.
So we can't directly convert `long` to anything in JS.

And there is a question why do you need `long` ? You may not use it in JS because there is no such type.
May be you need only an id. Then you may convert it to `String` .

Anyway this discussion is deja vu and no need to repeat it more and more time.

**Comment by denis-anisimov** [comment]
OK, good. Thanks.
Here is the ticket about long : https://github.com/vaadin/flow/issues/993

**Comment by mvysny** [comment]
Ok, good. *Now* that I know about the possible loss of precision, I can trust you ;)

**Comment by denis-anisimov** [comment]
OK, thanks :)

**Comment by mvysny** [comment]
The issue is deeper: Flow actually *is* able to transmit instances of `Review` even though it contains properties of type `java.lang.Long`. But if you create a class `ReviewWithFoo` which extends `Review`, suddenly Flow fails O_O. I'll create a new bug for this weird behavior.

**Comment by pleku** [comment]
>The issue is deeper: Flow actually is able to transmit instances of Review even though it contains properties of type java.lang.Long.

For the template model that has `List<Review>`, the id is converted to a string using LongToStringEncoder, so it not really transferring it as a long.

**Comment by mvysny** [comment]
True. As a developer, I'd expect the error message to be something along these lines:

> Error calling ReviewsModel.setReviews(): unsupported type of the ReviewWithCategory.categoryId field: primitive values such as Long are not supported. Please add the @Encode annotation to the ReviewsModel.setReviews() method.
