### ISSUE TITLE
Test GridItemRefreshPageIT.updateAndRefreshItemsOnTheServerUsingDataCommunicator_withComponentRenderer is unstable

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3625]
`GridItemRefreshPageIT.updateAndRefreshItemsOnTheServerUsingDataCommunicator_withComponentRenderer`  sometimes fails, sometimes passes.
The reason of the failure is : 

org.openqa.selenium.StaleElementReferenceException: stale element reference: element is not attached to the page document

The exception is:
```
at com.vaadin.flow.component.grid.it.GridItemRefreshPageIT.getContentIfComponentRenderered(GridItemRefreshPageIT.java:137)
    at com.vaadin.flow.component.grid.it.GridItemRefreshPageIT.lambda$waitUntilUpdated$1(GridItemRefreshPageIT.java:112)
    at com.vaadin.flow.component.grid.it.GridItemRefreshPageIT.waitUntilUpdated(GridItemRefreshPageIT.java:109)
    at com.vaadin.flow.component.grid.it.GridItemRefreshPageIT.updateAndRefreshItemsOnTheServer(GridItemRefreshPageIT.java:101)
    at com.vaadin.flow.component.grid.it.GridItemRefreshPageIT.updateAndRefreshItemsOnTheServerUsingDataCommunicator_withComponentRenderer(GridItemRefreshPageIT.java:58)
```

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/vaadin-grid-flow #107](https://github.com/vaadin/vaadin-grid-flow/issues/107) via [**ZenHub**](https://www.zenhub.com/)
