### ISSUE TITLE
Websockets with Spring Boot as a WAR throws ISE

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#3791]
The main exception is

```
Caused by: java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.util.Assert.state(Assert.java:73)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:106)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	... 70 more
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
```

See below the full stack trace.
I've disabled the war test module for a while until this is fixed somehow.
The module should be re-enabled and fix provided (either via Spring version update or workaround in our codebase).
The issue in Spring Boot: https://github.com/spring-projects/spring-boot/issues/12657
https://jira.spring.io/browse/SPR-16655

```
java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'websocketEndpointDeployer' defined in class path resource [com/vaadin/flow/spring/SpringBootAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:68)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:331)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1379)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:323)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1341)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:263)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:398)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.server.Server.start(Server.java:405)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:460)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:328)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:170)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.maven.plugin.JettyStartMojo.execute(JettyStartMojo.java:48)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[06:53:52] :	 [Step 5/6] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[06:53:52] :	 [Step 5/6] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:53:52] :	 [Step 5/6] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:53:52] :	 [Step 5/6] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:53:52] :	 [Step 5/6] 	at java.lang.reflect.Method.invoke(Method.java:498)
[06:53:52] :	 [Step 5/6] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[06:53:52] :	 [Step 5/6] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[06:53:52] :	 [Step 5/6] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[06:53:52] :	 [Step 5/6] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[06:53:52] :	 [Step 5/6] Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'websocketEndpointDeployer' defined in class path resource [com/vaadin/flow/spring/SpringBootAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1710)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
[06:53:52] :	 [Step 5/6] 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868)
[06:53:52] :	 [Step 5/6] 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
[06:53:52] :	 [Step 5/6] 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
[06:53:52] :	 [Step 5/6] 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
[06:53:52] :	 [Step 5/6] 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
[06:53:52] :	 [Step 5/6] 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
[06:53:52] :	 [Step 5/6] 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:155)
[06:53:52] :	 [Step 5/6] 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:135)
[06:53:52] :	 [Step 5/6] 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:87)
[06:53:52] :	 [Step 5/6] 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
[06:53:52] :	 [Step 5/6] 	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:63)
[06:53:52] :	 [Step 5/6] 	... 51 more
[06:53:52] :	 [Step 5/6] Caused by: java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
[06:53:52] :	 [Step 5/6] 	at org.springframework.util.Assert.state(Assert.java:73)
[06:53:52] :	 [Step 5/6] 	at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:106)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:460)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:328)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:170)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.eclipse.jetty.maven.plugin.JettyStartMojo.execute(JettyStartMojo.java:48)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at java.lang.reflect.Method.invoke(Method.java:498)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] Caused by: java.lang.IllegalStateException: javax.websocket.server.ServerContainer not available
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.util.Assert.state(Assert.java:73)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.web.socket.server.standard.ServerEndpointExporter.afterPropertiesSet(ServerEndpointExporter.java:106)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
[06:53:52]W:		 [com.vaadin:flow-test-spring-war] 	... 70 more
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769)
[06:53:52] :	 [Step 5/6] 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
```

**Comment by denis-anisimov** [comment]
At the moment Spring Boot applications deployed as a WAR are totally broken because of this.

**Comment by Artur-** [comment]
This has been fixed already

**Comment by denis-anisimov** [comment]
Issue moved to [vaadin/spring #262](https://github.com/vaadin/spring/issues/262) via [**ZenHub**](https://www.zenhub.com/)
