### ISSUE TITLE
"This instance is immutable" exception, when try to set FlexGrow on Text

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#3794]
In Java I wrap a Text component (plus some other components) inside a HorizontalLayout and call setFlexGrow(1, text) for the given Text component. As a result I get an exception.

**Code fragment:**
```
Text text = new Text("x");
HorizontalLayout layout = new HorizontalLayout();
layout.add(text);
// ... adding other stuff
layout.setFlexGrow(1, text); // throws exception
```

**Exception:**
```
java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: This instance is immutable
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_162]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_162]
	at com.vaadin.flow.server.FutureAccess.get(FutureAccess.java:61) ~[flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:1999) [flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:621) [flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1961) [flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1927) [flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:923) [flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.component.UI.access(UI.java:451) [flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.website.usermanagement.utils.UIAccessor.lambda$runInUI$0(UIAccessor.java:18) [classes/:na]
	at java.util.Optional.ifPresent(Optional.java:159) ~[na:1.8.0_162]
	at com.vaadin.website.usermanagement.utils.UIAccessor.runInUI(UIAccessor.java:18) [classes/:na]
	at com.vaadin.website.usermanagement.frontend.views.users.UsersListView.showChangedDataPopup(UsersListView.java:214) ~[classes/:na]
	at com.vaadin.website.usermanagement.frontend.views.users.UsersListPresenter.onUserDeleted(UsersListPresenter.java:192) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at com.vaadin.events.DefaultPublisher.invoke(DefaultPublisher.java:173) ~[events-core-1.0.0-SNAPSHOT.jar:na]
	at com.vaadin.events.DefaultPublisher.onListenerIteration(DefaultPublisher.java:155) ~[events-core-1.0.0-SNAPSHOT.jar:na]
	at com.vaadin.events.ThreadedPublisher.lambda$onListenerIteration$0(ThreadedPublisher.java:37) ~[events-core-1.0.0-SNAPSHOT.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_162]
Caused by: java.lang.UnsupportedOperationException: This instance is immutable
	at com.vaadin.flow.dom.impl.ImmutableEmptyStyle.set(ImmutableEmptyStyle.java:38) ~[flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.component.orderedlayout.FlexComponent.setFlexGrow(FlexComponent.java:266) ~[vaadin-ordered-layout-flow-1.0.0.beta2.jar:na]
	at org.vaadin.stefan.UpdaterNotification.addRemovableItem(UpdaterNotification.java:131) ~[updater-notification-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at com.vaadin.website.usermanagement.frontend.views.users.UsersListView.lambda$showChangedDataPopup$72d56f1c$1(UsersListView.java:217) ~[classes/:na]
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:390) [flow-server-1.0.0.beta4.jar:na]
	at com.vaadin.flow.component.UI$1.execute(UI.java:454) ~[flow-server-1.0.0.beta4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511) ~[na:1.8.0_162]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java) ~[na:1.8.0_162]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_162]
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:1996) [flow-server-1.0.0.beta4.jar:na]
	... 20 common frames omitted

```

**Comment by stefanuebe** [comment]
Since `Text` seems to be the only official user of ImmutableEmptySet I would propose to let `FlexComponent.setFlexGrow()` simply check, if the given style instance is ImmutableEmptySet and ignore it. This would improve the usage in generic batch calls of set flex grow (e.g. set flex grow for all children of component x) without the need to check for potential UnsupportedOpExceptions.

    default public void setFlexGrow(double flexGrow,
            HasElement... elementContainers) {
        if (flexGrow < 0) {
            throw new IllegalArgumentException(
                    "Flex grow property cannot be negative");
        }
        if (flexGrow == 0) {
            for (HasElement container : elementContainers) {
                Style style = container.getElement().getStyle();
                if(!(style instanceof ImmutableEmptyStyle)) {
                    style.remove(FlexConstants.FLEX_GROW_CSS_PROPERTY);
                }
            }
        } else {
            for (HasElement container : elementContainers) {
                Style style = container.getElement().getStyle();
                if(!(style instanceof ImmutableEmptyStyle)) {
                    style.set(FlexConstants.FLEX_GROW_CSS_PROPERTY,
                        String.valueOf(flexGrow));
                }
            }
        }
    }
