### ISSUE TITLE
Component added assynchronously - NPE on ServletHelper

### ISSUE THREAD

**Issue by lolytxd** [vaadin/flow#3798]
**Vaadin version: 10.0.0.beta4**

For this example I used project from [https://vaadin.com/start/v10-project-base](https://vaadin.com/start/v10-project-base)

I changed MainView class like this:

```
@BodySize(height = "100vh", width = "100vw")
@HtmlImport("styles/shared-styles.html")
@Route("")
@Theme(Lumo.class)
@Push
public class MainView extends VerticalLayout {

	public MainView() {
		UI ui = UI.getCurrent();
		try {
			new Thread(() -> {
				try {
					Thread.sleep(5000);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				ui.access(() -> {
					Button button = new Button("Button");
					add(button);
				});
			}).start();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
```

Executing this results in NPE
```
Exception in thread "Thread-12" java.lang.RuntimeException: Push failed
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:194)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:169)
	at com.vaadin.flow.component.UI.push(UI.java:565)
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:629)
	at com.vaadin.flow.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1961)
	at com.vaadin.flow.server.VaadinService.accessSession(VaadinService.java:1927)
	at com.vaadin.flow.server.VaadinSession.access(VaadinSession.java:923)
	at com.vaadin.flow.component.UI.access(UI.java:451)
	at com.example.test.MainView.lambda$0(MainView.java:31)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.ServletHelper.getContextRootRelativePath(ServletHelper.java:188)
	at com.vaadin.flow.server.BootstrapHandler.getApplicationParameters(BootstrapHandler.java:892)
	at com.vaadin.flow.server.BootstrapHandler.access$000(BootstrapHandler.java:82)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapUriResolver.getContextRootUrl(BootstrapHandler.java:344)
	at com.vaadin.flow.shared.VaadinUriResolver.processContextProtocol(VaadinUriResolver.java:89)
	at com.vaadin.flow.shared.VaadinUriResolver.resolveVaadinUri(VaadinUriResolver.java:60)
	at com.vaadin.flow.server.VaadinServlet.resolveUrl(VaadinServlet.java:697)
	at com.vaadin.flow.server.VaadinServlet.resourceIsFound(VaadinServlet.java:685)
	at com.vaadin.flow.server.VaadinServlet.computeUrlTranslation(VaadinServlet.java:677)
	at com.vaadin.flow.server.VaadinServlet.getUrlTranslation(VaadinServlet.java:635)
	at com.vaadin.flow.component.internal.UIInternals.getHtmlImportValue(UIInternals.java:902)
	at com.vaadin.flow.component.internal.UIInternals.lambda$addHtmlImport$5(UIInternals.java:896)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.vaadin.flow.component.internal.UIInternals.addHtmlImport(UIInternals.java:896)
	at com.vaadin.flow.component.internal.UIInternals.lambda$addComponentDependencies$2(UIInternals.java:887)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.vaadin.flow.component.internal.UIInternals.addComponentDependencies(UIInternals.java:887)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:331)
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:138)
	at com.vaadin.flow.server.communication.AtmospherePushConnection.push(AtmospherePushConnection.java:190)
	... 9 more
```

I've tried ```@Push(PushMode.MANUAL)``` and then after ```add(button)``` I called ```ui.push()``` but nothing changed. ```@Push(transport = Transport.LONG_POLLING)``` changes nothing too.

**Comment by pleku** [comment]
Should be verified after #3802 is fixed since I think it indirectly fix this also.
