### ISSUE TITLE
Vaadin app in production mode can not be deployed to WebLogic 12

### ISSUE THREAD

**Issue by Peppe** [vaadin/flow#3924]
1. Download Beverage buddy from https://vaadin.com/start/v10-simple-ui
1. Build war with `mvn package -Dvaadin.productionMode`
1. Download and install WebLogic Server 12.2.1.3 and open the Administration Console
1. Try to deploy the war to WebLogic with Administration Console

The app is not deployed and you are presented with the following error message:

```  
Error Unable to access the selected application.

Error VALIDATION PROBLEMS WERE FOUND /Users/peppe/Documents/Dev/Tools/oracle-weblogic-12.2.1.3/wls12213/user_projects/domains/base_domain/weblogic.utils.classloaders.GenericClassLoader@3196a99d finder: weblogic.utils.classloaders.CodeGenClassFinder@64281338 annotation: /WEB-INF/lib/flow-server-production-mode-1.0.0.beta6.jar!/META-INF/web-fragment.xml:8:50:8:50: problem: cvc-datatype-valid.1.1: string value 'flow-server-production-mode-fragment' does not match pattern for java-identifierType in namespace http://java.sun.com/xml/ns/javaee

Error VALIDATION PROBLEMS WERE FOUND /Users/peppe/Documents/Dev/Tools/oracle-weblogic-12.2.1.3/wls12213/user_projects/domains/base_domain/weblogic.utils.classloaders.GenericClassLoader@3196a99d finder: weblogic.utils.classloaders.CodeGenClassFinder@64281338 annotation: /WEB-INF/lib/flow-server-production-mode-1.0.0.beta6.jar!/META-INF/web-fragment.xml:8:50:8:50: problem: cvc-datatype-valid.1.1: string value 'flow-server-production-mode-fragment' does not match pattern for java-identifierType in namespace http://java.sun.com/xml/ns/javaee

Error VALIDATION PROBLEMS WERE FOUND /Users/peppe/Documents/Dev/Tools/oracle-weblogic-12.2.1.3/wls12213/user_projects/domains/base_domain/weblogic.utils.classloaders.GenericClassLoader@3196a99d finder: weblogic.utils.classloaders.CodeGenClassFinder@64281338 annotation: /WEB-INF/lib/flow-server-production-mode-1.0.0.beta6.jar!/META-INF/web-fragment.xml:8:50:8:50: problem: cvc-datatype-valid.1.1: string value 'flow-server-production-mode-fragment' does not match pattern for java-identifierType in namespace http://java.sun.com/xml/ns/javaee```
```

![screen shot 2018-04-18 at 10 59 11](https://user-images.githubusercontent.com/525503/38919532-84a06df6-42f9-11e8-83c1-afd0650d0b37.png)

**Comment by Peppe** [comment]
I think this is the log part which fails the deployment.

```
####<Apr 18, 2018 10:55:44,068 AM EEST> <Error> <Munger> <Peppe-Mirana> <AdminServer> <[ACTIVE] ExecuteThread: '12' for queue: 'weblogic.kernel.Default (self-tuning)'> <weblogic> <> <3d295f2b-df62-4d11-b30e-fe2b0681ea9a-0000003e> <1524038144068> <[severity-value: 8] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-2156200> <Unable to load descriptor weblogic.utils.classloaders.GenericClassLoader@3196a99d finder: weblogic.utils.classloaders.CodeGenClassFinder@64281338 annotation: /WEB-INF/lib/flow-server-production-mode-1.0.0.beta6.jar!/META-INF/web-fragment.xml of module testing-nopush-prod.war. The error is weblogic.descriptor.DescriptorException: VALIDATION PROBLEMS WERE FOUND
  /Users/peppe/Documents/Dev/Tools/oracle-weblogic-12.2.1.3/wls12213/user_projects/domains/base_domain/weblogic.utils.classloaders.GenericClassLoader@3196a99d finder: weblogic.utils.classloaders.CodeGenClassFinder@64281338 annotation: /WEB-INF/lib/flow-server-production-mode-1.0.0.beta6.jar!/META-INF/web-fragment.xml:8:50:8:50: problem: cvc-datatype-valid.1.1: string value 'flow-server-production-mode-fragment' does not match pattern for java-identifierType in namespace http://java.sun.com/xml/ns/javaee
	at weblogic.descriptor.internal.MarshallerFactory$1.evaluateResults(MarshallerFactory.java:249)
	at weblogic.descriptor.internal.MarshallerFactory$1.evaluateResults(MarshallerFactory.java:235)
	at weblogic.descriptor.internal.MarshallerFactory$1.createDescriptor(MarshallerFactory.java:159)
	at weblogic.descriptor.BasicDescriptorManager.createDescriptor(BasicDescriptorManager.java:345)
	at weblogic.descriptor.BasicDescriptorManager.createDescriptor(BasicDescriptorManager.java:307)
	at weblogic.application.descriptor.AbstractDescriptorLoader2.getDescriptorBeanFromReader(AbstractDescriptorLoader2.java:870)
	at weblogic.application.descriptor.AbstractDescriptorLoader2.createDescriptorBean(AbstractDescriptorLoader2.java:447)
	at weblogic.application.descriptor.AbstractDescriptorLoader2.loadDescriptorBeanWithoutPlan(AbstractDescriptorLoader2.java:832)
	at weblogic.application.descriptor.AbstractDescriptorLoader2.loadDescriptorBean(AbstractDescriptorLoader2.java:841)
	at weblogic.servlet.internal.fragment.WebFragmentLoader.getWebFragmentBean(WebFragmentLoader.java:53)
	at weblogic.servlet.internal.fragment.WebFragmentManager.prepareForTopologicalSort(WebFragmentManager.java:164)
	at weblogic.servlet.internal.fragment.WebFragmentManager.sortRelatively(WebFragmentManager.java:152)
	at weblogic.servlet.internal.fragment.WebFragmentManager.sortFragments(WebFragmentManager.java:109)
	at weblogic.servlet.internal.fragment.WebFragmentManager.<init>(WebFragmentManager.java:54)
	at weblogic.servlet.internal.fragment.WebFragmentManager.<init>(WebFragmentManager.java:43)
	at weblogic.servlet.tools.WARModule.initWebFragmentManager(WARModule.java:522)
	at weblogic.servlet.tools.WARModule.merge(WARModule.java:552)
	at weblogic.application.compiler.ToolsModuleWrapper.merge(ToolsModuleWrapper.java:96)
	at weblogic.application.utils.CustomModuleManager.merge(CustomModuleManager.java:78)
	at weblogic.application.compiler.flow.SingleModuleMergeFlow.proecessModule(SingleModuleMergeFlow.java:27)
	at weblogic.application.compiler.flow.SingleModuleFlow.compile(SingleModuleFlow.java:64)
	at weblogic.application.compiler.FlowDriver$FlowStateChange.next(FlowDriver.java:70)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.compiler.FlowDriver.nextState(FlowDriver.java:37)
	at weblogic.application.compiler.BaseMerger.merge(BaseMerger.java:20)
	at weblogic.application.compiler.flow.AppMergerFlow.mergeInput(AppMergerFlow.java:75)
	at weblogic.application.compiler.flow.AppMergerFlow.compile(AppMergerFlow.java:40)
	at weblogic.application.compiler.FlowDriver$FlowStateChange.next(FlowDriver.java:70)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.compiler.FlowDriver.nextState(FlowDriver.java:37)
	at weblogic.application.compiler.AppMerge.runBody(AppMerge.java:168)
	at weblogic.utils.compiler.Tool.run(Tool.java:159)
	at weblogic.utils.compiler.Tool.run(Tool.java:116)
	at weblogic.application.compiler.AppMerge.merge(AppMerge.java:198)
	at weblogic.deploy.api.internal.utils.AppMerger.merge(AppMerger.java:94)
	at weblogic.deploy.api.internal.utils.AppMerger.getMergedApp(AppMerger.java:58)
	at weblogic.deploy.api.model.internal.WebLogicDeployableObjectFactoryImpl.createDeployableObject(WebLogicDeployableObjectFactoryImpl.java:186)
	at weblogic.deploy.api.model.internal.WebLogicDeployableObjectFactoryImpl.createLazyDeployableObject(WebLogicDeployableObjectFactoryImpl.java:160)
	at weblogic.deploy.api.tools.SessionHelper.inspect(SessionHelper.java:781)
	at com.bea.console.actions.app.install.Flow$2.execute(Flow.java:530)
	at com.bea.console.utils.DeploymentUtils.runDeploymentAction(DeploymentUtils.java:5690)
	at com.bea.console.actions.app.install.Flow.appSelected(Flow.java:528)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.beehive.netui.pageflow.FlowController.invokeActionMethod(FlowController.java:870)
	at org.apache.beehive.netui.pageflow.FlowController.getActionMethodForward(FlowController.java:809)
	at org.apache.beehive.netui.pageflow.FlowController.internalExecute(FlowController.java:478)
	at org.apache.beehive.netui.pageflow.PageFlowController.internalExecute(PageFlowController.java:306)
	at org.apache.beehive.netui.pageflow.FlowController.execute(FlowController.java:336)
	at org.apache.beehive.netui.pageflow.internal.FlowControllerAction.execute(FlowControllerAction.java:52)
	at org.apache.struts.action.RequestProcessor.processActionPerform(RequestProcessor.java:431)
	at org.apache.beehive.netui.pageflow.PageFlowRequestProcessor.access$201(PageFlowRequestProcessor.java:97)
	at org.apache.beehive.netui.pageflow.PageFlowRequestProcessor$ActionRunner.execute(PageFlowRequestProcessor.java:2044)
	at org.apache.beehive.netui.pageflow.interceptor.action.internal.ActionInterceptors$WrapActionInterceptorChain.continueChain(ActionInterceptors.java:64)
	at org.apache.beehive.netui.pageflow.interceptor.action.ActionInterceptor.wrapAction(ActionInterceptor.java:184)
	at org.apache.beehive.netui.pageflow.interceptor.action.internal.ActionInterceptors$WrapActionInterceptorChain.invoke(ActionInterceptors.java:50)
	at org.apache.beehive.netui.pageflow.interceptor.action.internal.ActionInterceptors$WrapActionInterceptorChain.continueChain(ActionInterceptors.java:58)
	at org.apache.beehive.netui.pageflow.interceptor.action.internal.ActionInterceptors.wrapAction(ActionInterceptors.java:87)
	at org.apache.beehive.netui.pageflow.PageFlowRequestProcessor.processActionPerform(PageFlowRequestProcessor.java:2116)
	at com.bea.console.internal.ConsolePageFlowRequestProcessor.processActionPerform(ConsolePageFlowRequestProcessor.java:265)
	at org.apache.struts.action.RequestProcessor.process(RequestProcessor.java:236)
	at org.apache.beehive.netui.pageflow.PageFlowRequestProcessor.processInternal(PageFlowRequestProcessor.java:556)
	at org.apache.beehive.netui.pageflow.PageFlowRequestProcessor.process(PageFlowRequestProcessor.java:853)
	at org.apache.beehive.netui.pageflow.AutoRegisterActionServlet.process(AutoRegisterActionServlet.java:631)
	at org.apache.beehive.netui.pageflow.PageFlowActionServlet.process(PageFlowActionServlet.java:158)
	at com.bea.console.internal.ConsoleActionServlet.process(ConsoleActionServlet.java:262)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:414)
	at com.bea.console.internal.ConsoleActionServlet.doGet(ConsoleActionServlet.java:134)
	at org.apache.beehive.netui.pageflow.PageFlowUtils.strutsLookup(PageFlowUtils.java:1199)
	at org.apache.beehive.netui.pageflow.PageFlowUtils.strutsLookup(PageFlowUtils.java:1129)
	at com.bea.portlet.adapter.scopedcontent.framework.internal.PageFlowUtilsBeehiveDelegate.strutsLookupInternal(PageFlowUtilsBeehiveDelegate.java:43)
	at com.bea.portlet.adapter.scopedcontent.framework.PageFlowUtils.strutsLookup(PageFlowUtils.java:108)
	at com.bea.portlet.adapter.scopedcontent.ScopedContentCommonSupport.executeAction(ScopedContentCommonSupport.java:707)
	at com.bea.portlet.adapter.scopedcontent.ScopedContentCommonSupport.processActionInternal(ScopedContentCommonSupport.java:141)
	at com.bea.portlet.adapter.scopedcontent.PageFlowStubImpl.processAction(PageFlowStubImpl.java:108)
	at com.bea.portlet.adapter.NetuiActionHandler.raiseScopedAction(NetuiActionHandler.java:111)
	at com.bea.netuix.servlets.controls.content.NetuiContent.raiseScopedAction(NetuiContent.java:181)
	at com.bea.netuix.servlets.controls.content.NetuiContent.raiseScopedAction(NetuiContent.java:167)
	at com.bea.netuix.servlets.controls.content.NetuiContent.handlePostbackData(NetuiContent.java:225)
	at com.bea.netuix.nf.ControlLifecycle$2.visit(ControlLifecycle.java:180)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:324)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walkRecursive(ControlTreeWalker.java:334)
	at com.bea.netuix.nf.ControlTreeWalker.walk(ControlTreeWalker.java:130)
	at com.bea.netuix.nf.Lifecycle.processLifecycles(Lifecycle.java:399)
	at com.bea.netuix.nf.Lifecycle.processLifecycles(Lifecycle.java:361)
	at com.bea.netuix.nf.Lifecycle.processLifecycles(Lifecycle.java:352)
	at com.bea.netuix.nf.Lifecycle.runInbound(Lifecycle.java:184)
	at com.bea.netuix.nf.Lifecycle.run(Lifecycle.java:159)
	at com.bea.netuix.servlets.manager.UIServlet.runLifecycle(UIServlet.java:465)
	at com.bea.netuix.servlets.manager.UIServlet.doPost(UIServlet.java:291)
	at com.bea.netuix.servlets.manager.UIServlet.service(UIServlet.java:219)
	at com.bea.netuix.servlets.manager.SingleFileServlet.service(SingleFileServlet.java:275)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.bea.console.utils.MBeanUtilsInitSingleFileServlet.service(MBeanUtilsInitSingleFileServlet.java:64)
	at weblogic.servlet.AsyncInitServlet.service(AsyncInitServlet.java:125)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at com.bea.console.internal.ParamFilter.doFilter(ParamFilter.java:38)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.RequestEventsFilter.doFilter(RequestEventsFilter.java:32)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3701)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3667)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:326)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2443)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2291)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2269)
	at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1703)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1663)
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:644)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:415)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:355)
.> 
```

**Comment by denis-anisimov** [comment]
Seems the same issue: https://github.com/togglz/togglz/issues/204
