### ISSUE TITLE
Converter to primitive type gives client-side exception with null

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/flow#3931]
`<vaadin.version>10.0.0.beta7</vaadin.version>`
Bean class:
```java
public class FormValue {
	private double doubleValue;
	public double getDoubleValue() {
		return doubleValue;
	}
	public void setDoubleValue(double doubleValue) {
		this.doubleValue = doubleValue;
	}
}
```
Field and Binder:
```java
	final Binder<FormValue> binder = new Binder<>(FormValue.class);
	FormValue fv = new FormValue();
	fv.setDoubleValue(1.0);
	binder.setBean(fv);
	final TextField doubleField = new TextField("Double converter");
	binder.forField(doubleField)
			.withConverter(new StringToDoubleConverter("must be valid double"))
			.bind(FormValue::getDoubleValue, FormValue::setDoubleValue);
```
Remove the initially set value from the TextField and there is an Internal Error message in the UI: 
```
Internal error
Please notify the administrator.
Take note of any unsaved data, and click here or press ESC to continue.
```
No errors in the server log.

**Comment by pleku** [comment]
>Remove the initially set value from the TextField

@OlliTietavainenVaadin could you please clarify, remove as in how, from the UI ?

**Comment by OlliTietavainenVaadin** [comment]
Erase the text in the UI with backspace.

**Comment by denis-anisimov** [comment]
It's not a client side exception.
It's a server side exception which is not shown for some reason in your server log.
May be because you have no configured logger.

Here is the exception stacktrace :
```
java.lang.NullPointerException
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$writeFieldValue$5169480d$1(Binder.java:1125)
	at com.vaadin.flow.data.binder.SimpleResult.handle(SimpleResult.java:78)
	at com.vaadin.flow.data.binder.ValidationResultWrap.handle(ValidationResultWrap.java:81)
	at com.vaadin.flow.data.binder.Result.ifOk(Result.java:146)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.writeFieldValue(Binder.java:1125)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.access$1500(Binder.java:942)
	at com.vaadin.flow.data.binder.Binder.lambda$doWriteIfValid$4(Binder.java:1725)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.data.binder.Binder.doWriteIfValid(Binder.java:1724)
	at com.vaadin.flow.data.binder.Binder.handleFieldValueChange(Binder.java:1370)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.handleFieldValueChange(Binder.java:1109)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$initFieldValue$7c3bd67$1(Binder.java:1090)
	at com.vaadin.flow.component.internal.AbstractFieldSupport.lambda$addValueChangeListener$828eca10$1(AbstractFieldSupport.java:95)
	at com.vaadin.flow.component.ComponentEventBus.lambda$fireEvent$1(ComponentEventBus.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:128)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:341)
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:324)
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:206)
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setModelValue(AbstractFieldSupport.java:166)
	at com.vaadin.flow.component.AbstractField.setModelValue(AbstractField.java:223)
	at com.vaadin.flow.component.AbstractSinglePropertyField.handlePropertyChange(AbstractSinglePropertyField.java:325)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$5(ElementPropertyMap.java:401)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.fireEvent(ElementPropertyMap.java:401)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.access$100(ElementPropertyMap.java:47)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap$PutResult.run(ElementPropertyMap.java:169)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:366)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
```

**Comment by denis-anisimov** [comment]
I would say that this is invalid issue.

It's a bit confusing, yes but the confusion is because of generic Java boxing-unboxing which I have no idea how to deal with.

Everything works fine if `FormValue` is:

```
    public class FormValue {
        private double doubleValue;

        public Double getDoubleValue() {
            return doubleValue;
        }

        public void setDoubleValue(Double doubleValue) {
            if (doubleValue != null) {
                this.doubleValue = doubleValue;
            } else {
                this.doubleValue = 0;
            }
        }
    }
```

The problem in the original example is: there is no converters to primitive types.
All converters converts object to object which means that neither value may be primitive since they are not objects.
Java boxing unboxing helps to handle primitive types case but here you always should be aware that the value which you expect as primitive may be `null` and it may not be unboxed.

That's exactly the exception which you get here. Your `FormValue` setter expects primitive but it gets `null` when the field is empty.

Please note that the field gets an empty string `""` as a value when it's empty (not `null`).
It's `StringToDoubleConverter` who returns `null` as a conversation value for `""`.

May be `StringToDoubleConverter`  should return `0.0` as a conversation value for `""`.
But in `Double` case `null` may be desirable. And the converter doesn't know that you need primitive actually.

So I'm not sure how to deal with this.

May be we may provide additional CTOR for `StringToDoubleConverter` which has a parameter whose value is the conversation result for `""`. In this case this CTOR may be used for primitives.

Please let me know your thoughts.

**Comment by Legioth** [comment]
If I remember right, the conclusion from what was discussed on Slack before this ticket was filed was that a server-side exception is expected in this case, but a client-side exception is not.

Based on the conclusion that there was indeed a server-side exception, I'd say that there's nothing more about this issue, other than yet another pointer that it would be quite important to deal with https://github.com/vaadin/flow/issues/801.
