### ISSUE TITLE
Flow fails to transfer java.lang.Long of a class that extends model class

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#4030]
Please clone the https://github.com/mvysny/beverage-starter-flow project and run it. It will fail:

```
Caused by: java.lang.IllegalArgumentException: No properties are defined for the model bean type 'java.lang.Long'. Such bean is always represented by an empty object during server-client communication. It might be that you are trying to use some abstract super class which is not a bean instead of its direct bean subclass
	at com.vaadin.flow.templatemodel.BeanModelType.<init>(BeanModelType.java:107)
	at com.vaadin.flow.templatemodel.BeanModelType.<init>(BeanModelType.java:125)
	at com.vaadin.flow.templatemodel.BeanModelType.getModelType(BeanModelType.java:162)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.createModelType(PropertyMapBuilder.java:98)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.buildProperty(PropertyMapBuilder.java:84)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder$PropertyData.access$200(PropertyMapBuilder.java:42)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder.lambda$new$2(PropertyMapBuilder.java:169)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.vaadin.flow.templatemodel.PropertyMapBuilder.<init>(PropertyMapBuilder.java:168)
	at com.vaadin.flow.templatemodel.BeanModelType.<init>(BeanModelType.java:125)
	at com.vaadin.flow.templatemodel.BeanModelType.getListModelType(BeanModelType.java:251)
```

So Flow complains that it can't transmit values of `java.lang.Long`. However, the original Beverage Buddy project uses the `Review` class which contains the field `id` which is of type `java.lang.Long` and apparently Flow can transmit `Review.id` without any issues.

This behavior is highly confusing:
1. Flow can transfer `Review.id` but can't transfer `ReviewWithFoo.foo` even though they are of the same type
2. The exception message is confusing since it provides no explanation of this phenomenon.

**Comment by pleku** [comment]
>Flow can transfer Review.id but can't transfer ReviewWithFoo.foo even though they are of the same type

For the template model that has `List<Review>`, the id is converted to a string using LongToStringEncoder, so it not really transferring it as a long. 

I don't really see how this issue is any different from #3549, so I'm closing this. The error message is the same and equally confusing.

**Comment by mvysny** [comment]
Thanks @pleku for explanation. The reason is that `ReviewsModel` has the annotation of `Encode(value = LongToStringConverter::class, path = "id")` which tells Flow to convert that particular field from `Long` to `String`.

As a developer, I would pretty much welcome the error message to be as follows:

Error calling ReviewsModel.setReviews(): unsupported type of the ReviewWithCategory.categoryId field: primitive values such as Long are not supported. Please add the `@Encode` annotation to the ReviewsModel.setReviews() method.
