### ISSUE TITLE
Unable to send a new bean instance to the server

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#4078]
```
@ClientCallable
public void addTodo(Todo todo) {
	System.out.println(todo.getText());
}
```

```
this.$server.addTodo({text: cmd.text});
```

Results in 
```
java.lang.IllegalArgumentException: Class 'org.vaadin.artur.todomvc.TodoMvc' has the method 'addTodo' whose parameter 0 refers to unsupported type 'org.vaadin.artur.todomvc.Todo'
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.decodeArg(PublishedServerEventHandlerRpcHandler.java:265)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.decodeArgs(PublishedServerEventHandlerRpcHandler.java:198)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:152)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:137)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:116)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:63)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:377)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:367)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:367)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1495)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

The error message is obviously wrong but the real problem is that no Todo bean is sent to the method. For a similar `update` method, this works fine (when the `Todo` instance is in the model).

**Comment by pleku** [comment]
One thing is to fix the error message, but want you probably want is a way be able to create the bean from the json automatically ? For now you're using `addTodo(String text) { Todo t = new Todo(text); ...}` or ?
