### ISSUE TITLE
More info available in exception thrown from DataProvider.getId

### ISSUE THREAD

**Issue by bennewi** [vaadin/flow#4095]
I got an error at the initialization of my page:
> java.lang.NullPointerException: Cannot provide an id for a null item.
>    at java.util.Objects.requireNonNull(Objects.java:228)
>    at com.vaadin.flow.data.provider.DataProvider.getId(DataProvider.java:129)
....

I solved it in the end by debugging my code and imagining forward from initialization to exception, but there's no hints from the stack trace (none of which contains my code) to point me in the right direction. 

For instance knowing what type of component it was would already help troubleshooting.

**Comment by tdq** [comment]
It's not that easy to get type of generic T, but how about to print class name of this?

**Comment by Legioth** [comment]
> But anyway if we really need to display type of T it's possible by using reflection to check current type parameters (this.getClass().getTypeParameters()[0]) and if they are not set we have to do the same for our super class (and do it in the loop until we will come to DataProvider interface or some type will be found)

Easier to use `com.googlecode.gentyref.GenericTypeReflector` which is already part of the project. The problem is that in many cases data providers are used in ways that doesn't capture the type at all (e.g. `new ListDataProvider<>()` or `DataProvider.fromCallbacks(...)`.

More useful then might be to show the class of the component that uses the data provider, and maybe even some specific attribute and property value from its element (e.g. `id` or style names).
