### ISSUE TITLE
Creating polymer based component outside of UI thread throws NPE

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4434]
I create polymer template based components in a background thread. This leads to a NullPointerException since the VaadinService instance is null. 

Flow should either try to obtain the current VaadinService instance or if not possible throw a meaningful exception like "Creating polymer template components outside of the UI thread is not possible".

```
java.lang.NullPointerException
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:77)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:97)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:112)
	at com.vaadin.internal.dashboard.ui.views.misc.NotificationListEntry.<init>(NotificationListEntry.java:26)
	at com.vaadin.internal.dashboard.ui.views.misc.NotificationList.lambda$null$2(NotificationList.java:79)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
...
```

```
private void wrapInComponentsAndAdd(List<Notification> notifications) {
	getUI().ifPresent(ui -> {

		Component[] components = notifications.stream()
			.filter(notification -> !shownIds.contains(notification.getId()))
			.map(notification -> {
				shownIds.add(notification.getId());

				NotificationListEntry entry = new NotificationListEntry(notification, notificationService, eventBus); // << the polymer template based component
				NotificationListEntry.Source sourceDetails = entry.getSourceDetails();
				if (notification.getSourceType() == NotificationSourceType.PROJECT) {
					projectService.findEntityById(notification.getSourceId()).ifPresent(project -> {
						sourceDetails.setName(project.getName());
						sourceDetails.setType(notification.getSourceType().name().toLowerCase());
							sourceDetails.setUrl(QualifiedRoutes.PROJECTS_DETAILS + "/" + project.getId());
					});
				}

				return entry;
			}).toArray(Component[]::new);

		ui.access(() -> add(components));
	});
}
```

**Comment by denis-anisimov** [comment]
Yes, we should an exception if there is no `VaadinService` available.

Please note that you are doing things which are fundamentally wrong: work with UI elements outside of UI thread.

This is never allowed (unfortunately the design doesn't prevent it out of the box).

In your example you are calling `ui.access(` to "correctly" execute some task.

But your ui instance is the result of `getUI()` call.
That's the problem: you may not call this method outside servlet request thread because this method is not thread safe.

`getUI` calculates an `UI` instance based on ascendants  (via `parent` field in `StateNode` class).
Since this field is not synchronized in any way you may not get _ANY_ access to it without getting a lock on some monitor which guarantees you exclusive access to this field.
There is no such lock outside of request thread.
It means that this field may be at least cached by thread and may be just `null`.

That's exactly the reason why no any operation (regardless of read of write) may be done with ANY UI element outside of "UI thread".

Every time when you need to do something in a separate thread should be done on data.
Then data is "send" to UI thread and used to create/update UI components inside UI thread.
This is a common approach dealing with UI components everywhere.
