### ISSUE TITLE
Polymer Tabs cause java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow#4564]
Tabs defined in a Polymer template causes an IllegalArgumentException when tab is clicked in 11.0.0.beta2. It was not observed in previous builds.

**Polymer template**
```
<link rel="import" href="../bower_components/polymer/polymer.html">
<link rel="import" href="../bower_components/vaadin-tabs/src/vaadin-tabs.html">
<link rel="import" href="../bower_components/vaadin-tabs/src/vaadin-tab.html">

<dom-module id="tabs-error">
    <template>
<vaadin-tabs id="tabs">
 <vaadin-tab id="tab1" selected>
  <label>Tab 1</label>
 </vaadin-tab>
 <vaadin-tab id="tab2">
  <label>Tab 2</label>
 </vaadin-tab>
 <vaadin-tab id="tab3">
  <label>Tab 3</label>
 </vaadin-tab>
</vaadin-tabs>
</template>
    <script>
        class TabsError extends Polymer.Element {
            static get is() {
                return 'tabs-error';
            }
        }
        customElements.define(TabsError.is, TabsError);
    </script>
</dom-module>
```

**Java class**

```
import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.dependency.HtmlImport;
import com.vaadin.flow.component.polymertemplate.Id;
import com.vaadin.flow.component.polymertemplate.PolymerTemplate;
import com.vaadin.flow.component.tabs.Tab;
import com.vaadin.flow.component.tabs.Tabs;
import com.vaadin.flow.router.Route;
import com.vaadin.flow.templatemodel.TemplateModel;

@Tag("tabs-error")
@HtmlImport("frontend://src/tabs-error.html")
@Route(value = "tabserror")
public class TabsErrorView extends PolymerTemplate<TabsErrorView.TabViewModel> {

   @Id("tabs")
   private Tabs tabs;
   @Id("tab1")
   private Tab tab1;
   @Id("tab2")
   private Tab tab2;
   @Id("tab3")
   private Tab tab3;

   public interface TabViewModel extends TemplateModel {
   }

   public TabsErrorView() {
   }
}
```

**Stack trace**

```
java.lang.IllegalArgumentException: The 'index' argument should not be greater than or equals to the number of children components. It was: 1
	at com.vaadin.flow.component.HasOrderedComponents.lambda$getComponentAt$0(HasOrderedComponents.java:128) ~[flow-server-1.0.4.jar:na]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[na:1.8.0_171]
	at com.vaadin.flow.component.HasOrderedComponents.getComponentAt(HasOrderedComponents.java:128) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.component.tabs.Tabs.getSelectedTab(Tabs.java:151) ~[vaadin-tabs-flow-1.0.3.jar:na]
	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:237) ~[vaadin-tabs-flow-1.0.3.jar:na]
	at com.vaadin.flow.component.tabs.Tabs.lambda$new$c53a20e4$1(Tabs.java:58) ~[vaadin-tabs-flow-1.0.3.jar:na]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$5(ElementPropertyMap.java:402) ~[flow-server-1.0.4.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_171]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.fireEvent(ElementPropertyMap.java:402) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.access$100(ElementPropertyMap.java:48) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap$PutResult.run(ElementPropertyMap.java:170) ~[flow-server-1.0.4.jar:na]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_171]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:366) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1486) ~[flow-server-1.0.4.jar:na]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300) [flow-server-1.0.4.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:356) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316) [tomcat-embed-core-8.5.31.jar:8.5.31]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) [spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) [spring-webmvc-5.0.6.RELEASE.jar:5.0.6.RELEASE]
```

Creating tabs in plain Java code is working just fine.

```
import com.vaadin.flow.component.Composite;
import com.vaadin.flow.component.html.Div;
import com.vaadin.flow.component.tabs.Tab;
import com.vaadin.flow.component.tabs.Tabs;
import com.vaadin.flow.router.Route;

@Route("tabs")
public class Tab3 extends Composite<Div> {

   public Tab3() {

      Tabs tabs = new Tabs(new Tab("Tab 1"), new Tab("Tab 2"), new Tab("Tab 3"));

      getContent().add(tabs);
   }
}
```

**Comment by martinisraelsen** [comment]
Tested with 11.0.0.beta3. 

It no longer throws the exception, however, SelectedChangeListener is no longer working if the tabs are created in the Polymer template. It works fine with Tabs created in Java code.

**Comment by ZheSun88** [comment]
@martinisraelsen in this case,  could you create another ticket about the new issue and provide us some more details based on it? I will close this one which is not valid any more.
