### ISSUE TITLE
HasErrorParamter implementation not recognized

### ISSUE THREAD

**Issue by stefanuebe** [vaadin/flow#4607]
https://vaadin.com/docs/v10/flow/routing/tutorial-routing-exception-handling.html

When I understand the documentation correct, it should be enough to create a component implementing the interface with a specific Exception type, so that Flow uses that implementation as an error view for the given exception type.

This is my test implementation:
```
package com.test
// ... other imports
import org.springframework.security.access.AccessDeniedException;

@Tag(Tag.DIV)
@ParentLayout(SomeLayout.class)
public class PermissionDeniedView extends Component implements HasErrorParameter<AccessDeniedException> {

	@Override
	public int setErrorParameter(BeforeEnterEvent event, ErrorParameter<AccessDeniedException> parameter) {
		getElement().setText("Tried to navigate to a view without correct access rights");
		return HttpServletResponse.SC_FORBIDDEN;
	}
}
```

The `setErrorParameter` method is called, but the UI content does not change. Instead, the UI crashes (`Internal error Please notify the Administrator...`) and I get a server side exception:

```
org.springframework.security.access.AccessDeniedException: not-permitted
	at com.test.SomeLayout.beforeEnter(SomeLayout.java:93)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.executeBeforeEnterNavigation(AbstractNavigationStateRenderer.java:330)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:196)
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:49)
	at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:240)
	at com.vaadin.flow.router.Router.navigate(Router.java:175)
	at com.vaadin.flow.component.UI.navigate(UI.java:772)
	at com.vaadin.flow.component.UI.navigate(UI.java:735)
	at com.test.SomeLayout.lambda$new$1(SomeLayout.java:69)
	at com.test.MenuLink.lambda$new$5233d190$1(MenuLink.java:59)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:133)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:327)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$5ee67f2b$1(ComponentEventBus.java:191)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:379)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:379)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:59)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:377)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:367)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:367)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1486)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
```

**Comment by mehdi-vaadin** [comment]
I can't reproduce it with Vaadin 10 nor 14. @stefanuebe I know it's for a long time ago, but still, do you remember how to reproduce it?

**Comment by stefanuebe** [comment]
I can't reproduce it neither, so I'd say can be closed for now.
