### ISSUE TITLE
Java 11 support

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#4652]
`ByteBuddy 1.9.0 which has official support for Java 11. https://github.com/raphw/byte-buddy/releases/tag/byte-buddy-1.9.0` - @Legioth 

Need to update the Atmosphere version too https://github.com/Atmosphere/atmosphere/releases/tag/atmosphere-project-2.5.0

### Acceptance Criteria
Have a nightly IT that verifies Flow against Java 11. IMO this can replace the current test for Java 10 since it is EOL.

**Comment by caalador** [comment]
Java 11 will need the patch/fix:
https://github.com/eclipse/jetty.project/issues/2941
https://github.com/eclipse/jetty.project/pull/2957

as now starting Flow with Java11 gives us:
```
	Caused by: java.lang.UnsupportedOperationException
		at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
		at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737)
		... 6 more
```
And many more.

Also the `DomApiAbstractionUsageTest.java` fails on `Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7` 

Also note that ASM7 is still only 7.0-beta.
