### ISSUE TITLE
Vaadin Charts will cause dependency conflict on commons-io

### ISSUE THREAD

**Issue by TatuLund** [vaadin/flow#4757]
If the project uses (older) version of charts, there will be dependency conflict on commons-io, since Flow uses it internally, e.g. with Router. 

[WARNING] Error for /sw.js
java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.toString(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/String;
    at com.vaadin.flow.router.RouteNotFoundError.readHtmlFile(RouteNotFoundError.java:75)
    at com.vaadin.flow.router.RouteNotFoundError.getErrorHtml(RouteNotFoundError.java:69)
    at com.vaadin.flow.router.RouteNotFoundError.setErrorParameter(RouteNotFoundError.java:54)
    at com.vaadin.flow.router.internal.ErrorStateRenderer.notifyNavigationTarget(ErrorStateRenderer.java:60)
    at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:181)

Workaround is to exclude the transient dependency from chart dependency:

```
		<dependency>
			<groupId>com.vaadin.addon</groupId>
			<artifactId>vaadin-charts</artifactId>
			<version>2.0.0</version>
    		<exclusions>
        		<exclusion>
            		<groupId>commons-io</groupId>
            		<artifactId>commons-io</artifactId>
        		</exclusion>
    		</exclusions>
		</dependency>

```

**Comment by pleku** [comment]
We should not have any dependencies to common libraries in the platform.
