### ISSUE TITLE
OSGi: it's possible to request a web application before routes are discovered

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#4808]
`OSGiRouteRegistry` initializes routes when they are firstly asked.
It uses the routes data from a route data collector (specific for OSGi).

Current `OSGiRouteRegistry` implementation expects that all routes (their data) are discovered and available before a web application asks about it.
Otherwise it will get this data once from the OSGi route data collection once (and this data is not yet really available).

`OSGiRouteRegistry` should be aware somehow of this situation (may be this should be done along with dynamic routes update which allows to return incomplete route data but then it will be updated once it become available).

**Comment by denis-anisimov** [comment]
There maybe exception thrown (because of this issue I suppose) : 
```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.remove(HashMap.java:1451)
	at java.util.AbstractSet.removeAll(AbstractSet.java:178)
	at com.vaadin.flow.server.startup.RouteRegistry.setErrorNavigationTargets(RouteRegistry.java:366)
	at com.vaadin.flow.server.startup.RouteRegistry$OSGiRouteRegistry.initErrorTargets(RouteRegistry.java:182)
	at com.vaadin.flow.server.startup.RouteRegistry$OSGiRouteRegistry.getErrorNavigationTarget(RouteRegistry.java:130)
	at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:243)
	at com.vaadin.flow.router.Router.navigate(Router.java:194)
	at com.vaadin.flow.router.Router.initializeUI(Router.java:95)
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1117)
```

**Comment by denis-anisimov** [comment]
I've fixed the exception and the undesired behavior in the simplest case.
But this in fact is just another aspect of dynamic essence of OSGi and absence of initialization phase.

Here is what happens:
- bundle tracker scans all the classes and collects them
- in every meaningful application there are at least two bundles which are scanned: `flow-server`  and the application bundle which contains routes
- Now depending on the order of bundle activation either `flow-server`  is handled first or the application bundle is handled first.
  - If `flow-server`  is handled first then there are a number of pre-defined Error targets classes which are collected to be handled by the `ServletContainerInitializer`.
  - If the application bundle is handled first then there are route targets classes which are collected to be handled by the `ServletContainerInitializer`.

Now if a web request happens after the first bundle is handled but the second is not yet handled then it tries to initialize routes.
And if `flow-server` has been handled first then there are no routes are discovered yet but there are classes which are passed to the `RouteRegistryInitializer` : those classes are just Error targets.
They are filtered out inside `RouteRegistryInitializer`  and an empty navigation targets are set (though in reality no navigation targets have been found yet).

`RouteRegistry` doesn't allow to be reinitialized so it's initialized once with no routes and that produces a bug. Routes will be set later on once they are discovered but they will be rejected since the registry is already initialized.

As a result: the issue https://github.com/vaadin/flow/issues/4710 has to be fixed to make this work properly:
we should allow updating the route data registry on the fly (which is the essence of the bug) instead of having one time initialized registry
