### ISSUE TITLE
NullPointerException in AbstractRouteRegistryInitializer.validateRouteAnnotation on WebSphere 8.5.5.14

### ISSUE THREAD

**Issue by anders-special** [vaadin/flow#4901]
We are migrating our application from Vaadin 8 to Vaadin 12. Unfortunately the application refuses to deploy on IBM WebSphere 8.5.5.14.

The following NullPointerException occurs during application deployment.

`com.ibm.ws.exception.RuntimeWarning: com.ibm.ws.exception.RuntimeWarning: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: Failed to load webapp: null
	at com.ibm.wsspi.runtime.component.WsComponentImpl.join(WsComponentImpl.java:432)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.startCUList(CompositionUnitMgrImpl.java:1295)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:275)
	at com.ibm.ws.runtime.component.ContainerHelper.startComponents(ContainerHelper.java:540)
	at com.ibm.ws.runtime.component.ContainerImpl.startComponents(ContainerImpl.java:627)
	at com.ibm.ws.runtime.component.ContainerImpl.start(ContainerImpl.java:618)
	at com.ibm.ws.runtime.component.ApplicationServerImpl.start(ApplicationServerImpl.java:252)
	at com.ibm.ws.runtime.component.ContainerHelper.startComponents(ContainerHelper.java:540)
	at com.ibm.ws.runtime.component.ContainerImpl.startComponents(ContainerImpl.java:627)
	at com.ibm.ws.runtime.component.ContainerImpl.start(ContainerImpl.java:618)
	at com.ibm.ws.runtime.component.ServerImpl.start(ServerImpl.java:540)
	at com.ibm.ws.runtime.WsServerImpl.bootServerContainer(WsServerImpl.java:319)
	at com.ibm.ws.runtime.WsServerImpl.start(WsServerImpl.java:232)
	at com.ibm.ws.runtime.WsServerImpl.main(WsServerImpl.java:705)
	at com.ibm.ws.runtime.WsServer.main(WsServer.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.wsspi.bootstrap.WSLauncher.launchMain(WSLauncher.java:234)
	at com.ibm.wsspi.bootstrap.WSLauncher.main(WSLauncher.java:96)
	at com.ibm.wsspi.bootstrap.WSLauncher.run(WSLauncher.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.eclipse.core.launcher.Main.invokeFramework(Main.java:340)
	at org.eclipse.core.launcher.Main.basicRun(Main.java:282)
	at org.eclipse.core.launcher.Main.run(Main.java:981)
	at com.ibm.wsspi.bootstrap.WSPreLauncher.launchEclipse(WSPreLauncher.java:411)
	at com.ibm.wsspi.bootstrap.WSPreLauncher.main(WSPreLauncher.java:173)
Caused by: com.ibm.ws.exception.RuntimeWarning: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: Failed to load webapp: null
	at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:433)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.start(WebContainerImpl.java:719)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:1211)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.fireDeployedObjectStart(DeployedApplicationImpl.java:1450)
	at com.ibm.ws.runtime.component.DeployedModuleImpl.start(DeployedModuleImpl.java:639)
	at com.ibm.ws.runtime.component.DeployedApplicationImpl.start(DeployedApplicationImpl.java:1032)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.startApplication(ApplicationMgrImpl.java:795)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl$5.run(ApplicationMgrImpl.java:2279)
	at com.ibm.ws.security.auth.ContextManagerImpl.runAs(ContextManagerImpl.java:5482)
	at com.ibm.ws.security.auth.ContextManagerImpl.runAsSystem(ContextManagerImpl.java:5698)
	at com.ibm.ws.security.core.SecurityContext.runAsSystem(SecurityContext.java:255)
	at com.ibm.ws.runtime.component.ApplicationMgrImpl.start(ApplicationMgrImpl.java:2284)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:436)
	at com.ibm.ws.runtime.component.CompositionUnitImpl.start(CompositionUnitImpl.java:123)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.start(CompositionUnitMgrImpl.java:379)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl.access$500(CompositionUnitMgrImpl.java:127)
	at com.ibm.ws.runtime.component.CompositionUnitMgrImpl$CUInitializer.run(CompositionUnitMgrImpl.java:985)
	at com.ibm.wsspi.runtime.component.WsComponentImpl$_AsynchInitializer.run(WsComponentImpl.java:524)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892)
Caused by: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: Failed to load webapp: null
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:914)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApplication(WSWebContainer.java:789)
	at com.ibm.ws.webcontainer.component.WebContainerImpl.install(WebContainerImpl.java:427)
	... 18 more
Caused by: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: null
	at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:186)
	at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:904)
	... 20 more
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.startup.AbstractRouteRegistryInitializer.validateRouteAnnotation(AbstractRouteRegistryInitializer.java:191)
	at com.vaadin.flow.server.startup.AbstractRouteRegistryInitializer.lambda$checkForConflictingAnnotations$1(AbstractRouteRegistryInitializer.java:97)
	at com.vaadin.flow.server.startup.AbstractRouteRegistryInitializer$$Lambda$31.000000001F8D7EA0.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:959)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:591)
	at com.vaadin.flow.server.startup.AbstractRouteRegistryInitializer.checkForConflictingAnnotations(AbstractRouteRegistryInitializer.java:93)
	at com.vaadin.flow.server.startup.AbstractRouteRegistryInitializer$$Lambda$24.0000000011274F90.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:383)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1564)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:523)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:513)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:719)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:245)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:510)
	at com.vaadin.flow.server.startup.AbstractRouteRegistryInitializer.validateRouteClasses(AbstractRouteRegistryInitializer.java:63)
	at com.vaadin.flow.server.startup.RouteRegistryInitializer.onStartup(RouteRegistryInitializer.java:47)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initializeServletContainerInitializers(WebAppImpl.java:620)
	at com.ibm.ws.webcontainer.webapp.WebAppImpl.initialize(WebAppImpl.java:410)
	at com.ibm.ws.webcontainer.webapp.WebGroupImpl.addWebApplication(WebGroupImpl.java:88)
	at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:171)
	... 21 more`

The NullPointerException occurs because the Route interface itself comes as the parameter route in the AbstractRouteRegistryInitializer.validateRouteAnnotation method.  This occurs when trying to deploy our application on WebSphere.  It works fine on Glassfish.

I have investigated the problem and my conclusion is that WebSphere handled the @HandlesTypes({ Route.class, RouteAlias.class }) in the RouteRegistryInitializer class differently than Glassfish.  The variable classSet includes the class for both the Route and RouteAlias interface on Websphere but on Glassfish it is only classes that uses the Route annotation that are included.

I believe that the problem can be solved by filtering out the Route and RouterInterface in the AbstractRouteRegistryInitializer.validateRouteAnnotation method.

Vaadin version: 12.0.1
WebSphere version: 8.5.5.14
Java version: 1.8_64
OS: Windows 10

**Comment by anders-special** [comment]
I managed to get Vaadin 12 to work on WebSphere 8.5.5.14 by making the following changes.
1. Vaadin CDI - AbstractContextualStorageManager - added empty constructor.
2. Vaadin CDI - VaadinSessionScopedContext - changed the passivationCapable parameter to false.
3. Vaadin Flow - AbstractRouteRegistryInitializer - added null check in the methods validateRouteImplementation and validateRouteAnnotation.
4. Vaadin Flow - ResponseWriter - changed the method call to setContentLengthLong to setContentLength.

**Comment by Legioth** [comment]
Cases 1, 2 and 4 are out of scope because WebSphere 8.5.5.14 does not support CDI 1.2 and Servlet 3.1 that are required by Vaadin 10 and newer (CDI only if using the CDI integration).

Case 3 is in scope since it also affects newer WebSphere versions that support Servlet 3.1. This is still technically a bug in WebSphere, but it seems reasonable that we include the null checks.

**Comment by claudiocaldarella** [comment]
> Cases 1, 2 and 4 are out of scope because WebSphere 8.5.5.14 does not support CDI 1.2 and Servlet 3.1 that are required by Vaadin 10 and newer (CDI only if using the CDI integration).
> 
> Case 3 is in scope since it also affects newer WebSphere versions that support Servlet 3.1. This is still technically a bug in WebSphere, but it seems reasonable that we include the null checks.

Hi Legioth, since your fix will be available on Platform 14 during next summer and since we have an open ticket with IBM lab on this subject (we have Websphere 9.0.0.9 ), what info can we give to IBM so they can solve their bug?
Thanks
Claudio

**Comment by Legioth** [comment]
@claudiocaldarella I guess you're referring to Case 3, i.e. the `NullPointerException` related to `@HandlesTypes` since that's the only one that should apply to Websphere 9?

This relates to section 8.2.4 in the Servlet 3.1 specification (JSR 340) which states that the `Set` passed to `onStartup` should contain any classes that either "extend / implement the classes that the initializer expressed interest in or if it is annotated with any of the classes specified via the `@HandlesTypes` annotation.".

It seems the implementation in Websphere makes the assumption the classes specified in `@HandlesTypes` are also themselves fulfilling that criteria, i.e. that `Foo` either extends / implements  `Foo` or alternatively that `@Foo` is implicitly annotated with `@Foo`. In contrast, the other tested servlet container implementations would ignore `Foo`.

IBM might argue that the specification doesn't explicitly define whether `Foo` should be included or not and their interpretation is thus valid and. On the other hand, the specification declares that `null` shall be passed in case no class matches the `@HandlesTypes` definition. Based on this, I would argue that the only way of satisfying that condition is that the request type itself is ignored.

In either case, a workaround has been included in the branch from which Vaadin 14 will be built in roughly 5 weeks time. If needed, this fix could also be backported to Vaadin 10 LTS and/or Vaadin 13.

**Comment by claudiocaldarella** [comment]
Thanks @Legioth I try to forward to IBM your explanation. At the moment we're working on 10 LTS so it could be very useful to backport the fix.

**Comment by claudiocaldarella** [comment]
Hi @Legioth with your indications, IBM found the following APAR:
https://www-01.ibm.com/support/docview.wss?uid=swg1PI26448
So IBM asked to set 
com.ibm.ws.webcontainer.excludeHandledTypesClasses = true

Now on WebSphere we have a different NPE and and IBM found that it's similar to the one reported on Liberty Profile:
https://github.com/vaadin/flow/issues/4511

java.lang.NullPointerException
at com.vaadin.flow.server.startup.RouteRegistry.setErrorNavigationTargets(RouteRegistry.java:229)
at com.vaadin.flow.server.startup.ErrorNavigationTargetInitializer.onStartup(ErrorNavigationTargetInitializer.java:50)
at com.ibm.ws.webcontainer.webapp.WebAppImpl.initializeServletContainerInitializers(WebAppImpl.java:652)

Any thoughts about it?
Thanks

**Comment by Legioth** [comment]
#4511 also looks like something that would be worked around by the same `excludeHandledTypesClasses` setting, but maybe there might be some additional complication there that I fail to take into account.

The fix for that issue is included in Vaadin 12 and newer. It is marked as backported to Vaadin 10 as well, but it seems like it's mislabeled because the fixed code isn't present in that branch. We can backport it to an upcoming Vaadin 10 maintenance release if necessary, but it would be great if you could first verify that you're not seeing the same issue with some newer Vaadin version that already has the fix.

**Comment by claudiocaldarella** [comment]
Hi @Legioth I've just tested Vaadin 13 on Websphere 9.0.0.9 and with the property com.ibm.ws.webcontainer.excludeHandledTypesClasses = true it's working (without it's not working)
