### ISSUE TITLE
Classpath issue after DevModeHandler and concurrency issue with webpack log.

### ISSUE THREAD

**Issue by bogdanudrescu** [vaadin/flow#5225]
```
Caused by: java.lang.ClassNotFoundException: com.vaadin.flow.server.StaticFileServer
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass (SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass (ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass (ClassRealm.java:239)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass (WebAppClassLoader.java:556)
    at java.lang.ClassLoader.loadClass (ClassLoader.java:357)
    at com.vaadin.flow.server.VaadinServlet.createStaticFileHandler (VaadinServlet.java:107)
    at com.vaadin.flow.server.VaadinServlet.init (VaadinServlet.java:83)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet (ServletHolder.java:672)
    at org.eclipse.jetty.servlet.ServletHolder.getServlet (ServletHolder.java:521)
    at org.eclipse.jetty.servlet.ServletHolder.prepare (ServletHolder.java:805)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:537)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:146)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:548)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:257)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:1588)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:255)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1345)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:203)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:480)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:1557)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:201)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1247)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:144)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:220)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:126)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:132)
    at org.eclipse.jetty.server.Server.handle (Server.java:502)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:364)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:260)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:305)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:103)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run (ChannelEndPoint.java:118)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:765)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run (QueuedThreadPool.java:683)
    at java.lang.Thread.run (Thread.java:748)
```

If we move `devmodeHandler = DevModeHandler.createInstance(deploymentConfiguration);` after `staticFileHandler` and `webJarServer` the exception is:

```
javax.servlet.ServletException: javax.servlet.UnavailableException: Could not instantiate class com.vaadin.flow.server.VaadinServlet
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.UnavailableException: Could not instantiate class com.vaadin.flow.server.VaadinServlet
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:524)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:805)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:537)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1588)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1557)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	... 10 more
```

**Comment by bogdanudrescu** [comment]
There seem to be some concurrency issues when output the log from webpack so I'll be looking into those first, see if there is anything relevant for our main problem.

**Comment by bogdanudrescu** [comment]
Not happening anymore, might have been fixed or workaround by something else.
