### ISSUE TITLE
Update project bases to npm

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5355]
Create a 2.0 branch for the starters based on npm:

- [x] https://github.com/vaadin/skeleton-starter-flow
- [x] https://github.com/vaadin/skeleton-starter-flow-spring
- [x] https://github.com/vaadin/skeleton-starter-flow-cdi

Project base for OSGi will be part of another issue.

**Comment by SomeoneToIgnore** [comment]
The spring starter update branch is here: https://github.com/vaadin/skeleton-starter-flow-spring/tree/kb/update-to-npm

It's not possible to make it work currently because of https://github.com/vaadin/flow/issues/5426

**Comment by SomeoneToIgnore** [comment]
Also when you add a `gson` dependency into a Spring starter, it still fails to start:
```
Caused by: java.lang.NoSuchMethodError: com.vaadin.flow.server.webcomponent.WebComponentConfigurationRegistry.hasExporters()Z
        at com.vaadin.flow.spring.VaadinServletContextInitializer.onStartup(VaadinServletContextInitializer.java:294) ~[vaadin-spring-11.1-SNAPSHOT.jar:na]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:238) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:54) ~[spring-boot-2.0.2.RELEASE.jar:2.0.2.RELEASE]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5245) ~[tomcat-embed-core-8.5.31.jar:8.5.31]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.31.jar:8.5.31]
        ... 6 common frames omitted
```

Looks like an issue in the Flow spring plugin.
