### ISSUE TITLE
DX test the experience for a Java developer running a starter for the first time

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#5397]
EDIT: see last comments on what issue to fix, requires Windows.

Based on acceptance criteria in https://github.com/vaadin/flow/issues/5432 and blocked until that is done for `2.0.0.alpha4`.

Prerequisite: the developer has Java 8 (or newer) and Maven installed.

Task: the developer acquires a starter* using `git clone` is fine for now) and tries to run the project without installing any frontend tools (node.js & npm)

*Any of the following starters have a `2.0` branch available:
- beverage-starter-flow
- skeleton-starter-flow
- skeleton-starter-flow-cdi

Test with users having:
- [x] Windows
- [x] Mac
- [x] Linux (any)

**Comment by pleku** [comment]
Currently Windows user that doens't have node installed at all:
1) running `mvn clean jetty:run` for beverage buddy
2) jetty starts, but with errors:
```console
java.lang.RuntimeException: java.lang.IllegalStateException: Failed to determine 'npm' tool. Please install it using the https://nodejs.org/en/download/ guide.
    at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart (ServletContainerInitializersStarter.java:69)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start (AbstractLifeCycle.java:68)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext (ServletContextHandler.java:347)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp (WebAppContext.java:1497)
    at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp (JettyWebAppContext.java:360)
...
Caused by: java.lang.IllegalStateException: Failed to determine 'npm' tool. Please install it using the https://nodejs.org/en/download/ guide.
    at com.vaadin.flow.server.frontend.NodeUpdatePackages.lambda$null$4 (NodeUpdatePackages.java:250)
    at java.util.Optional.orElseThrow (Optional.java:290)
    at com.vaadin.flow.server.frontend.NodeUpdatePackages.lambda$getNpmCommand$5 (NodeUpdatePackages.java:250)
    at java.util.Optional.orElseGet (Optional.java:267)
    at com.vaadin.flow.server.frontend.NodeUpdatePackages.getNpmCommand (NodeUpdatePackages.java:249)
```

**Comment by vaadin-miki** [comment]
on a Windows system without globally installed node and npm the build fails with suggestion to install node globally or locally through maven - good and clear message

after successful local installation of node through maven, the build continues to fail with the same error message

relevant maven debug stack trace:

    com.vaadin.flow.server.frontend.FrontendUtils.getExecutable(FrontendUtils.java:152)
    at com.vaadin.flow.server.frontend.FrontendUtils.getNodeExecutable(FrontendUtils.java:118)
    at com.vaadin.flow.plugin.maven.NodeValidateMojo.execute(NodeValidateMojo.java:44)

**Comment by vaadin-miki** [comment]
tried again with new version of the code, got one step further
now the error is caused by (most likely) `npm` assuming that `node` is installed globally (it is not, it is installed locally through maven goal)
relevant error messages: 

```npm WARN lifecycle npm is using V:\path\here\beverage-starter-flow\node\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @vaadin/vaadin-usage-statistics@2.0.3 postinstall V:\path\here\beverage-starter-flow\node_modules\@vaadin\vaadin-usage-statistics
> node check.js

'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN beverage-starter-flow No repository field.
npm WARN beverage-starter-flow No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaadin/vaadin-usage-statistics@2.0.3 postinstall: `node check.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vaadin/vaadin-usage-statistics@2.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by caalador** [comment]
That would look like it's trying to use the shell script node instead of the actual exe file that it should use.

**Comment by caalador** [comment]
Found the command as `"postinstall\": \"node check.js\"` in https://github.com/vaadin/vaadin-usage-statistics/blob/e1e7e91376651ead2058c1fda95e366a072179fb/magi-p3-post.json

I would think that it shouldn't be run by us at all, but seems like it is.

**Comment by pleku** [comment]
Just as a note - I've run the same steps with Windows installing node in project several times, and have not yet run into this issue.

@web-padawan should the usage statistics fail like this if there is an error when running node ?

**Comment by caalador** [comment]
The fix for the issue with local node on windows has been merged and should work now with the latest snapshot.

**Comment by vaadin-miki** [comment]
running `mvn jetty:run` succeeds with locally installed node... but there are errors in the process - some dependencies are not available in `frontend` nor `node_modules`

error displayed:
```
[main] INFO dev-updater - Creating a default V:\github\beverage-starter-flow\package.json
[main] INFO dev-updater - Added @vaadin/vaadin-ordered-layout@=1.1.0 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-grid@=5.3.3 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-icons@=4.3.1 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-button@=2.1.5 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-date-picker@=3.3.4 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-text-field@=2.4.0 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-combo-box@=4.2.8 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-dialog@=2.2.1 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-form-layout@=2.1.2 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-list-box@=1.1.0 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-checkbox@=2.2.7 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-item@=2.1.0 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-context-menu@=4.3.4 dependency.
[main] INFO dev-updater - Added @vaadin/vaadin-lumo-styles@=1.4.2 dependency.
[main] INFO dev-updater - Added webpack dependency.
[main] INFO dev-updater - Added webpack-cli dependency.
[main] INFO dev-updater - Added webpack-dev-server dependency.
[main] INFO dev-updater - Added webpack-babel-multi-target-plugin dependency.
[main] INFO dev-updater - Added copy-webpack-plugin dependency.
[main] INFO dev-updater - Running `npm install` ...

> @vaadin/vaadin-usage-statistics@2.0.3 postinstall V:\github\beverage-starter-flow\node_modules\@vaadin\vaadin-usage-statistics
> node check.js

npm WARN lifecycle npm is using V:\github\beverage-starter-flow\node\node.exe but there is no node binary in the current PATH. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
'node' is not recognized as an internal or external command,
operable program or batch file.
npm WARN beverage-starter-flow No repository field.
npm WARN beverage-starter-flow No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaadin/vaadin-usage-statistics@2.0.3 postinstall: `node check.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @vaadin/vaadin-usage-statistics@2.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\miki\AppData\Roaming\npm-cache\_logs\2019-04-25T11_25_54_090Z-debug.log
[main] ERROR dev-updater - >>> Dependency ERROR. Check that all required dependencies are deployed in npm repositories.
[main] INFO dev-updater - Created webpack.config.js from jar:file:/C:/Users/miki/.m2/repository/com/vaadin/flow-server/2.0-SNAPSHOT/flow-server-2.0-SNAPSHOT.jar!/webpack.config.js
[main] INFO dev-updater - Installed 7 @vaadin/flow-frontend/ modules
[main] WARN com.vaadin.flow.server.startup.DevModeInitializer - Failed to start a dev mode, hot reload is disabled. Continuing to start the application.
java.lang.IllegalStateException: Failed to update the Flow imports file 'V:\github\beverage-starter-flow\target\frontend\generated-flow-imports.js'
	at com.vaadin.flow.server.frontend.NodeUpdateImports.execute(NodeUpdateImports.java:117)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:222)
	at com.vaadin.flow.server.startup.DevModeInitializer.onStartup(DevModeInitializer.java:84)
	at org.eclipse.jetty.plus.annotation.ContainerInitializer.callStartup(ContainerInitializer.java:140)
	at org.eclipse.jetty.annotations.ServletContainerInitializersStarter.doStart(ServletContainerInitializersStarter.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:347)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1497)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.startWebapp(JettyWebAppContext.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1459)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:545)
	at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:428)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:168)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
	at org.eclipse.jetty.server.Server.start(Server.java:415)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:477)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:343)
	at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:169)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: java.lang.IllegalStateException: Failed to resolve the following module imports neither in the node_modules directory 'V:\github\beverage-starter-flow\node_modules' nor in project files in 'V:\github\beverage-starter-flow\frontend': 
'@vaadin/vaadin-ordered-layout/theme/lumo/vaadin-vertical-layout.js' (the import was translated by Flow from the path '@vaadin/vaadin-ordered-layout/src/vaadin-vertical-layout.js')
'@vaadin/vaadin-grid/theme/lumo/vaadin-grid-column.js' (the import was translated by Flow from the path '@vaadin/vaadin-grid/src/vaadin-grid-column.js')
'@vaadin/vaadin-form-layout/theme/lumo/vaadin-form-item.js' (the import was translated by Flow from the path '@vaadin/vaadin-form-layout/src/vaadin-form-item.js')
'@vaadin/vaadin-dialog/theme/lumo/vaadin-dialog.js' (the import was translated by Flow from the path '@vaadin/vaadin-dialog/src/vaadin-dialog.js')
'@vaadin/vaadin-button/theme/lumo/vaadin-button.js' (the import was translated by Flow from the path '@vaadin/vaadin-button/src/vaadin-button.js')
'@vaadin/vaadin-checkbox/theme/lumo/vaadin-checkbox.js' (the import was translated by Flow from the path '@vaadin/vaadin-checkbox/src/vaadin-checkbox.js')
'@vaadin/vaadin-date-picker/theme/lumo/vaadin-date-picker.js' (the import was translated by Flow from the path '@vaadin/vaadin-date-picker/src/vaadin-date-picker.js')
'@vaadin/vaadin-combo-box/theme/lumo/vaadin-combo-box.js' (the import was translated by Flow from the path '@vaadin/vaadin-combo-box/src/vaadin-combo-box.js')
'@vaadin/vaadin-ordered-layout/theme/lumo/vaadin-horizontal-layout.js' (the import was translated by Flow from the path '@vaadin/vaadin-ordered-layout/src/vaadin-horizontal-layout.js')
'@vaadin/vaadin-context-menu/theme/lumo/vaadin-context-menu.js' (the import was translated by Flow from the path '@vaadin/vaadin-context-menu/src/vaadin-context-menu.js')
'@vaadin/vaadin-text-field/theme/lumo/vaadin-text-field.js' (the import was translated by Flow from the path '@vaadin/vaadin-text-field/src/vaadin-text-field.js')
'@vaadin/vaadin-list-box/theme/lumo/vaadin-list-box.js' (the import was translated by Flow from the path '@vaadin/vaadin-list-box/src/vaadin-list-box.js')
'@vaadin/vaadin-grid/theme/lumo/vaadin-grid-sorter.js' (the import was translated by Flow from the path '@vaadin/vaadin-grid/src/vaadin-grid-sorter.js')
'@vaadin/vaadin-grid/vaadin-grid-column-group.js'
'@vaadin/vaadin-grid/theme/lumo/vaadin-grid.js' (the import was translated by Flow from the path '@vaadin/vaadin-grid/src/vaadin-grid.js')
'@vaadin/vaadin-form-layout/theme/lumo/vaadin-form-layout.js' (the import was translated by Flow from the path '@vaadin/vaadin-form-layout/src/vaadin-form-layout.js')
Double check that those files exist in the project structure.
	at com.vaadin.flow.server.frontend.NodeUpdateImports.modulesToImports(NodeUpdateImports.java:188)
	at com.vaadin.flow.server.frontend.NodeUpdateImports.getMainJsContent(NodeUpdateImports.java:142)
```

**Comment by caalador** [comment]
Remove any old package.json + node_modules and then #5566 should fix the warnings and errors problem.

**Comment by vaadin-miki** [comment]
@caalador fresh import from github

**Comment by caalador** [comment]
Didn't have any problem with a clean checkout... but I do have the version from 5566

**Comment by pleku** [comment]
I did not have any errors with a clean project, using either local or global node installation.

**Comment by pleku** [comment]
Verified to work with 3 different windows machines.

**Comment by martaolszewskatusiek** [comment]
Test document: https://docs.google.com/document/d/1gpXpqj6N2bSA8_r8a5_Xnp8rYABKcVi1lR4luLeiOZU/edit?ts=5cb068e2
