### ISSUE TITLE
Stopping jetty while running `npm install` will fail the build next time.

### ISSUE THREAD

**Issue by bogdanudrescu** [vaadin/flow#5645]
If execute `mvn jetty:run` and stop it in the middle of `npm install`, a second `mvn jetty:run` will output even though the server itself starts:

```
java.lang.IllegalStateException: Failed to update the Flow imports file '/Users/bogdan/work/workspace-vaadin/my-starter-project/target/frontend/generated-flow-imports.js'
...
Caused by: java.lang.IllegalStateException: Failed to resolve the following module imports neither in the node_modules directory '/Users/bogdan/work/workspace-vaadin/my-starter-project/node_modules' nor in project files in '/Users/bogdan/work/workspace-vaadin/my-starter-project/frontend': 
'@vaadin/flow-frontend/dndConnector.js'
Double check that those files exist in the project structure.
	at com.vaadin.flow.server.frontend.NodeUpdateImports.modulesToImports(NodeUpdateImports.java:187)
	at com.vaadin.flow.server.frontend.NodeUpdateImports.getMainJsContent(NodeUpdateImports.java:141)
	at com.vaadin.flow.server.frontend.NodeUpdateImports.execute(NodeUpdateImports.java:114)
	... 56 more
```

**Comment by ujoni** [comment]
### Acceptance criteria:
- Modify the exception with instructions to remove `node_modules` and run `npm install` before doing anything else. Just in case.

**Comment by denis-anisimov** [comment]
Several things to note here:
- there is anymore `NodeUpdateImports`. Looks like it has been renamed to `TaskUpdateImports`.
- but `TaskUpdateImports` doesn't contain anymore the code which throws an exception.
- there is a log message similar to the one in the description. But it doesn't fail the build since this is not an exception
- the  build should fails because bundle file won't be build (by webpack/npm) .

So this is not that important anymore since the build is not failed somewhere inside `TaskUpdateImports`. Now it's just informational exception which doesn't even have to be shown if the logger level is lower than INFO.

I've improved the log message but it looks like this is different code now.
