### ISSUE TITLE
Error for maven plugin with autodetectTools on windows

### ISSUE THREAD

**Issue by ahoehma** [vaadin/flow#5647]
My yarn is installed under "C:\Program Files (x86)\Yarn\bin\yarn".
Was installed via "chocolatey" (I guess this is not really relevant).

The I run mvn clean package -Pproductive

Where "productive" defines the vaadin flow maven plugin like this:

```
<plugin>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-maven-plugin</artifactId>
            <executions>
              <execution>
                <goals>
                  <goal>copy-production-files</goal>
                  <goal>package-for-production</goal>
                </goals>
                <configuration>
                  <bundle>true</bundle>
                  <transpileOutputDirectory>${project.build.directory}/classes/static</transpileOutputDirectory>
                  <autodetectTools>true</autodetectTools>
                </configuration>
              </execution>
            </executions>
          </plugin>
```

Then during the run I see this error ... but the process doesn't stop ... everything seems to work after that ... compiling etc.

```
[ERROR] Failed to execute the command '[C:\Program Files (x86)\Yarn\bin\yarn, -v]'
java.io.IOException: Cannot run program "C:\Program Files (x86)\Yarn\bin\yarn": CreateProcess error=193, %1 ist keine zulΣssige Win32-Anwendung
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at com.vaadin.flow.plugin.common.FrontendToolsLocator.executeCommand(FrontendToolsLocator.java:103)
        at com.vaadin.flow.plugin.common.FrontendToolsLocator.verifyTool(FrontendToolsLocator.java:90)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at com.vaadin.flow.plugin.common.FrontendToolsLocator.tryLocateTool(FrontendToolsLocator.java:78)
        at com.vaadin.flow.plugin.common.RunnerManager.getToolPath(RunnerManager.java:260)
        at com.vaadin.flow.plugin.common.RunnerManager.<init>(RunnerManager.java:61)
        at com.vaadin.flow.plugin.common.RunnerManager.<init>(RunnerManager.java:44)
        at com.vaadin.flow.plugin.common.RunnerManager$Builder.build(RunnerManager.java:215)
        at com.vaadin.flow.plugin.maven.PackageForProductionMojo.getRunnerManager(PackageForProductionMojo.java:238)
        at com.vaadin.flow.plugin.maven.PackageForProductionMojo.execute(PackageForProductionMojo.java:226)
```

**Comment by mehdi-vaadin** [comment]
@ahoehma do you still have this issue? What exact version of Vaadin are you using?

**Comment by mehdi-vaadin** [comment]
I'm closing this as it's related to V13 which is at its end of line.
