### ISSUE TITLE
Random JSON parse errors when live relaoding

### ISSUE THREAD

**Issue by Legioth** [vaadin/flow#5688]
In a bigger project (@jouni has all the details) using npm mode, sometimes when you make client-side changes, the automatic reload fails with a variety of errors related to JSON parsing from `BundleParser.parseJsonStatistics(BundleParser.java:105)`.

I would guess this happens if the Java process tries to read `stats.json` before it has been completely generated or written out to the file system.

The relevant part from a typical stacktrace looks like this, but the section above `JreJsonFactory.parse` varies randomly.
```
Caused by: elemental.json.JsonException: Invalid object: expecting ":"
        at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:259)
        at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
        at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:192)
        at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:175)
        at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:231)
        at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
        at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:192)
        at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:175)
        at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:231)
        at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
        at elemental.json.impl.JreJsonFactory.parse(JreJsonFactory.java:64)
        at elemental.json.Json.parse(Json.java:53)
        at com.vaadin.flow.component.polymertemplate.BundleParser.parseJsonStatistics(BundleParser.java:105)
        at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.updateCache(NpmTemplateParser.java:189)
        at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getSourcesFromStats(NpmTemplateParser.java:179)
        at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:101)
        at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
        at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91)
        at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:107)
        at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:122)
```

Another typical error case is `elemental.json.JsonException: Invalid literal: ""`

**Comment by pleku** [comment]
@jouni can you provide details to reproduce this ?

**Comment by Legioth** [comment]
I guess we cannot reproduce this at all right now since we disabled live reloading.

**Comment by Legioth** [comment]
And if we reenable live reloading, then if my hypothesis holds true, we could reproduce this with any sufficiently big project.

**Comment by voodoohoo** [comment]
After upgrading our multi-module maven project from 14.4.2 to 14.5.3 we encountered the same error. I attached our log with the stacktrace.
[ion-web-hav.log](https://github.com/vaadin/flow/files/6357784/ion-web-hav.log)


Hope there will at least be a workaround, so that we can use the most recent LTS version.

Thanks,
Erik

**Comment by voodoohoo** [comment]
Some tests later:

14.4.3  works
14.4.8  works
14.4.9  works
14.4.10 does NOT work

I've also attached file target/classes/META-INF/VAADIN/config/stats.json from last build with 14.4.10
[stats.json.zip](https://github.com/vaadin/flow/files/6375840/stats.json.zip)
