### ISSUE TITLE
ConcurrentModificationException in Binder.doWriteIfValid() (v13 and v14 beta2)

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow#5772]
**Description:**  when using Binder in "setBean()" mode, calling binder.validate() on a BLUR event to trigger validation occasionally causes a ConcurrentModificationException
**Environment**: java-1.8.0-openjdk-1.8.0.181-1 on Windows 10
**Minimal reproducible example:** sorry, I have not found a systematic way to trigger.
**Stack trace** is as follows (all within Vaadin code)
```
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.vaadin.flow.data.binder.Binder.doWriteIfValid(Binder.java:1788)
	at com.vaadin.flow.data.binder.Binder.handleFieldValueChange(Binder.java:1426)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.handleFieldValueChange(Binder.java:1164)
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$new$f9b94f89$1(Binder.java:1002)
	at com.vaadin.flow.component.internal.AbstractFieldSupport.lambda$addValueChangeListener$828eca10$1(AbstractFieldSupport.java:96)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205)
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:194)
	at com.vaadin.flow.component.Component.fireEvent(Component.java:359)
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:390)
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:207)
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setModelValue(AbstractFieldSupport.java:167)
	at com.vaadin.flow.component.AbstractField.setModelValue(AbstractField.java:225)
	at com.vaadin.flow.component.AbstractSinglePropertyField.handlePropertyChange(AbstractSinglePropertyField.java:339)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$2(ElementPropertyMap.java:453)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.fireEvent(ElementPropertyMap.java:453)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.access$100(ElementPropertyMap.java:48)
	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap$PutResult.run(ElementPropertyMap.java:164)
	at com.vaadin.flow.server.communication.ServerRpcHandler.runMapSyncTask(ServerRpcHandler.java:365)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:359)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:359)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:302)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:87)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1522)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
```

**Comment by Legioth** [comment]
A `ConcurrentModificationException` that cannot be consistently reproduced an that only includes Vaadin code in the stacktrace is most often caused by application code that modifies some part of the Vaadin session state from a background thread without properly locking the session.

I'd recommend running your server with Java assertions enabled (`-ea` as a JVM parameter) since that will enable some additional sanity checks.

See http://vaadinsolutions.blogspot.com/2016/02/concurrentmodificationexception.html for more details.

**Comment by jflamy** [comment]
Thanks!  Not starting any threads in this case but was rather calling methods including setters on the underlying bean.  Closing the issue.
