### ISSUE TITLE
Templates not loaded in production mode

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#5795]
To reproduce, run e.g. beverage starter with the `production` profile:
`mvn -Pproduction install jetty:run`

The first request throws the following:

`java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'reviews-list' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
        at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:113)
        at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
        at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$null$23ee5b4f$1(TemplateInitializer.java:86)
        at com.vaadin.flow.internal.ReflectionCache.lambda$wrapValueProvider$d0062d93$1(ReflectionCache.java:84)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:101)
        at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:87)
        at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88)
        at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
        at com.vaadin.starter.beveragebuddy.ui.views.reviewslist.ReviewsList.<init>(ReviewsList.java:76)
        ... 53 more
`

The underlying reason seems to be that `stats.json` is not found in production mode.

**Comment by denis-anisimov** [comment]
`NpmTemplateParser::getSourcesFromTemplate`  tries to load the JS import via :
`InputStream content = getClass().getClassLoader().getResourceAsStream(url);`.

As I see in production mode the `reviews-list.js` is not copied anywhere during execution build in production mode. So it's inside `frontend` folder inside the project which is not in the classpath in any way. That's why it doesn't work.

**Comment by denis-anisimov** [comment]
This is a consequence of the current way of handling generated resource.
`jetty:run` is not the same as running a WAR file which is more close to `jetty:run-exploded`.

So if you run `mvn -Pproduction install jetty:run-exploded` then it works as expected.
`jetty:run` uses `/src/main/webapp` folder for static we resources.
But the resources which we need are in the `${project.build.directory}/${project.build.finalName}`  folder.
To be able to serve those resources properly one needs either set this folder as web app folder in the project config or use `jetty:run-exploded` .
This is quite similar to the way as it worked with production mode in bower mode.

But this situation should be changed by the fix for #5740.
As a result of this fix we won't need static resources anymore : they will be served by a servlet.
So there will be no such issue anymore.

I'm closing this as super-seeded by #5740.
