### ISSUE TITLE
Terminate early with a sensible error message if npm dependencies cannot be installed

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#5953]
If your Java class has a `@NpmDependency(value="something-not-found",version="1.0.0")` then running the project will result in 
```
[qtp453428216-21] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
====================================================================
Vaadin is running in DEBUG MODE.
Add productionMode=true to web.xml to disable debug features.
====================================================================
[qtp453428216-21] WARN com.vaadin.flow.server.frontend.FrontendUtils - Cannot get the stats file through webpack-dev-server. The webpack port is unavailable via VaadinContext.
[qtp453428216-21] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
java.lang.NullPointerException
	at elemental.json.impl.JreJsonFactory.parse(JreJsonFactory.java:60)
	at elemental.json.Json.parse(Json.java:53)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.appendNpmBundle(BootstrapHandler.java:854)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:835)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupDocumentHead(BootstrapHandler.java:718)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:521)
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:462)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:214)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:745)
```

There is also the real reason much higher up in the log but it is not what you see when starting from the bottom
```
[main] INFO dev-updater - Running `npm install` ...
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/a-game-card - Not found
npm ERR! 404 
npm ERR! 404  'a-game-card@1.0.0' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404 It was specified as a dependency of '@vaadin/flow-deps'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2019-06-20T12_56_47_276Z-debug.log
[main] ERROR dev-updater - >>> Dependency ERROR. Check that all required dependencies are deployed in npm repositories.
[main] INFO dev-updater - 

  Failed to find the following imports in the `node_modules` tree:
      ➜ @vaadin/vaadin-ordered-layout/src/vaadin-vertical-layout.js
       ➜ @vaadin/vaadin-lumo-styles/spacing.js
       ➜ @vaadin/vaadin-ordered-layout/src/vaadin-horizontal-layout.js
       ➜ game-card/game-card-deck.js
       ➜ @vaadin/vaadin-lumo-styles/icons.js
       ➜ @vaadin/vaadin-button/src/vaadin-button.js
       ➜ game-card/game-card.js
       ➜ @vaadin/vaadin-lumo-styles/typography.js
       ➜ @vaadin/vaadin-lumo-styles/style.js
       ➜ game-card/game-card-pile.js
       ➜ @vaadin/vaadin-lumo-styles/color.js
       ➜ @vaadin/vaadin-lumo-styles/sizing.js
       ➜ @vaadin/vaadin-checkbox/src/vaadin-checkbox.js
  If the build fails, check that npm packages are installed.

[main] INFO dev-updater - Updated .../Solitaire/target/frontend/generated-flow-imports.js
[main] WARN  - Instance not created because cannot execute '.../Solitaire/node_modules/webpack-dev-server/bin/webpack-dev-server.js'. Did you run `npm install`
```

There does not seem to be any point in continuing if `npm install` fails. I would have found the issue much sooner if the `npm install` error was the last output.

**Comment by mehdi-vaadin** [comment]
### Acceptance criteria
- Execution should stop when it encounters an error `npm install`.

**Comment by mehdi-vaadin** [comment]
It could be fixed in `TaskRunNpmInstall` class.
