### ISSUE TITLE
NPM Check error when running manven in Eclipse

### ISSUE THREAD

**Issue by neerup** [vaadin/flow#5988]
When building with maven in Eclipse I get the following Warning
macOS latest
Eclipse 2019-06 (4.12.0)
NPM 6.4.1

`[INFO] --- vaadin-maven-plugin:14.0.0.rc2:prepare-frontend (default) @ a4web-flow ---
[WARNING] Error checking if npm is new enough
com.vaadin.flow.server.frontend.FrontendUtils$UnknownVersionException: Unable to detect version of npm.Using command /usr/local/bin/npm --version
	at com.vaadin.flow.server.frontend.FrontendUtils.getVersion(FrontendUtils.java:498)
	at com.vaadin.flow.server.frontend.FrontendUtils.validateNodeAndNpmVersion(FrontendUtils.java:397)
	at com.vaadin.flow.plugin.maven.PrepareFrontendMojo.execute(PrepareFrontendMojo.java:146)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)`

**Comment by Artur-** [comment]
I have run into the same thing, the error output was that it could not find `node`. Is there some kind of PATH fix done for Eclipse which is not applied to the version checker?

**Comment by bedoro** [comment]
There still seems to be an issue with this. While starting a project using Flow 2.0.2, I get the error 

```
Unable to detect version of npm. Reported version Aktive Codepage: 1252.
6.9.0 could not be parsed`
```

Because of a company policy, the codepages of our Windows machine are set to 1252. When I run npm -v, the output actually looks like this:
```
Aktive Codepage: 1252
6.9.0
```

It seems like the first line that is output is taken as the npm version, which obviously won't work in this case.
