### ISSUE TITLE
HotswapAgent Vaadin plugin does not support V13+

### ISSUE THREAD

**Issue by tepi** [vaadin/flow#6212]
Vaadin version: 14.0.0.rc9 (latest available)
HotswapAgent version: 1.3.0.SNAPSHOT (latest available)

Running this combination produces an exception at startup:

`HOTSWAP AGENT: 15:20:17.502 INFO (org.hotswap.agent.config.PluginRegistry) - Plugin 'org.hotswap.agent.plugin.vaadin.VaadinPlugin' initialized in ClassLoader 'sun.misc.Launcher$AppClassLoader@18b4aac2'.
java.lang.ClassNotFoundException: com.vaadin.flow.server.startup.RouteRegistry
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at org.hotswap.agent.plugin.vaadin.VaadinPlugin.resolveClass(VaadinPlugin.java:179)
    at org.hotswap.agent.plugin.vaadin.VaadinPlugin.getRouteRegistryClass(VaadinPlugin.java:89)
    at org.hotswap.agent.plugin.vaadin.VaadinPlugin.registerServlet(VaadinPlugin.java:77)
`

and another exception when classes are swapped:

`HOTSWAP AGENT: 15:21:25.701 ERROR (org.hotswap.agent.annotation.handler.WatchEventCommand) - InvocationTargetException in method addNewRoute on plugin org.hotswap.agent.plugin.vaadin.VaadinPlugin
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:172)
    at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:80)
    at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:25)
Caused by: java.lang.NullPointerException
    at org.hotswap.agent.plugin.vaadin.VaadinPlugin.getRouteRegistry(VaadinPlugin.java:96)
    at org.hotswap.agent.plugin.vaadin.VaadinPlugin.ensureInRouter(VaadinPlugin.java:125)
    at org.hotswap.agent.plugin.vaadin.VaadinPlugin.addNewRoute(VaadinPlugin.java:119)
`

This has supposedly been fixed in the HotswapAgent Vaadin plugin code, but no release with that code is available right now. So the only option to get it functioning properly with routes seems to be building your own build of HotswapAgent jar.

**Comment by mstahv** [comment]
The patched version can be downloaded from: https://virit.in/v13compatible-hotswapagent/hotswap-agent.jar If you replace the that in your dcevm (in mac file in dcevm-11.0.1+8.jdk/Contents/Home/lib/hotswap/hotswap-agent.jar ), things should work at least better. 

The drawback currently is that new components that are not previously used are not picked up by the npm build to the module -> client side dies.

**Comment by mehdi-vaadin** [comment]
@mstahv What's the latest status of this?

**Comment by pleku** [comment]
Closed and further fixes to be done as part of #7174
