### ISSUE TITLE
vaadin-maven-plugin fails on build-frontend

### ISSUE THREAD

**Issue by raphw** [vaadin/flow#6279]
Building a simple Vaadin 14.0.0 project, my build fails with:

> 21 verbose stack TypeError: Cannot read property 'resolve' of undefined
> 21 verbose stack     at regFetch (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/npm-registry-fetch/index.js:76:23)
> 21 verbose stack     at fetchPackument (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:42:10)
> 21 verbose stack     at packument (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/lib/fetchers/registry/packument.js:20:10)
> 21 verbose stack     at getManifest (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:22:10)
> 21 verbose stack     at manifest (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:13:10)
> 21 verbose stack     at Object.manifest (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/lib/fetchers/registry/index.js:17:12)
> 21 verbose stack     at Object.Fetcher#manifest [as manifest] (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/node_modules/protoduck/node_modules/genfun/lib/genfun.js:15:38)
> 21 verbose stack     at manifest (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/lib/fetch.js:23:18)
> 21 verbose stack     at pinflight (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/pacote/manifest.js:24:12)
> 21 verbose stack     at /home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/promise-inflight/inflight.js:29:24
> 21 verbose stack     at Promise._execute (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/bluebird/js/release/debuggability.js:313:9)
> 21 verbose stack     at Promise._resolveFromExecutor (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/bluebird/js/release/promise.js:483:18)
> 21 verbose stack     at new Promise (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/bluebird/js/release/promise.js:79:10)
> 21 verbose stack     at _inflight (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/promise-inflight/inflight.js:28:25)
> 21 verbose stack     at /home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/promise-inflight/inflight.js:22:14
> 21 verbose stack     at tryCatcher (/home/k89074/experiment/admin/admin-main/node/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)

during the `build-frontend` phase. I have tried with installing node v10.16.3 and the latest release.

My *package.json* file looks fairly simple, too:

```
{
  "name": "@vaadin/flow-deps",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "dependencies": {
    "@vaadin/vaadin-grid": "5.4.6",
    "@vaadin/vaadin-icons": "4.3.1",
    "@vaadin/vaadin-split-layout": "4.1.1",
    "@vaadin/vaadin-combo-box": "5.0.6",
    "@vaadin/vaadin-core-shrinkwrap": "14.0.0",
    "@vaadin/vaadin-upload": "4.2.2",
    "@vaadin/vaadin-dialog": "2.2.1",
    "@vaadin/vaadin-select": "2.1.5",
    "@vaadin/vaadin-app-layout": "2.0.2",
    "@vaadin/vaadin-item": "2.1.0",
    "@vaadin/vaadin-notification": "1.4.0",
    "@vaadin/vaadin-progress-bar": "1.1.2",
    "@vaadin/vaadin-ordered-layout": "1.1.0",
    "@vaadin/vaadin-login": "1.0.1",
    "@vaadin/vaadin-button": "2.2.1",
    "@vaadin/vaadin-date-picker": "4.0.3",
    "@vaadin/vaadin-text-field": "2.4.8",
    "@vaadin/vaadin-menu-bar": "1.0.3",
    "@vaadin/vaadin-custom-field": "1.0.6",
    "@vaadin/vaadin-form-layout": "2.1.4",
    "@vaadin/vaadin-accordion": "1.0.1",
    "@polymer/iron-list": "3.0.2",
    "@vaadin/vaadin-list-box": "1.1.1",
    "@vaadin/vaadin-details": "1.0.1",
    "@vaadin/vaadin-checkbox": "2.2.10",
    "@polymer/iron-icon": "3.0.1",
    "@vaadin/vaadin-time-picker": "2.0.2",
    "@vaadin/vaadin-context-menu": "4.3.12",
    "@vaadin/vaadin-tabs": "3.0.4",
    "@vaadin/vaadin-radio-button": "1.2.3",
    "@vaadin/vaadin-lumo-styles": "1.5.0",
    "@vaadin/vaadin-material-styles": "1.2.3"
  }
}
```

I installed node using the suggested way by e.g.

    mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.8.1"

**Comment by caalador** [comment]
Sounds like there is some broken dependency or a miss match with versions.

But as I haven't seen this exception before, I would suggest removing folders `{project}/node` and `{project}/node_modules` running the node install command again. e.g.  `mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.8.1"` and then trying again.

**Comment by raphw** [comment]
I do now build the project in its own image where I have the latest LTS of node and npm installed. The build looks much better now but it still fails with:

```
[2019-08-19T09:43:55.479Z] > core-js@2.6.9 postinstall /var/jenkins_home/workspace/SKO_admin-experiment_master/admin-main/node_modules/core-js
[2019-08-19T09:43:55.479Z] > node scripts/postinstall || echo "ignore"
[2019-08-19T09:43:55.479Z] 
[2019-08-19T09:43:56.043Z] npm WARN no-name@ No description
[2019-08-19T09:43:56.043Z] npm WARN no-name@ No repository field.
[2019-08-19T09:43:56.043Z] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
[2019-08-19T09:43:56.043Z] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[2019-08-19T09:43:56.043Z] 
[2019-08-19T09:43:56.043Z] added 816 packages from 391 contributors in 12.092s
[2019-08-19T09:43:56.043Z] [INFO] package.json updated and npm dependencies installed. 
[2019-08-19T09:43:56.043Z] [INFO] Copying frontend resources from jar files ...
[2019-08-19T09:43:56.043Z] [INFO] Visited 200 jar files. Took 69 ms.
[2019-08-19T09:43:56.043Z] [WARNING] Use the './' prefix for files in JAR files: 'flow-component-renderer.js', please update your component.
[2019-08-19T09:43:56.043Z] [INFO] 
[2019-08-19T09:43:56.043Z] 
[2019-08-19T09:43:56.043Z]   Failed to find the following imports in the `node_modules` tree:
[2019-08-19T09:43:56.043Z]       - @vaadin/flow-frontend/highlight/highlight.pack.js
[2019-08-19T09:43:56.043Z]   If the build fails, check that npm packages are installed.
[2019-08-19T09:43:56.043Z] 
[2019-08-19T09:43:56.043Z] 
[2019-08-19T09:43:56.043Z] [INFO] Updated /var/jenkins_home/workspace/SKO_admin-experiment_master/admin-main/target/frontend/generated-flow-imports.js
[2019-08-19T09:43:56.043Z] [INFO] Running webpack ...
[2019-08-19T09:44:14.088Z] Hash: 0d79a3501abb4a59dfc0
[2019-08-19T09:44:14.088Z] Version: webpack 4.30.0
[2019-08-19T09:44:14.088Z] Time: 15502ms
[2019-08-19T09:44:14.088Z] Built at: 08/19/2019 11:44:12 AM
[2019-08-19T09:44:14.088Z]  2 assets
[2019-08-19T09:44:14.088Z] Entrypoint bundle = build/vaadin-bundle-72fd07785eb2783c1ffc.cache.js
[2019-08-19T09:44:14.088Z] Entrypoint bundle.es5 = build/vaadin-bundle.es5-90ebd38a8865d32f085a.cache.js
[2019-08-19T09:44:14.088Z] [31] ../target/frontend/generated-flow-imports.js?babel-target=es5 + 211 modules 1.95 MiB {1} [built]
[2019-08-19T09:44:14.088Z]      | ../target/frontend/generated-flow-imports.js?babel-target=es5 2.45 KiB [built]
[2019-08-19T09:44:14.088Z]      |     + 211 hidden modules
[2019-08-19T09:44:14.088Z] [32] ../target/frontend/generated-flow-imports.js?babel-target=es6 + 210 modules 1.62 MiB {0} [built]
[2019-08-19T09:44:14.088Z]      | ../target/frontend/generated-flow-imports.js?babel-target=es6 2.45 KiB [built]
[2019-08-19T09:44:14.088Z]      |     + 210 hidden modules
[2019-08-19T09:44:14.088Z]     + 31 hidden modules
[2019-08-19T09:44:14.088Z] 
[2019-08-19T09:44:14.088Z] ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es5
[2019-08-19T09:44:14.088Z] Module not found: Error: Can't resolve '@vaadin/flow-frontend/highlight/highlight.pack.js?babel-target=es5' in '/var/jenkins_home/workspace/SKO_admin-experiment_master/admin-main/target/frontend'
[2019-08-19T09:44:14.088Z]  @ ../target/frontend/generated-flow-imports.js?babel-target=es5 40:0-59
[2019-08-19T09:44:14.088Z] 
[2019-08-19T09:44:14.088Z] ERROR in ../target/frontend/generated-flow-imports.js?babel-target=es6
[2019-08-19T09:44:14.088Z] Module not found: Error: Can't resolve '@vaadin/flow-frontend/highlight/highlight.pack.js?babel-target=es6' in '/var/jenkins_home/workspace/SKO_admin-experiment_master/admin-main/target/frontend'
[2019-08-19T09:44:14.088Z]  @ ../target/frontend/generated-flow-imports.js?babel-target=es6 40:0-59
```

Do I need some npm libraries globally for the build to work? If so, is there a list of libraries that need to be installed?

I am also wondering about the warning message about the file not starting with ./ - is this something I can influence?

**Comment by caalador** [comment]
How is `highlight/highlight.pack.js` annotated? 
Also is it in META-INF/resources/frontend in a jar package or in the root/ui project?

**Comment by raphw** [comment]
It is basically just a direct plain file copy of https://highlightjs.org - It is included in a component by the `@JavaScript` annotation. The project is based on the Vaadin-Spring Boot-Starter.

**Comment by caalador** [comment]
Try adding them to `{project_root}/frontend/hightlight/*` and having instead of `frontend://` just `./`

**Comment by raphw** [comment]
This did not help but I did now work around this by adding the import dynamically:

```java
UI.getCurrent().getPage().addJavaScript("frontend:///highlight/highlight.pack.js");
```

**Comment by caalador** [comment]
In V14 and npm mode, `@JavaScript("file.js")` is searched for from `<project root>/frontend/file.js`, but `@StyleSheet("file.css")` is found from `src/main/webapp/frontend/file.css` .

This is due to the fact that `@StyleSheet` and `@JavaScript` are Bower mode concepts that still kind-of work in an npm project. Also the `frontend://` prefix is also for the compatibility mode handling and will give the wrong value when running in production mode and should probably now be referenced as `addJavaScript("context://frontend/highlight/highlight.pack.js")`.

**Comment by heruan** [comment]
@caalador I'm not sure if it's the same issue, but I'm affected by the same error running `build-frontend` when a component is annotated with `@JsModule("./my-component.js")` and `./my-component.js` is in the `META-INF/resources/frontend` folder of a JAR which the project depends from. Does the plugin look also in dependencies `META-INF/resources/frontend` folders?

**Comment by caalador** [comment]
@heruan Any "**/*.js", "**/*.css" files should be copied from the `META-INF/resources/frontend` folder to `node_modules/@vaadin/flow-frontend` .
But if it's during dev mode server start then you should check for a line `[INFO] Visited 10 jar files. Took 69 ms.`  to see that it visited jar files for copying as it sounds like the file is not found. 
also if this is using 14.0.0 does the jar or path contain special characters like space?

To verify that the file should be found you could try running `mvn vaadin:build-frontend` and see if the file gets copied in that case as then we get a better set for the jar dependencies.

**Comment by heruan** [comment]
Thanks @caalador! I must have had a dirty workspace, since starting from scratch it works. Seems like `mvn clean` isn't enough to clean things up! BTW you say the plugin copies any `*.js` and `*.css` files, is this configurable to copy also `*.ts` files for example?

**Comment by caalador** [comment]
At the moment it's not possible to add copied files inclusions due to the problem that they would need to be available both in maven and runtime (with or without maven), but adding .ts files would not be a problem as the list is just 
```
    private static final String[] WILDCARD_INCLUSIONS = new String[] {
            "**/*.js", "**/*.css" };
```
in `TaskCopyFrontendFiles`.

**Comment by ujoni** [comment]
@raphw has the latest comments helped you overcome the issue you were having, or are you still working with the workaround you have?

**Comment by raphw** [comment]
We discovered that an icon set was not available after the 14 update which was imported via `@HtmlImport` but we add it now using `UI.getCurrent().getPage().addHtml(...)` and it works again.

We have had a row of issues after updating and unfortunately only discovered them after deployment but the project does now build in our current setup.

**Comment by raphw** [comment]
Too much said, after updating to Vaadin 14.0.2 our build now fails with:

> [2019-09-03T12:28:31.707Z] ERROR in chunk bundle [entry]
> [2019-09-03T12:28:31.707Z] build/vaadin-bundle-e2482018adba03cc54af.cache.js
> [2019-09-03T12:28:31.707Z] /var/jenkins_home/workspace/SPAP_admin_fix/admin-main/node_modules/babel-loader/lib/index.js??ref--4-0!/var/jenkins_home/workspace/SPAP_admin_fix/admin-main/target/frontend/generated-flow-imports.js?babel-target=es6 939b5ff0c8b5d2d52a671f90408fac5a
> [2019-09-03T12:28:31.707Z] Unexpected token (7:47)
> [2019-09-03T12:28:31.707Z] | 
> [2019-09-03T12:28:31.707Z] | {
> [2019-09-03T12:28:31.707Z] |   class GridFlowSelectionColumnElement extends !(function webpackMissingModule() { var e = new Error("Cannot find module '@vaadin/vaadin-grid/src/vaadin-grid-column.js?babel-target=es6'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()) {
> [2019-09-03T12:28:31.707Z] |     static get template() {
> [2019-09-03T12:28:31.707Z] |       return __WEBPACK_MODULE_REFERENCE__47_68746d6c__`

**Comment by pleku** [comment]
>We discovered that an icon set was not available after the 14 update which was imported via @HtmlImport but we add it now using UI.getCurrent().getPage().addHtml(...) and it works again.

Just wanted to point that `@HtmlImport` is not supported in Vaadin 14 when running the _npm mode_, because it corresponds to the deprecated html imports, which "lost" the battle against JS modules. So you should convert that html file to a JS module instead and import it with `@JsModule`. ([instructions here](https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html#3-convert-polymer-2-to-polymer-3))

>Too much said, after updating to Vaadin 14.0.2 our build now fails with:

That looks like an error in the compiled output. I think we need some further details about how: which phase does this error happen in and is it happening consistently, so we could try to reproduce it

**Comment by raphw** [comment]
I migrated these bits and now the build fails with:

> [INFO] Copying frontend resources from jar files ...
> [INFO] Visited 214 jar files. Took 111 ms.
> [WARNING] Use the './' prefix for files in JAR files: 'flow-component-renderer.js', please update your component.

I have no idea what this means and to be honest, this update has been really frustrating.

**Comment by pleku** [comment]
>Quite honestly, this was anything but a smooth upgrading experience. The @HtmlImport is not deprecated and its javadoc does not mention the consequences of its use. Worse: in the debug mode that we use for testing things still seem to work but some stylings missed silently from the production environment. I understand that you have to follow the trends of frontend development but for enterprise environments, this makes things really difficult. I wish that the Maven build plugin would at least warn me of such misuse. Also, this will cause problems for years to come as any Google search for how to do certain things in Vaadin points to outdated information.

Since 14 supports the "old mode" also (but not at the same time as the new mode), the decision was not deprecate those. An unfortunately we cannot throw errors when `@HtmlImport` is used in the new mode as any web component Java integration that supports "both modes", has both the new `@JsModule` and the old `@HtmlImport` on the class, the latter is just silently ignored in npm mode.

**Comment by pleku** [comment]
.>Somehow it seems that the frontend resources are not copied correctly on CI or that I have some outdated local state that is not fixed with mvn clean. If I make copies of all resource files and place them in the META-INF/resources/frontend folder of the main module (that executes the Vaadin plugin and bundles the deployed jar), it seems to work. Updating to 14.0.3 still fails the CI with:

>I have no idea what this implies and since I cannot reproduce it locally, I am rather stuck on this and will rather stick with 14.0.0 for now.

I think you have the right idea, there is some weird caching going on for the CI and

**Comment by Legioth** [comment]
> we cannot throw errors when `@HtmlImport` is used in the new mode as any web component Java integration that supports "both modes", has both the new `@JsModule` and the old `@HtmlImport` on the class

What about throwing for any component class that only has `@HtmlImport`, but not a single `@JsModule` annotation?

**Comment by Legioth** [comment]
The fate of `@HtmlImport` in npm mode projects can be discussed in https://github.com/vaadin/flow/issues/6401 so that this ticket can focus on the other build issues reported here.

**Comment by pleku** [comment]
Just going back to an old comment:
>We discovered that an icon set was not available after the 14 update which was imported via @HtmlImport but we add it now using UI.getCurrent().getPage().addHtml(...) and it works again.

There has been code for two months that throws if someone tries to use `addHtmlImport(...)` in `Page` when in npm mode. If this has not happened, then the project has been running in compatibility mode and then it should have not worked at all ... We will try to make it more obvious to everyone that `@HtmlImport` is not supposed to be used in npm mode in #6401.

But for this issue with the build failing in the CI server, we don't really have any good idea where to get started. We suspect there is some caching error, and the CI should be setup to do a "clean checkup" of everything, meaning that if there are any local changes (like old node_modules), those should be deleted. We've had a similar report in build failing in Jenkins and `svn revert & svn update` fixed the issue. Unfortunately we don't really have a good direction to look for bugs since we cannot replicate the issue. If it happens consistently on your CI server, we could try to take a look at the packaged `node_modules`, `target` and configuration files for the project to try to find what is causing the error.

**Comment by mehdi-vaadin** [comment]
@raphw Would you please try `14.0.8` and see it still fails?

**Comment by mehdi-vaadin** [comment]
@raphw note that after upgrading Vaadin version in `pom.xml`, you should delete `package-lock.json` and run `mvn clean` before running your project.

**Comment by raphw** [comment]
Sorry for the delay, the problem seems to have disappeared with 14.0.10, I did not manage to test it before.
