### ISSUE TITLE
Fail on migrate to P3

### ISSUE THREAD

**Issue by adexerivera** [vaadin/flow#6333]
Hi

I'm lost, because i tried a lot of ways to migrate from p2 to p3, but i not get it. My project is spring boot on war package, and this is my project structure.

![](https://vaadin.com/attachment/caabc3ac-8e42-4ba5-8c2a-595ba63d719c/ProjectDirectory.PNG)

Commands that execute:

* mvn clean
* mvn package -DskipTests
* mvn vaadin:migrate-to-p3 -DkeepOriginal=true

But when execute mvn vaadin:migrate-to-p3 fails with this information.

![](https://vaadin.com/attachment/4abf45a5-5911-4977-978d-130ecc18c430/MigrateToP3Error.PNG)

- Versions:
    - Vaadin / Flow version: 14.0.0
    - Java version: 1.8.0_221
    - OS version: Windows 10

Anyone can help me

**Comment by denis-anisimov** [comment]
Hi,
migration tool currently is made to support WAR projects by default ( and default settings).
Spring boot project has another structure than WAR : it has resources in a different folder (by default it's `src/main/webapp`).

There are parameters which you may set and get it working:
https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/v14-migration/migration-tool.asciidoc#goal-parameters

`resources` : should point to your `META-INF/resources` folder.
`frontendDirectory` should be the `META-INF/resources/frontend` I think if you want the migrated files there.

The default values don't fit to your case and you can see them in the link provided above.
There is already a ticket to make default values working in JAR projects (and Spring boot projects) automatically.
But for now there is already a way to do it via the configuration.

**Comment by adexerivera** [comment]
It doesn't work for me either, but I don't know if I'm doing something wrong. According to the migration guide of vaadin

* We have to move the webapp [files](https://vaadin.com/docs/v14/flow/v14-migration/v14-migration-guide.html#move-contents-of-src-main-webapp-frontend).
* And then use this migration tool.

But from what I understand this migration tool is responsible for searching the `resources `directory and copying it to the `frontendDirectory`, or am I wrong?

I need to migrate several projects but I have been two weeks and I have not been able to do it.

I have followed the steps in the migration guide and cannot get the migration tool to work. @denis-anisimov  could you help me with the recommended steps?

Because executing this, I have not generated the migrated files either.

`mvn vaadin:migrate-to-p3 -Dresources='${project.basedir}/src/main/resources/META-INF/resources'`
or
`mvn vaadin:migrate-to-p3 -Dresources='${project.basedir}/src/main/resources/META-INF/resources' -DfrontendDirectory='${project.basedir}/src/main/resources/META-INF/resources/frontend'`

Thanks

**Comment by denis-anisimov** [comment]
Please refer to :

https://github.com/vaadin/flow-and-components-documentation/blob/master/documentation/v14-migration/migration-tool.asciidoc#goal-parameters

`-Dresources` can't be used.

From the link above: 

```
It’s configured in the pom file via <resources> parent element and <resource> child elements inside it.
```

It means that you should use
```
<resources>
   <resources>${project.basedir}/src/main/resources/META-INF/resources</resources>
</resources>
```
in your `configuration` tag inside the plugin declaration in your pom.xml file.

And the `frontendDirectory` is configured in a similar way via `frontendDirectory` tag inside the  `configuration` tag.

**Comment by adexerivera** [comment]
Thank you, now migrate some files but not all, take a look on this image and the command results.

![Result](https://user-images.githubusercontent.com/1585009/63761358-ef8c5580-c8b8-11e9-9047-347aac89ca68.PNG)

Command result:

```
$ mvn vaadin:migrate-to-p3
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.itccanarias.dcct:minorcontracts:war:1.0
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.ws:jaxws-rt:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/jaxws-rt.jar will be unresolvable by dependent projects @ line 136, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.ws:jaxws-tools:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/jaxws-tools.jar will be unresolvable by dependent projects @ line 144, column 25
[WARNING] 'dependencies.dependency.systemPath' for javax.jws:jsr181-api:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/jsr181-api.jar will be unresolvable by dependent projects @ line 152, column 25
[WARNING] 'dependencies.dependency.systemPath' for javax.annotation:jsr250-api:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/jsr250-api.jar will be unresolvable by dependent projects @ line 160, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.wss.tools:keyexport:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/keyexport.jar will be unresolvable by dependent projects @ line 168, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.wss.tools:pkcs12import:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/pkcs12import.jar will be unresolvable by dependent projects @ line 176, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.rpc.plugins:security-plugin:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/security-plugin.jar will be unresolvable by dependent projects @ line 184, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.wss:wss-provider-update:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/wss-provider-update.jar will be unresolvable by dependent projects @ line 192, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.ws:xws-security_jaxrpc:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/xws-security_jaxrpc.jar will be unresolvable by dependent projects @ line 200, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.sun.xml.ws:xws-security:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/xws-security.jar will be unresolvable by dependent projects @ line 208, column 25
[WARNING] 'dependencies.dependency.systemPath' for javax.xml.ws:jaxws-api:jar should not point at files within the project directory, ${project.basedir}/lib/xws-security/jaxws-api.jar will be unresolvable by dependent projects @ line 216, column 25
[WARNING] 'dependencies.dependency.systemPath' for codice:codice-place-ext:jar should not point at files within the project directory, ${project.basedir}/lib/codice_place_ext-1.1.jar will be unresolvable by dependent projects @ line 232, column 25
[WARNING] 'dependencies.dependency.systemPath' for codice:codice:jar should not point at files within the project directory, ${project.basedir}/lib/codice-2.04.jar will be unresolvable by dependent projects @ line 240, column 25
[WARNING] 'dependencies.dependency.systemPath' for com.microsoft.sqlserver:sqljdbc4:jar should not point at files within the project directory, ${project.basedir}/lib/sqljdbc/jre8/sqljdbc42.jar will be unresolvable by dependent projects @ line 250, column 25
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.springframework:spring-context-support:jar -> version (?) vs 5.1.1.RELEASE @ line 312, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ----------------< org.itccanarias.dcct:minorcontracts >-----------------
[INFO] Building Minor Contracts 1.0
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- vaadin-maven-plugin:14.0.0:migrate-to-p3 (default-cli) @ minorcontracts ---
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN no-name@ No repository field.

+ polymer-modulizer@0.4.3
updated 1 package and audited 3008 packages in 24.007s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
bower                     invalid-meta for:D:\Projects\minor-contracts\target\migration\bower.json
bower                     invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .html files: ["src/login-view.html","src/main-view.html","src/pagination-grid.html","styles/shared-styles.html","offline-page.html"]
bower polymer#2.8.0             cached https://github.com/Polymer/polymer.git#2.8.0
bower polymer#2.8.0           validate 2.8.0 against https://github.com/Polymer/polymer.git#2.8.0
bower vaadin-icons#*            cached https://github.com/vaadin/vaadin-icons.git#4.3.1
bower vaadin-icons#*          validate 4.3.1 against https://github.com/vaadin/vaadin-icons.git#*
bower iron-form#*               cached https://github.com/PolymerElements/iron-form.git#3.0.1
bower iron-form#*             validate 3.0.1 against https://github.com/PolymerElements/iron-form.git#*
bower polymer#^2.0.0            cached https://github.com/Polymer/polymer.git#2.8.0
bower polymer#^2.0.0          validate 2.8.0 against https://github.com/Polymer/polymer.git#^2.0.0
bower iron-icon#*               cached https://github.com/PolymerElements/iron-icon.git#3.0.1
bower iron-icon#*             validate 3.0.1 against https://github.com/PolymerElements/iron-icon.git#*
bower vaadin-button#*           cached https://github.com/vaadin/vaadin-button.git#2.2.1
bower vaadin-button#*         validate 2.2.1 against https://github.com/vaadin/vaadin-button.git#*
bower app-layout#*              cached https://github.com/PolymerElements/app-layout.git#3.0.2
bower app-layout#*            validate 3.0.2 against https://github.com/PolymerElements/app-layout.git#*
bower vaadin-text-field#*       cached https://github.com/vaadin/vaadin-text-field.git#2.4.11
bower vaadin-text-field#*     validate 2.4.11 against https://github.com/vaadin/vaadin-text-field.git#*
bower vaadin-item#*             cached https://github.com/vaadin/vaadin-item.git#2.1.1
bower vaadin-item#*           validate 2.1.1 against https://github.com/vaadin/vaadin-item.git#*
bower iron-icon#^2.0.0          cached https://github.com/PolymerElements/iron-icon.git#2.1.0
bower iron-icon#^2.0.0        validate 2.1.0 against https://github.com/PolymerElements/iron-icon.git#^2.0.0
bower vaadin-control-state-mixin#^2.1.1           cached https://github.com/vaadin/vaadin-control-state-mixin.git#2.1.3
bower vaadin-control-state-mixin#^2.1.1         validate 2.1.3 against https://github.com/vaadin/vaadin-control-state-mixin.git#^2.1.1
bower vaadin-element-mixin#^2.0.0                 cached https://github.com/vaadin/vaadin-element-mixin.git#2.1.3
bower vaadin-element-mixin#^2.0.0               validate 2.1.3 against https://github.com/vaadin/vaadin-element-mixin.git#^2.0.0
bower vaadin-material-styles#^1.2.0               cached https://github.com/vaadin/vaadin-material-styles.git#1.2.3
bower vaadin-material-styles#^1.2.0             validate 1.2.3 against https://github.com/vaadin/vaadin-material-styles.git#^1.2.0
bower vaadin-themable-mixin#^1.2.1                cached https://github.com/vaadin/vaadin-themable-mixin.git#1.4.4
bower vaadin-themable-mixin#^1.2.1              validate 1.4.4 against https://github.com/vaadin/vaadin-themable-mixin.git#^1.2.1
bower vaadin-lumo-styles#^1.3.3                   cached https://github.com/vaadin/vaadin-lumo-styles.git#1.5.0
bower vaadin-lumo-styles#^1.3.3                 validate 1.5.0 against https://github.com/vaadin/vaadin-lumo-styles.git#^1.3.3
bower iron-iconset-svg#^2.0.0                     cached https://github.com/PolymerElements/iron-iconset-svg.git#2.2.1
bower iron-iconset-svg#^2.0.0                   validate 2.2.1 against https://github.com/PolymerElements/iron-iconset-svg.git#^2.0.0
bower iron-meta#1 - 2                             cached https://github.com/PolymerElements/iron-meta.git#2.1.1
bower iron-meta#1 - 2                           validate 2.1.1 against https://github.com/PolymerElements/iron-meta.git#1 - 2
bower iron-flex-layout#1 - 2                      cached https://github.com/PolymerElements/iron-flex-layout.git#2.0.3
bower iron-flex-layout#1 - 2                    validate 2.0.3 against https://github.com/PolymerElements/iron-flex-layout.git#1 - 2
bower shadycss#^v1.1.0                            cached https://github.com/webcomponents/shadycss.git#1.9.1
bower shadycss#^v1.1.0                          validate 1.9.1 against https://github.com/webcomponents/shadycss.git#^v1.1.0
bower webcomponentsjs#^v1.1.0                     cached https://github.com/webcomponents/webcomponentsjs.git#1.3.3
bower webcomponentsjs#^v1.1.0                   validate 1.3.3 against https://github.com/webcomponents/webcomponentsjs.git#^v1.1.0
bower vaadin-usage-statistics#^2.0.2              cached https://github.com/vaadin/vaadin-usage-statistics.git#2.0.9
bower vaadin-usage-statistics#^2.0.2            validate 2.0.9 against https://github.com/vaadin/vaadin-usage-statistics.git#^2.0.2
bower vaadin-development-mode-detector#^2.0.0     cached https://github.com/vaadin/vaadin-development-mode-detector.git#2.0.4
bower vaadin-development-mode-detector#^2.0.0   validate 2.0.4 against https://github.com/vaadin/vaadin-development-mode-detector.git#^2.0.0

Please note that,
    vaadin-icons#4.3.1 depends on iron-icon#^2.0.0 which resolved to iron-icon#2.1.0
    vaadin-lumo-styles#1.5.0 depends on iron-icon#^2.0.1 which resolved to iron-icon#2.1.0
    none depends on iron-icon#^3.0.1 which resolved to iron-icon#3.0.1
Resort to using iron-icon# which resolved to iron-icon#3.0.1
Code incompatibilities may occur.

bower iron-icon#^3.0.1                           install iron-icon#3.0.1
bower iron-form#^3.0.1                           install iron-form#3.0.1
bower vaadin-icons#^4.3.1                        install vaadin-icons#4.3.1
bower vaadin-button#^2.2.1                       install vaadin-button#2.2.1
bower polymer#2.8.0                              install polymer#2.8.0
bower app-layout#^3.0.2                          install app-layout#3.0.2
bower vaadin-control-state-mixin#^2.1.1          install vaadin-control-state-mixin#2.1.3
bower vaadin-item#^2.1.1                         install vaadin-item#2.1.1
bower vaadin-text-field#^2.4.11                  install vaadin-text-field#2.4.11
bower vaadin-element-mixin#^2.0.0                install vaadin-element-mixin#2.1.3
bower vaadin-material-styles#^1.2.0              install vaadin-material-styles#1.2.3
bower vaadin-themable-mixin#^1.2.1               install vaadin-themable-mixin#1.4.4
bower vaadin-lumo-styles#^1.3.3                  install vaadin-lumo-styles#1.5.0
bower iron-iconset-svg#^2.0.0                    install iron-iconset-svg#2.2.1
bower iron-meta#1 - 2                            install iron-meta#2.1.1
bower iron-flex-layout#1 - 2                     install iron-flex-layout#2.0.3
bower shadycss#^v1.1.0                           install shadycss#1.9.1
bower vaadin-usage-statistics#^2.0.2             install vaadin-usage-statistics#2.0.9
bower vaadin-development-mode-detector#^2.0.0    install vaadin-development-mode-detector#2.0.4
bower webcomponentsjs#^v1.1.0                    install webcomponentsjs#1.3.3

iron-icon#3.0.1 bower_components\iron-icon

iron-form#3.0.1 bower_components\iron-form

vaadin-icons#4.3.1 bower_components\vaadin-icons
├── iron-icon#3.0.1
├── iron-iconset-svg#2.2.1
└── polymer#2.8.0

vaadin-button#2.2.1 bower_components\vaadin-button
├── polymer#2.8.0
├── vaadin-control-state-mixin#2.1.3
├── vaadin-element-mixin#2.1.3
├── vaadin-lumo-styles#1.5.0
├── vaadin-material-styles#1.2.3
└── vaadin-themable-mixin#1.4.4

polymer#2.8.0 bower_components\polymer
├── shadycss#1.9.1
└── webcomponentsjs#1.3.3

app-layout#3.0.2 bower_components\app-layout

vaadin-control-state-mixin#2.1.3 bower_components\vaadin-control-state-mixin
└── polymer#2.8.0

vaadin-item#2.1.1 bower_components\vaadin-item
├── polymer#2.8.0
├── vaadin-lumo-styles#1.5.0
├── vaadin-material-styles#1.2.3
└── vaadin-themable-mixin#1.4.4

vaadin-text-field#2.4.11 bower_components\vaadin-text-field
├── polymer#2.8.0
├── vaadin-control-state-mixin#2.1.3
├── vaadin-element-mixin#2.1.3
├── vaadin-lumo-styles#1.5.0
├── vaadin-material-styles#1.2.3
└── vaadin-themable-mixin#1.4.4

vaadin-element-mixin#2.1.3 bower_components\vaadin-element-mixin
├── polymer#2.8.0
├── vaadin-development-mode-detector#2.0.4
└── vaadin-usage-statistics#2.0.9

vaadin-material-styles#1.2.3 bower_components\vaadin-material-styles
└── polymer#2.8.0

vaadin-themable-mixin#1.4.4 bower_components\vaadin-themable-mixin
└── polymer#2.8.0

vaadin-lumo-styles#1.5.0 bower_components\vaadin-lumo-styles
├── iron-icon#3.0.1
├── iron-iconset-svg#2.2.1
└── polymer#2.8.0

iron-iconset-svg#2.2.1 bower_components\iron-iconset-svg
├── iron-meta#2.1.1
└── polymer#2.8.0

iron-meta#2.1.1 bower_components\iron-meta
└── polymer#2.8.0

iron-flex-layout#2.0.3 bower_components\iron-flex-layout
└── polymer#2.8.0

shadycss#1.9.1 bower_components\shadycss

vaadin-usage-statistics#2.0.9 bower_components\vaadin-usage-statistics
└── vaadin-development-mode-detector#2.0.4

vaadin-development-mode-detector#2.0.4 bower_components\vaadin-development-mode-detector

webcomponentsjs#1.3.3 bower_components\webcomponentsjs
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.

> core-js@2.6.9 postinstall D:\Projects\minor-contracts\target\migration\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @vaadin/migration@14.0.0 No description
npm WARN @vaadin/migration@14.0.0 No repository field.

added 355 packages from 281 contributors and audited 3007 packages in 27.695s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[1/2] 🌀  Converting Package...
Out directory: D:\Projects\minor-contracts\target\migration
Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: url.replace is not a function
      at Object.replaceHtmlExtensionIfFound (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\src\urls\util.ts:32:14)
      at Object.generatePackageJson (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\src\package-manifest.ts:205:24)
      at Object.<anonymous> (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\src\convert-package.ts:133:23)
      at Generator.next (<anonymous>)
      at fulfilled (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\lib\convert-package.js:17:58) }  reason:  TypeError: url.replace is not a function
    at Object.replaceHtmlExtensionIfFound (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\src\urls\util.ts:32:14)
    at Object.generatePackageJson (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\src\package-manifest.ts:205:24)
    at Object.<anonymous> (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\src\convert-package.ts:133:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Projects\minor-contracts\target\migration\node_modules\polymer-modulizer\lib\convert-package.js:17:58)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min
[INFO] Finished at: 2019-08-27T10:50:19+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by denis-anisimov** [comment]
The command result doesn't add any value to already discussed symptoms.

Build is successful.

The `url.replace` issue should be ignored.

In the result : there is no information which proves `now migrate some files but not all,`.

Anyway: in case you have issues with migration tool apart of the specifying the resources dir and the frontend dir it's a separate issue.
This issue was about default values for configuration parameters and we already have such issue and I've provided a workaround which works for you.
I'm closing this issue.
Please create another one in case some files are not migrated with the detailed description (steps to reproduce, expected and actual results).

**Comment by adexerivera** [comment]
If you look the image, only offline-page.js, has been migrated but, rest of files not migrate to *.js, for example login-view.html or main-view.html, not migrate.

**Comment by denis-anisimov** [comment]
The image doesn't give me the exact information what's going on exactly there.
That's why I suggest to make a separate ticket with the detailed description of the steps to reproduce, expected and actual result.

The original report which has a long discussion is about maven plugin config parameters which is not technically a bug at all (and there is another bug about the  default values).

Now you report an issue with the migration tool itself.
It should be made as a separate ticket since it's not related to the configuration.
I'm pretty sure that a developer who will work in this will request more details to be able to reproduce the bug.
Would be good to have a project .

**Comment by adexerivera** [comment]
Ok thanks for your help
