### ISSUE TITLE
Application does not start if icon is invalid

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#6344]
```
npx @vaadin/cli init --tech plain-java hello
cd hello
echo foo > src/main/webapp/icons/icon.png 
mvn
```

Expected: application starts normally

Actual: 
```
HTTP ERROR 503
Problem accessing /. Reason:

    Service Unavailable
Caused by:
javax.servlet.ServletException: org.eclipse.jetty.servlet.ServletHolder$1: java.lang.NullPointerException
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:168)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.servlet.ServletHolder$1: java.lang.NullPointerException
	at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:630)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:689)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:520)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:814)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:537)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	... 3 more
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.PwaRegistry.<init>(PwaRegistry.java:95)
	at com.vaadin.flow.server.PwaRegistry.getInstance(PwaRegistry.java:275)
	at java.util.Optional.map(Optional.java:215)
	at com.vaadin.flow.server.VaadinServletService.getPwaRegistry(VaadinServletService.java:187)
	at com.vaadin.flow.server.VaadinService.createRequestHandlers(VaadinService.java:367)
	at com.vaadin.flow.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:83)
	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:262)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:204)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:185)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:671)
	... 28 more
Caused by:
org.eclipse.jetty.servlet.ServletHolder$1: java.lang.NullPointerException
	at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:630)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:689)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:520)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:814)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:537)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1711)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1347)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1678)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1249)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.PwaRegistry.<init>(PwaRegistry.java:95)
	at com.vaadin.flow.server.PwaRegistry.getInstance(PwaRegistry.java:275)
	at java.util.Optional.map(Optional.java:215)
	at com.vaadin.flow.server.VaadinServletService.getPwaRegistry(VaadinServletService.java:187)
	at com.vaadin.flow.server.VaadinService.createRequestHandlers(VaadinService.java:367)
	at com.vaadin.flow.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:83)
	at com.vaadin.flow.server.VaadinService.init(VaadinService.java:262)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:204)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:185)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:671)
	... 28 more
```

**Comment by pleku** [comment]
I don't think we should prevent the app from starting when something goes wrong with loading / generating the different sized icons, but not sure if logging an error is enough.
