### ISSUE TITLE
Vaadin 14, Plain Java starter doesn't start on Tomcat 8.5

### ISSUE THREAD

**Issue by tailtap** [vaadin/flow#6384]
Plain Java Servlet Starter (Vaadin 14) works perfectly fine when I start it with jetty:run command in IDE (Eclipse). After export to WAR and deploy on Tomcat server the app doesn't start.

My environment:
- Vaadin 14
- Java 1.8.0_221
- Tomcat 8.5.45
- Eclipse 2018-12 (4.10.0)

Error in tomcat log file:

[https-jsse-nio-8080-exec-139] INFO com.vaadin.flow.server.startup.DevModeInitializer - Starting dev-mode updaters in C:\Users\u04111\eclipse-workspace\plain folder.
[https-jsse-nio-8080-exec-139] INFO dev-updater - Scanning classes to find frontend configurations and dependencies...
[https-jsse-nio-8080-exec-139] INFO dev-updater - Visited 657 classes. Took 772 ms.
[https-jsse-nio-8080-exec-139] INFO dev-updater - Added "name": "no-name" line.
[https-jsse-nio-8080-exec-139] INFO dev-updater - Added "license": "UNLICENSED" line.
[https-jsse-nio-8080-exec-139] INFO dev-updater - Added "@polymer/polymer": "3.2.0" line.
[https-jsse-nio-8080-exec-139] INFO dev-updater - Added "@webcomponents/webcomponentsjs": "^2.2.10" line.
03-Sep-2019 14:56:50.329 SEVERE [https-jsse-nio-8080-exec-139] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/plain]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:985)
	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:507)
	at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1650)
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.manager.ManagerServlet.check(ManagerServlet.java:1565)
	at org.apache.catalina.manager.HTMLManagerServlet.upload(HTMLManagerServlet.java:289)
	at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:207)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:136)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:109)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: 'other' is different type of Path
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:416)
	at sun.nio.fs.UnixPath.relativize(UnixPath.java:43)
	at com.vaadin.flow.server.frontend.NodeUpdater.updateMainDefaultDependencies(NodeUpdater.java:215)
	at com.vaadin.flow.server.frontend.TaskCreatePackageJson.execute(TaskCreatePackageJson.java:50)
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:368)
	at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:248)
	at com.vaadin.flow.server.startup.DevModeInitializer.onStartup(DevModeInitializer.java:164)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5267)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 48 more

**Comment by ujoni** [comment]
Investigator: First step for investigation: make a war in development mode and deploy that to TomCat 8.5

**Comment by tailtap** [comment]
> Investigator: First step for investigation: make a war in development mode and deploy that to TomCat 8.5

What is development mode? Should I change vaadin.productionMode to false in pom.xml? Like this:
```
<properties>
      <vaadin.productionMode>false</vaadin.productionMode>
 </properties>
```

**Comment by ujoni** [comment]
Hello @tailtap 

I left the message for the person who picks up this ticket, but if you could provide details about the deployment setup (perhaps Vaadin related bits from the pom.xml), that would be helpful. Thank you for the help!

**Comment by tailtap** [comment]
> Hello @tailtap
> 
> I left the message for the person who picks up this ticket, but if you could provide details about the deployment setup (perhaps Vaadin related bits from the pom.xml), that would be helpful. Thank you for the help!

Ok. Here is pom.xml, It goes with Plain Java starter project. I didn't change anything,

[pom.xml.txt](https://github.com/vaadin/flow/files/3578501/pom.xml.txt)

**Comment by caalador** [comment]
Hi.

How are you exporting the war?

On the same system doing a `mvn package`  and taking that to tomcat 8.5 should work as long as the project files are not moved. At least I didn't get any exceptions for this.

The better way to build the war would be using production mode `mvn package -Pproduction` then we would have no need for searching for the paths.

The exception that you are receiving is that in a windows environment the WindowsPathType is for some reason different for the two paths when both should be ABSOLUTE.

**Comment by tailtap** [comment]
Hi.

Thank you, sir, problem solved!
So for those who experiences same problem here is the steps to make WAR in Eclipse:

1. Right click on a project
2. Choose  Run As-> Maven build...
3. Put in Goals: `package -Pproduction`
4. Click Run

After all you can find your WAR in %eclipse-workspase-folder%\<project-name>\target\

P.S.: Previously I was exporting war by File->Export->WAR file

**Comment by caalador** [comment]
Closing issue as resolved as with the project files available the exported war could start the webpack dev server as is possible with mvn jetty:run

If the problem persists please recreate a ticket after running with a version containing #6410
