### ISSUE TITLE
Unable to set exported web component properties of type json

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#6566]
```
public static class Exporter extends WebComponentExporter<RoomInfo> {
  public Exporter() {
    super("room-info");
    addProperty("room", Json.createObject()).onChange((roominfo, json) -> {
      System.out.println("Value changed to "+json);
    });
  }
}
```

One would assume that doing e.g.
```
element.room = {hello: "world"}
```
in the browser would print a "Value changed" on the server but instead you get
```
java.lang.IllegalArgumentException: Parameter 'newValue' is of the wrong type: onChangeHandler of the property expected to receive elemental.json.JsonValue but found elemental.json.impl.JreJsonObject instead.
	at com.vaadin.flow.server.webcomponent.WebComponentBinding$PropertyBinding.updateValue(WebComponentBinding.java:254) ~[flow-server-2.0.12.jar:2.0.12]
	at com.vaadin.flow.server.webcomponent.WebComponentBinding.updateProperty(WebComponentBinding.java:97) ~[flow-server-2.0.12.jar:2.0.12]
	at com.vaadin.flow.server.webcomponent.WebComponentBinding.updateProperty(WebComponentBinding.java:125) ~[flow-server-2.0.12.jar:2.0.12]
	at com.vaadin.flow.component.webcomponent.WebComponentWrapper.sync(WebComponentWrapper.java:80) ~[flow-server-2.0.12.jar:2.0.12]
```

**Comment by ujoni** [comment]
Hmm. Can you provide some extra information about the setup. I am unable to replicate using skeleton-starter:

Exporter:
```java
public class E extends WebComponentExporter<MainView> {
    public E() {
        super("tag-name");
        addProperty("json", Json.createObject()).onChange((view, json) -> {
            System.out.println("What" + json);
        });
    }

    @Override
    protected void configureInstance(WebComponent<MainView> webComponent, MainView component) { }
}
```

Page:
```html
    <tag-name id ="tagname"></tag-name>
    
    <script>
        var tn = document.getElementById("tagname");
        tn.json={
            dog: "cat"
        };
    </script>
```

prints:
`What{"dog":"cat"}`

What in your project could warrant this operation? Do you have some Json dependency which could alter the raw types?

**Comment by Artur-** [comment]
Wrap  `tn.json= ...` in a timeout, e.g.
```
setTimeout(() => tn.json={dog: "cat"}, 1000);
```
