### ISSUE TITLE
WebComponentExporter for 2.1.0.beta2 adds extra component definitions to bundle

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6632]
Adding a `WebComponentExporter` to a project with `@Route()` seems to add duplicate component definitions to the bundle. 

**Steps to reproduce:**
- Get skeleton-starter-flow
- Add `public class Exporter extends WebComponentExporter<MainView> { ...` with tag `tag-name`
- Add `/src/main/webapps/importer.html`
  ```html
  <html>
    <head>
      <script type="module" src="/web-component/tag-name.js"></script>
    </head>
    <tag-name id ="tagname"></tag-name>
  </html>
  ```
- Run `mvn jetty:run`
- Navigate to both `/` and `/importer.html`
- **Expected:**
  - Contents of `MainView.java` are displayed on both pages and there is no error in browser logs
- **Actual:**
  - Only `/` has contents and both pages show an error in the browser logs.

HOWEVER: Running `mvn jetty:run -Ddevmode.optimizeBundle` will fix the issue

<details><summary><b>Error log</b></summary>

```
Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-grid/node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js?babel-target=es6:145:16)
    at Module.../node_modules/@vaadin/vaadin-grid/node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:2415:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:20:30)
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-grid/src/vaadin-grid-filter.js?babel-target=es6:4:108)
    at Module.../node_modules/@vaadin/vaadin-grid/src/vaadin-grid-filter.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:2583:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:20:30)
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-crud/src/vaadin-crud-grid.js?babel-target=es6:8:103)
    at Module.../node_modules/@vaadin/vaadin-crud/src/vaadin-crud-grid.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:1707:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:20:30)
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-crud/src/vaadin-crud.js?babel-target=es6:11:78)
    at Module.../node_modules/@vaadin/vaadin-crud/src/vaadin-crud.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:1731:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:20:30)
    at eval (webpack-internal:///../node_modules/@vaadin/vaadin-crud/theme/lumo/vaadin-crud.js?babel-target=es6:10:77)
    at Module.../node_modules/@vaadin/vaadin-crud/theme/lumo/vaadin-crud.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:1767:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:20:30)
    at eval (webpack-internal:///../target/frontend/generated-flow-imports.js?babel-target=es6:9:103)
    at Module.../target/frontend/generated-flow-imports.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:6021:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:20:30)
    at http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:84:18
    at http://localhost:8080/VAADIN/build/vaadin-bundle-c7cb8564fa004b8b7e42.cache.js:87:10
```
</details>

**Comment by denis-anisimov** [comment]
I don't think it adds extra component definition.

I don't think it's related to full CP scanning.
I can't reproduce it with the latest SNAPSHOT with removed `node_modules`.
And the symptoms are very close to the very known issue: version conflict of the same component.
Most likely  there is a component which is not discovered during byte code scanning which depends on one version of `vaadin-text-field WC and `text-filed-flow` depends on vaadin-text-field WC with another version.
This component is added to imports file with full CP scanning and the issue with Platform becomes more visible.

**Comment by ujoni** [comment]
I have been unable to reproduce this issue with either the example I've given, nor by using the https://github.com/Artur-/micro-front code base. I'll close this ticket. If similar problem arises, we'll have another ticket. 

There is the following behavior:
Given a class 
```java
@NpmPackage(value="@vaadin/vaadin-text-field", version="2.3.10")
public class MagicClass {
}
```
1. If running in "mega" mode, the newest text-field (2.4.12) will be in the frontend/package.json
2. If running with `-Ddevmode.optimizeBundle`, the text-field will have version 2.3.10
