### ISSUE TITLE
v14 Excessive heap use on page reloads after server restart

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow#6635]
To make sure we can quickly validate and fix the bug, please provide as much as possible of the following information:

Description
- If a page in in push mode us open, when the server is restarted each page attempts to reload when it notices that a server is back (this is normal)
- When several pages  (observed with 6 or more) are open, Jetty then produces OutOfMemory errors (**see log below**) on *some* of the pages being reloaded  in spite of the heap being very large relative to the steady state (-Xmx400m whereas application uses 90m after a System.gc() and runs at 200m steady)
- A refresh on each of the broken pages systematically works
- Pure Unsollicited Speculation: It is as if all pages were trying to load all the javascript all at the same time by copying it in memory

- Minimal reproducible example
  - I have a working heroku configuration that systematically produces the outcome
    http://github.com/jflamy/owlcms4  submodule owlcms if you need to browse code
 - given the location of the message,  I have not attempted to whittle it down. 
 - The behaviour is reproducible when windows originate from the same chrome browser (6 windows logged in to same site), have not tried other configurations.

- Expected behavior
  - pages should reload correctly when they detect the server is back.
  - this worked fine in v13

- Actual behavior
  - pages produce a OutOfMemory error on the heap, but only in this specific circumstance (reload on server restart).   A minority of pages does manage to reload.

- Versions:
    - Vaadin / Flow version 14.07
    - Java version JDK 8 on Heroku
    - OS version Linux
    - Browser version Chrome 77

- Specific error message

```
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:596)
	at java.lang.StringBuilder.append(StringBuilder.java:190)
	at org.apache.commons.io.output.StringBuilderWriter.write(StringBuilderWriter.java:143)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2370)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2348)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2325)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2273)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:1041)
	at com.vaadin.flow.server.frontend.FrontendUtils.streamToString(FrontendUtils.java:307)
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsContent(FrontendUtils.java:372)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.appendNpmBundle(BootstrapHandler.java:853)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:835)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupDocumentHead(BootstrapHandler.java:718)
	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:521)
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:462)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at app.owlcms.init.HttpsEnforcer.doFilter(HttpsEnforcer.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
```

**Comment by pleku** [comment]
Thanks for the precise report Jean-François, we have identified the problem and will fix it promptly.

**Comment by jensgoe** [comment]
same problem for me. for me it occurs immediatly when browser loads initial page. My guess is that stats.json cannot read properly. Either it is to big (12MB) or it contains special chars that cannot handled as a String. My heapdump shows char[] of size 80MB (at java.util.Arrays.copyOf(Arrays.java:3332)). Or maybe it is a line ending problem?

**Comment by jflamy** [comment]
My stats.json is at 20MB.  Slightly puzzled that this is needed in production.

Jean-François Lamy

**Comment by jensgoe** [comment]
![grafik](https://user-images.githubusercontent.com/6022600/66481279-d7574b00-eaa0-11e9-808d-9f327b24164d.png)

**Comment by mehdi-vaadin** [comment]
Fixed by #6648

**Comment by jflamy** [comment]
See #6679 for collateral damage.

Le lun. 14 oct. 2019 à 05:26, Mehdi Javan <notifications@github.com> a
écrit :

**Comment by mehdi-vaadin** [comment]
Thank you @jflamy for reporting that.

**Comment by jensgoe** [comment]
i tried it with vaadin release 14.1.0.alpha3 and i still get OutOfMemoryError. My glassfish is running with JVM-Option -Xmx256m. 

![outofmemory](https://user-images.githubusercontent.com/6022600/67274543-ef779300-f4c0-11e9-9672-866797be3fd4.png)

Currently my workaround is increasing to -Xmx512m, but my machine is very limited and i got other problems.
