### ISSUE TITLE
Remove "FIXME Implement Resync Bug"

### ISSUE THREAD

**Issue by sport3** [vaadin/flow#6673]
This is issue occurs in productive code of applications compiled with14 LTS vaadin.

See https://github.com/vaadin/flow/blob/6e8f181c8cb972ae98c042c517cc01203f5ed3b8/flow-server/src/main/java/com/vaadin/flow/server/communication/ServerRpcHandler.java#L306

Stacktrace is e.g. 
`java.lang.UnsupportedOperationException: FIXME: Implement resync
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:306) ~[flow-server-2.0.14.jar!/:2.0.14]
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:87) ~[flow-server-2.0.14.jar!/:2.0.14]
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.0.14.jar!/:2.0.14]
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540) ~[flow-server-2.0.14.jar!/:2.0.14]
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246) ~[flow-server-2.0.14.jar!/:2.0.14]
        at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:95) ~[vaadin-spring-12.0.6.jar!/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750) ~[javax.servlet-api-4.0.1.jar!/:4.0.1]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.21.jar!/:9.0.21]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.21.jar!/:9.0.21]
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712) ~[tomcat-embed-core-9.0.21.jar!/:9.0.21]
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459) ~[tomcat-embed-core-9.0.21.jar!/:9.0.21]
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:352) ~[tomcat-embed-core-9.0.21.jar!/:9.0.21]
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312) ~[tomcat-embed-core-9.0.21.jar!/:9.0.21]

See also this forum entry`with more stacktraces:
https://vaadin.com/forum/thread/17123523/error-fixme-implement-resync

**Comment by sport3** [comment]
This is probably a duplicate of https://github.com/vaadin/flow/issues/2210.
