### ISSUE TITLE
GitHub cherry-pick bot

### ISSUE THREAD

**Issue by ujoni** [vaadin/flow#6691]
A bot which automatically cherry-picks maintenance changes from master and creates PRs for the cherry-picks for the minor version branches under active maintenance (LTS branches and latest minor release)

**Comment by mehdi-vaadin** [comment]
[Trop bot](https://github.com/electron/trop) could be exactly what we need. But, it gives me the following  error after the main PR is merged.
```
Error: error: Failed to merge in the changes.

    at /Users/mehdi/Documents/GitHub/trop/node_modules/simple-git/promise.js:21:26
    at Git.<anonymous> (/Users/mehdi/Documents/GitHub/trop/node_modules/simple-git/src/git.js:641:18)
    at Function.Git.fail (/Users/mehdi/Documents/GitHub/trop/node_modules/simple-git/src/git.js:1474:18)
    at fail (/Users/mehdi/Documents/GitHub/trop/node_modules/simple-git/src/git.js:1432:20)
    at /Users/mehdi/Documents/GitHub/trop/node_modules/simple-git/src/git.js:1441:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I created a fork of it [here](https://github.com/mehdi-vaadin/trop) including some fixes. To install it locally on Mac, you need to have `xcode-select` installed. You can install it with `xcode-select --install`.

I also had some progress with creating my own bot [here](https://github.com/mehdi-vaadin/cherry-pick-bot). It uses [Probot](https://github.com/probot/probot).
