### ISSUE TITLE
Make webpack 5 work and benchmark Bakery

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#6773]
Webpack 5.0 is in beta and it should contain some performance improvements for the frontend builds.

https://github.com/webpack/changelog-v5/blob/master/README.md
https://github.com/webpack/changelog-v5/blob/master/MIGRATION%20GUIDE.md

Updating the used version doesn't directly work,  as tried with this branch https://github.com/vaadin/flow/tree/test/webpack-5 and Bakery, it will fail with 
```
npm WARN webpack-cli@3.3.0 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN copy-webpack-plugin@5.0.4 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.9.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN compression-webpack-plugin@3.0.0 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN raw-loader@3.1.0 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@2.2.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN no-name@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
And
```
2019-10-25 10:55:44.050  INFO 14544 --- [           main] dev-webpack                              : Starting webpack-dev-server, port: 64635 dir: C:\Users\Pekka\workspaces\flow\bakery-app-starter-flow-spring
   C:\Program Files\nodejs\node.exe C:\Users\Pekka\workspaces\flow\bakery-app-starter-flow-spring\node_modules\webpack-dev-server\bin\webpack-dev-server.js --config C:\Users\Pekka\workspaces\flow\bakery-app-starter-flow-spring\webpack.config.js --port 64635 --watchDogPort=64634 -d --inline=false
2019-10-25 10:55:45.115  INFO 14544 --- [        webpack] dev-webpack                              : C:\Users\Pekka\workspaces\flow\bakery-app-starter-flow-spring\node_modules\webpack-cli\bin\convert-argv.js:139
2019-10-25 10:55:45.118  INFO 14544 --- [        webpack] dev-webpack                              :            if (webpackConfigurationValidationErrors.length) {
2019-10-25 10:55:45.124  INFO 14544 --- [        webpack] dev-webpack                              :                                                     ^
2019-10-25 10:55:45.125  INFO 14544 --- [        webpack] dev-webpack                              :
2019-10-25 10:55:45.127  INFO 14544 --- [        webpack] dev-webpack                              : TypeError: Cannot read property 'length' of undefined
2019-10-25 10:55:45.132  INFO 14544 --- [        webpack] dev-webpack                              :     at processConfiguredOptions (C:\Users\Pekka\workspaces\flow\bakery-app-starter-flow-spring\node_modules\webpack-cli\bin\convert-argv.js:139:44)
2019-10-25 10:55:45.134  INFO 14544 --- [        webpack] dev-webpack                              :     at module.exports (C:\Users\Pekka\workspaces\flow\bakery-app-starter-flow-spring\node_modules\webpack-cli\bin\convert-argv.js:132:10)
2019-10-25 10:55:45.136  INFO 14544 --- [        webpack] dev-webpack                              :     at Object.<anonymous> (C:\Users\Pekka\workspaces\flow\bakery-app-starter-flow-spring\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
2019-10-25 10:55:45.143  INFO 14544 --- [        webpack] dev-webpack                              :     at Module._compile (internal/modules/cjs/loader.js:956:30)
2019-10-25 10:55:45.144  INFO 14544 --- [        webpack] dev-webpack                              :     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
2019-10-25 10:55:45.145  INFO 14544 --- [        webpack] dev-webpack                              :     at Module.load (internal/modules/cjs/loader.js:812:32)
2019-10-25 10:55:45.151  INFO 14544 --- [        webpack] dev-webpack                              :     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2019-10-25 10:55:45.152  INFO 14544 --- [        webpack] dev-webpack                              :     at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
2019-10-25 10:55:45.153  INFO 14544 --- [        webpack] dev-webpack                              :     at internal/main/run_main_module.js:17:11
```

Once the build is actually working, we should benchmark starting up of Bakery `mvn spring-boot:run` using webpack 5. There are benchmarks for current versions already.

**Comment by denis-anisimov** [comment]
I don't see how we may use webpack 5.0 today without dramatic changes.
All plugins which we are using has webpack 4 as a dependency.

This is what's printed here:
```
compression-webpack-plugin@3.0.0 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN copy-webpack-plugin@5.0.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN raw-loader@3.1.0 requires a peer of webpack@^4.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@2.2.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.7.2 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.9.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-cli@4.0.0-alpha-5 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN webpack-babel-multi-target-plugin@2.4.0-next.1 requires a peer of webpack@^4.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.6 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.
npm WARN html-webpack-plugin@3.2.0 requires a peer of webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
```

I've been trying to find plugin version for webpack 5 but without any success.
Let's consider `webpack-babel-multi-target-plugin`  :
The most recent version of it depends on webpack 4 : https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/blob/release/2.4.0/package.json `"webpack": "^4.19.0"` .
And there is no any other version for 5.

This is in fact serious limitation since it causes the code failure:

```
Error: Cannot find module 'webpack/lib/MultiModuleFactory'
[ERROR] Require stack:
[ERROR] - /Users/denis/workspace/bakery-app-starter-flow-spring/node_modules/webpack-babel-multi-target-plugin/dist/src/babel.target.multi.entry.plugin.js
[ERROR] - /Users/denis/workspace/bakery-app-starter-flow-spring/node_modules/webpack-babel-multi-target-plugin/dist/src/babel.target.entry.option.plugin.js
[ERROR] - /Users/denis/workspace/bakery-app-starter-flow-spring/node_modules/webpack-babel-multi-target-plugin/dist/src/babel.multi.target.plugin.js
```

So the code requires `MultiModuleFactory` and it exists in webpack 4 `lib` folder and doesn't exist in webpack 5 `lib` folder.

So we need  a replacement for this plugin and perhaps for all other plugins.

**Comment by pleku** [comment]
Blocked until Webpack 5 gets more plugins support.

**Comment by denis-anisimov** [comment]
webpack 5 still can't be used because of plugins.
The most important plugin `webpack-dev-server`  latest version is not compatible with webpack 5: https://github.com/webpack/webpack-dev-server/issues/2424.
The previous version requires `webpack-cli` (not the latest version) which is incompatible with webpack 5.
So we still cannot use webpack 5.

**Comment by pleku** [comment]
>webpack 5 still can't be used because of plugins.

@denis-anisimov care to add the webpack and WDS versions you tested with ? Will make it easier to recheck things later on.

When looking at WDS issues in github, there seems to be indications that the latest versions of it are compatbile with webpack 5 beta but there are some bugs still.

**Comment by joheriks** [comment]
[Live-reload in TS views ](https://github.com/vaadin/flow/issues/8852) will require hooking into the webpack recompilation to trigger live reload. So the replacement for webpack should also support this.

**Comment by caalador** [comment]
Initially webpack 5 seemed to perform ~50% faster than webpack 4 on windows 10 system, but later it was noted that the ProgressPlugin was making such an output overhead that after dropping it form webpack 4 (webpack 5 didn't have a supported version) webpack4 was ~55% faster that webpack5 when starting development mode for bakery.

**Comment by pleku** [comment]
I think this issue has run its course and we have better benchmarks than Bakery now with hybrid fusion & flow apps. Closing and to be continued in #8757
