### ISSUE TITLE
Allow rerouting when the target view is a HasErrorParameter

### ISSUE THREAD

**Issue by tmattsso** [vaadin/flow#6838]
If you have a UI-wide BeforeEnterListerer, and an error view for NotFoundException, the error view is shown regardless of where you try to reroute or forward to.

Use case:
my BeforeEnter checks for a logged in user. If none is found, always reroute to LoginView.

If I try to navigate to /asdf, the router resolves to the error view. Then the BeforeEnterListener is fired; the user is not logged in, so I try to reroute. Instead of login, the error view is show. In my case it also shows the Parent view, with menus, etc...

Workaround is to check for logged in user in the error view too.

**Comment by denis-anisimov** [comment]
Steps to reproduce:
- Use skeleton starter project https://github.com/vaadin/skeleton-starter-flow
- Add two classes `MyLayout`  and `MyError` (see below)
- Add `AnotherView` (see below).
- Open a browser and use some not-existent route (e.g. "foo" ).
- Result: an empty view is shown. Also an exception is thrown (see below).
- Open route "a".
- Result the MainView is shown as expected (`AnotherView`  forwards to `MainView`).

The behavior with non-existent route should be the same as for existing route (and of course no exception thrown).

```
@Route("a")
public class AnotherView extends Div implements BeforeEnterObserver {

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        event.forwardTo(MainView.class);
    }

}
```

```
public class MyLayout extends Div implements RouterLayout, BeforeEnterObserver {

    @Override
    public void beforeEnter(BeforeEnterEvent event) {
        event.forwardTo(MainView.class);
    }

}
```

```
@ParentLayout(MyLayout.class)
public class MyError extends RouteNotFoundError {

}
```

```
 java.lang.NullPointerException
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:207)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:177)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:137)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:125)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:64)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:402)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$1(ServerRpcHandler.java:383)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:383)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:318)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1536)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:237)
```

**Comment by denis-anisimov** [comment]
```
 java.lang.NullPointerException
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:248)
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:51)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.handleErrorNavigation(JavaScriptBootstrapUI.java:239)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.renderViewForRoute(JavaScriptBootstrapUI.java:170)
	at com.vaadin.flow.component.internal.JavaScriptBootstrapUI.connectClient(JavaScriptBootstrapUI.java:108)
```

**Comment by denis-anisimov** [comment]
Everything is broken because of this method : https://github.com/vaadin/flow/blob/a3847c7883cef2aa19f74e9884041df37d632584/flow-server/src/main/java/com/vaadin/flow/router/internal/AbstractNavigationStateRenderer.java#L306

When an exception is thrown the `ErrorStateRenderer::handle`  method is used to handle the navigation event but `ErrorStateRenderer::eventActionsSupported` returns `false` which means the renderer doesn't support reroute or postpone navigation.

So this is an explicit decision.

So two things here:
- Do we really don't want to support reroute or postpone navigation for `HasErrorParameter` views ?
- In any case there should not be an exception. It needs to be fixed anyway.

The first means that this is not a bug (except the exception should not be thrown).
And we need somehow fix the exception even though it's not clear how because the code assumes that `locationChangeEvent` is never `null`   otherwise `int statusCode = locationChangeEvent.getStatusCode();` throws NPE inside `handle` method.

Well, if we make `forwardTo` no-op in case of errors handling then it should be possible to workaround this code.

**Comment by denis-anisimov** [comment]
Should we may be delete `eventActionsSupported`  at all ?

**Comment by caalador** [comment]
I can't remember the base reason why event actions were not to be executed for error handlers. Perhaps @Legioth would remember the reason.
