### ISSUE TITLE
FIXME: implement resync appears in logs in spite of #6673 and #2210

### ISSUE THREAD

**Issue by jflamy** [vaadin/flow#6896]
- Description of the bug
In version 14.0.10 `java.lang.UnsupportedOperationException: FIXME: Implement resync` appears in logs.  This appears related to issues #6673 and #2210 that are marked as closed.

- Minimal reproducible example
   None available; observed during/immediately after a network outage

- Expected behavior
   resync takes place

- Actual behavior
```
java.lang.UnsupportedOperationException: FIXME: Implement resync
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:306)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:87)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```
- Versions:
    - Vaadin / Flow version  14.0.10
    - Java version  AdaptOpenJDK 8
    - Windows 10
    - Browser version  Chrome 77

**Comment by pleku** [comment]
The fix mentioned #2210 is not yet released as a part of a Vaadin 14 release, but should be tomorrow Monday 11th of November included in 14.0.13 and probably also in 14.1.0.beta2. 

I'm closing this issue as duplicate.
