### ISSUE TITLE
Frontend compilation failed

### ISSUE THREAD

**Issue by trickert76** [vaadin/flow#6897]
I've started with the starter pack of Vaadin for SpringBoot and added everything necessary from the business app (java-sources, frontend-dir). When I run it within the IDE/source project everything is ok - but when I run mvn install and copy the target/*jar and the frontend-dir to a different location, then during start of the SpringBoot application the frontend compilation fails.

```
2019-11-10 09:45:54.765 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.765 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/comboBoxConnector-es6.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.765 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 84:0-56
2019-11-10 09:45:54.766 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.766 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.766 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/comboBoxConnector-es6.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.766 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 84:0-56
2019-11-10 09:45:54.767 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.767 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.767 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/comboBoxConnector.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.767 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 91:0-52
2019-11-10 09:45:54.767 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.768 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.768 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/comboBoxConnector.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.768 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 91:0-52
2019-11-10 09:45:54.768 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.768 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.769 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector-es6.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.769 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 73:0-59
2019-11-10 09:45:54.769 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.769 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.770 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector-es6.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.770 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 73:0-59
2019-11-10 09:45:54.770 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.770 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.770 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.771 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 90:0-55
2019-11-10 09:45:54.771 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.771 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.771 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/contextMenuConnector.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.772 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 90:0-55
2019-11-10 09:45:54.772 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.772 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.772 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.773 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 70:0-58
2019-11-10 09:45:54.773 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.773 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.773 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/flow-component-renderer.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.773 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 70:0-58
2019-11-10 09:45:54.774 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.774 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.775 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector-es6.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.775 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 71:0-52
2019-11-10 09:45:54.775 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.775 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.776 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector-es6.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.776 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 71:0-52
2019-11-10 09:45:54.776 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.776 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.776 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.777 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 89:0-48
2019-11-10 09:45:54.777 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.777 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.777 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/gridConnector.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.777 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 89:0-48
2019-11-10 09:45:54.778 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.778 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.778 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.778 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 72:0-68
2019-11-10 09:45:54.779 ERROR 12934 --- [        webpack] dev-webpack                              : 
2019-11-10 09:45:54.779 ERROR 12934 --- [        webpack] dev-webpack                              : ERROR in ../target/frontend/generated-flow-imports.js
2019-11-10 09:45:54.779 ERROR 12934 --- [        webpack] dev-webpack                              : Module not found: Error: Can't resolve '@vaadin/flow-frontend/vaadin-grid-flow-selection-column.js' in '/Users/thoralf/test/target/frontend'
2019-11-10 09:45:54.779 ERROR 12934 --- [        webpack] dev-webpack                              :  @ ../target/frontend/generated-flow-imports.js 72:0-68
2019-11-10 09:45:54.779 ERROR 12934 --- [        webpack] dev-webpack                              : ℹ ｢wdm｣: Failed to compile.
2019-11-10 09:45:54.780 ERROR 12934 --- [        webpack] dev-webpack                              : 
------------------ Frontend compilation failed. -----------------
```
And in the browser I'm getting a very similar message to #6286 

But I use Vaadin 14.0.12

What I did:
- downloaded starter app Spring Boot
- downloaded business app  (Jetty)
- copied Java sources and frontend and some POM details to starter app folder
- run mvn install
- copy target/*.jar and frontend to a different location like "test"
- go to "test" and start the app with java -jar ...jar

**Comment by trickert76** [comment]
When I copy the node_modules directory from the source dir - everything works. So the start-up-phase from within Vaadin StringBoot must have a problem with some modules.

**Comment by Artur-** [comment]
If you run the project in development mode, it needs access to the project folder as it uses frontend files from there, which enables hotreload/hotswapping. If you are running on another host you need to run in production mode, e.g. `mvn install -Pproduction`. 

Now if you only move the jar on the same host, it should still find the project folder. Might be that the problem is resolved #6858 (not yet released), if the problem is that the metadata file `flow-build-info.json` is not found.

**Comment by trickert76** [comment]
Thanks Artur, I tried to build it for production and the behaviour doesn't change. (I'm on the same host).

Is there a documentation how to pack a Vaadin-Springboot Application to production? Of course, if I would copy the node_modules dir too, it would work, but I'm not sure if this "best practice".

```
  Failed to find the following imports in the `node_modules` tree:
      - @vaadin/flow-frontend/contextMenuConnector-es6.js
      - @vaadin/flow-frontend/comboBoxConnector.js
      - @vaadin/flow-frontend/gridConnector.js
      - @vaadin/flow-frontend/contextMenuConnector.js
      - @vaadin/flow-frontend/flow-component-renderer.js
      - @vaadin/flow-frontend/gridConnector-es6.js
      - @vaadin/flow-frontend/comboBoxConnector-es6.js
      - @vaadin/flow-frontend/vaadin-grid-flow-selection-column.js
````

What I really don't understand - whiy is it loading "parts" of the modules but not all?

**Comment by trickert76** [comment]
I've tested that a little bit more today - here is my pom.xml - the production profile produces a jar which doesn't contain any node modules etc., there is a VAADIN dir in META-INF but there aren't enough JS files. Also during `mvn install -Pproduction` phase it puts the missing files into target/frontend/.

Also I would expect that the CSS etc. from the `frontend` directory itself should be integrated. But when I start the JAR it says, that the files in frontend are missing. Based on the documentation under https://vaadin.com/docs/flow/production/tutorial-production-mode-basic.html this goals do not create a "production release".

```
<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>de.example.frontend</groupId>
    <artifactId>example-frontend-v2</artifactId>
    <name>example-frontend-v2</name>
    <version>2.1.0</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <vaadin.version>14.0.12</vaadin.version>
        <swagger-core-version>1.5.24</swagger-core-version>
        <gson-fire-version>1.8.3</gson-fire-version>
        <okhttp-version>3.14.2</okhttp-version>
        <threetenbp-version>1.4.0</threetenbp-version>
        <maven-plugin-version>1.0.0</maven-plugin-version>
        <javax-annotation-version>1.0</javax-annotation-version>

        <drivers.dir>${project.basedir}/drivers</drivers.dir>
        <drivers.downloader.phase>pre-integration-test</drivers.downloader.phase>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.7.RELEASE</version>
    </parent>

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
            <snapshots><enabled>false</enabled></snapshots>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo1.maven.org/maven2/</url>
            <snapshots><enabled>false</enabled></snapshots>
        </repository>
        <!-- Repository used by many Vaadin add-ons -->
        <repository>
            <id>Vaadin Directory</id>
            <url>https://maven.vaadin.com/vaadin-addons</url>
            <snapshots><enabled>false</enabled></snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-bom</artifactId>
                <version>${vaadin.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.vaadin</groupId>
            <!-- Replace artifactId with vaadin-core to use only free components -->
            <artifactId>vaadin</artifactId>
            <exclusions>
                <!-- Webjars are only needed when running in Vaadin 13 compatibility mode -->
                <exclusion>
                    <groupId>com.vaadin.webjar</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.insites</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.polymer</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.polymerelements</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.vaadin</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.webjars.bowergithub.webcomponents</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-spring-boot-starter</artifactId>
            <exclusions>
                <!-- Excluding so that webjars are not included. -->
                <exclusion><groupId>com.vaadin</groupId>
                    <artifactId>vaadin-core</artifactId></exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>vaadin-testbench</artifactId>
            <scope>test</scope>
        </dependency>
        
        <!-- SpringBoot:Start -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-config</artifactId>
        </dependency>
        <!-- SpringBoot:End -->

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>${swagger-core-version}</version>
        </dependency>
        <!-- @Nullable annotation -->
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>${okhttp-version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>${okhttp-version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.gsonfire</groupId>
            <artifactId>gson-fire</artifactId>
            <version>${gson-fire-version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.threeten</groupId>
            <artifactId>threetenbp</artifactId>
            <version>${threetenbp-version}</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>jsr250-api</artifactId>
            <version>${javax-annotation-version}</version>
        </dependency>
                    

    </dependencies>

    <build>
        <defaultGoal>spring-boot:run</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <wait>500</wait>
                    <maxAttempts>240</maxAttempts>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.vaadin</groupId>
                <artifactId>vaadin-maven-plugin</artifactId>
                <version>${vaadin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-frontend</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/example-backend-api-v1.0.2.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <configOptions>
                                <sourceFolder>src/gen/java</sourceFolder>
                            </configOptions>
                            <apiPackage>de.example.frontend.generated.client.api</apiPackage>
                            <modelPackage>de.example.frontend.generated.client.model</modelPackage>
                            <invokerPackage>de.example.frontend.generated.client</invokerPackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            <plugin>
                                                    <groupId>org.codehaus.mojo</groupId>
                                                    <artifactId>build-helper-maven-plugin</artifactId>
                                                    <executions>
                                                        <execution>
                                                            <phase>generate-sources</phase>
                                                            <goals>
                                                                <goal>add-source</goal>
                                                            </goals>
                                                            <configuration>
                                                                <sources>
                                                                    <source>target/generated-sources/openapi/src/gen/java</source>
                                                                </sources>
                                                            </configuration>
                                                        </execution>
                                                    </executions>
                                                </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <!-- Production mode is activated using -Pproduction -->
            <id>production</id>
            <properties>
                <vaadin.productionMode>true</vaadin.productionMode>
            </properties>

            <dependencies>
                <dependency>
                    <groupId>com.vaadin</groupId>
                    <artifactId>flow-server-production-mode</artifactId>
                </dependency>
            </dependencies>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <configuration>
                            <jvmArguments>-Dvaadin.productionMode</jvmArguments>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.vaadin</groupId>
                        <artifactId>vaadin-maven-plugin</artifactId>
                        <version>${vaadin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>prepare-frontend</goal>
                                    <goal>build-frontend</goal>
                                    <goal>copy-production-files</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>integration-tests</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>start-spring-boot</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>stop-spring-boot</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- Runs the integration tests (*IT) after the server is started -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            <execution>
                                <id>start-spring-boot</id>
                                <phase>pre-integration-test</phase>
                                <goals>
                                    <goal>start</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>stop-spring-boot</id>
                                <phase>post-integration-test</phase>
                                <goals>
                                    <goal>stop</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>

                    <!-- Runs the integration tests (*IT) after the server is started -->
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                            </execution>
                        </executions>
                        <configuration>
                            <trimStackTrace>false</trimStackTrace>
                            <enableAssertions>true</enableAssertions>
                            <systemPropertyVariables>
                                <!-- Pass location of downloaded webdrivers to the tests -->
                                <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>com.lazerycode.selenium</groupId>
                        <artifactId>driver-binary-downloader-maven-plugin</artifactId>
                        <version>1.0.17</version>
                        <configuration>
                            <onlyGetDriversForHostOperatingSystem>true
                            </onlyGetDriversForHostOperatingSystem>
                            <rootStandaloneServerDirectory>
                                ${project.basedir}/drivers/driver
                            </rootStandaloneServerDirectory>
                            <downloadedZipFileDirectory>
                                ${project.basedir}/drivers/driver_zips
                            </downloadedZipFileDirectory>
                            <customRepositoryMap>
                                ${project.basedir}/drivers.xml
                            </customRepositoryMap>
                        </configuration>
                        <executions>
                            <execution>
                                <!-- use phase "none" to skip download step -->
                                <phase>${drivers.downloader.phase}</phase>
                                <goals>
                                    <goal>selenium</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>
</project>
```

**Comment by denis-anisimov** [comment]
Looks like there are many confusions here:
- I don't think you need dev mode when you run  `java -jar`.  It will requires a complicated setup which we don't support out of the box. Only project with all modules, frontend folder and so on should work in dev mode out of the box. Otherwise you should care about access to those folders from FS and it's too tricky.
- `I tried to build it for production and the behaviour doesn't change.` if it's true then you don't run production mode. Production mode doesn't require any files and it doesn't compile anything. The compilation is done during packaging the application into production . And after that all files are compiled into a bundle file and no modules are needed anymore and they should not be required/placed into the resulting app.
- `copy-production-files`  should not be used. It's for compatibility mode which you don't use here apparently.
- `production` profile should be activated via the property `vaadin.productionMode`. Do you have it ? https://github.com/vaadin/skeleton-starter-flow-spring/blob/master/pom.xml#L157
- Use `production` profile to produce the app in production mode. Then you should be able to start it . You may start it using spring boot plugin as shown here :https://github.com/vaadin/skeleton-starter-flow-spring/blob/master/pom.xml#L170

**Comment by trickert76** [comment]
Ok, good example - I've used https://github.com/vaadin/skeleton-starter-flow-spring

- `git clone https://github.com/vaadin/skeleton-starter-flow-spring`
- `mvn clean install -Pproduction`
- `scp target/spring-skeleton-2.0-SNAPSHOT.jar user@server:...`

On the server is only java available and no npm etc.

- `java -jar spring-skeleton-2.0-SNAPSHOT.jar`

And then I'm getting an exception:

```
Caused by: java.lang.IllegalStateException: 

======================================================================================================
Failed to determine 'npm' tool.
Please install it either:
  - by following the https://nodejs.org/en/download/ guide to install it globally
  - or by running the frontend-maven-plugin goal to install it in this project:
  $ mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.13.0" 
======================================================================================================

	at com.vaadin.flow.server.frontend.FrontendUtils.getExecutable(FrontendUtils.java:326) ~[flow-server-2.0.17.jar!/:2.0.17]
	at com.vaadin.flow.server.frontend.FrontendUtils.getNpmExecutable(FrontendUtils.java:284) ~[flow-server-2.0.17.jar!/:2.0.17]
	at com.vaadin.flow.server.frontend.TaskRunNpmInstall.runNpmInstall(TaskRunNpmInstall.java:79) ~[flow-server-2.0.17.jar!/:2.0.17]
	... 50 common frames omitted
``` 

So - it needs (compiled in production mode) a npm on the server. 

But after some trials I found out, that I need to start the server process with the attribute.

- `java -Dvaadin.productionMode -jar ...`

Then it comes up and everything is fine.

I've read the `Book f Vaadin 14` and in chapter 17 I could not find a hint, that I need to add that attribute during runtime.

**Comment by denis-anisimov** [comment]
If you look here:
https://github.com/vaadin/skeleton-starter-flow-spring/blob/master/pom.xml#L157
and here:
https://github.com/vaadin/skeleton-starter-flow-spring/blob/master/pom.xml#L173

you can see that the `production` profile is activated by the property `vaadin.productionMode`.
And this property is set to run the application using Spring boot.

There is a bug https://github.com/vaadin/flow/issues/6657 (fixed already) which allows to run the jar file without `vaadin.productionMode` property: it should be stored in the file during build (in production mode) and read on startup.

>I've read the Book f Vaadin 14 and in chapter 17 I could not find a hint, that I need to add that attribute during runtime.

That's an issue. We should have it properly documented. Could you please create a ticket about this in the https://github.com/vaadin/flow-and-components-documentation/ repository ?

May I close now this ticket ?

**Comment by trickert76** [comment]
yes, you can. ;-)
