### ISSUE TITLE
"Vaadin is running in DEBUG MODE" should be shown way earlier

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#7017]
It seems to be a common problem that you build your application for production, do something wrong and end up with a production war/jar which is actually running in development mode. The output you will get when deploying is something like
```
2019-11-21 08:37:29.992  INFO 3780 --- [           main] dev-updater                              : Running `npm install` ...
2019-11-21 08:37:30.007 ERROR 3780 --- [           main] c.v.f.s.frontend.FrontendToolsLocator    : Command '[which, npm]' failed with exit code '1'
2019-11-21 08:37:30.030 ERROR 3780 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener]
java.lang.RuntimeException: Unable to initialize Vaadin DevModeHandler
    at com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener.contextInitialized(VaadinServletContextInitializer.java:326) ~[vaadin-spring-12.0.6.jar!/:na]
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4680) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5143) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat-embed-core-9.0.22.jar!/:9.0.22]
...
Caused by: javax.servlet.ServletException: com.vaadin.flow.server.ExecutionFailedException: 
======================================================================================================
Failed to determine 'npm' tool.
Please install it either:
  - by following the https://nodejs.org/en/download/ guide to install it globally
  - or by running the frontend-maven-plugin goal to install it in this project:
  $ mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.13.0" 
======================================================================================================
```

There are two simple things to improve here:

1. Show the debug mode banner as early as possible, before anything related to dev mode handler/updaters/npm install etc. If the above output started with
```
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
```

Then the problem would be much more obvious.

2. Do not suggest that `npm` must be installed when going for production. Change the text to something like
```
======================================================================================================
Failed to determine 'npm' tool.

If you are developing, please install it either:
  - by following the https://nodejs.org/en/download/ guide to install it globally
  - or by running the frontend-maven-plugin goal to install it in this project:
  $ mvn com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm -DnodeVersion="v12.13.0" 

If you are looking to deploy into production you do not need the `npm` tool but this application is not build for production mode. See https://vaadin.com/docs/flow/production/tutorial-production-mode-basic.html for more information about production mode.
======================================================================================================

**Comment by Legioth** [comment]
The current `DEBUG MODE` banner is on purpose among the very last things to be logged so that you will notice it in the happy path. Moving it to some other point would negatively impact that use case.

**Comment by mehdi-vaadin** [comment]
What about showing the `DEBUG MODE` banner twice, once where it is at the moment and once as early as possible?

**Comment by pleku** [comment]
Starting from 14.2 Node.js is automatically installed to `home/.vaadin`.

There is also an issue about improving the DX when looking at the logs for application startup #7762.

Thus I would think this issue is not valid anymore - in case there is still some obscurity after 14.2 release, a new issue will surely appear.
