### ISSUE TITLE
Unexpected message id from the client. When using Hazelcast for session storage

### ISSUE THREAD

**Issue by eltonkent** [vaadin/flow#7079]
Hi
I'm seeing the following crash when I setup Hazelcast for session management.
Followed the instructions outlined in 
https://vaadin.com/learn/tutorials/microservices/high-availability

The page loads fine, but certain 'push' features don't work.

```
java.lang.UnsupportedOperationException: Unexpected message id from the client. Expected sync id: 0, got 1. Message start: {"csrfToken":"1d8bb839-b17a-4bca-a2b3-51c1ccfa95be","rpc":[{"type":"mSync","node":51,"feature":1,"property":"opened","value":true},{"type":"publishedEventHandler","node":49,"templateEventMethodName":"updateSelectedTab","templateEventMethodArgs":[true]},{"type":"publishedEventHandler","node":38,"templateEventMethodName":"updateSelectedTab","templateEventMethodArgs":[true]},{"type":"publishedEventHandler","node":27,"templateEventMethodName":"updateSelectedTab","templateEventMethodArgs":[true]},{"type":"publishedEventHandler","node":19,"templateEventMethodName":"updateSelectedTab","templateEventMethodArgs":[true]},{"type":"channel","node":5,"channel":0,"args":[null]},{"type":"channel","node":5,"channel":2,"args":[null]}],"syncId":-1,"clientId":1}
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:88)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:95)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframe
```
Vaadin Version: 14.0.13
Java version : 11
OS version: Mac OS X 10.14.6

**Comment by Legioth** [comment]
What has most likely happened here is that while sticky sessions ensure that all requests from a specific clients always go to a specific node in the cluster, there are still no guarantees that push messages are processed on that same node in the cluster.

This will very easily lead to situations where two different nodes are at the same time making updates to the same user's session. This will cause the sequential message ids to go out of sync and after that nothing can work.

What this means in practice is that you'd have to update your own application logic so that you're always only doing `ui.access` on the same node that is otherwise processing requests for that client. You could also verify that sticky sessions are also effective for websocket connections so that they also get directed to the same node that handles regular requests for that client.

I don't see how Vaadin could help you there since it isn't really aware of the session replication. The one thing we could do is to clarify this detail in the tutorial.

**Comment by alejandro-du** [comment]
All requests go thought an _edge service_ implemented with Zuul. Unfortunately, the version of Zuul I used in the tutorial doesn't support WebSocket. Zuul 2 supports it and latest versions of Spring Cloud use it. I just need to find time to update the tutorial to more recent versions of Vaadin and Spring.

I'd like to highlight that the tutorial purpose is to teach you what microservices are from a practical point of view. But I'm convinced most projects don't need this! I should have named the tutorial with something like "Learn microservices and why you don't need them" ;) Anyway, check this out: https://dwmkerr.com/the-death-of-microservice-madness-in-2018

**Comment by eltonkent** [comment]
Thanks for the response guys. I should point out that this happens during development with just one node in the cluster.

**Comment by pleku** [comment]
As this is an issue to just update the tutorial and not really for the framework, I'm closing this issue.
