### ISSUE TITLE
Confirmed duplicate message from the client when opening a resource

### ISSUE THREAD

**Issue by r-smirnov** [vaadin/flow#7106]
This issue is intermittent. To reproduce, create a button that opens a resource:
```java
AbstractStreamResource href = new StreamResource(
    "dummy.pdf",
    () -> {
        try {
            return new URL("https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf").openStream();
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
    }).setContentType("application/pdf");

Anchor anchor = new Anchor(href, null);
anchor.add(new Button("Open"));

add(anchor);
```
Clicking the button sometimes results in "Internal error" message on the client and the following exception on the server:
```
java.lang.UnsupportedOperationException: Confirmed duplicate message from the client. Expected sync id: 1, got 0. Message start: {"csrfToken":"334a7aca-f61a-414b-9c29-79dbd7c1ee27","rpc":[{"type":"event","node":4,"event":"click","data":{"event.shiftKey":false,"event.metaKey":false,"event.detail":1,"event.ctrlKey":false,"event.clientX":69,"event.clientY":44,"event.altKey":false,"event.button":0,"event.screenY":172,"event.screenX":3909}}],"syncId":0,"clientId":0}
        at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
        at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:88)
        at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
        at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
        at com.vaadin.cdi.CdiVaadinServlet.service(CdiVaadinServlet.java:65)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.openejb.server.httpd.EEFilter.doFilter(EEFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.tomee.catalina.OpenEJBSecurityListener$RequestCapturer.invoke(OpenEJBSecurityListener.java:97)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```
Vaadin 14.1.1
Firefox 68.2.0

**Comment by Legioth** [comment]
Seems like this happens because of the two different requests that are sent when clicking:
1. There's a request to load the pdf resource
2. There's a request to send a click event for the button

The problem occurs when the click event request is sent before the pdf request. What will happen in such situations is that the event request will be aborted when the browser sees that it's about to navigate away to a pdf, but then there's something that causes the request to be resent. This may be related to logic around the `webkitMaybeIgnoringRequests` flag in `XhrConnection`.

As a workaround in your application, you can use a raw `<vaadin-button>` element (e.g. `new Element("vaadin-button")`) instead of the `Button` component since in that way, there won't be any server-side listener and in that way there would be only one request. You should remember to annotate the layout component with `@Uses(Button.class)` to ensure the web component implementation is still loaded.
