### ISSUE TITLE
Hotswap agent: InvocationTargetException on changes 

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#7174]
**UPDATE**: Hotswap doesn't work . Most likely because of exception. It was working for me because I had scan interval set to `1` for jetty plugin which reloads the whole web app. Without this reload nothing works.

This is not a bug in Flow.
But may be we should somehow participate in fixing this.

Steps to reproduce:
- setup Hotswap agent (instructions on http://hotswapagent.org/).
- checkout skeleton-starter
- configure run in your IDE to use the agent.
- Run the project
- Make a change in `MainView` class. 
- hostswap will note a change and start to do something

It will throw `InvocationTargetException` :
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.plugin.vaadin.VaadinPlugin.addToRouterConfiguration(VaadinPlugin.java:234)
	at org.hotswap.agent.plugin.vaadin.VaadinPlugin.addNewRoute(VaadinPlugin.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.onWatchEvent(WatchEventCommand.java:190)
	at org.hotswap.agent.annotation.handler.WatchEventCommand.executeCommand(WatchEventCommand.java:98)
	at org.hotswap.agent.command.impl.CommandExecutor.run(CommandExecutor.java:43)
Caused by: com.vaadin.flow.server.AmbiguousRouteConfigurationException: Navigation targets must have unique routes, found navigation targets 'com.vaadin.starter.skeleton.MainView' and 'com.vaadin.starter.skeleton.MainView' with the same route.
	at com.vaadin.flow.server.startup.RouteTarget.validateNormalTarget(RouteTarget.java:163)
	at com.vaadin.flow.server.startup.RouteTarget.addTargetByType(RouteTarget.java:107)
	at com.vaadin.flow.server.startup.RouteTarget.addRoute(RouteTarget.java:100)
	at com.vaadin.flow.router.internal.ConfigureRoutes.setRoute(ConfigureRoutes.java:133)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.addRouteToConfiguration(AbstractRouteRegistry.java:366)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.lambda$setRoute$83b15968$1(AbstractRouteRegistry.java:308)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.configure(AbstractRouteRegistry.java:95)
	at com.vaadin.flow.router.internal.AbstractRouteRegistry.setRoute(AbstractRouteRegistry.java:307)
	at com.vaadin.flow.server.startup.ApplicationRouteRegistry.setRoute(ApplicationRouteRegistry.java:233)
	at com.vaadin.flow.router.RouteConfiguration.setAnnotatedRoute(RouteConfiguration.java:225)
	... 13 more
```

Apparently route registry is reinitialized and it fails since the same route is already registered.
I assume it happens because `ServletContainerInitializer` (`RouteRegistryInitializer`) is rerun.

**Comment by pleku** [comment]
There was some effort in fixing the routes for hotswap agent, but apparently didn't work https://github.com/mstahv/HotswapAgent/tree/feature/vaadin13-support-route-removal

**Comment by joheriks** [comment]
Fixed by https://github.com/HotswapProjects/HotswapAgent/pull/341.
