### ISSUE TITLE
[PUSH] NullPointerException on Atmosphere

### ISSUE THREAD

**Issue by letrthang** [vaadin/flow#7177]
NullPointerException happened with websocket connection between browser and server.

Vaadin: 14.1.2
Atmosphere: 2.4.30.slf4jvaadin1
Server: Tomcat 9
Java: OpenJDK 11, 64bit
OS: Amazon Linux.

`ERROR [http-nio-9090-exec-5] (PushAtmosphereHandler.java:116) - Exception in push connection
java.lang.NullPointerException
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:652)
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:630)
	at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:499)
	at org.atmosphere.cpr.AsynchronousProcessor.endRequest(AsynchronousProcessor.java:604)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.executeClose(DefaultWebSocketProcessor.java:710)
	at org.atmosphere.websocket.DefaultWebSocketProcessor.close(DefaultWebSocketProcessor.java:658)
	at org.atmosphere.container.JSR356Endpoint.onClose(JSR356Endpoint.java:310)
	at org.apache.tomcat.websocket.WsSession.fireEndpointOnClose(WsSession.java:555)
	at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:533)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.close(WsHttpUpgradeHandler.java:239)
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:155)
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by denis-anisimov** [comment]
Hi, thanks for reporting this.
Could you please provide steps to reproduce the issue ?

**Comment by letrthang** [comment]
Hi Denis,
this is randomly error so i don't have  steps to reproduce the issue. our server runs for few days and this error message happens in some times.

**Comment by denis-anisimov** [comment]
OK, thanks. :(

**Comment by Springrbua** [comment]
I recently found a similar exception in our logs:

```
Cannot invoke
"org.atmosphere.cpr.AtmosphereResource.removeEventListener(org.atmosphere.cpr.AtmosphereResourceEven
tListener)" because the return value of "org.atmosphere.cpr.AtmosphereResourceEvent.getResource()"
is null

Cannot invoke "org.atmosphere.cpr.AtmosphereResource.removeEventListener(org.atmosphere.cpr.AtmosphereResourceEventListener)" because the return value of "org.atmosphere.cpr.AtmosphereResourceEvent.getResource()" is null
	java.lang.NullPointerException: Cannot invoke "org.atmosphere.cpr.AtmosphereResource.removeEventListener(org.atmosphere.cpr.AtmosphereResourceEventListener)" because the return value of "org.atmosphere.cpr.AtmosphereResourceEvent.getResource()" is null
		at org.atmosphere.interceptor.PaddingAtmosphereInterceptor$ForcePreSuspend.onPreSuspend(PaddingAtmosphereInterceptor.java:151)
		at org.atmosphere.cpr.AtmosphereResourceImpl.onPreSuspend(AtmosphereResourceImpl.java:747)
		at org.atmosphere.cpr.AtmosphereResourceImpl.suspend(AtmosphereResourceImpl.java:350)
		at com.vaadin.flow.server.communication.PushHandler.suspend(PushHandler.java:191)
		at com.vaadin.flow.server.communication.PushHandler.lambda$new$0(PushHandler.java:116)
		at com.vaadin.flow.server.communication.PushHandler.callWithUi(PushHandler.java:257)
		at com.vaadin.flow.server.communication.PushHandler.onConnect(PushHandler.java:562)
		at com.vaadin.flow.server.communication.PushAtmosphereHandler.onConnect(PushAtmosphereHandler.java:103)
		at com.vaadin.flow.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
		at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:225)
		at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:114)
		at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67)
		at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2297)
		at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:594)
		at org.atmosphere.websocket.DefaultWebSocketProcessor.open(DefaultWebSocketProcessor.java:224)
		at org.atmosphere.container.JSR356Endpoint.onOpen(JSR356Endpoint.java:264)
		at org.eclipse.jetty.websocket.javax.common.JavaxWebSocketFrameHandler.onOpen(JavaxWebSocketFrameHandler.java:175)
		at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.lambda$onOpen$6(WebSocketCoreSession.java:407)
		at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1463)
		at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1482)
		at org.eclipse.jetty.websocket.core.server.internal.AbstractHandshaker$1.handle(AbstractHandshaker.java:212)
		at org.eclipse.jetty.websocket.core.internal.WebSocketCoreSession.onOpen(WebSocketCoreSession.java:407)
		at org.eclipse.jetty.websocket.core.internal.WebSocketConnection.onOpen(WebSocketConnection.java:545)
		at org.eclipse.jetty.http2.HTTP2StreamEndPoint.upgrade(HTTP2StreamEndPoint.java:538)
		at org.eclipse.jetty.http2.server.HttpTransportOverHTTP2.prepareUpgrade(HttpTransportOverHTTP2.java:352)
		at org.eclipse.jetty.http2.server.HTTP2ServerConnection$ServerHttpChannelOverHTTP2.checkAndPrepareUpgrade(HTTP2ServerConnection.java:345)
		at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:551)
		at org.eclipse.jetty.server.HttpChannel.run(HttpChannel.java:370)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:190)
		at org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:208)
		at org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:155)
		at org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:378)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
		at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:548)
		at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:397)
		at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164)
		at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
		at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268)
		at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138)
		at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407)
		at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894)
		at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038)
		at java.base/java.lang.Thread.run(Unknown Source)
```
Unfortunately I don't have any other information about the issue and I don't know how to reproduce it.
I'll update this issue with any detail I find.

Vaadin Version: 22.0.1 
JRE: 17.0.1 (Adoptium)

**Comment by eberleant** [comment]
We are seeing a similar exception as well.

Vaadin version: 24.1.2
Java: 17.0.3

```
Exception in push connection
java.lang.NullPointerException: Cannot invoke "org.atmosphere.cpr.AtmosphereResource.uuid()" because the return value of "org.atmosphere.cpr.AtmosphereResourceEvent.getResource()" is null
	at org.atmosphere.cpr.DefaultAtmosphereResourceSessionFactory$1.onDisconnect(DefaultAtmosphereResourceSessionFactory.java:29) ~[atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.onDisconnect(AtmosphereResourceImpl.java:752) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:644) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereResourceImpl.notifyListeners(AtmosphereResourceImpl.java:625) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.completeLifecycle(AsynchronousProcessor.java:486) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.interceptor.OnDisconnectInterceptor.inspect(OnDisconnectInterceptor.java:75) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.invokeInterceptors(AsynchronousProcessor.java:335) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:192) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:103) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.container.Servlet30CometSupport.service(Servlet30CometSupport.java:67) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2284) [atmosphere-runtime-3.0.3.slf4jvaadin1.jar:3.0.3.slf4jvaadin1]
	at com.vaadin.flow.server.communication.PushRequestHandler.handleRequest(PushRequestHandler.java:292) [flow-server-24.1.3.jar:24.1.3]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1529) [flow-server-24.1.3.jar:24.1.3]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) [flow-server-24.1.3.jar:24.1.3]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) [vaadin-spring-24.1.3.jar:?]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) [jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1608) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1541) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.Dispatcher.forward(Dispatcher.java:122) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) [spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:178) [spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) [spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) [spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) [spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) [spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) [spring-webmvc-6.0.10.jar:6.0.10]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:547) [jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) [spring-webmvc-6.0.10.jar:6.0.10]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) [jakarta.servlet-api-6.0.0.jar:6.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1608) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195) [jetty-ee10-websocket-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1580) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1541) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletChannel$RequestDispatchable.dispatch(ServletChannel.java:910) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:686) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:483) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:510) [jetty-security-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:663) [jetty-ee10-servlet-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:808) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:587) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.Handler$Wrapper.handle(Handler.java:596) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.Server.handle(Server.java:177) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:651) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:480) [jetty-server-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322) [jetty-io-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [jetty-io-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) [jetty-io-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478) [jetty-util-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441) [jetty-util-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293) [jetty-util-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201) [jetty-util-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:410) [jetty-util-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) [jetty-util-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) [jetty-util-12.0.0.jar:12.0.0]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) [jetty-util-12.0.0.jar:12.0.0]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by TatuLund** [comment]
In Vaadin 7, 8 and 14 this could be solved by this fix: https://github.com/vaadin/atmosphere/commit/b60fe57b8e96e45404dbd13f12c02b99e7c5004f But will require building a new Vaadin Atmosphere 2.4.30 release and updating the Vaadin 7, 8 and 14 to use the new release. According to my checking the Atmosphere release used in Vaadin 23 and the latest Vaadin 24 versions should have this fix by now already.

**Comment by TatuLund** [comment]
This NPE should be fixed now in Vaadin 7.7.49 and Vaadin 8.28.4.

**Comment by ponziani** [comment]
That bugfix is not where the NPE occurs for us (and @eberleant). I assume you need to add a null-check to DefaultAtmosphereResourceSessionFactory as well:

```java
public void onDisconnect(AtmosphereResourceEvent event) {
    String uuid = event.getResource().uuid();
    AtmosphereResourceSession session = sessions.remove(uuid);

    if (session != null) {
        session.invalidate();
    }
}

**Comment by TatuLund** [comment]
> That bugfix is not where the NPE occurs for us (and @eberleant). 

But it is the fix of the original issue reported.

**Comment by ponziani** [comment]
True, but it would nice to have both bugs fixed.

**Comment by TatuLund** [comment]
> True, but it would nice to have both bugs fixed.

It would be better to have different ticket for that, and it looks to me to be Atmosphere bug, so ticket there should be opened. Just by brief checking I noticed that in that class there is no other way to get session, and it is unclear for me that in which use case the resource is null here. 

https://github.com/Atmosphere/atmosphere/blob/main/modules/cpr/src/main/java/org/atmosphere/cpr/DefaultAtmosphereResourceSessionFactory.java#L28

If one just checks for null and returns, it may not be correct ... I.e. could the session be uncleared then.

https://github.com/Atmosphere/atmosphere/blob/main/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereResourceEvent.java

It is weird bug ...

By brief glance this looks correct

https://github.com/Atmosphere/atmosphere/blob/main/modules/cpr/src/main/java/org/atmosphere/cpr/AsynchronousProcessor.java#L486

As impl.cancel() is called after notifyListeners. My understanding is that the only way resource can be null there is that something has called cancel, or event.destroy() before listeneres are notified. And that should be debugged and fixed, or verified that null check above is safe and we can be sure that session is already closed.

**Comment by ponziani** [comment]
Maybe this is useful to you:

I’ve been looking into a heap dump from a OOM and noticed a large number of `VaadinSession` objects, some of them up to 3 days old with their `(http-)session` field set to `null`.

Interestingly, the stack trace I posted earlier appears once in the logs 3 days before the OOM, exactly when memory usage started to climb in our monitoring. Since the application restart, the same stack trace has already shown up 3 more times, each time matching another jump in memory usage.

To me this strongly suggests a memory leak. Besides the “old” `VaadinSession` objects, the heap also contains a very large Atmosphere queue, presumably still referencing those sessions and preventing them from being garbage-collected.

**Comment by TatuLund** [comment]
> To me this strongly suggests a memory leak. Besides the “old” VaadinSession objects, the heap also contains a very large Atmosphere queue, presumably still referencing those sessions and preventing them from being garbage-collected.

Just noting here, the variable "session" in Atmosphere code does not refer to VaadinSession.

**Comment by ponziani** [comment]
> > To me this strongly suggests a memory leak. Besides the “old” VaadinSession objects, the heap also contains a very large Atmosphere queue, presumably still referencing those sessions and preventing them from being garbage-collected.
> 
> Just noting here, the variable "session" in Atmosphere code does not refer to VaadinSession.

I know. I just see a lot of VaadinSessions in the heapdump, with as GC root an Atmosphere queue/list.

**Comment by TatuLund** [comment]
> I know. I just see a lot of VaadinSessions in the heapdump, with as GC root an Atmosphere queue/list.

Then even more reason to have separate ticket for the issue.

**Comment by ponziani** [comment]
> > I know. I just see a lot of VaadinSessions in the heapdump, with as GC root an Atmosphere queue/list.
> 
> Then even more reason to have separate ticket for the issue.

https://github.com/Atmosphere/atmosphere/issues/2527

**Comment by TatuLund** [comment]
I verified that both Vaadin 23.6 and Vaadin 14.14 are using the Atmosphere 2.7.3.slf4jvaadin7 version and thus they have the fix of the original issue. Hence I am close this as fixed as the fix is in all Vaadin versions.

https://github.com/vaadin/atmosphere/blob/2.7.3/modules/cpr/src/main/java/org/atmosphere/cpr/AtmosphereResourceImpl.java#L649
