### ISSUE TITLE
AWT error when using @PWA on headless server

### ISSUE THREAD

**Issue by mkemmerz** [vaadin/flow#7194]
Vaadin 14.1.2
Java:
> openjdk version "11.0.4" 2019-07-16
> OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
> OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

Hello, we are facing an issue with our Vaadin 14 PWA. The moment Flow tries to process the PWA images an exception is thrown from java.awt. The PWA is deployed on a headless server. I also found this commit which provided support for AWT headless: https://github.com/vaadin/flow/commit/5b5a18c003cb0f8889209a8c8cb89c3a8c4917e5

We think it could also be a misconfiguration on our side but just to be sure I want to ask here as well. Is there any bug or issue known?

We have tried a lot like using a different Java version etc. but nothing worked.

> java.awt.AWTError: Could not create Toolkit: sun.awt.HeadlessToolkit
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:607)
        at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
        at java.desktop/java.awt.Image.getScaledInstance(Image.java:178)
        at com.vaadin.flow.server.PwaRegistry.drawIconImage(PwaRegistry.java:156)
        at com.vaadin.flow.server.PwaRegistry.initializeIcons(PwaRegistry.java:120)
        at com.vaadin.flow.server.PwaRegistry.<init>(PwaRegistry.java:98)
        at com.vaadin.flow.server.PwaRegistry.getInstance(PwaRegistry.java:275)
        at java.base/java.util.Optional.map(Optional.java:265)
        at com.vaadin.flow.server.VaadinServletService.getPwaRegistry(VaadinServletService.java:187)
        at com.vaadin.flow.server.VaadinService.createRequestHandlers(VaadinService.java:367)
        at com.vaadin.flow.server.VaadinServletService.createRequestHandlers(VaadinServletService.java:83)
        at com.vaadin.flow.server.VaadinService.init(VaadinService.java:262)
        at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:204)
        at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:185)
        at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)

The exception is thrown in Toolkit::getDefaultToolkit():

```
try {
         if (cls != null) {
             toolkit = (Toolkit)cls.getConstructor().newInstance();
        if (GraphicsEnvironment.isHeadless()) {
            toolkit = new HeadlessToolkit(toolkit);
        }
     }
    } catch (final ReflectiveOperationException ignored) {
        throw new AWTError("Could not create Toolkit: " + nm);
    }
```

The PWA registration in our Servlet:

```
public class VaadinFlowServlet extends com.vaadin.flow.server.VaadinServlet  {
    @Override
    public void init(ServletConfig servletConfig) throws ServletException {
        registerPWAClass(servletConfig);
        super.init(servletConfig);
    }

    private void registerPWAClass(ServletConfig servletConfig) {
        final var registry = ApplicationRouteRegistry.getInstance(servletConfig.getServletContext());
        registry.setPwaConfigurationClass(MainView.class);
    }
```

Any ideas?

**Comment by Artur-** [comment]
Does it help to define `-Djava.awt.headless` ?

**Comment by mkemmerz** [comment]
@Artur- defining the flag produces the same exception. `PWARegistry` sets the flag if it is not set anyway so the case that `-Djava.awt.headless=false` does not happen.

```
    private static final String HEADLESS_PROPERTY = "java.awt.headless";
    private PwaRegistry(PWA pwa, ServletContext servletContext)
            throws IOException {
        if (System.getProperty(HEADLESS_PROPERTY) == null) {
            // set headless mode if the property is not explicitly set
            System.setProperty(HEADLESS_PROPERTY, Boolean.TRUE.toString());
        }
```

**Comment by mkemmerz** [comment]
We found our issue and were able to fix it.

During the startup of the application we set '-Dawt.toolkit=sun.awt.HeadlessToolkit' explicitly. Simply removing this flag let the PWA start correctly. I can't tell why this causing this issue (and AWT is unable to create the HeadlessToolkit) but at least it was not on your side thus I close the issue.
