### ISSUE TITLE
Throws random NullPointerException

### ISSUE THREAD

**Issue by scrmtrey91** [vaadin/flow#7224]
Idle application with PUSH enabled (Vaadin 14.1.3 version, cdi):

Exception stack trace:
```
[2019-12-22T18:13:00.372+0100] [Payara 5.194] [SEVERE] [] [] [tid: _ThreadID=57 _ThreadName=http-thread-pool::http-listener-2(3)] [timeMillis: 1577034780372] [levelValue: 1000] [[
  [http-thread-pool::http-listener-2(3)] ERROR com.vaadin.flow.component.UI - null]]

[2019-12-22T18:13:00.372+0100] [Payara 5.194] [SEVERE] [] [] [tid: _ThreadID=57 _ThreadName=http-thread-pool::http-listener-2(3)] [timeMillis: 1577034780372] [levelValue: 1000] [[
  java.lang.NullPointerException
	at com.vaadin.flow.component.UI$1.handleError(UI.java:514)
	at com.vaadin.flow.server.FutureAccess.handleError(FutureAccess.java:76)
	at com.vaadin.flow.server.VaadinService.runPendingAccessTasks(VaadinService.java:1989)
	at com.vaadin.flow.server.VaadinSession.unlock(VaadinSession.java:651)
	at com.vaadin.flow.server.VaadinService.requestEnd(VaadinService.java:1479)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1554)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
	at com.vaadin.cdi.CdiVaadinServlet.service(CdiVaadinServlet.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1628)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:339)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.glassfish.tyrus.servlet.TyrusServletFilter.doFilter(TyrusServletFilter.java:282)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:251)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:209)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:256)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:755)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:575)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:159)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:371)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:238)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:520)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:217)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
	at java.lang.Thread.run(Thread.java:748)
]]
```

**Comment by caalador** [comment]
Would you have a simple application that reproduces the issue?
Also is this for GlassFish server run from idea?
What is the action that fails in an exception outside of a session?

**Comment by mehdi-vaadin** [comment]
@scrmtrey91 I wasn't able to reproduce it. So, I'm closing this issue. Of course, we will reopen it as soon as you could provide more info and a reproducing example :)
