### ISSUE TITLE
ccdm: flow-client build failed on windows machine

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/flow#7283]
Node version: 12.8.0
OS: Windows 10 (works with Mac OS)

run `mvn clean install -DskipTests`

the build failed on `flow-client` module, the error log is listed:

```
[INFO] --- gwt-maven-plugin:2.8.2:compile (default) @ flow-client ---
[INFO] Compiling module com.vaadin.ClientEngine
[INFO]    Warnings in com/vaadin/client/flow/dom/DomElement.java
[INFO]       [WARN] Line 119: [unusable-by-js] Return type of 'Element DomElement.getFirstElementChild()' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 127: [unusable-by-js] Return type of 'Element DomElement.getLastElementChild()' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 153: [unusable-by-js] Return type of 'HTMLCollection DomElement.getChildren()' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 163: [unusable-by-js] Return type of 'Element DomElement.querySelector(String)' is not usable by but exposed to JavaScript.
[INFO]    Warnings in com/vaadin/client/flow/dom/DomNode.java
[INFO]       [WARN] Line 61: [unusable-by-js] Return type of 'Node DomNode.getFirstChild()' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 69: [unusable-by-js] Return type of 'Node DomNode.getLastChild()' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 77: [unusable-by-js] Return type of 'Node DomNode.getNextSibling()' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 85: [unusable-by-js] Return type of 'Node DomNode.getPreviousSibling()' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 110: [unusable-by-js] Type of parameter 'node' in 'void DomNode.appendChild(Node)' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 121: [unusable-by-js] Type of parameter 'newChild' in 'void DomNode.insertBefore(Node, Node)' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 121: [unusable-by-js] Type of parameter 'refChild' in 'void DomNode.insertBefore(Node, Node)' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 130: [unusable-by-js] Type of parameter 'childNode' in 'void DomNode.removeChild(Node)' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 142: [unusable-by-js] Type of parameter 'newChild' in 'void DomNode.replaceChild(Node, Node)' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 142: [unusable-by-js] Type of parameter 'oldChild' in 'void DomNode.replaceChild(Node, Node)' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 154: [unusable-by-js] Return type of 'Node DomNode.cloneNode(boolean)' is not usable by but exposed to JavaScript.
[INFO]       [WARN] Line 163: [unusable-by-js] Return type of 'Node DomNode.getParentNode()' is not usable by but exposed to JavaScript.
[INFO]    Warnings in com/vaadin/client/flow/dom/PolymerDomApiImpl.java
[INFO]       [WARN] Line 68: [unusable-by-js] Type of parameter 'node' in 'DomElement PolymerDomApiImpl.Polymer.dom(Node)' is not usable by but exposed to JavaScript.
[INFO]    [WARN] Suppress "[unusable-by-js]" warnings by adding a `@SuppressWarnings("unusable-by-js")` annotation to the corresponding member.
[INFO]    Compiling 1 permutation
[INFO]       Compiling permutation 0...
[INFO]    Compile of permutations succeeded
[INFO]    Compilation succeeded -- 18.299s
[INFO] Linking into C:\WorkFolder\flow\flow-client\target\classes\META-INF\resources\VAADIN\static\client; Writing extras to C:\WorkFolder\flow\flow-client\target\extra\client
[INFO]    Link succeeded
[INFO]    Linking succeeded -- 0.904s
[INFO]
[INFO] --- gwt-maven-plugin:2.8.2:generateAsync (default) @ flow-client ---
[INFO]
[INFO] --- exec-maven-plugin:1.6.0:exec (typescript-compile) @ flow-client ---

> @vaadin/flow-deps@0.0.1 compile C:\WorkFolder\flow\flow-client
> npm run build && npm run lint


> @vaadin/flow-deps@0.0.1 build C:\WorkFolder\flow\flow-client
> npm run client && tsc


> @vaadin/flow-deps@0.0.1 client C:\WorkFolder\flow\flow-client
> npm run _cp_to_src && npm run _wrap_fnc && npm run _cp_to_tgt


> @vaadin/flow-deps@0.0.1 _cp_to_src C:\WorkFolder\flow\flow-client
> ncp target/classes/META-INF/resources/VAADIN/static/client/client-*.cache.js src/main/resources/META-INF/resources/frontend/FlowClient.js

There were errors during the copy.
Error: ENOENT: no such file or directory, lstat 'C:\WorkFolder\flow\flow-client\target\classes\META-INF\resources\VAADIN\static\client\client-*.cache.js'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaadin/flow-deps@0.0.1 _cp_to_src: `ncp target/classes/META-INF/resources/VAADIN/static/client/client-*.cache.js src/main/resources/META-INF/resources/frontend/FlowClient.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vaadin/flow-deps@0.0.1 _cp_to_src script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhe\AppData\Roaming\npm-cache\_logs\2020-01-07T09_33_42_868Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaadin/flow-deps@0.0.1 client: `npm run _cp_to_src && npm run _wrap_fnc && npm run _cp_to_tgt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vaadin/flow-deps@0.0.1 client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhe\AppData\Roaming\npm-cache\_logs\2020-01-07T09_33_42_889Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaadin/flow-deps@0.0.1 build: `npm run client && tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vaadin/flow-deps@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhe\AppData\Roaming\npm-cache\_logs\2020-01-07T09_33_42_914Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @vaadin/flow-deps@0.0.1 compile: `npm run build && npm run lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @vaadin/flow-deps@0.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhe\AppData\Roaming\npm-cache\_logs\2020-01-07T09_33_42_936Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by ZheSun88** [comment]
there are a few tools not supported by windows.

- the `ncp` tool with wildcard usage is not working
  -  solution can be `_cp_to_src": "cpy target/classes/META-INF/resources/VAADIN/static/client/client-*.cache.js src/main/resources/META-INF/resources/frontend/ --rename=FlowClient.js` instead

- the `replace-in-files` is not supported in windows 
  -  probably related to https://github.com/sindresorhus/replace-in-files-cli/issues/6

**Comment by haijian-vaadin** [comment]
@platosha promised to make a branch, thanks

**Comment by ZheSun88** [comment]
probably need to reopen this ticket, as the problem still exists.
