### ISSUE TITLE
Stackoverflow when extending HasElement in a TemplateModel

### ISSUE THREAD

**Issue by gsedlacz** [vaadin/flow#7311]
- Description of the bug
Stackoverflow during page load if a `TemplateModel` extends `HasElement`.

- Minimal reproducible example
Define a `PolymerElement` (in my case `org.demo.web.test.internal.TEST_SUB_COMPONENT`) whos `TemplateModel` looks like this:

```
public interface TEST_MODEL extends TemplateModel, HasElement {
    String getValue();
    void setValue(String value);
}
```
If you remove `HasElement` and restart the server everything loads perfectly fine.

- Expected behavior
no stackoverflow :)

- Actual behavior
```
16:21:25,402 ERROR [com.vaadin.flow.router.InternalServerError] (default task-3) There was an exception while trying to navigate to 'test': java.lang.IllegalArgumentException: Unable to create an instance of 'org.demo.web.test.internal.TEST'. The constructor threw an exception.
	at deployment.web.war//com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:512)
	at deployment.web.war//com.vaadin.flow.internal.ReflectTools.createInstance(ReflectTools.java:449)
	at deployment.web.war//com.vaadin.flow.di.DefaultInstantiator.create(DefaultInstantiator.java:137)
	at deployment.web.war//com.vaadin.flow.di.DefaultInstantiator.getOrCreate(DefaultInstantiator.java:66)
	at deployment.web.war//com.vaadin.flow.di.Instantiator.createRouteTarget(Instantiator.java:158)
	at deployment.web.war//com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$getRouteTarget$1(AbstractNavigationStateRenderer.java:127)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at deployment.web.war//com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.getRouteTarget(AbstractNavigationStateRenderer.java:126)
	at deployment.web.war//com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChain(AbstractNavigationStateRenderer.java:314)
	at deployment.web.war//com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:195)
	at deployment.web.war//com.vaadin.flow.router.Router.handleNavigation(Router.java:223)
	at deployment.web.war//com.vaadin.flow.router.Router.navigate(Router.java:194)
	at deployment.web.war//com.vaadin.flow.router.Router.initializeUI(Router.java:92)
	at deployment.web.war//com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1449)
	at deployment.web.war//com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:452)
	at deployment.web.war//com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at deployment.web.war//com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540)
	at deployment.web.war//com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:246)
	at javax.servlet.api@1.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websocket@2.0.21.Final//io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:55)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.0.21.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.core@2.0.21.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at org.wildfly.extension.undertow@17.0.1.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet@2.0.21.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.core@2.0.21.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.core@2.0.21.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at deployment.web.war//com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:481)
	... 67 more
Caused by: java.lang.IllegalArgumentException: Unable to create an instance of 'org.demo.web.test.internal.TEST_SUB_COMPONENT'. The constructor threw an exception.
	at deployment.web.war//com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:512)
	at deployment.web.war//com.vaadin.flow.internal.ReflectTools.createInstance(ReflectTools.java:449)
	at deployment.web.war//com.vaadin.flow.di.DefaultInstantiator.create(DefaultInstantiator.java:137)
	at deployment.web.war//com.vaadin.flow.di.DefaultInstantiator.createComponent(DefaultInstantiator.java:71)
	at deployment.web.war//com.vaadin.flow.component.ComponentUtil.componentFromElement(ComponentUtil.java:429)
	at deployment.web.war//com.vaadin.flow.component.Component.from(Component.java:497)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.IdMapper.injectTemplateElement(IdMapper.java:192)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.IdMapper.attachExistingElementById(IdMapper.java:176)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.IdMapper.injectClientSideElement(IdMapper.java:116)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.IdMapper.mapComponentOrElement(IdMapper.java:80)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$mapComponents$2(TemplateInitializer.java:159)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer$ParserData.lambda$forEachInjectedField$0(TemplateDataAnalyzer.java:139)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1505)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer$ParserData.forEachInjectedField(TemplateDataAnalyzer.java:138)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.TemplateInitializer.mapComponents(TemplateInitializer.java:158)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.TemplateInitializer.initChildElements(TemplateInitializer.java:101)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:90)
	at deployment.web.war//com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
	at deployment.web.war//org.demo.web.test.internal.TEST_COMPONENT.<init>(TEST_COMPONENT.java:19)
	at deployment.web.war//org.demo.web.test.internal.TEST.TEST_setupTopo(TEST.java:185)
	at deployment.web.war//org.demo.web.test.internal.TEST.<init>(TEST.java:42)
	... 72 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at deployment.web.war//com.vaadin.flow.internal.ReflectTools.createProxyInstance(ReflectTools.java:481)
	... 93 more
Caused by: java.lang.StackOverflowError
	at deployment.web.war//com.vaadin.flow.templatemodel.TemplateModelUtil.lambda$getFilterFromIncludeExclude$0(TemplateModelUtil.java:158)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.test(PropertyFilter.java:104)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.lambda$composeFilter$2(PropertyFilter.java:99)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.test(PropertyFilter.java:104)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.lambda$composeFilter$2(PropertyFilter.java:99)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.test(PropertyFilter.java:104)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.lambda$composeFilter$2(PropertyFilter.java:99)
    [...]
    at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.lambda$composeFilter$2(PropertyFilter.java:99)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.test(PropertyFilter.java:104)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.lambda$composeFilter$2(PropertyFilter.java:99)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyFilter.test(PropertyFilter.java:104)
	at deployment.web.war//com.vaadin.flow.templatemodel.PropertyMapBuilder.lambda$getPropertiesData$4(PropertyMapBuilder.java:186)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
```

- Usecase:
Adding getter / setter for non-standard properties like `:value`.

```
default String getSpecialValue() {
    return getElement().getProperty(":value");
}
```

- Versions:
    - Vaadin / Flow version: 14.1.0
    - Java version: 11.0.3
    - OS version: Windows 10 (1909)

**Comment by caalador** [comment]
A template model can never be an HasElement as it is used pass properties to the client-side PolymerTemplate and thus will never have an element itself.

Also the model wouldn't actually execute the default method at any point as we create a proxy of the model and try to read the value specialValue that would never be synced from the client as it doesn't exist.

If you have non-standard properties you should just have the getter/setter on the PolymerTemplate component and not the model.

**Comment by gsedlacz** [comment]
You are absolutely right.
I have no idea why I assumed this would make sense in the first place.

Im sorry for waisting your time.
