### ISSUE TITLE
Upgrade to version 14.1.4 produces Paper-Ripple Error

### ISSUE THREAD

**Issue by allenvpn312** [vaadin/flow#7312]
Hi I just upgraded to version 14.1.4 from 14.1.3.  I am getting a strange error I have not seen before.  Reverting back to 14.1.3 still produce the same error.

`login:1 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "paper-ripple" has already been used with this registry
    at Polymer (webpack-internal:///../node_modules/@polymer/polymer/lib/legacy/polymer-fn.js?babel-target=es6:47:18)
    at eval (webpack-internal:///../node_modules/@polymer/paper-ripple/paper-ripple.js?babel-target=es6:315:90)
    at Module.../node_modules/@polymer/paper-ripple/paper-ripple.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-993e684fd5cfd21e61df.cache.js:1044:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-993e684fd5cfd21e61df.cache.js:20:30)
    at eval (webpack-internal:///../node_modules/@polymer/paper-behaviors/paper-ripple-behavior.js?babel-target=es6:4:95)
    at Module.../node_modules/@polymer/paper-behaviors/paper-ripple-behavior.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-993e684fd5cfd21e61df.cache.js:1008:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-993e684fd5cfd21e61df.cache.js:20:30)
    at eval (webpack-internal:///../node_modules/@polymer/paper-tabs/paper-tab.js?babel-target=es6:6:107)
    at Module.../node_modules/@polymer/paper-tabs/paper-tab.js?babel-target=es6 (http://localhost:8080/VAADIN/build/vaadin-bundle-993e684fd5cfd21e61df.cache.js:1116:1)
    at __webpack_require__ (http://localhost:8080/VAADIN/build/vaadin-bundle-993e684fd5cfd21e61df.cache.js:20:30)`

Has anyone else seen this error in their app?

**Comment by allenvpn312** [comment]
Not sure why but during the upgrade the paper-ripple web component was installed in the target/frontend folder.  Once I remove the paper-ripple folder, the app loads properly.
