### ISSUE TITLE
The server refuses to start if one of the endpoint methods is called "delete"

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/flow#7460]
This makes the server refuse to start:
```
@AnonymousAllowed
public void delete(Location location) {
```

Changing the name to anything else fixes the issue and the server starts up fine:
```
@AnonymousAllowed
public void deleteLocation(Location location) {
```

Output with the issue:
```
2020-01-31 13:21:56.592 ERROR 25148 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Exception sending context initialized event to listener instance of class [com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener]

java.lang.RuntimeException: Unable to initialize com.vaadin.flow.spring.VaadinServletContextInitializer$DevModeServletContextListener
        at com.vaadin.flow.spring.VaadinServletContextInitializer$FailFastServletContextListener.contextInitialized(VaadinServletContextInitializer.java:166) ~[vaadin-spring-13.0.0.alpha5.jar:na]
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4683) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_121]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) [tomcat-embed-core-9.0.27.jar:9.0.27]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) [tomcat-embed-core-9.0.27.jar:9.0.27]
...
```

**Comment by tomivirkki** [comment]
Probably has to do with `delete` being a reserved work in JS

**Comment by haijian-vaadin** [comment]
Yes, it does. I can confirm that `function` also does not work. 

So let's document the limitation and improve the error message for now.

**Comment by haijian-vaadin** [comment]
I just debug it a bit, it says so in the exception cause.
![Screenshot 2020-02-03 at 11.21.49.png](https://images.zenhubusercontent.com/5e0dcbb3f28dea52f669852b/e08f306c-ea00-4373-9ba6-f1165f867737)

**Comment by Haprog** [comment]
Flow seems to generate the endpoints with syntax similar to:
```js
export function delete() {}
```
which won't work if the function name is a reserved word, but you can get around it by just using different syntax, so this should be fixable.

This would work just fine in ES module:
```js
function _delete() {}
export { _delete as delete };
```

And it can then be called like:
```js
import * as viewEndpoint from './my-module.js';
viewEndpoint.delete();
```
