### ISSUE TITLE
Intellij integration + WebSphere Liberty + CDI exception on startup

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7531]
1. Install WebSphere Liberty
2. Download `skeleton-starter-flow-cdi` and import the project into IntellIJ (Ultimate Edition)
3. Create Run configuration for installed WebSpehere and deploy the artifact `skeleton-starter-flow-cdi`
4. Run the configuration, see log below.

To investigate: can we do anything in Flow or the starters so that the server starts up normally? If not, document the limitation. See #7303.

Versions:
- Vaadin 14.0.2
- WebSphere Liberty 20.0.0.1

```
/opt/IBM/WebSphere/Liberty/bin/server run defaultServer

Detected server http port: 9080
[2020-02-10 01:14:08,685] Artifact skeleton-starter-flow-cdi:war: Waiting for server connection to start artifact deployment...
Connected to the target VM, address: '127.0.0.1:61224', transport: 'socket'
Launching defaultServer (WebSphere Application Server 20.0.0.1/wlp-1.0.36.cl200120200108-0300) on Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_202-b08 (en_GB)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
Connected to server
[2020-02-10 01:14:10,487] Artifact skeleton-starter-flow-cdi:war: Artifact is being deployed, please wait...
[AUDIT   ] CWWKG0016I: Starting server configuration update.
[AUDIT   ] CWWKG0018I: The server configuration was not updated. No functional changes were detected.
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/skeleton_starter_flow_cdi_war/
[AUDIT   ] CWWKZ0001I: Application skeleton_starter_flow_cdi_war started in 0.986 seconds.
[AUDIT   ] CWWKF0015I: The server has the following interim fixes active in the runtime: PH19528. For a full listing of installed fixes run: productInfo version --ifixes
[AUDIT   ] CWWKF0012I: The server installed the following features: [el-3.0, jsp-2.3, localConnector-1.0, servlet-3.1].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 2.671 seconds.
[2020-02-10 01:14:11,537] Artifact skeleton-starter-flow-cdi:war: Artifact is deployed successfully
[2020-02-10 01:14:11,537] Artifact skeleton-starter-flow-cdi:war: Deploy took 1,050 milliseconds
[WARNING ] CWNEN0047W: Resource annotations on the fields of the com.vaadin.cdi.CdiVaadinServlet class will be ignored. The annotations could not be obtained because of the exception : java.lang.NoClassDefFoundError: Ljavax/enterprise/inject/spi/BeanManager;
[err] [Default Executor-thread-16] INFO com.vaadin.cdi.CdiServletDeployer - Automatically deploying CDI Vaadin servlet to /*
[err] [Default Executor-thread-16] INFO com.vaadin.flow.server.startup.ServletDeployer - Skipping automatic servlet registration because there is already a Vaadin servlet with the name com.vaadin.cdi.CdiServletDeployer
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler mapped to context-path: /*
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed the following AtmosphereInterceptor mapped to AtmosphereHandler com.vaadin.flow.server.communication.PushAtmosphereHandler
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using org.atmosphere.util.VoidAnnotationProcessor for processing annotation
[err] [Default Executor-thread-16] INFO org.atmosphere.util.ForkJoinPool - Using ForkJoinPool  java.util.concurrent.ForkJoinPool. Set the org.atmosphere.cpr.broadcaster.maxAsyncWriteThreads to -1 to fully use its power.
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installing Default AtmosphereInterceptors
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.CorsInterceptor : CORS Interceptor Support
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.CacheHeadersInterceptor : Default Response's Headers Interceptor
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.PaddingAtmosphereInterceptor : Browser Padding Interceptor Support
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.AndroidAtmosphereInterceptor : Android Interceptor Support
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Dropping Interceptor org.atmosphere.interceptor.HeartbeatInterceptor
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.SSEAtmosphereInterceptor : SSE Interceptor Support
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.JSONPAtmosphereInterceptor : JSONP Interceptor Support
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.JavaScriptProtocol : Atmosphere JavaScript Protocol
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor : org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.OnDisconnectInterceptor : Browser disconnection detection
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - 	org.atmosphere.interceptor.IdleResourceInterceptor : org.atmosphere.interceptor.IdleResourceInterceptor
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Set org.atmosphere.cpr.AtmosphereInterceptor.disableDefaults to disable them.
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Browser Padding Interceptor Support with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor org.atmosphere.interceptor.WebSocketMessageSuspendInterceptor with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor org.atmosphere.interceptor.IdleResourceInterceptor with priority BEFORE_DEFAULT 
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Using BroadcasterCache: org.atmosphere.cache.UUIDBroadcasterCache
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Default Broadcaster Class: org.atmosphere.cpr.DefaultBroadcaster
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Broadcaster Shared List Resources: false
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Broadcaster Polling Wait Time 100
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Shared ExecutorService supported: true
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Messaging ExecutorService Pool Size unavailable - Not instance of ThreadPoolExecutor
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Async I/O Thread Pool Size: 200
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Using AtmosphereResurceFactory: org.atmosphere.cpr.DefaultAtmosphereResourceFactory
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Invoke AtmosphereInterceptor on WebSocket message true
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - HttpSession supported: true
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using DefaultAtmosphereObjectFactory for dependency injection and object creation
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Atmosphere is using async support: org.atmosphere.container.Servlet30CometSupport running under container: IBM WebSphere Liberty/20.0.0.1 using javax.servlet/3.0
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Atmosphere Framework 2.4.30.slf4jvaadin1 started.
[err] [Default Executor-thread-16] INFO org.atmosphere.cpr.AtmosphereFramework - Installed AtmosphereInterceptor  Track Message Size Interceptor using | with priority BEFORE_DEFAULT 
[WARNING ] Detected JSESSIONID with invalid length; expected length of 23, found 28, setting: 7CF2B7D1E23D575CFAE889B756BD to null.
[err] [Default Executor-thread-7] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
[ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [com.vaadin.cdi.CdiServletDeployer] in application [skeleton_starter_flow_cdi_war]: java.lang.NoClassDefFoundError: javax/enterprise/inject/AmbiguousResolutionException
	at com.vaadin.cdi.CdiVaadinServletService.<init>(CdiVaadinServletService.java:79)
	at com.vaadin.cdi.CdiVaadinServlet.createServletService(CdiVaadinServlet.java:92)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:185)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
	at com.vaadin.cdi.CdiVaadinServlet.init(CdiVaadinServlet.java:56)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:291)
	at [internal classes]

[ERROR   ] SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5075)
	at [internal classes]
Caused by: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:360)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: javax/enterprise/inject/AmbiguousResolutionException
	at com.vaadin.cdi.CdiVaadinServletService.<init>(CdiVaadinServletService.java:79)
	at com.vaadin.cdi.CdiVaadinServlet.createServletService(CdiVaadinServlet.java:92)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:185)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
	at com.vaadin.cdi.CdiVaadinServlet.init(CdiVaadinServlet.java:56)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:291)
	... 1 more

[WARNING ] Detected JSESSIONID with invalid length; expected length of 23, found 28, setting: 6672900CD0868501043261448E0C to null.
[ERROR   ] SRVE0271E: Uncaught init() exception created by servlet [com.vaadin.cdi.CdiServletDeployer] in application [skeleton_starter_flow_cdi_war]: java.lang.NoClassDefFoundError: javax/enterprise/inject/AmbiguousResolutionException
	at com.vaadin.cdi.CdiVaadinServletService.<init>(CdiVaadinServletService.java:79)
	at com.vaadin.cdi.CdiVaadinServlet.createServletService(CdiVaadinServlet.java:92)
	at com.vaadin.flow.server.VaadinServlet.createServletService(VaadinServlet.java:185)
	at com.vaadin.flow.server.VaadinServlet.init(VaadinServlet.java:72)
	at com.vaadin.cdi.CdiVaadinServlet.init(CdiVaadinServlet.java:56)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:291)
	at [internal classes]
```

**Comment by joheriks** [comment]
Core issue may be #7542.

**Comment by pleku** [comment]
To be investigated if this still reproduces
