### ISSUE TITLE
DevModeHandler not initialized on WebSphere Application Server 9

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#7542]
Synopsis: `DevModeHandler` fails to start when deploying a devmode WAR packaged inside an EAR to WAS 9.0.5.21 using IntellIJ Ultimate's WebSphere integration. Deploying a production mode WAR using the same steps as below works.

To reproduce:
1. Install IBM WebSphere Application Server and create a standard profile using the included WebSphere Customization Toolbox.
2. Download [skeleton-starter-flow-ws.zip](https://github.com/vaadin/flow/files/4185340/skeleton-starter-flow-ws.zip) and import both `pom.xml` and `pom-ear.xml` into IntelliJ (Ultimate Edition). This is the basic skeleton starter with added IntelliJ run configuration and a pom for wrapping the built WAR file in an EAR file (as WAS cannot directly deploy WAR files.)
3. Run `mvn -f pom.xml install` to install the WAR and `mvn -f pom-ear.xml` to package it into an EAR file.
4. Update the existing run configuration or create a new configuration for the installed WebSphere that deploys the artifact `deployment:ear` to your WebSphere installation.
5. Run the configuration and navigate in a browser to `localhost:9080/base`.
6. Application fails with the following `NullPointerException` because `DevModeHandler` is never started (due to the test `registrations.isEmpty()` in `DevModeInitializer::onStartup` being positive).

```
[2/11/20 11:40:52:674 EET] 00000099 SystemErr     R [Thread-59] INFO com.vaadin.flow.server.osgi.OSGiAccess - Unable to detect used OSGi framework version due to null
[2/11/20 11:40:53:236 EET] 00000099 SystemErr     R [Thread-59] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet with name com.vaadin.flow.server.startup.ServletDeployer to /*
[2/11/20 11:40:54:908 EET] 000000b7 SystemErr     R [WebContainer : 0] WARN com.vaadin.flow.server.DefaultDeploymentConfiguration - 
====================================================================
Vaadin is running in DEBUG MODE.
In order to run your application in production mode and disable debug features, you should enable it by setting the servlet init parameter productionMode to true.
See https://vaadin.com/docs/v14/flow/production/tutorial-production-mode-basic.html for more information about the production mode.
====================================================================
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R [WebContainer : 1] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R java.lang.NullPointerException
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsAssetsByChunkName(FrontendUtils.java:693)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.appendNpmBundle(BootstrapHandler.java:907)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupFrameworkLibraries(BootstrapHandler.java:889)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.setupDocumentHead(BootstrapHandler.java:768)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler$BootstrapPageBuilder.getBootstrapPage(BootstrapHandler.java:537)
[2/11/20 11:41:15:189 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:478)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1235)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:779)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:478)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1124)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:82)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:963)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:382)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:465)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:532)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:318)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.ready(HttpInboundLink.java:289)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:214)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:113)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
[2/11/20 11:41:15:205 EET] 000000b8 SystemErr     R 	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
```

Versions:
- WebSphere Application Server 9.0.5.21
- Vaadin 14.2-SNAPSHOT
- Windows 10

**Comment by joheriks** [comment]
The same issue also occurs with WebSphere Liberty (20.0.0.1).

**Comment by jm-ferreira** [comment]
After investigation, it seems that because IBM Websphere is using a `VaadinServlet`, its behaviour is different from when deploying using Jetty, as it has its own set of Servlets.
What seems to be happening is that when a `VaadinServlet` is automatically created, no `ServletRegisration` is found when running `ServletContext::getServletRegistrations` and because of this `DevModeHandler` is never initialised. Upon further investigation, this lack of registrations could be happening because `DevModeInitializer::onStartup` is executing before `ServletDeployer::createServletIfNotExists`.

**Comment by denis-anisimov** [comment]
This is very weird behavior which may be caused by a bug in WebSphere.

`DevModeInitializer` is a `ServletContainerInitializer` which should be run with the web app :

```
Interface which allows a library/runtime to be notified of a web
 application's startup phase and perform any required programmatic
 registration of servlets, filters, and listeners in response to it.
```

And as I understand `ServletContainerInitializer`  is always executed before any `@WebListener`.

At the same time `DevModeInitializer`  is a  `@WebListener` (it implements `ServletContextListener`).

`ServletDeployer`  is "kind of"  a  `@WebListener` : it could have been a  `@WebListener`  but because of ordering it's a part of `ServletContextListeners`  class which delegates to `ServletDeployer`  and `JSR356WebsocketInitializer`.

It might be that WebSphere uses `@WebListener` as an indicator that `DevModeInitializer` can be run later on and disregard the fact that `DevModeInitializer` is also a `ServletContainerInitializer` .

So I may suggest to do :
- first remove `@WebListener` from `DevModeInitializer` and see what happens 
- if it fixes the issue then `DevModeInitializer`  should not be a `@WebListener`  but some other class should be `@WebListener` . The only reason why  `DevModeInitializer` is a web listener is : it stops the handler when the context is destroyed . I don't think we even need this functionality nowadays. But it may be moved to another class for sure (e.g. nested).
- if it doesn't fix then `ServletContainerInitializer` needs to be forced to be executed before any `@WebListener`  somehow ( not sure how ) similarly to `ServletContextListeners`  : the only problem `ServletContainerInitializer`  is not the same as `ServletContextListener`.
