### ISSUE TITLE
NPE in migration tool CopyResourcesStep

### ISSUE THREAD

**Issue by javier-godoy** [vaadin/flow#7649]
Execution of the migration tool fails with the following exception at [CopyResourcesStep:130](https://github.com/vaadin/flow/blob/aa78ddcd9e65a5b1837ba19a02c7d17dc0eba49d/flow-migration/src/main/java/com/vaadin/flow/migration/CopyResourcesStep.java#L130)

```
Caused by: java.lang.NullPointerException
at com.vaadin.flow.migration.CopyResourcesStep$HtmlImportRewriter.adjustContent (CopyResourcesStep.java:130)
at com.vaadin.flow.migration.CopyResourcesStep$HtmlImportRewriter.handle (CopyResourcesStep.java:84)
at com.vaadin.flow.migration.AbstractCopyResourcesStep$CopyFileVisitor.visitFile (AbstractCopyResourcesStep.java:88)
at com.vaadin.flow.migration.AbstractCopyResourcesStep$CopyFileVisitor.visitFile (AbstractCopyResourcesStep.java:68)
at java.nio.file.Files.walkFileTree (Files.java:2803)
at java.nio.file.Files.walkFileTree (Files.java:2875)
at com.vaadin.flow.migration.AbstractCopyResourcesStep.doCopyResources (AbstractCopyResourcesStep.java:186)
at com.vaadin.flow.migration.AbstractCopyResourcesStep.copyResources (AbstractCopyResourcesStep.java:178)
at com.vaadin.flow.migration.CopyResourcesStep.copyResources (CopyResourcesStep.java:191)
at com.vaadin.flow.migration.Migration.migrate (Migration.java:171)
at com.vaadin.flow.plugin.maven.MigrateMojo.execute (MigrateMojo.java:120)
```

No information is provided in the log about what file caused that.

Vaadin 14.1.17

**Comment by mehdi-vaadin** [comment]
@javier-godoy how can it be reproduced? Can you provide a minimal reproducing example? Maybe an HTML file including a polymer template that causes this Exception would be enough.

**Comment by javier-godoy** [comment]
@mehdi-vaadin This issue was reported by a customer. We couldn't identify an example since there is no filename in the log.

**Comment by pleku** [comment]
Without a file name we would have to start just endlessly trying out things to try to get this reproduced. I don't think that is a good way to spend our limited time.

Closing this issue as not reproducible, please file a new issue with instructions on how to reproduce if still relevant.

**Comment by javier-godoy** [comment]
@pleku I share your concern. It's hard to provide a reproducible example when there is only an uncaught exception in the log.

**Comment by mvysny** [comment]
Instead of closing as WON'T FIX, the source can be hardened. Looking at CopyResourcesStep:130, the `body` variable is clearly null, which means that there is a html file which clearly has no body. If this can happen, simply return from the function. If this should not happen, add a simple check which will fail with an informative error message!

```
            if (body == null) {
                throw new IllegalArgumentException("File " + file + " has no <body> element");
            }
```

**Comment by mvysny** [comment]
Indeed, when I added the lines above, recompiled the migration tool on the 2.6 branch and ran it, the exception is now much more informative:
```
Exception in thread "main" java.lang.IllegalArgumentException: File ./src/main/webapp/frontend/flowgraph/node_modules/paper/dist/docs/index.html has no <body> element
	at com.vaadin.flow.migration.CopyResourcesStep$HtmlImportRewriter.adjustContent(CopyResourcesStep.java:113)
	at com.vaadin.flow.migration.CopyResourcesStep$HtmlImportRewriter.handle(CopyResourcesStep.java:84)
	at com.vaadin.flow.migration.AbstractCopyResourcesStep$CopyFileVisitor.visitFile(AbstractCopyResourcesStep.java:88)
```

The HTML file in question is:
```html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Paper.js v0.12.0</title>
</head>
<frameset cols="230,*">
<frame src="classes/index.html" name="packageListFrame" title="All Packages">
<frame src="about:blank" name="class-frame" title="Class and interface descriptions">
</frameset>
</html>
````
It can be safely skipped.
