### ISSUE TITLE
StateNode#handleOnAttach exception message should be improved

### ISSUE THREAD

**Issue by thigg** [vaadin/flow#7813]
I ran into this exception: https://github.com/vaadin/flow/blob/907cbbd59612ac2e31daf5c1566fb48529d75200/flow-server/src/main/java/com/vaadin/flow/internal/StateNode.java#L705-L706
When you get it, the stack trace gives you no hint what this is about:
```
Unexpected exception occured: java.lang.IllegalStateException: Can't change id once it has been ass
igned
        at com.vaadin.flow.internal.StateNode.handleOnAttach(StateNode.java:705)
        at com.vaadin.flow.internal.StateNode.lambda$onAttach$1(StateNode.java:312)
        at com.vaadin.flow.internal.StateNode.visitNodeTreeBottomUp(StateNode.java:669)
        at com.vaadin.flow.internal.StateNode.onAttach(StateNode.java:311)
        at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:270)
        at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:78)
        at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:53)
        at com.vaadin.flow.internal.nodefeature.ElementChildrenList.add(ElementChildrenList.java:42)
        at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.insertChild(AbstractNodeStateProvider.java:102)
        at com.vaadin.flow.dom.Node.insertChild(Node.java:250)
        at com.vaadin.flow.dom.Node.appendChild(Node.java:141)
        at com.vaadin.flow.data.provider.AbstractComponentDataGenerator.registerRenderedComponent(AbstractComponentDataGenerator.java:128)
        at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:84)
        at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.vaadin.flow.data.provider.CompositeDataGenerator.generateData(CompositeDataGenerator.java:47)
        at com.vaadin.flow.data.provider.DataCommunicator.generateJson(DataCommunicator.java:660)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
...
```

Expected behavior: it should at least tell, what kind of  id is the problem.

**Comment by denis-anisimov** [comment]
You are right that the exception message is quite cryptic.
But unfortunately it's not clear how to make it better.

The exception happens on the low level. And this level doesn't know anything about the cause of this on the top level.
And there is no any way to know this cause on the low level.

So there should be a context in which the exception happens: could you please provide an sample code which causes the exception.
We probably should throw another exception on the top abstraction layer preventing this one.

**Comment by thigg** [comment]
I finally found the cause: find the minimal non working example here:
https://github.com/thigg/vaadin-flow-issue-7813

To reproduce the error, simply switch tabs working->buggy->working->buggy -> error

The bug is caused by this line: https://github.com/thigg/vaadin-flow-issue-7813/blob/18d66c9cfe446f3559f4d14cde3e465c29345ac1/src/main/java/org/example/BuggyView.java#L14
It is fixed, when `new Image()` is used instead of `EMPTY_IMAGE`

**Comment by denis-anisimov** [comment]
I'm pretty sure I've seen already the same report.
Give me a moment, I will find it.
This is not about the exception message.
This is just a bug in our code : so normally you should not see this exception ever.

**Comment by denis-anisimov** [comment]
Unfortunately I cannot find the similar bug.
I'm not sure in which repo it is.
But the reason of the behavior is  :
`private static final Image EMPTY_IMAGE = new Image();`.

You are using the same image component in every column with the renderer:
`addColumn((new IconRenderer<>((group) -> EMPTY_IMAGE)));`

Instead this should be a new component generated every time when `SerializableFunction` in the CTOR is called.
The low level API `handleOnAttach` doesn't know anything about that incorrect usage.
So there should be a check inside `IconRenderer` which tries to predict such situations and throws an exception based on this top level logic.

**Comment by thigg** [comment]
Maybe it could give an unspecific hint like:

    Can't change id once it has been assigned. (This is most likely a bug somewhere else.)

I could imagine that this would help. I basically bisected components from the page as long as i got to the source, but it cost me a long time until i figured, that the source of the problem must be somewhere else.

Is there already an Issue for IconRenderer, or will you create one?

**Comment by denis-anisimov** [comment]
The reason of the behavior is the code: 
` addColumn((new IconRenderer<>((group) -> EMPTY_IMAGE)));`

Here the `EMPTY_IMAGE`  is a singleton.
So the same component is used for rendering everywhere.
Since component is used directly : it's not possible to have the same component attached in many different places.
So singleton may not be  used with renderers.
In the end it's a user error. 
But we should be able to report this error in a proper way : as  a ticket says.

**Comment by denis-anisimov** [comment]
I cannot reproduce this issue anymore.
The behavior is "expected": the image is shown only once .
Since the same component is used all the time : it's removed from the previous parent and added to a new one.
As a result only one row contains the component.

BUT. There is an exception if I reload the page.
And that is again expected : the component used in one `UI`  is using now in another `UI`  which is unsupported.

So the correct steps to reproduce are:
- use https://github.com/vaadin/skeleton-starter-flow
- Chane `MainView` to :
```
public class MainView extends VerticalLayout {

    private static final Text EMPTY_IMAGE = new Text("foo");

    public MainView() {
        Grid<String> grid = new Grid<>();
        grid.addColumn(new IconRenderer<>((group) -> EMPTY_IMAGE));
        grid.setItems(IntStream.range(0, 10).mapToObj(i -> "a"));
        add(grid);
    }
}
```
-start the project
- open http://localhost:8080/ URL  browser 
- the page should be loaded without errors
- reload the page
- now there is an error on the page and an exception is thrown

```
java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree
	at com.vaadin.flow.internal.StateNode.doSetTree(StateNode.java:717)
	at com.vaadin.flow.internal.StateNode.lambda$setTree$3(StateNode.java:370)
	at com.vaadin.flow.internal.StateNode.visitNodeTree(StateNode.java:670)
	at com.vaadin.flow.internal.StateNode.setTree(StateNode.java:370)
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:270)
	at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:78)
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:53)
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.add(ElementChildrenList.java:42)
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.insertChild(AbstractNodeStateProvider.java:102)
	at com.vaadin.flow.dom.Node.insertChild(Node.java:294)
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141)
	at com.vaadin.flow.data.provider.AbstractComponentDataGenerator.registerRenderedComponent(AbstractComponentDataGenerator.java:128)
	at com.vaadin.flow.data.provider.ComponentDataGenerator.generateData(ComponentDataGenerator.java:84)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.lambda$generateData$0(CompositeDataGenerator.java:47)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.generateData(CompositeDataGenerator.java:47)
	at com.vaadin.flow.data.provider.DataCommunicator.generateJson(DataCommunicator.java:1353)
```

**Comment by MathiasAugstein** [comment]
I tried to recreate this exception using Vaadin 14.5.1 to create a Kubernetes Liveness Probe for this exact exception (as it puts the server in a non-operating state without Kubernetes noticing), but was not able to.
Does the exception no longer occur? Does Vaadin recover safely from this exception?

**Comment by TatuLund** [comment]
The exception is still throw in other case, but the text has been changed to give better hint, what is the likely cause so that it is easier to address the issue in application code.

"The component '"
                    + component.getClass()
                    + "' is already attached to a UI instance which differs "
                    + "from the conainer's UI instance. It means that the component instance is "
                    + "reused instead being produced every time on 'createComponent' call."
                    + " Check whether the component instance is a singleton or has inappropriate Spring scope.");
                    
                    
 OR, logging warning

            if (renderedComponent.getParent().isPresent()) {
                LoggerFactory.getLogger(ComponentDataGenerator.class).warn(
                        "The 'createComponent' method returned a component '{}' which already has a parent."
                                + " It means that most likely your component renderer '{}' class is implemented incorrectly",

**Comment by pleku** [comment]
> I tried to recreate this exception using Vaadin 14.5.1

@MathiasAugstein please note that 14.5 has been unsupported since May 2021 , I'd advice you to update to the latest minor version 14.7.
