### ISSUE TITLE
Navigating on a page that contains an embedded component result in Internal Error

### ISSUE THREAD

**Issue by martinisraelsen** [vaadin/flow#7883]
I have a page with an embedded component. If you use the browser buttons to navigate it can result in an internal error.

![Screen Shot 2020-03-25 at 8 09 36 AM](https://user-images.githubusercontent.com/6271003/77540412-099f0e00-6e71-11ea-954c-03984f07a694.png)

```
java.lang.UnsupportedOperationException: Unexpected message id from the client. Expected sync id: 4, got 0. Message start: {"csrfToken":"05f072c9-2ed1-49c7-a066-78da0ff75115","rpc":[{"type":"event","node":1,"event":"connect-web-component","data":{"tag":"embedded-component","id":"EmbeddedComponent-0","userAssignedId":"","attributeValues":{}}}],"syncId":0,"clientId":0}
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:307) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1540) ~[flow-server-2.1.6.jar:2.1.6]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) [flow-server-2.1.6.jar:2.1.6]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at bc.embedded.WebComponentServlet.service(WebComponentServlet.java:29) [classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.27.jar:9.0.27]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.27.jar:9.0.27]

```

To reproduce:
- Run the attached application with mvn spring-boot:run. 
- Go to localhost:8080/embedded
- Click one of the buttons
- Click the browser back button
- Click the browser forward button

In the real-world app, the error happens simply when clicking back on a page that has an embedded component. In this test app it's necessary to click back and forward to reproduce the same error message/stack trace.

[embedded-app.zip](https://github.com/vaadin/flow/files/4381051/embedded-app.zip)

**Comment by martinisraelsen** [comment]
Forgot to mention it's Vaadin 14.1.18 NPM mode.

**Comment by caalador** [comment]
Hi.
I couldn't replicate this exception according to the steps. 
The downloaded project was using 14.1.21 so perhaps this has been fixed since 14.1.18?
Also what page should be there to go back to? Tried with localhost:8080/ and an external page.
Should this happen with all browsers?

**Comment by martinisraelsen** [comment]
@caalador I was able to get it to happen but going to localhost:8080 and then localhost:8080/embedded, then back-button and then forward-button. However, I opened the app again and ran it and this time I was not able to replicate the issue. We can close this ticket. I can reopen or create a new ticket if it happens again. Thanks for your help.

**Comment by caalador** [comment]
I'll close this issue. Comment here with new information or create a new ticket if the issue somehow reappears.
