### ISSUE TITLE
Vaadin 14.1.25 ignore Vaadin properties if deployed in Apache Tomcat

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/flow#8050]
Environment:
Apache Tomcat 9.0.34
Vaadin 14.1.25
Gradle 6.3
Spring Boot 2.2.6
OpenJDK 11.0.2

Conditions:
Gradle task bootWar and bootJar
classes/config/application.properties contains:
vaadin.compatibilityMode=true
vaadin.productionMode=true
vaadin.original.frontend.resources=true

Case 1) bootJar
java -jar xy.jar
Seems work OK so possibly uses resources done in webjars
Case2) bootWar 
tomcat/bin/startup

Leads to error as seems ignore configuration (even if set setenv to extend CATALINA_OPTS by -DcompatibilityMode=true -Doriginal.frontend.resources=true):
...
Vaadin requires node.js & npm to be installed. Please install the latest LTS version of node.js (with npm) either by:
...
 at com.vaadin.flow.server.frontend.TaskRunNpmInstall.runNpmInstall(TaskRunNpmInstall.java:93)
        at com.vaadin.flow.server.frontend.TaskRunNpmInstall.execute(TaskRunNpmInstall.java:64)
        at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:430)
        at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:281)
        at com.vaadin.flow.server.startup.DevModeInitializer.process(DevModeInitializer.java:182)
        at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:76)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5140)
...
at com.vaadin.flow.server.frontend.FrontendUtils.getExecutable(FrontendUtils.java:369)
        at com.vaadin.flow.server.frontend.FrontendUtils.getNpmExecutable(FrontendUtils.java:323)
        at com.vaadin.flow.server.frontend.TaskRunNpmInstall.runNpmInstall(TaskRunNpmInstall.java:90)
...
at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:292)
                at com.vaadin.flow.server.startup.DevModeInitializer.process(DevModeInitializer.java:182)
                at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:76)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5140)

In context:
https://vaadin.com/docs/v14/flow/advanced/tutorial-all-vaadin-properties.html

Expected behaviour:
No error and works perfectly as "java -jar" so as even like 10-13 version with no compatibilityMode.
That includes no creation of "target" folder and file package.json under bin.

**Comment by juhopiirainen** [comment]
Thanks for the ticket @netbeansuser2019. I'll transfer this to the Flow team for further investigations.

**Comment by pleku** [comment]
Hi @netbeansuser2019 what are the Gradle tasks you're mentioning 
>Gradle task bootWar and bootJar

Where do those come from ?

**Comment by netbeansuser2019** [comment]
It is default spring plugin task for Gradle that just pack jar and war according to spring framework.

**Comment by caalador** [comment]
The `CATALINA_OPTS` should start with the vaadin prefix like `-Dvaadin.compatibilityMode=true -Dvaadin.original.frontend.resources=true`

Another choice would be to add the file `META-INF/VAADIN/config/flow-build-info.json` to the resources dierectory (so that it ends up with compiled classes) with the content
```json
{
  "compatibilityMode": true
}
```
This will then force compatibility mode in all cases

**Comment by netbeansuser2019** [comment]
Sorry to say, but it is not so well solution.
1) It is not possibly to rely on CATALINA_OPTS as:
1.1) one customer can use jar deployment and another one can use war
1.2) possibly needs reset each and every deployments
2) about ...json
2.1) it sounds little bit hardcode and if there is any decision from your side like renaming that could be issue
2.2) having extra configuration is not so good
2.3) possibly needed to change building e.g. if there is need different deployments 

All in all I would like to rather to see it functional as any other via application.properties.

**Comment by caalador** [comment]
For running the application in compatibility mode I wouldn't count the json as an extra source as it would just be there to force the mode. 
If you weren't using compatibility I would suggest using the plugin https://github.com/vaadin/vaadin-gradle-plugin as for creating a production build there are many things to collect at build time.

**Comment by pleku** [comment]
Closing the issue due to inactivity and since it is not clear what we should do at this point. In case there are still problems when using the official Vaadin gradle plugin, please create a new issue.

**Comment by netbeansuser2019** [comment]
> 
> 
> For running the application in compatibility mode I wouldn't count the json as an extra source as it would just be there to force the mode.
> If you weren't using compatibility I would suggest using the plugin https://github.com/vaadin/vaadin-gradle-plugin as for creating a production build there are many things to collect at build time.

@pleku 
@caalador 
It is always as extra source and especially if it is relevant only if it is deployed as war. So you do not need that file in case of running in IDE (properly respect application.properties), running as jar  (properly respect application.properties), but only in case of WAR. I do not see reason why you do not properly find that "application.properties" in WAR deployment.

I do not see a reason to have another configuration file, by the way as there is another one via META-INF/services just due to Vaadin itself.
