### ISSUE TITLE
Flow 3.0 All Tests (including slow and push) build fails

### ISSUE THREAD

**Issue by mehdi-vaadin** [vaadin/flow#8120]
https://bender.vaadin.com/viewLog.html?buildId=141451&tab=buildResultsDiv&buildTypeId=Flow_Nightly_FlowAllTestsIncludingSlowAndPush

**Comment by denis-anisimov** [comment]
The reason of failure is :
```
 UnknownError: [POST http://localhost:4444/wd/hub/session / {"desiredCapabilities":{"name":"intern","idle-timeout":60,"browserName":"chrome","chromeOptions":{"args":["headless","disable-gpu","window-size=1024x768"]},"browser":"chrome"}}] unknown error: Chrome failed to start: exited abnormally.
[09:19:20] :	 [Step 3/3]   (unknown error: DevToolsActivePort file doesn't exist)
[09:19:20] :	 [Step 3/3]   (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[09:19:20] :	 [Step 3/3] Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
[09:19:20] :	 [Step 3/3] System info: host: 'ip-172-16-1-184.eu-west-1.compute.internal', ip: '172.16.1.184', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.123-111.109.amzn2.x86_64', java.version: '1.8.0_201'
[09:19:20] :	 [Step 3/3] Driver info: driver.version: unknown
[09:19:20] :	 [Step 3/3] remote stacktrace: #0 0x55fab2203d29 <unknown>
[09:19:20] :	 [Step 3/3] 
[09:19:20] :	 [Step 3/3]   at Server.post @ node_modules/src/Server.ts:384:16
[09:19:20] :	 [Step 3/3]   at Server.createSession @ node_modules/src/Server.ts:429:16
[09:19:20] :	 [Step 3/3]   at Suite.before @ src/lib/executors/Node.ts:488:15
[09:19:20] :	 [Step 3/3]   @ src/lib/Suite.ts:435:54
[09:19:20] :	 [Step 3/3]   at new e @ node_modules/@theintern/common/index.js:16:5068
[09:19:20] :	 [Step 3/3]   at runLifecycleMethod @ src/lib/Suite.ts:400:13
[09:19:20] :	 [Step 3/3]   at before @ src/lib/Suite.ts:503:13
[09:19:20] :	 [Step 3/3]   at Suite.run @ src/lib/Suite.ts:522:10
[09:19:20] :	 [Step 3/3]   @ src/lib/executors/Node.ts:974:27
[09:19:20] :	 [Step 3/3]   at FunctionQueue.next @ src/lib/executors/Node.ts:1102:19
```
the  reason is the same for all branches starting from `3.0` : `3.1`, `3.2`.

**Comment by haijian-vaadin** [comment]
This ticket can be closed as it's green now. https://bender.vaadin.com/viewLog.html?buildId=144734&tab=buildResultsDiv&buildTypeId=Flow_Nightly_FlowAllTestsIncludingSlowAndPush
