### ISSUE TITLE
DevModeInitializer generates ClassNotFoundException for WildFly builtin servlets

### ISSUE THREAD

**Issue by fomich-artem** [vaadin/flow#8149]
Vaadin 14.2.0.beta1
WildFly 16.0.0.Final

Greetings!

After upgrading Vaadin from 14.1.23 to 14.2.0.beta1 we have exceptions at deployment time

```
Caused by: javax.servlet.ServletException: Servlet class name (io.undertow.servlet.handlers.DefaultServlet) can't be found!
	at com.vaadin.flow.server.startup.DevModeInitializer.process(DevModeInitializer.java:194)
	... 26 more
Caused by: java.lang.ClassNotFoundException: io.undertow.servlet.handlers.DefaultServlet from [Module "deployment.openicarStart.ear" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.vaadin.flow.server.startup.DevModeInitializer.isVaadinServletSubClass(DevModeInitializer.java:214)
	at com.vaadin.flow.server.startup.DevModeInitializer.process(DevModeInitializer.java:187)
	... 26 more
```

at the same point

`java.lang.ClassNotFoundException: org.apache.jasper.servlet.JspServlet`

WildFly application server has class-loading isolation in modules and Vaadin's behavior in my opinion is not entirely correct. Can this be fixed (by ignoring ClassNotFoundException)?

Workaround that helps us is append dependencies to jboss-deployment-structure:

```
<module name="io.undertow.servlet" export="true" />
<module name="io.undertow.jsp" export="true" />
```

Thanks!

**Comment by Legioth** [comment]
I guess we need to catch and ignore those exceptions in `isVaadinServletSubClass`. We used to have similar logic in other places also for the same reason, but it seems like it's missing for this case.

**Comment by pleku** [comment]
Thanks for clear issue. Since there is a workaround available, we have not set this as critical severity but we'll still put it on top-ish of the bug backlog as it is related to an upcoming version.
