### ISSUE TITLE
Dynamic register route doesn't work

### ISSUE THREAD

**Issue by yurili8** [vaadin/flow#8415]
I create some views.  if I add the annotation "Route" to the view class , it works well:

`@Route(value = UserViewImpl.ROUTE, layout = SMSConfigurationWorkspace.class)
public class UserViewImpl extends BaseViewWithToolbar {
`

but if I register it as the application scope view like this:
`@Component
public class ConfigureUIServiceInitListener implements VaadinServiceInitListener {

	private static Logger log = LoggerFactory.getLogger(ConfigureUIServiceInitListener.class);

	@Autowired
	private IMenuConfigService menuService;

	@SuppressWarnings("unchecked")
	@Override
	public void serviceInit(ServiceInitEvent event) {
		event.getSource().addUIInitListener(uiEvent -> {
			final UI ui = uiEvent.getUI();
			ui.addBeforeEnterListener(this::beforeEnter);
		});

	    RouteConfiguration.forApplicationScope().setRoute("user",UserViewImpl.class,SMSConfigurationWorkspace.class);

	}`

After I restart the application, when I enter the page first time, it seems everything works well, I could enter the page well. but if I refresh the page, it will just hang there and show the following error in the backend:

`java.lang.IllegalStateException: Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree
	at com.vaadin.flow.internal.StateNode.doSetTree(StateNode.java:701) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.internal.StateNode.lambda$setTree$3(StateNode.java:364) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.internal.StateNode.visitNodeTree(StateNode.java:660) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.internal.StateNode.setTree(StateNode.java:364) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.internal.StateNode.setParent(StateNode.java:264) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.internal.nodefeature.NodeFeature.attachPotentialChild(NodeFeature.java:78) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.add(StateNodeNodeList.java:53) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.add(ElementChildrenList.java:42) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.insertChild(AbstractNodeStateProvider.java:102) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.dom.Node.insertChild(Node.java:294) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.dom.Node.appendChild(Node.java:141) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.component.internal.UIInternals.showRouteTarget(UIInternals.java:733) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:252) ~[flow-server-2.2.0.jar:2.2.0]
	at com.vaadin.flow.router.Router.handleNavigation(Router.java:249) [flow-server-2.2.0.jar:2.2.0]`

and If I change to another browser, it will throw the following exception:

`java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.

	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:527)

	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:541)

	at com.vaadin.flow.internal.StateTree.checkHasLock(StateTree.java:408)

	at com.vaadin.flow.internal.StateTree.markAsDirty(StateTree.java:279)

	at com.vaadin.flow.internal.StateNode.markAsDirty(StateNode.java:548)

	at com.vaadin.flow.internal.nodefeature.NodeList.addChange(NodeList.java:277)

	at com.vaadin.flow.internal.nodefeature.NodeList.remove(NodeList.java:256)

	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.remove(StateNodeNodeList.java:64)

	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.remove(ElementChildrenList.java:52)

	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeChild(AbstractNodeStateProvider.java:125)

	at com.vaadin.flow.dom.Node.removeChild(Node.java:376)

	at com.vaadin.flow.dom.Element.removeFromParent(Element.java:577)

	at com.vaadin.flow.dom.Node.insertChild(Node.java:293)

	at com.vaadin.flow.dom.Node.appendChild(Node.java:141)

	at com.vaadin.flow.component.HasComponents.add(HasComponents.java:53)

	at com.vaadin.flow.component.orderedlayout.VerticalLayout.<init>(VerticalLayout.java:57)

	at com.yuri.sms.platform.view.component.tabs.TabWidget.select(TabWidget.java:67)

	at com.yuri.sms.platform.view.component.tabs.TabWidget.lambda$0(TabWidget.java:49)

	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205)

	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:194)

	at com.vaadin.flow.component.Component.fireEvent(Component.java:359)

	at com.vaadin.flow.component.tabs.Tabs.updateSelectedTab(Tabs.java:487)

	at com.vaadin.flow.component.tabs.Tabs.lambda$new$c53a20e4$1(Tabs.java:77)

	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.lambda$fireEvent$2(ElementPropertyMap.java:452)

	at java.util.ArrayList.forEach(Unknown Source)

	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.fireEvent(ElementPropertyMap.java:452)

	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.access$100(ElementPropertyMap.java:48)

	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap$PutResult.run(ElementPropertyMap.java:163)

	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.put(ElementPropertyMap.java:145)

	at com.vaadin.flow.internal.nodefeature.AbstractPropertyMap.setProperty(AbstractPropertyMap.java:60)

	at com.vaadin.flow.internal.nodefeature.ElementPropertyMap.setProperty(ElementPropertyMap.java:92)
`

**Comment by caalador** [comment]
It's really hard to say about the problem with the given information.
Could you create a minimal application that would reproduce the problem?

**Comment by yurili8** [comment]
Finally it is proved to be my mistake.
I create one custome component with spring annotation"@Component", it is singleton by default. 
After I add @UIScope, it is working now.

Thanks.
