### ISSUE TITLE
Starting a Vaadin 16 app with Node 14 on Mac prints 1172 error lines

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#8432]
```
vaadin init --pre test16
cd test16
mvn
```

```
2020-05-27 15:43:15.669  INFO 37473 --- [nPool-worker-19] com.vaadin.flow.server.DevModeHandler    : Started webpack-dev-server. Time: 8375ms
(node:37536) UnhandledPromiseRejectionWarning: TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:93:25)
    at setFSEventsListener (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:148:16)
    at FsEventsHandler._watchWithFsEvents (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:352:18)
    at FsEventsHandler.initWatch (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:429:23)
    at FsEventsHandler._addToFsEvents (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:518:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37536) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37536) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:37536) UnhandledPromiseRejectionWarning: TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:93:25)
    at setFSEventsListener (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:148:16)
    at FsEventsHandler._watchWithFsEvents (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:352:18)
    at FsEventsHandler.initWatch (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:429:23)
    at FsEventsHandler._addToFsEvents (/Users/artur/tmp/tst-16/node_modules/.pnpm/registry.npmjs.org/chokidar/3.4.0/node_modules/chokidar/lib/fsevents-handler.js:518:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
...
```

Most probably related to #8278

**Comment by alvarezguille** [comment]
Same issue on macOS 10.15.4 with
* node v12.1.0
* npm 6.13.7
* no global pnpm

**Comment by Artur-** [comment]
Apparent workaround:
```
pnpm i --save-dev chokidar@3.4.0
```

**Comment by pleku** [comment]
Quick fix for pnpm could be to just make the `pnpmfile.js` to force chokidar to ^ 3.4.0 version

**Comment by mocca-dev** [comment]
Thanks @Artur- for the mention in the other issue. I already solved the problem locally with this fix but I continue having the problem when I deploy to Vercel/Zeit Now. I received the same error message in the logs. 

Now build logs output: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents): 
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by Artur-** [comment]
The npm WARNings are no problems. They just state that you are running on Linux and `fsevents` is only ever needed on Mac

**Comment by mocca-dev** [comment]
> The npm WARNings are no problems. They just state that you are running on Linux and `fsevents` is only ever needed on Mac

you are right. I don't know what happened but now the page is working fine. I think that was a problem with the deploy process form Now side. thank you very much @Artur- !!
