### ISSUE TITLE
VaadinServlet creates the `build/resources/main/META-INF/VAADIN/build` folder causing Gretty to immediately hot-reload the app

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8531]
### Description of the bug
When Vaadin is run in development mode, at some point an empty `build/` folder is created in `META-INF/VAADIN/`, causing Gretty to immediately hot-reload the application. Vaadin 14.2.0, Gradle project, Linux Ubuntu 20.04
### Minimal reproducible example
1. git clone https://github.com/mvysny/karibu10-helloworld-application
2. ./gradlew clean appRun --info

You can see in the terminal that the app starts, then Gretty detects a folder being created:
```
changed file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build affects project :
file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build is in output of :, servlet-container will be restarted
```
and restarts the app immediately.

A workaround would be for Gretty to ignore empty folders and don't hot-reload in such case. I've filed a bug in this regard: https://github.com/gretty-gradle-plugin/gretty/issues/169
### Expected behavior
The app should not be restarted immediately; the empty `build/` folder does not need to be created.
### Actual behavior
The app restarts. I'll attach a full terminal output below.
### Versions:
    - Vaadin / Flow version: 14.2.0/2.2.0
    - Java version: 1.8.0_252
    - OS version: Ubuntu x86-64 20.04
    - Browser version (if applicable): Firefox
    - Application Server (if applicable): Gretty embedded Jetty 9.4
    - IDE (if applicable): Intellij

**Comment by mvysny** [comment]
```
...
15:42:17 WARN  Ignoring deprecated socket close linger time

> Task :appRun
Caching disabled for task ':appRun' because:
  Build cache is disabled
Task ':appRun' is not up-to-date because:
  Task.upToDateWhen is false.

2020-06-09 15:42:19.107 [main] INFO com.vaadin.flow.server.startup.DevModeInitializer - Starting dev-mode updaters in /home/mavi/work/my/vok/karibu10-helloworld-application folder.
2020-06-09 15:42:19.154 [main] INFO dev-updater - Visited 90 classes. Took 32 ms.
2020-06-09 15:42:19.175 [main] INFO dev-updater - Skipping `pnpm install`.
2020-06-09 15:42:19.175 [main] INFO dev-updater - Copying frontend resources from jar files ...
2020-06-09 15:42:19.201 [main] INFO dev-updater - Visited 11 resources. Took 25 ms.
2020-06-09 15:42:19.221 [main] INFO dev-updater - Updated /home/mavi/work/my/vok/karibu10-helloworld-application/target/frontend/generated-flow-imports.js

------------------ Starting Frontend compilation. ------------------
2020-06-09 15:42:19.384 [main] INFO dev-webpack - Running webpack to compile frontend resources. This may take a moment, please stand by...
2020-06-09 15:42:21.642 [main] INFO dev-webpack - Started webpack-dev-server. Time: 26941461ms
2020-06-09 15:42:21.663 [main] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet with name com.vaadin.flow.server.startup.ServletDeployer to /*

=======================================================================

 Vaadin application has started in DEBUG MODE and is available by opening http://localhost:8080/ in the browser.

 NOTE: the server HTTP port may vary - see server log output.

=======================================================================
    15:42:21 INFO  Jetty 9.4.24.v20191120 started and listening on port 8080
15:42:21 INFO   runs at:
15:42:21 INFO    http://localhost:8080/
changed file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN affects project :
file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN is in output of :, servlet-container will be restarted
changed file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build affects project :
file /home/mavi/work/my/vok/karibu10-helloworld-application/build/resources/main/META-INF/VAADIN/build is in output of :, servlet-container will be restarted
15:42:21 WARN  Ignoring deprecated socket close linger time

> Task :appRun
Press any key to stop the server.

2020-06-09 15:42:22.366 [main] INFO com.vaadin.flow.server.startup.DevModeInitializer - Starting dev-mode updaters in /home/mavi/work/my/vok/karibu10-helloworld-application folder.
2020-06-09 15:42:22.406 [main] INFO dev-updater - Visited 90 classes. Took 28 ms.
2020-06-09 15:42:22.420 [main] INFO dev-updater - Skipping `pnpm install`.
2020-06-09 15:42:22.420 [main] INFO dev-updater - Copying frontend resources from jar files ...
2020-06-09 15:42:22.454 [main] INFO dev-updater - Visited 11 resources. Took 33 ms.
2020-06-09 15:42:22.473 [main] INFO dev-updater - No js modules to update '/home/mavi/work/my/vok/karibu10-helloworld-application/target/frontend/generated-flow-imports.js' file

------------------ Starting Frontend compilation. ------------------
2020-06-09 15:42:22.658 [main] INFO dev-webpack - Running webpack to compile frontend resources. This may take a moment, please stand by...
2020-06-09 15:42:24.978 [main] INFO dev-webpack - Started webpack-dev-server. Time: 26944797ms
2020-06-09 15:42:24.991 [main] INFO com.vaadin.flow.server.startup.ServletDeployer - Automatically deploying Vaadin servlet with name com.vaadin.flow.server.startup.ServletDeployer to /*

=======================================================================

 Vaadin application has started in DEBUG MODE and is available by opening http://localhost:8080/ in the browser.

 NOTE: the server HTTP port may vary - see server log output.

=======================================================================
    15:42:25 INFO  Jetty 9.4.24.v20191120 started and listening on port 8080
15:42:25 INFO   runs at:
15:42:25 INFO    http://localhost:8080/
Exception in thread "main" java.lang.NullPointerException
        at org.akhikhl.gretty.Runner$ServerStartEventImpl.onServerStart(Runner.groovy:41)
        at org.akhikhl.gretty.ServerStartEvent$onServerStart.call(Unknown Source)
        at org.akhikhl.gretty.JettyServerManager.startServer(JettyServerManager.groovy:72)
        at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.akhikhl.gretty.Runner.run(Runner.groovy:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.akhikhl.gretty.Runner.main(Runner.groovy:54)
```

**Comment by mvysny** [comment]
Workaround is to make the VAADIN folder unwritable by the app right when the `appRun` task starts executing, e.g. `chown root:root build/resources/main/META-INF/VAADIN`. The `build/` folder is not created anymore. Curiously I expected a Java IOException to be thrown by the offending code which tries to create the `build/` folder, however no such exception is logged anywhere.

**Comment by mvysny** [comment]
Could it be that it's the WebPack who's creating the folder? `webpack.generated.js:32` reads
```
mkdirp(buildFolder);
```

And `buildFolder` is computed as follows:
```
const mavenOutputFolderForFlowBundledFiles = require('path').resolve(__dirname, 'build/resources/main/META-INF/VAADIN');
const buildFolder = `${mavenOutputFolderForFlowBundledFiles}/${build}`;
```

Could it be that VaadinServlet doesn't wait until Webpack fully starts?

**Comment by mvysny** [comment]
Yes, that's it! Commenting the `mkdirp(buildFolder);` command prevents the folder from being created, which in turn prevents Gretty from restarting the app.

**Comment by mshabarov** [comment]
A similar issue had been observed for Jetty - https://github.com/vaadin/flow/issues/7922 and build folder should not be created in dev mode. This fix is in master, but not in `Flow 2.2` for some reason.

**Comment by mvysny** [comment]
Thank you for pointing the bug for me; in fact this bug sounds like a duplicate of #7922 to me, so I'd propose to close this issue.
