### ISSUE TITLE
IdTestIT::testIds fails when running on Windows agent

### ISSUE THREAD

**Issue by mshabarov** [vaadin/flow#8664]
Integration test `com.vaadin.flow.mixedtest.ui.IdTestIT::testIds` is failing when running on Windows Server 2019 agent in TeamCity. This only happens when `gen-dev-deps` maven profile is set.

```
[12:45:12]	[Step 2/2] [ERROR] testIds[ANY_Chrome_](com.vaadin.flow.mixedtest.ui.IdTestIT)  Time elapsed: 313.138 s  <<< ERROR!
[12:45:12]	[Step 2/2] java.lang.RuntimeException: testIds[ANY_Chrome_](com.vaadin.flow.mixedtest.ui.IdTestIT): run failed 2 times
[12:45:12]	[Step 2/2] 	at com.vaadin.testbench.RetryRule$1.evaluate(RetryRule.java:69)
[12:45:12]	[Step 2/2] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[12:45:12]	[Step 2/2] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
[12:45:12]	[Step 2/2] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
[12:45:12]	[Step 2/2] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
[12:45:12]	[Step 2/2] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
[12:45:12]	[Step 2/2] 	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:410)
[12:45:12]	[Step 2/2] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:45:12]	[Step 2/2] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:45:12]	[Step 2/2] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[12:45:12]	[Step 2/2] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[12:45:12]	[Step 2/2] 	at java.lang.Thread.run(Thread.java:748)
[12:45:12]	[Step 2/2] Caused by: java.lang.AssertionError: Failed to load my-component
[12:45:12]	[Step 2/2] 	at org.junit.Assert.fail(Assert.java:88)
[12:45:12]	[Step 2/2] 	at com.vaadin.flow.mixedtest.ui.IdTestIT.waitUntilWithMessage(IdTestIT.java:81)
[12:45:12]	[Step 2/2] 	at com.vaadin.flow.mixedtest.ui.IdTestIT.testIds(IdTestIT.java:41)
```
Error screenshot shows no components and looks like just an empty white rectangle.

Link to Binder job: https://bender.vaadin.com/viewLog.html?buildId=161272&buildTypeId=Flow_Misc_Flow32SnapshotWindows_Flow32SnapshotMasterWindows

**Comment by mshabarov** [comment]
Closed because obsolete. `IdTestIT::testIds` currently passes.
