### ISSUE TITLE
[BUG] Can't encode class java.lang.Long to json

### ISSUE THREAD

**Issue by markathomas** [vaadin/flow#8702]
**Describe the bug**

The Element API doesn't allow encoding of Long values to son though there's nothing technically preventing it in Javascript  AFAIK.

**To Reproduce**
1. Call Element.callJsFunction method with a long value as a parameter

**Expected behavior**
Longs are encoded to JSON

**Desktop (please complete the following information):**
 - Version 14
 - Vaadin platform version 14.2.3

**Additional context**
```
java.lang.IllegalArgumentException: Can't encode class java.lang.Long to json
	at com.vaadin.flow.internal.JsonCodec.encodeWithoutTypeInfo(JsonCodec.java:205)
	at com.vaadin.flow.internal.JsonCodec.encodeWithTypeInfo(JsonCodec.java:92)
	at com.vaadin.flow.component.internal.UIInternals$JavaScriptInvocation.<init>(UIInternals.java:124)
	at com.vaadin.flow.dom.Element.scheduleJavaScriptInvocation(Element.java:1734)
	at com.vaadin.flow.dom.Element.callJsFunction(Element.java:1638)
```

**Comment by Legioth** [comment]
There is actually one limitation here, which is that numbers larger than 2^53 would lose precision since the numeric type in JS is based on 64-bit floating point numbers.

This in itself isn't a reason to not support `java.lang.Long` at all, but it is a small detail to take into account. Preferably, the implementation would throw an exception or at the very least log a warning if trying to encode a value that is larger than supported.

**Comment by markathomas** [comment]
Agreed, it's not just Long that's not supported.  Any number other than Integer and Double faces the same fate.  For example, I shouldn't have to convert a 32-bit float to a 64-bit double, doubling the memory used in the process, to send a value to the FE.
