### ISSUE TITLE
npm install of fsevents 1.x errors

### ISSUE THREAD

**Issue by joheriks** [vaadin/flow#8741]
### To reproduce:
1. Get [base starter for V14](https://github.com/vaadin/skeleton-starter-flow/tree/v14)
2. `mvn jetty:run`
3. Wait for `npm install` stage.

### Expected behavior
Frontend packages are installed silently.

### Actual behavior

The following npm errors are reported:
```
[main] INFO dev-updater - Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
npm WARN lifecycle The node binary used for scripts is /usr/local/bin/node but npm is using /Users/joheriks/.vaadin/node/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn node-gyp EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ]
}
npm WARN no-name@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@babel/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
The application starts up normally.

Versions:
- Vaadin 14.3.1
- Node v12.16.0 (automatically installed into `~/.vaadin`)

**Comment by joheriks** [comment]
Possibly a variant of https://github.com/vaadin/flow/issues/8411.

**Comment by denis-anisimov** [comment]
Everything works fine for me with my `node` version (quite old).

I wasn't able to install `12.16.0` node.
I've upgraded node js to the latest `12.18.0` version and then got this error:

```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/denis/workspace/skeleton-starter-flow/node_modules/@babel/cli/node_modules/fsevents
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

But this is related to my `xcode` tool. I've upgraded it and now everything works fine for me.
It looks like a local env issue.
I return the ticket back since I cannot reproduce it....

**Comment by pleku** [comment]
Let's just update the version that we install to `12.18.3` which is the latest LTS and target that for 4.1 (v18) and 2.4 (v14.4).

**Comment by Artur-** [comment]
This happens at least with Node 14 and V14 that uses npm

I guess it is the same as #8411 as you get chokidar 2.x an fsevents 1.x

This warning in the issue description also sounds like the installed `node` version is not actually used?
```
npm WARN lifecycle The node binary used for scripts is /usr/local/bin/node but npm is using /Users/joheriks/.vaadin/node/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
```

**Comment by mshabarov** [comment]
I'm able to reproduce these errors in the log with Node `v12.16.1` (installed globally) and `V14.3.3`:

```
[main] INFO dev-updater - Running `npm install` to resolve and optionally download frontend dependencies. This may take a moment, please stand by...
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/@babel/cli/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/@babel/cli/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/@babel/cli/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/webpack-dev-server/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mikhail/workspace/vaadin/test/8741/skeleton-starter-flow/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN no-name@ No repository field.

[main] INFO dev-updater - Frontend dependencies resolved successfully.
```

The application is fully operational though. 
Not reproduced with `V17.0.0.beta1`.

**Comment by joheriks** [comment]
The `Error: spawn node-gyp EACCES` are due to missing `node-gyp` during the install phase of `fsevents.1.2.13`. To get rid of the error, `node-gyp` could be added to dev dependencies so that the compilation succeeds, but this is effectively useless as `fsevents.1.2.13` is a transitive dependency of `chokidar.2` which is not used at runtime. It would only serve to make the package installation slower. The installation errors can be safely ignored.

A proper fix requires not having `fsevents.1` in the transitive dependencies. As `npm` does not provide a built-in mechanism for excluding or modifying the version of transitive dependencies, need to wait for webpack to phase out `chokidar.2` (should be done in version 5).

**Comment by joheriks** [comment]
Note that the `fsevents` install errors do not occuring with V17 as it uses `pnpm` by default and currently the [pnpmfile.js read hook](https://github.com/vaadin/flow/blob/master/flow-server/src/main/resources/pnpmfile.js) forcibly updates all transitive `chokidar` dependencies to 3. One way to accomplish the same for npm could be to use [npm-force-resolutions](https://www.npmjs.com/package/npm-force-resolutions) to update `package-lock.json` in the `preinstall` stage.

**Comment by Artur-** [comment]
This was a problem only with webpack
