### ISSUE TITLE
DefaultTemplateParser Fails in OSGi Project

### ISSUE THREAD

**Issue by QNENet** [vaadin/flow#8756]
It is not possible to use templates produced by Designer (4.5.7) in an OSGi compatability mode project because of a problem in
DefaultTemplateParser Flow V2.2 

This is a show stopper for me. I have attempted to override DefaultTemplateParser to fix but not possible as it is declared as final.

https://github.com/vaadin/flow/blob/2bf46573eadfe9a520983c296e3cddf0bde27240/flow-server/src/main/java/com/vaadin/flow/component/polymertemplate/DefaultTemplateParser.java#L98

does not resolve the url before passing it to getResourceAsStream

```
            String url = dependency.getUrl();
            try (InputStream content = service.getResourceAsStream(url, browser,
                    null)) {

```
causes error

```
java.lang.IllegalStateException: Can't find resource 'frontend://src/q-view-welcome.html' via the servlet context
	at com.vaadin.flow.component.polymertemplate.DefaultTemplateParser.getTemplateContent(DefaultTemplateParser.java:103)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
	at net.qnenet.qne.qwebsite.provider.views.QViewWelcome.<init>(QViewWelcome.java:32)

```
The url needs to be resolved
```
            String url = dependency.getUrl();

            url = service.resolveResource(url, browser);

            try (InputStream content = service.getResourceAsStream(url, browser,
                    null)) {

```

If you can suggest a workaround until the problem can be fixed it would be most appreciated (assuming I have my facts right and it is actually this causing the problem)

**Comment by QNENet** [comment]
Closing issue, this is not correct, the url is resolved but the error message is misleading.
