### ISSUE TITLE
Flow fails with InvalidPathException "Illegal char <" on Windows

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#8906]
An example project which imports vcf-enhanced-dialog and then attempts to extend the VcfEnhancedDialog JavaScript class will cause Vaadin to fail on Windows with the following exception:

```
	Caused by: java.nio.file.InvalidPathException: Illegal char <
> at index 73: @vaadin-component-factory/vcf-enhanced-dialog/src/vcf-enhanced-dialog.js'

class AraDialog extends VcfEnhancedDialog {

    static get is() {
        return 'ara-dialog
		at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
		at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
		at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
		at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
		at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
		at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53)
		at com.vaadin.flow.server.frontend.AbstractUpdateImports.resolve(AbstractUpdateImports.java:579)
		at com.vaadin.flow.server.frontend.AbstractUpdateImports.visitImportsRecursively(AbstractUpdateImports.java:516)
		at com.vaadin.flow.server.frontend.AbstractUpdateImports.handleImports(AbstractUpdateImports.java:553)
		at com.vaadin.flow.server.frontend.AbstractUpdateImports.getUniqueEs6ImportPaths(AbstractUpdateImports.java:349)
		at com.vaadin.flow.server.frontend.AbstractUpdateImports.getModuleLines(AbstractUpdateImports.java:385)
		at com.vaadin.flow.server.frontend.AbstractUpdateImports.collectModules(AbstractUpdateImports.java:298)
		at com.vaadin.flow.server.frontend.AbstractUpdateImports.run(AbstractUpdateImports.java:107)
		at com.vaadin.flow.server.frontend.TaskUpdateImports.execute(TaskUpdateImports.java:389)
		at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:512)
		at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:324)
		at com.vaadin.flow.server.startup.DevModeInitializer.process(DevModeInitializer.java:211)
```

When debugging, it can be clearly seen that Vaadin is trying to call `Path.resolve(importedPath)` with the `importedPath` variable having the value of

```
@vaadin-component-factory/vcf-enhanced-dialog/src/vcf-enhanced-dialog.js'

class AraDialog extends VcfEnhancedDialog {

    static get is() {
        return 'ara-dialog
```

It's the `\n` character that's giving Windows hard time.

I'll attach an example project shortly.

### Versions:
    - Vaadin / Flow version: Flow 2.3.4, Vaadin 14.3.4
    - Java version: 1.8
    - OS version: Windows 10

**Comment by mvysny** [comment]
The `ara-dialog.j` is quite innocent:

```javascript
import '@polymer/polymer/polymer-element.js';
import {VcfEnhancedDialog} from '@vaadin-component-factory/vcf-enhanced-dialog/src/vcf-enhanced-dialog.js'

class AraDialog extends VcfEnhancedDialog {

    static get is() {
        return 'ara-dialog';
    }

}

customElements.define(AraDialog.is, AraDialog);
```

**Comment by mvysny** [comment]
Aha! The problem was the missing semicolon at the end of the import. When I fix the import to

```javascript
import {VcfEnhancedDialog} from '@vaadin-component-factory/vcf-enhanced-dialog/src/vcf-enhanced-dialog.js';
```
then everything starts working properly.

**Comment by mvysny** [comment]
[karibu10-helloworld-application.zip](https://github.com/vaadin/flow/files/5134995/karibu10-helloworld-application.zip)

Example app which reproduces the issue.
