### ISSUE TITLE
Bug: NPE on console

### ISSUE THREAD

**Issue by netbeansuser2019** [vaadin/flow#8919]
- Vaadin: 14.3.4
- Java version: 11

ERROR c.v.flow.server.DefaultErrorHandler      : 

java.lang.NullPointerException: null
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:176)
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:121)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)

**Comment by pleku** [comment]
Hi @netbeansuser2019 can you please elaborate a bit - what are the steps to reproduce this issue ?

**Comment by netbeansuser2019** [comment]
I just see in logs when there was testing of several opening of same dialog and even F5 in play.
BTW: I have test that because it seems that sometimes it is end up with so long opening of modal (numbers of seconds).
In any case there should not be null pointer exceptions on such level.

To make it complete it is used @PreserveOnRefresh on main router layout.

**Comment by netbeansuser2019** [comment]
According to sources seems that NPE is behind calls of 
.getSession() or following .getService()

Is there really reason to get it once again as this has been gotten already?

BTW: Has com.vaadin.flow.server.VaadinService.runPendingAccessTasks() proper logic about line of savings of 
CurrentInstance.getInstances()?

In any case it seems that session or service has been set to null (L159-L176).

**Comment by pleku** [comment]
Closing the issue as there is no way to reproduce it and no updates for a long time. I don't think #9397 is necessarily related (like pointed out there).

**Comment by netbeansuser2019** [comment]
Well, even it is not reproducible to you it is not so good program code style that ends up with null pointer exception.
