### ISSUE TITLE
Exception in push connection after automatic recompilation

### ISSUE THREAD

**Issue by edler-san** [vaadin/flow#8984]
I tested the V14 branch from https://github.com/vaadin/bookstore-example with Vaadin version 14.4.0.alpha1.
I am using Eclipse Oxygen.3a/JDK 1.8.0_131/MacOS 10.14.6/Chrome  85.0.4183.83 and run the application via run as -> maven -> jetty:run
The application starts up and works. I edit `ProductForm.java` and change 
``` 
format.setMaximumFractionDigits(2);
format.setMinimumFractionDigits(2);
``` 

to 3 and 1 respectively. The changes get picked up and recompiled. After that is done, I refresh the browser and get consistently 

```
[Atmosphere-Shared-0] ERROR com.vaadin.flow.server.communication.PushAtmosphereHandler - Exception in push connection
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:720)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:680)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:539)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:839)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:916)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:259)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:506)
	at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1023)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:215)
	at org.atmosphere.cpr.AtmosphereResponseImpl.flushBuffer(AtmosphereResponseImpl.java:506)
	at org.atmosphere.cpr.AtmosphereInterceptorWriter.flush(AtmosphereInterceptorWriter.java:102)
	at org.atmosphere.cpr.AtmosphereResponseImpl$Stream.flush(AtmosphereResponseImpl.java:1001)
	at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:156)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:52)
	at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1037)
	at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1057)
	at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:871)
	at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

upon every refresh now.

**Comment by edler-san** [comment]
Addendum: In Firefox 79 I get the slightly different error:

```
[Atmosphere-Shared-2] ERROR com.vaadin.flow.server.communication.PushAtmosphereHandler - Exception in push connection
java.io.IOException: org.eclipse.jetty.http.BadMessageException: 500: No version
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:245)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:506)
	at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1023)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:215)
	at org.atmosphere.cpr.AtmosphereResponseImpl.flushBuffer(AtmosphereResponseImpl.java:506)
	at org.atmosphere.cpr.AtmosphereInterceptorWriter.flush(AtmosphereInterceptorWriter.java:102)
	at org.atmosphere.cpr.AtmosphereResponseImpl$Stream.flush(AtmosphereResponseImpl.java:1001)
	at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:156)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:52)
	at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1037)
	at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1057)
	at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:871)
	at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.jetty.http.BadMessageException: 500: No version
	at org.eclipse.jetty.http.HttpGenerator.generateResponse(HttpGenerator.java:389)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:735)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:223)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:541)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:839)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:916)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:259)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:235)
	... 17 more
```

**Comment by mstahv** [comment]
I'm getting the second exception with Safari on V14 branch, so apparently this is not any new issue. Would be nice though to catch these "expected connection drops" from actual ones, but I don't know if that is possible.

**Comment by pleku** [comment]
Seems to be only reproducing when `scanIntervalSeconds` >0 is used for jetty maven plugin. Not reproducing when that is not used (no context reload) or when using live reload like hotswapagent, which is the recommended way.

**Comment by xylo** [comment]
This bug (enabled scan interval) is also part of the [Business App starter](https://vaadin.com/start/v14/business-app).  And I was a bit surprised that this official Vaadin demo app constantly crashes with those errors after some code changes.  I'm glad that I found this issue and I will try setting up live reloading via HotswapAgent.

**Comment by Legioth** [comment]
This isn't only about getting an annoying error message in the console, but the push connection will also end up in different states of weirdness.

* Sometimes, it manages to recover by immediately switching to using `long-polling` as a transport.
* Sometimes it ends up in a loop that retries the websocket connection over and over again and never manages to open a push connection.
* Yet other times, it triggers a `Resynchronizing UI by client's request` and then falls back to `long-polling`.

It seems like the more severe outcomes are more likely if multiple `UI::access` calls as triggered when the UI is opened. One easy way of doing this is to add some `ForkJoinPool` abuse to the view's constructor:
```
UI ui = UI.getCurrent();
ForkJoinPool.commonPool().submit(() -> {
    try {
        for (int i = 0; i < 10; i++) {
            Thread.sleep(1000);
            ui.access(() -> add(new Span("Pushed")));
        }
    } catch (InterruptedException e1) {
        e1.printStackTrace();
    }
});
```

**Comment by Legioth** [comment]
Trying to reproduce gets slightly faster by adding `<reload>manual</reload>` to the Jetty plugin configuration since you can then trigger a redploy by pressing Enter in the console instead of having to do a dummy code change.
