### ISSUE TITLE
SPIKE: run OSGi base starter the "bnd way"

### ISSUE THREAD

**Issue by pleku** [vaadin/flow#9106]
- Create a branch for base-starter-flow-osgi and update it to use the feature snapshot `2.5-osgi-SNAPSHOT`
- Switch the project base to run Enroute instead of Felix-Jetty
- Any documentation needed should go to the starter readme for now

Target is to just get the application deployed and running using enroute. It is fine if it is still ugly and requires workarounds in the starter.

Related to #4968

**Comment by stbischof** [comment]
AFAIK Enroute uses also jetty https://github.com/osgi/osgi.enroute/blob/main/indexes/impl-index/pom.xml

But maybe you mean the pom should work like enroute.
So you should use bnd to resolve and launch an osgi framework.

see PR: https://github.com/vaadin/base-starter-flow-osgi/pull/94

Tell me, if you need a more powerful example with integration-tests.

**Comment by denis-anisimov** [comment]
Flow :  feature/osgi-enroute branch is created with fixes in Flow that I needed to be able to run base starter with enRoute.
base-starter: feature/osgi-enroute branch is created .
base-starter project can be built and run (via `java -jar app/target/app.jar` ) but the browser doesn't render anything.
I was not able to detect a reason why.

I see some weird exception and it's unclear whether they are related to the fact that the app is not working or not.
The exception is related to the fetching `stats.json`  but I'm able to get its content via the browser for sure.
On the other hand: the file is fetched programmatically inside the bootstrap handler via HTTP and it might be there is a difference.
It's also possible that the reason is the file size: it's huge (1.5 Mb) and might be this is an issue for runtime in enRoute ( I don't know how it's configured).

The exception points to the line `writer.write(line);` in the `FixedVaadinServlet::service` method which his very weird.
(as said: the content is shown fine in the browser on accessing the `stats.json` URL).

So the task is unfinished and I'm dropping it for now.

**Comment by stbischof** [comment]
Can you please tell me what you mean with "osgi-enroute"?

I know the
- osgi specs
- bnd to build resolve test run
- felix and equinix as reference implementations.

- enroute is for me just an "stater tutorial" that uses maven to build with bnd and run with the reference implementations of the spec

**Comment by pleku** [comment]
> enroute is for me just an "stater tutorial" that uses maven to build with bnd and run with the reference implementations of the spec

Yes, the point would be to run the base starter "the enroute way" as standalone packed .jar that can be run to get the Vaadin WAB up and running, so that there is no need to configure separately in pom.xml to download felix-jetty, run it and to deploy the app to it. https://github.com/vaadin/base-starter-flow-osgi/blob/master/pom.xml#L450

**Comment by stbischof** [comment]
You have seen the PR: https://github.com/vaadin/base-starter-flow-osgi/pull/94
?

**Comment by pleku** [comment]
Yes I saw that, thank you, but did not yet take a deeper look into what it does and how it does it. 
We will take a look into it later, we decided to first resolve some known issues with the npm mode for OSGi.
My guess (and hope) is that it could fill the gaps for https://github.com/vaadin/base-starter-flow-osgi/commit/139f68897d722cc225cda1fe0ad84957611f8fc6 which is not yet working as based on the comment https://github.com/vaadin/flow/issues/9106#issuecomment-708251217

> you may should name it "bnd way" because enroute just uses bnd. there happend a lot of enhancements in bnd since the enroute tutorials has been created.

Thanks for this clarification.

**Comment by stbischof** [comment]
Thank you! I didn't noticed the https://github.com/vaadin/base-starter-flow-osgi/commit/139f68897d722cc225cda1fe0ad84957611f8fc6

**Comment by stbischof** [comment]
I added the bnd exporter to my PR (vhttps://github.com/vaadin/base-starter-flow-osgi/pull/94)  

I could run the application via java -jar target/launch.jar

Vaadin and Felix Webconsole does work!!!

**Comment by denis-anisimov** [comment]
This is really cool.
For some reason modified enRoute tutorial doesn't work for me : nothing is rendered in the browser and I cannot understand why.
If you have any time and clue why it may happen please let me know.

And we will need a task to analyze your PR and make another base-starter either branch or just even a new project which works that way.
Unfortunately there are another tasks with higher priority.

**Comment by stbischof** [comment]
I understand that you will do the other task.
I will have a look on you branch and maybe i can find the problem. it is just becaus i am more familiar with mine. So i started there.

**Comment by stbischof** [comment]
Here is what i found 

- there are a lot of old dependencys that should be updated.
- i do not like the indexer because the resolver run and exporter plugin could get the dependencies also from the pom. there is no need to create and use an index
- a lot of dependencys to resolve the app.bndrun are in the impl project but not in the app project.
when i change the framework from eclipse to felix I got this exception.

```
ERROR : bundle com.example.impl:1.0.0.202010151535 (2)[com.example.starter.base.osgi.VaadinServletRegistration(1)] : The activate method has thrown an exception
org.osgi.service.http.NamespaceException: Alias /VAADIN/config/stats.json is already in use.
	at org.apache.felix.http.base.internal.service.SharedHttpServiceImpl.registerServlet(SharedHttpServiceImpl.java:74)
	at org.apache.felix.http.base.internal.service.PerBundleHttpServiceImpl.registerServlet(PerBundleHttpServiceImpl.java:153)
	at org.apache.felix.http.base.internal.service.PerBundleHttpServiceImpl.registerResources(PerBundleHttpServiceImpl.java:98)
	at com.example.starter.base.osgi.VaadinServletRegistration.activate(VaadinServletRegistration.java:87)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685)
	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318)
	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000)
	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:785)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
	at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
	at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
	at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
	at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
	at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
	at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
	at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
	at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
	at org.apache.felix.scr.impl.AbstractExtender.addingBundle(AbstractExtender.java:139)
	at org.apache.felix.scr.impl.AbstractExtender.addingBundle(AbstractExtender.java:49)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:420)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183)
	at org.osgi.util.tracker.BundleTracker.open(BundleTracker.java:159)
	at org.apache.felix.scr.impl.AbstractExtender.startTracking(AbstractExtender.java:100)
	at org.apache.felix.scr.impl.AbstractExtender.doStart(AbstractExtender.java:92)
	at org.apache.felix.scr.impl.Activator.doStart(Activator.java:197)
	at org.apache.felix.scr.impl.AbstractExtender.start(AbstractExtender.java:72)
	at org.apache.felix.scr.impl.Activator.restart(Activator.java:164)
	at org.apache.felix.scr.impl.config.ScrConfigurationImpl.configure(ScrConfigurationImpl.java:228)
	at org.apache.felix.scr.impl.config.ScrConfigurationImpl.start(ScrConfigurationImpl.java:123)
	at org.apache.felix.scr.impl.Activator.start(Activator.java:121)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:698)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2402)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2308)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
```

**Comment by denis-anisimov** [comment]
Thank you for investigation.
I haven't see this exception.

It's weird because I'm able to access `/VAADIN/config/stats.json` web resource in my original project from the browser.
So it works fine.
The exception looks like `/VAADIN/config/stats.json`   is registered via `HttpService`  twice. But I think I don't have a code which register it via `HttpService`  at all: it's registered via `HttpService` in the `osgi` branch but not in the `osgi-enroute`

**Comment by stbischof** [comment]
If I try to unregister  the alias  `/VAADIN/config/stats.json` before i register it is thows the exception that `/VAADIN/config/stats.json`does not exist.

I will work on my version starter project. https://github.com/bipolis/base-starter-flow-osgi/tree/feature_osgi_bnd
- multi-module-project
- build a bundle
- itest the bundle insite an osgi framework
- generate all-in-one-application jar
- http://localhost:8080/ works

**Comment by pleku** [comment]
I think this spike is concluded for now with https://github.com/vaadin/base-starter-flow-osgi/
