### ISSUE TITLE
DevModeInitializer ServletException on IBM Liberty with javax.jws and javax.ws.rs services

### ISSUE THREAD

**Issue by ulisse1996** [vaadin/flow#9213]
# Description of the bug
With Custom Servlet that extend **javax.ws.rs.Application** or annotated **javax.jws.WebService** DevModeInitializer throw ServletException for not Vaadin class currently not present in war classpath.

```
exception.occurred.while.running.ServletContainerInitializers.onStartup
com.vaadin.flow.server.startup.DevModeInitializer@7b91bde3
```

### Minimal reproducible example
Simple Application with Vaadin CDI and a javax.* servlet
### Expected behavior
DevModeInitializer should throw exception only missing Vaadin Servlet Classes
### Actual behavior
DevModeInitializer throw exception for every missing class that extends Servlet
### Versions:
    - Vaadin / Flow version: 14.4.0 / 2.4.0
    - Java version: 1.8
    - OS version: Mac OSX

**Comment by tanbt** [comment]
Hi, can you share the full error log? Or even a simple reproducable project is much more appreciated.

I tried with a very simple javax.servlet.http.HttpServlet application with Vaadin CDI but the only error I see is that I was using a wrong project structure (which is expected).
```
Caused by: java.lang.IllegalStateException: Failed to determine project directory for dev mode. Directory 'C:\Users\tanbui\Downloads\tomee-servlet-example\hello-servlet\target\apache-tomee' does not look like a Maven or Gradle project. Ensure that you have run the prepare-frontend Maven goal, which gen
erates 'flow-build-info.json', prior to deploying your application
                at com.vaadin.flow.server.startup.DevModeInitializer.getBaseDirectoryFallback(DevModeInitializer.java:442)
                at com.vaadin.flow.server.startup.DevModeInitializer.initDevModeHandler(DevModeInitializer.java:275)
                at com.vaadin.flow.server.startup.DevModeInitializer.process(DevModeInitializer.java:224)
                at com.vaadin.flow.server.startup.ClassLoaderAwareServletContainerInitializer.onStartup(ClassLoaderAwareServletContainerInitializer.java:76)
```

**Comment by pleku** [comment]
Closing the issue due to no steps to reproduce and inactivity.
