### ISSUE TITLE
Binder.doWriteIfValid raise java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by leotu** [vaadin/flow#9217]
java.util.ConcurrentModificationException raising if binder withValidator updated multiple components inside it's code block.
(https://vaadin.com/forum/thread/18462098/java-util-concurrentmodificationexception-if-binder-withvalidator-update-m)

### Description of the bug
It only happens when multiple components are updated, no error if just only update one.

### Minimal reproducible example
- Goto https://start.spring.io/ download example
Spring Boot: 2.3.4
Packaging: jar
Java: 11
Dependencies: Vaadin web (version 14.4.1)

- Copy example "MainView.java" to DemoApplication's package
My IDE eclipse & MacOS 10.15.7 & Java 11.0.5

- Error Message
```text
2020-10-22 15:39:24.459 ERROR 9541 --- [nio-8080-exec-2] c.v.flow.server.DefaultErrorHandler   
java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[na:na]
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:741) ~[na:na]
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[na:na]
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.vaadin.flow.data.binder.Binder.doWriteIfValid(Binder.java:1946) ~[flow-data-2.4.0.jar:2.4.0]
	at com.vaadin.flow.data.binder.Binder.handleFieldValueChange(Binder.java:1560) ~[flow-data-2.4.0.jar:2.4.0]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.handleFieldValueChange(Binder.java:1230) ~[flow-data-2.4.0.jar:2.4.0]
	at com.vaadin.flow.data.binder.Binder$BindingImpl.lambda$new$f9b94f89$1(Binder.java:1068) ~[flow-data-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.lambda$addValueChangeListener$828eca10$1(AbstractFieldSupport.java:96) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:205) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.ComponentEventBus.fireEvent(ComponentEventBus.java:194) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.Component.fireEvent(Component.java:359) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.ComponentUtil.fireEvent(ComponentUtil.java:386) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:207) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.internal.AbstractFieldSupport.setValue(AbstractFieldSupport.java:133) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.AbstractField.setValue(AbstractField.java:181) ~[flow-server-2.4.0.jar:2.4.0]
	at com.vaadin.flow.component.textfield.TextField.setValue(TextField.java:442) ~[vaadin-text-field-flow-2.3.1.jar:na]
	at com.example.demo.MainView.lambda$0(MainView.java:42) ~[classes/:na]
	at com.vaadin.flow.data.binder.Binder$BindingBuilderImpl.lambda$withValidator$7d13c2a2$1(Binder.java:898) ~[flow-data-2.4.0.jar:2.4.0]
...
```

- Vaadin version 14.x & version 17.x both this issue.
When the error raised would occur  my components' value lost. (real project complex situation)

```java
package com.example.demo;

import com.vaadin.flow.component.AttachEvent;
import com.vaadin.flow.component.formlayout.FormLayout;
import com.vaadin.flow.component.formlayout.FormLayout.ResponsiveStep;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.component.textfield.IntegerField;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.data.binder.Binder;
import com.vaadin.flow.data.binder.ValidationResult;
import com.vaadin.flow.router.Route;

@SuppressWarnings("serial")
@Route
public class MainView extends VerticalLayout {

	private TextField deptNo = new TextField("deptNo");
	private TextField deptName = new TextField("deptName");
	private IntegerField empNo = new IntegerField("empNo");
	private TextField firstName = new TextField("firstName");
	private TextField lastName = new TextField("firstName");

	private Binder<DeptWithManager> binder = new Binder<>(DeptWithManager.class);

	public MainView() {
//		Button button = new Button("Click me", event -> Notification.show("Clicked!"));
//		add(button);

		FormLayout formLayout = new FormLayout();
		formLayout.setResponsiveSteps(new ResponsiveStep("120px", 1));
		formLayout.add(deptNo, deptName, empNo, firstName, lastName);

		add(formLayout);

		//
		binder.forField(deptNo).asRequired().bind("deptNo");
		binder.forField(deptName).asRequired().bind("deptName");

		binder.forField(empNo).asRequired().withValidator((val, context) -> {
			System.out.println(String.format("old: %s, val: %s", binder.getBean().getEmpNo(), val));
			if (1002 == val) {
				firstName.setValue("Leo-1002");
				lastName.setValue("Tu-1002");
			}
			return ValidationResult.ok();
		}).bind("empNo");

		binder.forField(firstName).bind("firstName");
		binder.forField(lastName).bind("lastName");
	}

	@Override
	protected void onAttach(AttachEvent evt) {
		DeptWithManager bean = new DeptWithManager();
		bean.setDeptNo("A001");
		bean.setDeptName("HR");
		bean.setEmpNo(1001);
		bean.setFirstName("Leo-1001");
		bean.setLastName("Tu-1001");

		binder.setBean(bean);
	}

	static public class DeptWithManager {

		private String deptNo;
		private String deptName;
		private Integer empNo;
		private String firstName;
		private String lastName;

		public String getDeptNo() {
			return deptNo;
		}

		public void setDeptNo(String deptNo) {
			this.deptNo = deptNo;
		}

		public String getDeptName() {
			return deptName;
		}

		public void setDeptName(String deptName) {
			this.deptName = deptName;
		}

		public Integer getEmpNo() {
			return empNo;
		}

		public void setEmpNo(Integer empNo) {
			this.empNo = empNo;
		}

		public String getFirstName() {
			return firstName;
		}

		public void setFirstName(String firstName) {
			this.firstName = firstName;
		}

		public String getLastName() {
			return lastName;
		}

		public void setLastName(String lastName) {
			this.lastName = lastName;
		}

	}
}
```

1) No error only update firstName
```java
binder.forField(empNo).asRequired().withValidator((val, context) -> {
			System.out.println(String.format("old: %s, val: %s", binder.getBean().getEmpNo(), val));
			if (1002 == val) {
				firstName.setValue("Leo-1002");
//				lastName.setValue("Tu-1002");
			}
			return ValidationResult.ok();
		}).bind("empNo");
```

2) No error only update lastName
```java
binder.forField(empNo).asRequired().withValidator((val, context) -> {
			System.out.println(String.format("old: %s, val: %s", binder.getBean().getEmpNo(), val));
			if (1002 == val) {
//				firstName.setValue("Leo-1002");
				lastName.setValue("Tu-1002");
			}
			return ValidationResult.ok();
		}).bind("empNo");
```

3) Error when update both firstName and lastName.
```java
binder.forField(empNo).asRequired().withValidator((val, context) -> {
			System.out.println(String.format("old: %s, val: %s", binder.getBean().getEmpNo(), val));
			if (1002 == val) {
				firstName.setValue("Leo-1002");
				lastName.setValue("Tu-1002");
			}
			return ValidationResult.ok();
		}).bind("empNo");
```

**Comment by caalador** [comment]
The main problem is that when updating the field values in for bound fields inside the validator the change will fire a new validator run while the intial validation is still running.

Validation should be about checking the value and not doing any changes to data.

To do this correctly you should add a value change listener on the empNo field where you would change the values e.g.
```
        empNo.addValueChangeListener(event -> {
            if(event.getValue() == 1002) {
                firstName.setValue("Leo-1002");
                lastName.setValue("Tu-1002");
            }
        });
```

**Comment by leotu** [comment]
empNo.addValueChangeListener(...)  The listener is called maybe before any validated, what I want is the value after been validated.

i.e,
```java
binder.forField(empNo).asRequired())
                .withValidator((val, context) -> { // (1) condition checking
			...
		})
		.withValidator((val, context) -> { // (2) condition checking
			...
		})
                .withValidator((val, context) -> { // (3) last step will query database
                         if (1002 == val && empService.existsById(val)) {  // (4) check data from database
				firstName.setValue("Leo-1002");
				lastName.setValue("Tu-1002");
			}
                }
```

A workaround solution:

1) Implements ValidationResult carry with data
```java
public class ValidationResultOkWithData implements ValidationResult {
        private final Object data;

        public ValidationResultOkWithData(Object data) { // <--- carry with data
            this.data = data;
        }
        ...
        public <T> T getData() {
            return (T)data;
        }
    }
```

2) withValidator Ok with data (Employees)
```java

binder.forField(empNo).asRequired()
                .withValidator((val, context) -> { // (1) condition checking
			...
		})
		.withValidator((val, context) -> { // (2) condition checking
			...
		})
                .withValidator((val, context) -> { // (3) last step will query database
                    Employees emp = empService.findById(val).orElse(null); // (4) retrieved from database
                    if (emp == null) {
                        return ValidationResult.error(...);
                    } else {
                        return new ValidationResultOkWithData(emp); // <--- carry with data
                    }
                }).bind("empNo");
```

3) It works for "binder.setValidationStatusHandler" to find 'ValidationResultOkWithData' object

```java
binder.setValidationStatusHandler(evt -> {
            Optional<Employees> opt = fetchData(evt, fvs -> fvs.getField() == empNo);
            opt.ifPresent(emp -> {
                firstName.setValue(emp.getFirstName());
                lastName.setValue(emp.getLastName());
            });
        });
		...
		...
 public <T> Optional<T> fetchData(BinderValidationStatus<?> bvs, Predicate<BindingValidationStatus<?>> predicate) {
        AtomicReference<ValidationResultOkWithData> result = new AtomicReference<>();
        bvs.getFieldValidationStatuses().stream().filter(fvs -> !fvs.isError() && predicate.test(fvs)).forEach(fvs -> {
            fvs.getValidationResults().stream().filter(vr -> vr instanceof ValidationResultOkWithData && !vr.isError()) // <--- search data
                    .findFirst().ifPresent(vr -> result.set((ValidationResultOkWithData) vr));
        });
        return Optional.ofNullable((T) result.get() == null ? null : result.get().getData());
    }
```
