### ISSUE TITLE
Get null pointer exception when refresh multiple times

### ISSUE THREAD

**Issue by nloke** [vaadin/flow#9397]
### Description of the bug
I am using preserveOnRefresh and there are a lot of widgets in the form. When I refresh multiple times, the server throws a NPE also the UI console log will show:
Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission.
### Minimal reproducible example
We don't have a minimal reproducible example. It happening in our production code. We talked to your expert via prime chat and he suggested to file a bug based on the stack trace.
### Expected behavior
No NPE after the refresh.
### Actual behavior
**Server error stack trace:**
java.lang.NullPointerException: null
	at com.vaadin.flow.component.internal.UIInternals.addJavaScriptInvocation(UIInternals.java:549)
	at com.vaadin.flow.component.page.Page.executeJs(Page.java:439)
	at com.vaadin.flow.component.page.Page.executeJavaScript(Page.java:394)
	at com.vaadin.flow.component.datepicker.DatePicker.lambda$initConnector$2f364bb9$1(DatePicker.java:320)
	at com.vaadin.flow.component.datepicker.DatePicker.lambda$null$fb4fab81$1(DatePicker.java:364)
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:368)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:365)
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:411)
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:187)
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:121)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:90)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247)
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:173)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:155)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**UI console log stack trace:**
VM180973 client-C4B53966888EAB6CBD0D20BD246409CB.cache.js:212 Push connection using websocket failed!

Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission

Internal error
Please notify the administrator.<br>Take note of any unsaved data, and <u>click here</u> or press ESC to continue

### Versions:
    - Vaadin / Flow version:  14.3.0
    - Java version: jdk1.8.0_201
    - OS version: windows10
    - Browser version (if applicable): Chrome Version 86.0.4240.111 (Official Build) (64-bit)
    - Application Server (if applicable):
    - IDE (if applicable): Eclipse

**Comment by pleku** [comment]
Hello. Even though you were instructed to create an issue by our expert team in the chat based on just the stacktrace, there is not much we can do unless we can reproduce the issue somehow. We don't like spending our limited time in guessing things, I hope you can understand that. For now, I think the best we can do is to test by adding a `DatePicker` to a view with `@PreserveOnRefresh` and then refreshing the page to see if it reoccurs. For testing we'll use 14.4 though since 14.3.0 is not even supported anymore.

**Comment by nloke** [comment]
@pleku it's not really related with specific component, I've seen it on textfield, datefield, select, tab... etc. 
Basically, any component that calls your javascript init might cause issue

**Comment by pleku** [comment]
@nloke can you please provide details on
1) which Spring Boot version you're using
2) Is it in development mode (webpack devserver running) or production mode (bundled frontend resources & production mode) 
3) Are you using push ? Are you sure you're accessing the UI using `UI.access` ?

Apparently it is also with Undertow (instead of Tomcat). I'm not optimistic that we can reproduce this with just the details but we can try if we get lucky.

**Comment by TatuLund** [comment]
I think this is duplicate of the this one https://github.com/vaadin/flow/issues/8919

**Comment by pleku** [comment]
So forwarding some comments received via another channel:

- there is `@PreserveOnRefresh` in use
- there are bunch of `Details` sections in the UI
- after a refresh, the code expands only the first `Details`, and "the rest are hidden" with `details.setOpened(false);`
- if all the details are expanded manually (by user), everything works after the refresh
- if the details are not expanded, then after the refresh it fails with the exception given ^
  - the component(s) that throw are inside the hidden details and are 

Not sure if I got that all right, please correct me if not.

So just by looking at the code, my guess is that the issue is caused by an executeJS being enqueued for the old UI that is no longer used and will not be attached to the session anymore.

**Comment by netbeansuser2019** [comment]
#8919 If it is similar issue 

Be so kind and: 

According to sources seems that NPE is behind calls of
.getSession() or following .getService()

**Is there really reason to get it once again as this has been gotten already?**

BTW: Has com.vaadin.flow.server.VaadinService.runPendingAccessTasks() proper logic about line of savings of
CurrentInstance.getInstances()?

In any case it seems that session or service has been set to null (L159-L176).

**Comment by denis-anisimov** [comment]
I think I understand why it happens.
It should be possible to reproduce this with the following example:

```
@Route("refresh-js")
@PreserveOnRefresh
public class RefreshView extends AbstractDivView {

    @Override
    protected void onAttach(AttachEvent attachEvent) {
        getElement().getNode().runWhenAttached(
                ui -> ui.beforeClientResponse(this, context -> {
                    ui.getPage().executeJs("console.log('foo')");
                }));
    }

}
```

But I can't reproduce with this example. May be it matters that the component is somewhere deep in the hierarchy (in this case it topmost).

The problem with this ticket is: there is no exact steps to reproduce so only back engineering of the exception and description is possible.

Here is my opinion what's going on (very technical):
- Overall this is the mixture of design which doesn't assume changing `UI` (all Flow has been designed in assumption that `UI`  for components is never changed : components could not be moved from one UI to another).
- The implementation of `UI.beforeClientResponse` is trying to solve one issue (with checking whether the context node is attached or not) but it's failing in assumption that the node is always in the same `StateTree` 
- The design of `UI.beforeClientResponse` has a proper API which has to be used but it's ignore in this case.

Details are here:
- `UI.beforeClientResponse` accepts `SerializableConsumer<ExecutionContext>`  as a parameter. So the consumer should consume `ExecutionContext`. The `ExecutionContext`  instance gives the `UI`  instance. **This** `UI`  instance has to be used to invoke operations with . _But_  the context is silently ignored int he execution completely in the example. Instead the `ui` instance which is given in the `runWhenAttached` is used.
- The above is the source of the problems: at the very first time the node is attached to the initial `UI`. For this `UI` instance `runWhenAttached` is called. But the consumer which is invoked inside `runWhenAttached`  (immediately since the node is already attached) uses `beforeClientResponse` for the initial `UI` to postpone execution of JS when response to the client will be sent.
- `beforeClientResponse`  has an issue : it doesn't store executions _per_ `UI`  instance. It stores all the executions inside `StateNode`.
- Once refresh is called the new `UI`  instance is created and the node is reattached to this _new_ `UI`.
- The old `UI` is marked as "closing" and it will be closed as some point which results with `VaadinSession` being `null` for this `UI`.
- Now for the new `UI`  the postponed JS executions are invoked (scheduled via `beforeClientResponse` ).
- Here the problem comes: the execution is stored inside the node itself which has different `UI` at the moment of the consumer execution. But the consumer itself doesn't care which `UI`  it should use (it has to use the `UI`  from the execution context). It uses the UI for which the node has been attached the first time . But this `UI`  is invalid already and may not be used.

Several notes: 
- `beforeClientResponse` is not called for the old `UI`  because it's already closed and then it can't be found in the session.
- If my assumption is correct the consumer is called twice: for the old invalid `UI` and for the new `UI` (so the `StateNode` instance contains two executions for different `UI`s). But only one of them should be called.
- everything would have been worked fine if the code had used the provided execution context instead of being lazy and use the same `UI`  which has been provided in `runWhenAttached`: 
```
 getElement().getNode().runWhenAttached(
                ui -> ui.beforeClientResponse(this, context -> {
                    context.getUI().getPage().executeJs("console.log('foo')");
                }));
```

So there is also a developer mistake in `DatePicker`  at least.
I believe the same mistake is done in every other component.
And this mistake is something that we have to deal with : it's too easy to make the mistake.
So we should prevent it in our implementation.

I think I can try to fix this (based on my assumptions) via saving the initial `StateTree`  reference from the `StateNode`  context in the `BeforeClientResponseEntry`  and check whether the `UI`  in the `ExecutionContext`  is the same as in the `BeforeClientResponseEntry` . That should prevent execution of the consumer for invalid `UI`s.
I'm not sure about one issue: if there is a code which I'm not aware of which prevents the "same" code execution (so instead of several "similar" consumers only one will be scheduled for execution). In that case the fix won't work and I won't be able to verify it since there are no exact steps to reproduce.
