### ISSUE TITLE
Resync Issue

### ISSUE THREAD

**Issue by bjlemke** [vaadin/flow#9407]
### Description of the bug

org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpConnection$SendCallback.reset(HttpConnection.java:724)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.access$300(HttpConnection.java:683)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:542)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:833)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:910)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:284)
	at org.eclipse.jetty.server.HttpOutput.channelWrite(HttpOutput.java:268)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:713)
	at org.eclipse.jetty.server.Response.flushBuffer(Response.java:1075)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:215)
	at org.atmosphere.cpr.AtmosphereResponseImpl.flushBuffer(AtmosphereResponseImpl.java:506)
	at org.atmosphere.cpr.AtmosphereInterceptorWriter.flush(AtmosphereInterceptorWriter.java:102)
	at org.atmosphere.cpr.AtmosphereResponseImpl$Stream.flush(AtmosphereResponseImpl.java:1001)
	at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:156)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:52)
	at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1037)
	at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1057)
	at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:871)
	at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
16.11.2020 11:29:26 WARN com.vaadin.flow.server.communication.ServerRpcHandler - Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform.
If you see this message regularly please open a bug report at 
https://github.com/vaadin/flow/issues

### Minimal reproducible example
 dependencies -->
### Versions:
    - Vaadin / Flow version: 14.4.2
    - Java version: 15.0.1
    - OS version: Windows 10
    - Browser version (if applicable): Chrome
    - Application Server (if applicable): Jetty
    - IDE (if applicable): Eclipse

**Comment by pleku** [comment]
Hello. It would be great if you could provide a bit more details on how / when this reproduces.

I see that Java 15 is used so I would be interested to know which version of Jetty you are using with it ? 9.4.34.v20201102 is the latest.

**Comment by bjlemke** [comment]
hi,

i am using jetty 9.4.31.v20200723

Von meinem iPhone gesendet

**Comment by bjlemke** [comment]
updated to latest jetty, error messages seem to disapear. thanks !

Von meinem iPhone gesendet
