### ISSUE TITLE
Malformed URL "/..**" causes Error 500 instead of 404

### ISSUE THREAD

**Issue by fluorumlabs** [vaadin/flow#9443]
Steps to reproduce:
1. Navigate to [https://cookbook.vaadin.com/..**](https://cookbook.vaadin.com/..**)

Expected behavior:
404 error

Actual behavior:
500 error

Example stacktrace:
```
java.lang.IllegalArgumentException: Relative path cannot contain .. segments
	at com.vaadin.flow.router.Location.verifyRelativePath(Location.java:322) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Location.parsePath(Location.java:281) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Location.<init>(Location.java:56) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Router.getLocationForRequest(Router.java:148) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.router.Router.resolveNavigationTarget(Router.java:163) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.server.BootstrapUtils.resolvePageConfigurationHolder(BootstrapUtils.java:285) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
	at com.vaadin.flow.server.BootstrapHandler$BootstrapContext.<init>(BootstrapHandler.java:195) ~[flow-server-5.0.0.beta1.jar:5.0.0.beta1]
```

**Comment by pleku** [comment]
To me `406 Not acceptable` or `403 Forbidden` would be more appropriate than `404 not found`. @fluorumlabs did you have a specific reason why it should be a 404 ?

**Comment by fluorumlabs** [comment]
On second thought, Tomcat serves `400 Bad Request` in case of malformed request URL (like if the requested path contains forbidden characters). Since we're also talking about forbidden characters there, maybe we should stick with that convention.
