### ISSUE TITLE
Application becomes unresponsive after failed Upload using HTTP/2

### ISSUE THREAD

**Issue by tulioag** [vaadin/flow#9492]
### Description of the bug / feature
Tested on a Spring Boot application using Java 11:

If you try to upload a file greater than the configured limit, causing a `org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException`, the application becomes unresponsive and generates exceptions like this:
```
org.apache.catalina.connector.ClientAbortException: org.apache.coyote.CloseNowException: Timeout waiting to read data from client
	at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:340) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.InputBuffer.realReadChars(InputBuffer.java:408) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.InputBuffer.checkCharBufferEof(InputBuffer.java:642) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:469) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.connector.CoyoteReader.read(CoyoteReader.java:101) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at com.vaadin.flow.server.communication.ServerRpcHandler.getMessage(ServerRpcHandler.java:424) ~[flow-server-2.4.1.jar:2.4.1]
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:245) ~[flow-server-2.4.1.jar:2.4.1]
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89) ~[flow-server-2.4.1.jar:2.4.1]
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-2.4.1.jar:2.4.1]
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1545) ~[flow-server-2.4.1.jar:2.4.1]
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:247) ~[flow-server-2.4.1.jar:2.4.1]
	at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:111) ~[vaadin-spring-12.3.2.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.37.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.37.jar:9.0.37]

```
Related to https://github.com/vaadin/vaadin-flow-components/issues/346

### Minimal reproducible example

- Download [my-project.zip](https://github.com/vaadin/flow/files/5595569/my-project.zip)
- Run the `ssl_setup.sh` script
- Run the application with `mvn spring-boot:run`. **(Use Java 11)**
- Navigate to https://localhost:8443/
- Upload a file greater than **5MB** but less than **10MB** (or change the configuration)
- Verify that the application becomes unresponsive.

### Versions:
    - Vaadin version: 14.4.2
    - Java version: OpenJDK 11
    - OS version: Linux

**Comment by tulioag** [comment]
Related issues in Tomcat and Spring boot:

https://bz.apache.org/bugzilla/show_bug.cgi?id=63948

https://github.com/spring-projects/spring-boot/issues/18806

**Comment by mshabarov** [comment]
Adding some extra observations here:

> If I set server.http2.enabled=false it works, by which I mean it shows an error message in the component, and I can still interact with the application.
It seems to be related to https://bz.apache.org/bugzilla/show_bug.cgi?id=63948
This proposed workaround did not fix it for me:
```java
@Bean
public TomcatConnectorCustomizer http2ProtocolCustomizer() {
  return (connector) -> {
    for (UpgradeProtocol upgradeProtocol: connector.findUpgradeProtocols()) {
      if (upgradeProtocol instanceof Http2Protocol) {
        Http2Protocol http2Protocol = (Http2Protocol)upgradeProtocol;
        http2Protocol.setOverheadContinuationThreshold(0);
        http2Protocol.setOverheadDataThreshold(0);
        http2Protocol.setOverheadWindowUpdateThreshold(0);
      }
    }
  };
}
```
