### ISSUE TITLE
Unable to use an element with _ in the tag name

### ISSUE THREAD

**Issue by Artur-** [vaadin/flow#9669]
### Description of the bug / feature
It is impossible to use a LitTemplate or other element containing a _ in the tag name

### Minimal reproducible example
```
new Element("a-b_c");
```

corresponding to
```
document.createElement("a-b_c")
```
in the browser, which works fine

### Expected behavior
An element with the given tag is created

### Actual behavior
```
Exception in thread "main" java.lang.IllegalArgumentException: Tag a-b_c is not a valid tag name
        at com.vaadin.flow.dom.Element.createStateNode(Element.java:243)
        at com.vaadin.flow.dom.Element.<init>(Element.java:111)
        at com.example.application.Application.main(Application.java:1
```

### Versions:
    - Vaadin / Flow version: 14

**Comment by fluorumlabs** [comment]
See https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name for allowed custom element tag names.

**Comment by denis-anisimov** [comment]
Wrong impl in `ElementUtil::isValidTagName` .
