### ISSUE TITLE
Vaadin 14.4.3: Hung threads on IBM WAS

### ISSUE THREAD

**Issue by FedericoGv** [vaadin/flow#9696]
In IBM Websphere 9, we found a lot of errors about threads lock.
 Could be similar to this issue: https://vaadin.com/forum/thread/16531334/hung-threads-and-deadlock-when-locking-sessions ?

Here the stacktrace that we found in the WAS log.

Thanks.
 Federico

"WebContainer : 23" J9VMThread:0x0000000033DA8A00, omrthread_t:0x00000001A5AEFA10, java/lang/Thread:0x00000007078C20D0, state:R, prio=5
      (java/lang/Thread getId:0x16D84, isDaemon:true)
      (native thread ID:0xA5309F, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x000000a1)
     CPU usage total: 36.819923000 secs, user: 32.953020000 secs, system: 3.866903000 secs, current category="Application"
     Heap bytes allocated since last GC cycle=0 (0x0)
     Java callstack:
         at java/net/SocketInputStream.socketRead0(Native Method)
         at java/net/SocketInputStream.socketRead(SocketInputStream.java:127(Compiled Code))
         at java/net/SocketInputStream.read(SocketInputStream.java:182(Compiled Code))
         at java/net/SocketInputStream.read(SocketInputStream.java:152(Compiled Code))
         at sun/nio/cs/StreamDecoder.readBytes(StreamDecoder.java:323(Compiled Code))
         at sun/nio/cs/StreamDecoder.implRead(StreamDecoder.java:365(Compiled Code))
         at sun/nio/cs/StreamDecoder.read(StreamDecoder.java:211(Compiled Code))
            (entered lock: java/io/InputStreamReader@0x0000000714EF0FB8, entry count: 2)
         at java/io/InputStreamReader.read(InputStreamReader.java:205(Compiled Code))
         at java/io/BufferedReader.fill(BufferedReader.java:172(Compiled Code))
         at java/io/BufferedReader.readLine(BufferedReader.java:335(Compiled Code))
            (entered lock: java/io/InputStreamReader@0x0000000714EF0FB8, entry count: 1)
         at java/io/BufferedReader.readLine(BufferedReader.java:400(Compiled Code))
         at com/gruppoveronesi/Totem/model/Model.checkStatoStampanteTicket(Model.java:193(Compiled Code))
         at com/gruppoveronesi/Totem/ViewMenu13.checkTicketPrinter(ViewMenu13.java:531)
         at com/gruppoveronesi/Totem/ViewMenu13.access$300(ViewMenu13.java:73)
         at com/gruppoveronesi/Totem/ViewMenu13$8.buttonClick(ViewMenu13.java:446)
         at sun/reflect/GeneratedMethodAccessor4618.invoke(Bytecode PC:42)
         at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55(Compiled Code))
         at java/lang/reflect/Method.invoke(Method.java:508(Compiled Code))
         at com/vaadin/event/ListenerMethod.receiveEvent(ListenerMethod.java:508(Compiled Code))
         at com/vaadin/event/EventRouter.fireEvent(EventRouter.java:198(Compiled Code))
         at com/vaadin/event/EventRouter.fireEvent(EventRouter.java:161(Compiled Code))
         at com/vaadin/server/AbstractClientConnector.fireEvent(AbstractClientConnector.java:1003(Compiled Code))
         at com/vaadin/ui/Button.fireClick(Button.java:377)
         at com/vaadin/ui/Button$1.click(Button.java:54)
         at sun/reflect/GeneratedMethodAccessor4617.invoke(Bytecode PC:42)
         at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55(Compiled Code))
         at java/lang/reflect/Method.invoke(Method.java:508(Compiled Code))
         at com/vaadin/server/ServerRpcManager.applyInvocation(ServerRpcManager.java:158(Compiled Code))
         at com/vaadin/server/ServerRpcManager.applyInvocation(ServerRpcManager.java:118(Compiled Code))
         at com/vaadin/server/communication/ServerRpcHandler.handleInvocations(ServerRpcHandler.java:408(Compiled Code))
         at com/vaadin/server/communication/ServerRpcHandler.handleRpc(ServerRpcHandler.java:273(Compiled Code))
         at com/vaadin/server/communication/UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:79(Compiled Code))
         at com/vaadin/server/SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41(Compiled Code))
         at com/vaadin/server/VaadinService.handleRequest(VaadinService.java:1409(Compiled Code))
         at com/vaadin/server/VaadinServlet.service(VaadinServlet.java:364(Compiled Code))

"WebContainer : 13" J9VMThread:0x0000000038DB6900, omrthread_t:0x00000001AA76D2C0, java/lang/Thread:0x000000070849B808, state:P, prio=5
      (java/lang/Thread getId:0xC3E0, isDaemon:true)
      (native thread ID:0xCBE035, native priority:0x5, native policy:UNKNOWN, vmstate:P, vm thread flags:0x00020081)
     CPU usage total: 52.355211000 secs, user: 47.239985000 secs, system: 5.115226000 secs, current category="Application"
Parked on: java/util/concurrent/locks/ReentrantLock$NonfairSync@0x000000070F7392F0 Owned by: "WebContainer : 23" (J9VMThread:0x0000000033DA8A00, java/lang/Thread:0x00000007078C20D0)
Heap bytes allocated since last GC cycle=0 (0x0)
Java callstack:
    at sun/misc/Unsafe.park(Native Method)
    at java/util/concurrent/locks/LockSupport.park(LockSupport.java:186(Compiled Code))
    at java/util/concurrent/locks/AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:847(Compiled Code))
    at java/util/concurrent/locks/AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:881(Compiled Code))
    at java/util/concurrent/locks/AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1210(Compiled Code))
    at java/util/concurrent/locks/ReentrantLock$NonfairSync.lock(ReentrantLock.java:220(Compiled Code))
    at java/util/concurrent/locks/ReentrantLock.lock(ReentrantLock.java:296(Compiled Code))
    at com/vaadin/server/VaadinService.lockSession(VaadinService.java:626(Compiled Code))
    at com/vaadin/server/VaadinService.findOrCreateVaadinSession(VaadinService.java:662(Compiled Code))
    at com/vaadin/server/VaadinService.findVaadinSession(VaadinService.java:527(Compiled Code))
    at com/vaadin/server/VaadinService.handleRequest(VaadinService.java:1403(Compiled Code))
    at com/vaadin/server/VaadinServlet.service(VaadinServlet.java:364(Compiled Code))
    at javax/servlet/http/HttpServlet.service(HttpServlet.java:790(Compiled Code))
    at com/ibm/ws/webcontainer/servlet/ServletWrapper.service(ServletWrapper.java:1235(Compiled Code))
    at com/ibm/ws/webcontainer/servlet/ServletWrapper.handleRequest(ServletWrapper.java:779(Compiled Code))
    at com/ibm/ws/webcontainer/servlet/ServletWrapper.handleRequest(ServletWrapper.java:478(Compiled Code))
    at com/ibm/ws/webcontainer/servlet/ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:179(Compiled Code))
    at com/ibm/ws/webcontainer/filter/WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1134(Compiled Code))
    at com/ibm/ws/webcontainer/webapp/WebApp.handleRequest(WebApp.java:4219(Compiled Code))

**Comment by Legioth** [comment]
It seems like `checkStatoStampanteTicket` is reading from some stream without making progress in the `WebContainer : 23` thread. What isn't apparent is what it tries to read, i.e. what is that stream trying to read from?

At the same time, there's the `WebContainer : 13` thread which is stuck waiting for the session lock that thread 23 is currently holding (since it's currently running a click listener related to that session). Could it be that request that is being handled by thread 13 is supposed to generate data for the stream that is read by thread 23? If that is the case, the Vaadin cannot do anything about it. Instead, you'd have to change the logic in the application so that `checkStatoStampanteTicket` accesses the data directly from the session that it already has a lock for instead of trying to get the data indirectly by making a network request.

**Comment by pleku** [comment]
Since there is nothing that we can do about this as there are no steps to reproduce and the issue has been inactive for over two weeks, closing the issue. Please create a new issue with steps to reproduce if still valid.

**Comment by TatuLund** [comment]
May be related to this https://github.com/vaadin/flow/issues/16293

**Comment by TatuLund** [comment]
It looks like this problem should have been fixed in Open WebSphere Liberty 22005, see:  https://github.com/OpenLiberty/open-liberty/issues/20676
