### ISSUE TITLE
LogoutIT is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9705]
LogoutIT.setLocation_noErrorMessages

https://bender.vaadin.com/viewLog.html?buildId=205639&buildTypeId=Flow_Flow25_Nightly_FlowFelixJettyIntegrationTests25

I'm pretty sure this is the bug for the test:
https://github.com/vaadin/flow/issues/9647

**Comment by joheriks** [comment]
Note that there was already an [existing exception in the IT](https://github.com/vaadin/flow/blob/master/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java#L34) to not fail for "Session expired" which could occur spuriously.
The test is now flaky because the logged error has more information:

```[SEVERE] http://172.16.1.226:8888/VAADIN/static/client/client-C4B53966888EAB6CBD0D20BD246409CB.cache.js 211:19 "Session Expired"```

So this could also be due to Chrome update. In the `offline` branch, the condition on the error log is relaxed as follows:
https://github.com/vaadin/flow/blob/feature/offline/flow-tests/test-root-context/src/test/java/com/vaadin/flow/uitest/ui/LogoutIT.java#L35

If these log messages are due to an actual bug, that should of course be fixed and the relaxations in the ITs removed.

**Comment by denis-anisimov** [comment]
As I understand the `Session Expired` log message is a bug ( #9647 ) : it just should not be there.

**Comment by mshabarov** [comment]
No corresponding fix found so far, but most likely the issue is in client engine functionality in `flow-client`.
I temporary give it back to backlog and switch to more urgent issue.

**Comment by denis-anisimov** [comment]
```
Caused by: java.lang.AssertionError: Received error message in browser log console right after opening the page, message: [2020-12-21T00:26:05+0000] [SEVERE] http://172.16.1.226:8888/VAADIN/static/client/client-C4B53966888EAB6CBD0D20BD246409CB.cache.js 211:19 "Session Expired"
	at com.vaadin.flow.testutil.TestBenchHelpers.lambda$checkLogsForErrors$4(TestBenchHelpers.java:378)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.testutil.TestBenchHelpers.checkLogsForErrors(TestBenchHelpers.java:373)
	at com.vaadin.flow.uitest.ui.LogoutIT.setLocation_noErrorMessages(LogoutIT.java:34)
```

**Comment by denis-anisimov** [comment]
The reason is exactly the same as #9647
