### ISSUE TITLE
DeploymentConfigurationFactory can't load flow-build-info.json on Quarkus

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9713]
The `DeploymentConfigurationFactory` class uses `DeploymentConfiguration.class.getClassLoader()` to load `flow-build-info.json` file. Unfortunately, Quarkus loads vaadin jars in a classloader different from the 'app' classloader which actually  contains the `flow-build-info.json` file. That makes the `DeploymentConfigurationFactory` class fail to find the `flow-build-info.json` file, ultimately failing to initialize with 
```
2020-12-22 16:59:03,834 ERROR [io.und.req.io] (executor-thread-4) Exception handling request 310f94c1-5596-4340-ab15-d78bb8230b2a-6 to /VAADIN/static/server/workbox/workbox-sw.js: java.lang.IllegalStateException: The compatibility mode is explicitly set to 'false', but there are neither 'flow-build-info.json' nor 'webpack.config.js' file available in the project/working directory. Ensure 'webpack.config.js' is present or trigger creation of 'flow-build-info.json' via running 'prepare-frontend' Maven goal.
	at com.vaadin.flow.server.DeploymentConfigurationFactory.verifyMode(DeploymentConfigurationFactory.java:465)
	at com.vaadin.flow.server.DeploymentConfigurationFactory.lambda$readBuildInfo$1ac205d3$1(DeploymentConfigurationFactory.java:192)
	at com.vaadin.flow.server.DefaultDeploymentConfiguration.checkCompatibilityMode(DefaultDeploymentConfiguration.java:320)
```

The solution is to use context class loader: `Thread.currentThread().getContextClassLoader().getResources(tokenResource)`. Alternatively we can use Vaadin 19 and take advantage of the new Lookup SPI.
### Versions:
    - Vaadin / Flow version: 14.4.4 / 2.4.3
    - Java version: 11

**Comment by mshabarov** [comment]
For Vaadin `14.4`/ Flow `2.4` there is a workaround which allows to avoid the exception and start the app (but it won't be possible to use token file to configure the app):
1. Create a custom impl of `VaadinServlet`
2. Override the following method and exclude the compatibility mode check as follows:
```java
@Override
protected DeploymentConfiguration createDeploymentConfiguration(Properties initParameters) {
   initParameters.remove(DeploymentConfigurationFactory.DEV_MODE_ENABLE_STRATEGY);
   return new DefaultDeploymentConfiguration(getClass(), initParameters);
}
```

**Comment by mvysny** [comment]
Thank you @mshabarov , unfortunately that workaround is not possible because of https://github.com/vaadin/flow/issues/9755

**Comment by pleku** [comment]
### Acceptance Criteria
- [ ] Add a new `QuarkusResourceProvider implements ResourceProvider` into the new `vaadin/quarkus` artifact
