### ISSUE TITLE
windows: DevModeInitializer tests fail with webpack exception

### ISSUE THREAD

**Issue by caalador** [vaadin/flow#9774]
After merge of offline mode devmodeinitializer tests started failing with a webpack error when executin on windows.
```
[webpack] ERROR com.vaadin.flow.server.DevModeHandler - Error when reading manifest.json from webpack-dev-server
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.vaadin.flow.server.DevModeHandler.readManifestPaths(DevModeHandler.java:581)
	at com.vaadin.flow.server.DevModeHandler.processLine(DevModeHandler.java:513)
	at com.vaadin.flow.server.DevModeHandler.readLinesLoop(DevModeHandler.java:478)
	at com.vaadin.flow.server.DevModeHandler.lambda$logStream$2(DevModeHandler.java:449)
	at java.lang.Thread.run(Thread.java:748)
```

which leads to 
```
Caused by: java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.flow.server.DevModeHandler.doStartWebpack(DevModeHandler.java:736)
	at com.vaadin.flow.server.DevModeHandler.doStartDevModeServer(DevModeHandler.java:662)
	at com.vaadin.flow.server.DevModeHandler.runOnFutureComplete(DevModeHandler.java:561)
	at com.vaadin.flow.server.DevModeHandler.lambda$new$0(DevModeHandler.java:169)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
```

**Comment by platosha** [comment]
This particular error message seems to be a false alarm in this context. It throws because `DevModeInitializer` tests are runned against stub “webpack-dev-server”, which is not a real server, and thus does not listen on the port. Not a windows specific thing.

Looks like those tests are expected to succeed even with this error being thrown.
