### ISSUE TITLE
Add support for jakarta validation

### ISSUE THREAD

**Issue by mvysny** [vaadin/flow#9782]
The new hibernate-validator (the reference validator implementation) version 7.0.0 is no longer compatible with `javax.validation:validation-api:2.0.1` which `BeanValidationBinder` uses; instead it pulls in `jakarta.validation-api` (probably the same API as `javax.validation` but packaged to `jakarta.validation`.

Perhaps `BeanValidationBinder` should be able to use either `javax.validation` or `jakarta.validation` (whichever is available on the classpath); alternatively we can introduce new `Binder` which only supports `jakarta.validation`.

Trying to use hibernate-validator 7.0.0 with Vaadin 14.4.5's BeanValidationBinder will result in the following exception:

```
[main] INFO com.vaadin.validator.BeanValidator - A JSR-303 bean validation implementation not found on the classpath or could not be initialized. BeanValidator cannot be used.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.vaadin.flow.internal.BeanUtil$LazyValidationAvailability.isAvailable(BeanUtil.java:242)
	at com.vaadin.flow.internal.BeanUtil$LazyValidationAvailability.<clinit>(BeanUtil.java:233)
	at com.vaadin.flow.internal.BeanUtil.checkBeanValidationAvailable(BeanUtil.java:161)
	at com.vaadin.flow.data.binder.BeanValidationBinder.<init>(BeanValidationBinder.java:80)
	at com.vaadin.flow.data.binder.BeanValidationBinder.<init>(BeanValidationBinder.java:61)
	at com.vaadin.starter.beveragebuddy.ui.reviews.ReviewEditorForm.<init>(ReviewEditorDialog.kt:105)
	at com.vaadin.starter.beveragebuddy.ui.reviews.ReviewEditorDialog.edit(ReviewEditorDialog.kt:98)
	at com.vaadin.starter.beveragebuddy.ui.reviews.ReviewEditorDialog.createNew(ReviewEditorDialog.kt:86)
	at com.vaadin.starter.beveragebuddy.ui.ReviewEditorDialogTest$1$1.invoke(ReviewEditorDialogTest.kt:16)
	at com.vaadin.starter.beveragebuddy.ui.ReviewEditorDialogTest$1$1.invoke(ReviewEditorDialogTest.kt:12)
	at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$1$1.invoke(DynaTestEngine.kt:92)
	at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$1$1.invoke(DynaTestEngine.kt:28)
	at com.github.mvysny.dynatest.engine.DynaNodeTestDescriptor.runBlock(DynaTestEngine.kt:205)
	at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$1.invoke(DynaTestEngine.kt:92)
	at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$2.invoke(DynaTestEngine.kt:120)
	at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$2.invoke(DynaTestEngine.kt:116)
	at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$2.invoke(DynaTestEngine.kt:116)
	at com.github.mvysny.dynatest.engine.DynaTestEngine.execute(DynaTestEngine.kt:131)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: javax.validation.NoProviderFoundException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:291)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	... 31 more
```

### Versions:
    - Vaadin / Flow version: 14.4.5 / 2.4.3
    - Java version: 8

**Comment by mvysny** [comment]
Workaround is to downgrade hibernate-validator to 6.2.0.Final (or one of the 6.x series).

**Comment by Legioth** [comment]
This is similar to how Vaadin isn't compatible with Servlet 5.0 or any other previous Java EE specification that has now been updated to use the new `jakarta` namespace.

Supporting both namespaces in parallel causes some additional complexity that I'm not sure how to best deal with.
