### ISSUE TITLE
cannot be cast to class java.lang.String (java.lang.StackTraceElement and java.lang.String are in module java.base of loader 'bootstrap')

### ISSUE THREAD

**Issue by DanielMartensson** [vaadin/flow#9791]
### Description of the bug / feature
I get an error when I run my project with `mvn spring-boot:run`

```
dell@dell-Precision-M6400:~/Dokument/GitHub/OpenSourceLogger$ mvn spring-boot:run
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------< se.danielmartensson:opensourcelogger >----------------
[INFO] Building OpenSourceLogger 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:2.3.2.RELEASE:run (default-cli) > test-compile @ opensourcelogger >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ opensourcelogger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO] 
[INFO] --- vaadin-maven-plugin:14.4.5:prepare-frontend (default) @ opensourcelogger ---
[INFO] Copying frontend resources from jar files ...
[INFO] Visited 140 resources. Took 590 ms.
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ opensourcelogger ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ opensourcelogger ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/dell/Dokument/GitHub/OpenSourceLogger/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ opensourcelogger ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< spring-boot-maven-plugin:2.3.2.RELEASE:run (default-cli) < test-compile @ opensourcelogger <<<
[INFO] 
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.3.2.RELEASE:run (default-cli) @ opensourcelogger ---
[INFO] Attaching agents: []
  ___                       ____                                   _                                      
 / _ \  _ __    ___  _ __  / ___|   ___   _   _  _ __   ___   ___ | |      ___    __ _   __ _   ___  _ __ 
| | | || '_ \  / _ \| '_ \ \___ \  / _ \ | | | || '__| / __| / _ \| |     / _ \  / _` | / _` | / _ \| '__|
| |_| || |_) ||  __/| | | | ___) || (_) || |_| || |   | (__ |  __/| |___ | (_) || (_| || (_| ||  __/| |   
 \___/ | .__/  \___||_| |_||____/  \___/  \__,_||_|    \___| \___||_____| \___/  \__, | \__, | \___||_|   
       |_|                                                                       |___/  |___/             

2021-01-11 19:22:11.911  INFO 25205 --- [  restartedMain] se.danielmartensson.Application          : Starting Application on dell-Precision-M6400 with PID 25205 (/home/dell/Dokument/GitHub/OpenSourceLogger/target/classes started by dell in /home/dell/Dokument/GitHub/OpenSourceLogger)
2021-01-11 19:22:11.916  INFO 25205 --- [  restartedMain] se.danielmartensson.Application          : No active profile set, falling back to default profiles: default
2021-01-11 19:22:12.048  INFO 25205 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2021-01-11 19:22:12.049  INFO 25205 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
2021-01-11 19:22:12.802  INFO 25205 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFERRED mode.
2021-01-11 19:22:12.900  INFO 25205 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 89ms. Found 6 JPA repository interfaces.
2021-01-11 19:22:13.808  INFO 25205 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-01-11 19:22:13.848  INFO 25205 --- [  restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-01-11 19:22:13.849  INFO 25205 --- [  restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.37]
2021-01-11 19:22:14.003  INFO 25205 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-01-11 19:22:14.003  INFO 25205 --- [  restartedMain] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1954 ms
2021-01-11 19:22:18.540  INFO 25205 --- [  restartedMain] c.v.f.s.VaadinServletContextInitializer  : Search for subclasses and classes with annotations took 4 seconds
2021-01-11 19:22:18.542  INFO 25205 --- [  restartedMain] c.v.f.server.startup.DevModeInitializer  : Starting dev-mode updaters in /home/dell/Dokument/GitHub/OpenSourceLogger folder.
2021-01-11 19:22:18.603  INFO 25205 --- [  restartedMain] dev-updater                              : Visited 108 classes. Took 30 ms.
2021-01-11 19:22:18.690  INFO 25205 --- [  restartedMain] dev-updater                              : Skipping `npm install` because the frontend packages are already installed in the folder '/home/dell/Dokument/GitHub/OpenSourceLogger/node_modules' and the hash in the file '/home/dell/Dokument/GitHub/OpenSourceLogger/node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
2021-01-11 19:22:18.690  INFO 25205 --- [  restartedMain] dev-updater                              : Copying frontend resources from jar files ...
2021-01-11 19:22:18.769  INFO 25205 --- [  restartedMain] dev-updater                              : Visited 14 resources. Took 79 ms.
2021-01-11 19:22:19.119  INFO 25205 --- [  restartedMain] dev-updater                              : Updated /home/dell/Dokument/GitHub/OpenSourceLogger/target/frontend/generated-flow-imports.js
2021-01-11 19:22:19.133  INFO 25205 --- [  restartedMain] dev-updater                              : Visited 108 classes. Took 13 ms.
Vaadin application has been deployed and started to the context path "/".
2021-01-11 19:22:19.171  INFO 25205 --- [       Thread-4] dev-updater                              : Skipping `npm install` because the frontend packages are already installed in the folder '/home/dell/Dokument/GitHub/OpenSourceLogger/node_modules' and the hash in the file '/home/dell/Dokument/GitHub/OpenSourceLogger/node_modules/.vaadin/vaadin.json' is the same as in 'package.json'
2021-01-11 19:22:19.177  INFO 25205 --- [       Thread-4] dev-updater                              : Copying frontend resources from jar files ...
2021-01-11 19:22:19.329  INFO 25205 --- [       Thread-4] dev-updater                              : Visited 14 resources. Took 151 ms.
2021-01-11 19:22:19.370  INFO 25205 --- [       Thread-4] dev-updater                              : No js modules to update '/home/dell/Dokument/GitHub/OpenSourceLogger/target/frontend/generated-flow-imports.js' file
2021-01-11 19:22:19.417  INFO 25205 --- [       Thread-5] dev-webpack                              : Starting webpack-dev-server
2021-01-11 19:22:19.742  WARN 25205 --- [  restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Cannot deserialize session attribute [com.vaadin.flow.server.VaadinSession.springServlet] for session [3114100345232A647CE4A2A13F392A84]
2021-01-11 19:22:19.750 ERROR 25205 --- [  restartedMain] o.a.catalina.session.StandardManager     : Exception loading sessions from persistent storage

java.lang.ClassCastException: class java.lang.StackTraceElement cannot be cast to class java.lang.String (java.lang.StackTraceElement and java.lang.String are in module java.base of loader 'bootstrap')
	at java.base/java.io.ObjectInputStream.readTypeString(ObjectInputStream.java:1759) ~[na:na]
	at java.base/java.io.ObjectStreamClass.readNonProxy(ObjectStreamClass.java:793) ~[na:na]
	at java.base/java.io.ObjectInputStream.readClassDescriptor(ObjectInputStream.java:965) ~[na:na]
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1984) ~[na:na]
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1862) ~[na:na]
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2169) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679) ~[na:na]
	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464) ~[na:na]
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2358) ~[na:na]
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:493) ~[na:na]
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:451) ~[na:na]
	at org.apache.catalina.session.StandardSession.doReadObject(StandardSession.java:1587) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.session.StandardSession.readObjectData(StandardSession.java:1040) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.session.StandardManager.doLoad(StandardManager.java:218) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.session.StandardManager.load(StandardManager.java:162) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:354) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5156) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) ~[tomcat-embed-core-9.0.37.jar:9.0.37]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:437) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:191) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:178) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:158) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.2.RELEASE.jar:2.3.2.RELEASE]
	at se.danielmartensson.Application.main(Application.java:14) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.3.2.RELEASE.jar:2.3.2.RELEASE]

```

### Minimal reproducible example
```
git clone https://github.com/DanielMartensson/OpenSourceLogger.git
cd OpenSourceLogger
```
Follow instructions on https://github.com/DanielMartensson/OpenSourceLogger/ step 2 to 5. You don't need to write in an Outlook accout, only MySQL user

```
mvn spring-boot:run
```

### Expected behavior
I will not get an error when I start the project
### Actual behavior
No problem, just an error at start up.
### Versions:
    - Vaadin / Flow version: 14.4.5
    - Java version: OpenJDK 11.0.9.1
    - OS version: Lubuntu 18.04
    - NPM version: 6.14.10

**Comment by Legioth** [comment]
The key part of that exception message is `Exception loading sessions from persistent storage`.

It tries to the user sessions that were open when the server was previously shut down but this fails for some reason. The most likely reason is that the type of some instance field is different from what it was when the sessions were serialized. The same problem will thus not occur for someone else who doesn't have the same old sessions serialized. You can most likely resolve the issue by removing the old serialized sessions - they should be in a file named `SESSIONS.ser` that can be deleted.
