### ISSUE TITLE
Running from SpringBoot's main is not detecting existing theme jar dependency

### ISSUE THREAD

**Issue by taefi** [vaadin/flow#9802]
If the theme jar dependency is added to a SpringBoot application, by running it from the main method, the theme jar dependency is not being detected/loaded, so it fails to start with the following error log:
```
Caused by: com.vaadin.flow.server.ExecutionFailedException: Discovered @Theme annotation with theme name 'custom-theme', but could not find the theme directory in the project or available as a jar dependency. Check if you forgot to create the folder under '/Users/soroosh/workspaces/vaadin/application-theme-demo/reusing-theme-jar-demo/./frontend/themes' or have mistyped the theme or folder name for 'custom-theme'.
	at com.vaadin.flow.server.frontend.TaskUpdateThemeImport.verifyThemeDirectoryExistence(TaskUpdateThemeImport.java:108) ~[flow-server-6.0.0.alpha4.jar:6.0.0.alpha4]
	at com.vaadin.flow.server.frontend.TaskUpdateThemeImport.execute(TaskUpdateThemeImport.java:68) ~[flow-server-6.0.0.alpha4.jar:6.0.0.alpha4]
	at com.vaadin.flow.server.frontend.NodeTasks.execute(NodeTasks.java:672) ~[flow-server-6.0.0.alpha4.jar:6.0.0.alpha4]
	at com.vaadin.flow.server.startup.DevModeInitializer.runNodeTasks(DevModeInitializer.java:472) ~[flow-server-6.0.0.alpha4.jar:6.0.0.alpha4]
	at com.vaadin.flow.server.startup.DevModeInitializer.lambda$initDevModeHandler$0(DevModeInitializer.java:374) ~[flow-server-6.0.0.alpha4.jar:6.0.0.alpha4]
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	... 1 common frames omitted
```
But running the application using `mvn spring-boot:run` is working completely fine.

Tested against: 
Flow: `6.0.0.alpha4` and `6.0-SNAPSHOT`
Vaadin: `19.0.0.alpha2 and `19.0-SNAPSHOT`
Vaadin-Spring: `16.0.0.alpha3` and `16.0-SNAPSHOT`
OS: macOS BigSur 11.1
IDE: Intellij 2020.2 CE

**Comment by caalador** [comment]
Have you checked that the reusable jar file contents have been extracted to `target/flow-frontend/themes/custom-theme`?

**Comment by taefi** [comment]
> Have you checked that the reusable jar file contents have been extracted to `target/flow-frontend/themes/custom-theme`?

No, the contents of the jar haven't been extracted in neither of the followings:
- `target/flow-frontend/themes/custom-theme`
- `node_modules/@vaadin/flow-frontend/themes/custom-theme`

**Comment by caalador** [comment]
I would guess that `DevModeInitializer::getFrontendLocationsFromClassloader` need read in also RESOURCES_JAR_DEFAULT
