### ISSUE TITLE
Exception in push connection

### ISSUE THREAD

**Issue by rodolforfq** [vaadin/flow#9882]
### Description of the bug / feature
I've been having this issue with Push where the UI becomes unresponsive, reloads after a while and keeps on throwing the same error over and over again (views start to load, but never finish and are then reloaded after a while).
### Minimal reproducible example
Simply start an application with Push enabled and navigate to any Route other than root context path.
### Expected behavior
Navigation should work correctly when Push is enabled.
### Actual behavior
Navigation doesn't work, and server log keeps on throwing the same error over and over again.
### Versions:
    - Vaadin / Flow version: all 14.4.* versions. 14.3.* work flawlessly.
    - Java version: 11 (Azul 11.0.10)
    - OS version: Windows 10 Pro
    - Browser version (if applicable): Firefox Developer Edition, Chrome and Microsoft Edge (non chromium)
    - Application Server (if applicable): Spring Boot default (Tomcat)
### Error log:
```
2021-01-26 17:11:04.056 ERROR 1327320 --- [sphere-Shared-0] c.v.f.s.c.PushAtmosphereHandler          : Exception in push connection

org.apache.coyote.CloseNowException: Failed write
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:548)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:110)
	at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:193)
	at org.apache.coyote.Response.doWrite(Response.java:601)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:339)
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:298)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:272)
	at org.apache.catalina.connector.Response.flushBuffer(Response.java:500)
	at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:312)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:181)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:181)
	at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:165)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:181)
	at org.springframework.security.web.util.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:165)
	at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:181)
	at org.atmosphere.cpr.AtmosphereResponseImpl.flushBuffer(AtmosphereResponseImpl.java:506)
	at org.atmosphere.cpr.AtmosphereInterceptorWriter.flush(AtmosphereInterceptorWriter.java:102)
	at org.atmosphere.cpr.AtmosphereResponseImpl$Stream.flush(AtmosphereResponseImpl.java:1001)
	at org.atmosphere.handler.AbstractReflectorAtmosphereHandler.onStateChange(AbstractReflectorAtmosphereHandler.java:156)
	at com.vaadin.flow.server.communication.PushAtmosphereHandler.onStateChange(PushAtmosphereHandler.java:52)
	at org.atmosphere.cpr.DefaultBroadcaster.invokeOnStateChange(DefaultBroadcaster.java:1037)
	at org.atmosphere.cpr.DefaultBroadcaster.prepareInvokeOnStateChange(DefaultBroadcaster.java:1057)
	at org.atmosphere.cpr.DefaultBroadcaster.executeAsyncWrite(DefaultBroadcaster.java:871)
	at org.atmosphere.cpr.DefaultBroadcaster$2.run(DefaultBroadcaster.java:474)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

2021-01-26 17:11:04.078  INFO 1327320 --- [nio-8080-exec-8] o.a.catalina.connector.CoyoteAdapter     : Encountered a non-recycled response and recycled it forcedly.

org.apache.catalina.connector.CoyoteAdapter$RecycleRequiredException: null
	at org.apache.catalina.connector.CoyoteAdapter.checkRecycled(CoyoteAdapter.java:525)
	at org.apache.coyote.http11.Http11Processor.recycle(Http11Processor.java:1368)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.release(AbstractProtocol.java:1092)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:1013)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

2021-01-26 17:12:53.648  WARN 1327320 --- [nio-8080-exec-6] c.v.f.s.communication.ServerRpcHandler   : Resynchronizing UI by client's request. Under normal operations this should not happen and may indicate a bug in Vaadin platform. If you see this message regularly please open a bug report at https://github.com/vaadin/flow/issues
```

**Comment by rodolforfq** [comment]
I have already tried everything mentioned on both #7553 and #9399 to no avail. While they are similar errors, I believe the one I'm reporting was specifically introduced on version 14.4.0 and its not related to those.

**Comment by denis-anisimov** [comment]
Hello, thanks for the report. Can you please provide an example project based on https://github.com/vaadin/skeleton-starter-flow/  that reproduces the issue ? We have tests with the scenario which you mentioned. So I'm not able to reproduce the issue based on your minimal reproducible example and there are some details in your setup which we are not able to see without the example project.

**Comment by rodolforfq** [comment]
> 
> 
> Hello, thanks for the report. Can you please provide an example project based on https://github.com/vaadin/skeleton-starter-flow/ that reproduces the issue ? We have tests with the scenario which you mentioned. So I'm not able to reproduce the issue based on your minimal reproducible example and there are some details in your setup which we are not able to see without the example project.

Hello @denis-anisimov, sorry for the delay. I'm currently testing with the [V14 Spring Boot Starter](https://github.com/vaadin/skeleton-starter-flow-spring/tree/v14) and haven't been able to reproduce the issue yet. I'm adding modules one at a time and trying to find what combination is breaking my projects (I have even added Spring Cloud now and all seems good). I'm starting to have a feeling this is related to Spring Security (weird, because it works if I rollback my Vaadin version).

I'll test extensively and report my findings. I'm not sure if this issue should remain open in the meantime. What do you think?

**Comment by rodolforfq** [comment]
I'm back, after a long week of testing 😆 

Turns out my issue was not related to Spring or Vaadin at all, but to me using a custom servlet url mapping.

Since I use Spring Boot and Actuator endpoints, I serve Vaadin on /ui, so I can use /actuator (and others) without creating a conflict.

For the record, in case anyone else finds this issue on the future, this is on my application.properties file: `vaadin.urlMapping=/ui/*`

And up to Vaadin 14.3.9, this did the trick and allowed me to use Vaadin on a custom url path (on my @SpringBootApplication class):
```java
@Bean
public ServletRegistrationBean<SpringServlet> springServlet(ApplicationContext context) {
    return new ServletRegistrationBean<>(new SpringServlet(context, false), "/ui/*", "/frontend/*");
}
```

I had to change the method above for it work with 14.4.X (tried with all, up to 14.4.7, which is the latest at the time of this writing) for this:
```java
@Bean
public ServletRegistrationBean<VaadinServlet> vaadinServlet() {
    var bean = new ServletRegistrationBean<VaadinServlet>(new VaadinServlet() {
        @Override
        protected void service(HttpServletRequest req, HttpServletResponse resp) throws IOException {
            if (!serveStaticOrWebJarRequest(req, resp)) {
                resp.sendError(404);
            }
        }
    }, "/frontend/*");
    bean.setLoadOnStartup(1);
    return bean;
}
```

Thanks for your attention and great work on the framework @VaadinTeam. Sorry for assuming the problem was introduced by the framework (while I find it interesting it works until a specific version). Fun fact: the second method works for both 14.4.X and 14.3.X versions.

Cheers!

**Comment by balajia-opentext** [comment]
i am seeing this error in <version>2.5.8</version> spring parent, spring-boot app.
