### ISSUE TITLE
RerouteIT::testReroutingToErrorView is flaky

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/flow#9965]
`RerouteIT.testReroutingToErrorView` sometimes fails.

https://bender.vaadin.com/viewLog.html?buildId=212186&tab=buildResultsDiv&buildTypeId=Flow_Flow24_Nightly_FlowFelixJettyIntegrationTests24

The screenshot shows a loading indicator so it might be a timing issue.

**Comment by denis-anisimov** [comment]
```
Caused by: java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.vaadin.flow.uitest.ui.RerouteIT.testReroutingToErrorView(RerouteIT.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by denis-anisimov** [comment]
![Uploading testReroutingToErrorView[ANY_Chrome_](com.vaadin.flow.uitest.ui.RerouteIT).png…]()

**Comment by denis-anisimov** [comment]
![testReroutingToErrorView ANY_Chrome_ (com vaadin flow uitest ui RerouteIT)](https://user-images.githubusercontent.com/11425472/111961923-b357c000-8b02-11eb-9438-127fd04b05b2.png)
